### ISSUE TITLE
As Developer I want Molgenis supports case sensitive databases

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#1162]
Molgenis is not case sensitive!

Example: the names of attributes can be case sensietief but when asking for the data from the REST API the names of the attributes, the first letter of the name is in lower case.
Identifier in meta data ==> identifier when getting the data.

A solution can be changing the GeneratorHelper.ftl

**Comment by Mark-de-Haan** [comment]
Discussion to be held?
Or we keep as is and close this

**Comment by fdlk** [comment]
See http://www.molgenis.org/ticket/3498 . If you generate technical names for the entities and arrtibutes, those can be case insensitive, leaving the user free to specify case sensitive names.

**Comment by dennishendriksen** [comment]
MOLGENIS entity and attribute names are case-sensitive.
