### ISSUE TITLE
Cannot upload data sets with identifiers from composite excel cells.

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#1384]
Cannot upload data sets with identifiers from composite excel cells. Needs to be text.

**Comment by dennishendriksen** [comment]
What is the expected behavior when importing an xls file with composite cells?

**Comment by Mark-de-Haan** [comment]
Expected behavior:
A1 A2 A3
   C1   C3

Above example C1 is composite. Because it takes the space for attribute2 that attribute has no value.
Attribute1 its value is the C1 composite cell.

At least I would expect something like this

**Comment by mswertz** [comment]
So this requires a validation point in the ExcelRepository to test for composite cells?

**Comment by dennishendriksen** [comment]
@Mark-de-Haan For your example I would expect C1 to be assigned as a value for both attribute A1 and A2.

We have three solutions:
1) Assign C1 only to A1
2) Assign C1 to A1 and A2
3) Throw an exception when encountering composite cells and add a note to the EMX upload documentation that composite cells cannot be used.

Personally I would go for 3) to avoid confusion.
