### ISSUE TITLE
EntityMetaData idAttribute should always have a value

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1400]
EntityMetaData idAttribute should always have a value and this value should be an attribute that is exposed through the REST api

**Comment by bartcharbon** [comment]
The idAttribute is exposed through a field "idAttribute" using the API.
For example, my testEntity "testSparql", has an idAttribgute "id"

{"href":"/api/v1/testSparql/meta","name":"testSparql","label":"testSparql","attributes":{"molgenis_annotated_test1Annotator":{"href":"/api/v1/testSparql/meta/molgenis_annotated_test1Annotator"},"country":{"href":"/api/v1/testSparql/meta/country"},"long":{"href":"/api/v1/testSparql/meta/long"},"lat":{"href":"/api/v1/testSparql/meta/lat"}},"labelAttribute":"id",**"idAttribute":"id"**,"isAbstract":false}

**Comment by Mark-de-Haan** [comment]
So fixed?

**Comment by dennishendriksen** [comment]
There are no known cases of EntityMetaData implementations that have no IdAttribute.

**Comment by dennishendriksen** [comment]
Not fixed

**Comment by Mark-de-Haan** [comment]
@dennishendriksen Did you fix this problem by the recent ID attribute changes?

**Comment by dennishendriksen** [comment]
The statement "EntityMetaData idAttribute should always have a value" is invalid, only concrete entity types must have an id attribute (defined by themselves or one of the entities that they extend), abstract entities can have an id attribute.
