### ISSUE TITLE
Option to download the values for the categorical values instead of the name

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#1458]
Should there be an option to be able to download the value code of categorical variables instead of name? 

When it comes to data analysis, the value codes are much more useful in my opinion

**Comment by Mark-de-Haan** [comment]
You can download with either the labels or names.
This is what was meant with name / values?

**Comment by djvanenckevort** [comment]
The names / labels option deals with the header row of the CSV file, this issue deals with the data. If you have a categorical/xref/mref value you will currently get the label attribute of the referenced entity, while the usually the id attribute contains the code as it is used by the researchers. The label is nice for presentation purposes, but the code is more useful in downstream analysis.

**Comment by mswertz** [comment]
AFAIK this prevents round trip download + upload because xref values don't contain the 'id' but the 'label' of the refered to attribute. This is undesired. We want to enable a 'importable' download.
