### ISSUE TITLE
omx2emx does not create entities for all xls tabs

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1631]
Reproduce:
- Convert genome_browser_test.xls from molgenis-omx-dataexplorer with Omx2EmxExcelConverter
- Import converted xls
Expected: No validation warnings
Actual: See screenshot
![emx_validationreport](https://cloud.githubusercontent.com/assets/2477186/3383436/3f081e8c-fc4a-11e3-9eae-841afcb28743.png)

**Comment by mswertz** [comment]
this is a private tool to speed up OMX-EMX conversion. However, most data is now converted so I propose to discontinue maintenance of this tool
