### ISSUE TITLE
Importer validation report does not report unimportable entities

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1632]
Reproduce:
- Convert genome_browser_test.xls from molgenis-omx-dataexplorer with Omx2EmxExcelConverter
- Remove genomic_1 and genomic_2 rows from entities tab in converted xls
- Import converted xls
Expected: Error genomic_1 and genomic_2 can't be imported
Actual: Ok for genomic_1 and genomic_2

**Comment by bartcharbon** [comment]
Does not sound like a bug to me... entities do not need to be on the entities tab right? if they are described on the attributes tab that's enough I think?

**Comment by Mark-de-Haan** [comment]
Agree with Bart,
Entities are mentioned for each attribute so it does not matter if the entity tab does not contain them.

**Comment by djvanenckevort** [comment]
I think it is good to at least give a warning. For an end-user it is not obvious how this is handled and reasoning from the principle of the least surprises you should tell that there is an inconsistency between what is defined in the metadata for the entities and the attributes.

**Comment by Mark-de-Haan** [comment]
Depends on how you look at it I think. I would see the entity tab as a way to describe your entities, and to have some bookkeeping when creating your EMX. Its arbitrary, and does not have an impact on importing your attributes. Its no really an inconsistency, because its optional to define an entity tab.

**Comment by dennishendriksen** [comment]
What needs to be fixed?

**Comment by mswertz** [comment]
There should be no error if entities are not in entity tab, but do exist either in attributes tab or are already in database. I yesterday uploaded data without entities and that worked fine. If others cannot reproduce I propose to close

**Comment by dennishendriksen** [comment]
No errors occur if entities are not in entity tab, but do exist either in attributes tab or are already in database.

**Comment by djvanenckevort** [comment]
Will you be able to later add a metadata to an entity if it was first imported without listing the entity in the entities tab? If you can later update this metadata it's ok for me, but if that's not possible I think we should at least warn the user.
