### ISSUE TITLE
Nice error message when registering with existing username

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1767]
Instead of a error message like:
Details: remove(MolgenisUser) failed: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`lifelines`.`MolgenisGroupMember`, CONSTRAINT `FK_MolgenisGroupMember_molgenisUser` FOREIGN KEY (`molgenisUser`) REFERENCES `MolgenisUser` (`id`)) Error Code: 1451 Call: DELETE FROM MolgenisUser WHERE (id = ?) bind => [1 parameter bound]

**Comment by Mark-de-Haan** [comment]
There already is a warning, which should be made nicer. But it no longer throws a MySQL error.
