### ISSUE TITLE
EMX entities that extend an abstract entity

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#1775]
If I define an abstract entity 'OntologyTerm' and a concrete entity 'material_type' the concrete entity Category will not be created if it doesn't define an additional field.

This doesn't work
entities
ontologyterm abstract
material_type extends ontologyterm

attributes
ontologyterm label
ontologyterm code

But if I add to the attributes tab
material_type id

it will import.

**Comment by Mark-de-Haan** [comment]
This is expected behavior because your material_type entity needs an id attribute.
What would you like to see? The entity that is extending one to inherit the id attribute of the abstract entity? Then you need to define an id attribute for the abstract entity.

**Comment by djvanenckevort** [comment]
I think this issue has already been resolved, but I will verify.
Indeed I expect that an entity can inherit the definition of an id attribute from an abstract base entity.

**Comment by djvanenckevort** [comment]
This now works as I expect in 1.4.3 and 1.5.0. An entity can extend an abstract entity and not add any additional fields.
