### ISSUE TITLE
Not possible to create a new xref/mref entity in the data explorer

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#1780]
When editing in the data explorer is enabled it is not possible to create a new xref or mref entity. This means you will have to go to the table of the referenced entity first to create the entity and then go back and update your edit.
The workflow of editing data would be improved if you would be able to add a new entity directly when it is not yet available.

**Comment by Mark-de-Haan** [comment]
Will be solved soon in the react forms
