### ISSUE TITLE
MysqlRepository: updating id attribute does not throw Exception

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1807]
Updating the id attribute of an entity does not throw an Exception (and does not update the id of an entity).

**Comment by Mark-de-Haan** [comment]
Via import or via code?
Via import it is not possible

**Comment by mswertz** [comment]
I suppose this is not via UI so therefore put it on 'later'. Programmers can cope with this. Still, question of Mark still relevant. When does this happen?

**Comment by Mark-de-Haan** [comment]
With the recent idAttribute changes still the case?
