### ISSUE TITLE
EMX misses DefaultValue

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#1810]
AttributeMetaData has an method getDefaultValue().
This is not (yet?) supported by EMX

**Comment by dennishendriksen** [comment]
- The MySQL attributes table does not contain a column defaultValue, so it is not supported by the meta data service
- Our entity XML format uses the default keyword, but is is ignored at the moment (e.g. for MolgenisGroup)
- AttributeMetaData has a getDefaultValue method that is exposed by the REST API and used by the Repository validator

**Comment by fdlk** [comment]
So what should happen?

* The metadata service understands defaultValue attribute and remembers it.
* Forms preselect defaultValue when it is provided.
* REST API and repositories do not fill in defaultValue when you're storing null values.
* If you wish to store null and the value is nillable, null still gets stored.

**Comment by fdlk** [comment]
Question: Should the EMX importer forbid unlikely combinations?
Like 
* a unique field with defaultValue,
* an ID field with defaultValue,
* a computed field with defaultValue
