### ISSUE TITLE
Jenkins reverse proxy set up is broken

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1838]
See error reported here: http://www.molgenis.org/jenkins/manage
Can be solved by taking steps described in https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Apache, but this required Apache 2.2.18 (latest available update 2.2.15.*) or later http://httpd.apache.org/docs/2.2/mod/core.html#allowencodedslashes

This causes some plugins such as the Disk Usage plugin not to work

**Comment by Mark-de-Haan** [comment]
Can we deal with this issue or is our apache version still to old?

**Comment by mswertz** [comment]
bump

**Comment by dennishendriksen** [comment]
Still to old. Apache delivered with CentOS 7 is suitable.

**Comment by dennishendriksen** [comment]
http://molgenis.org/jenkins now redirects to https://molgenis50.gcc.rug.nl/jenkins which solved this issue.
