### ISSUE TITLE
Entity class user permissions unworkable.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#1839]
In the permission manager, I can choose what entity class permissions I assign to a user.
The choice is one of Edit, View, Count, None.
But whichever I choose for user anonymous and entity e_CeliacSprue, when I issue a GET on http://localhost:8080/api/v1/e_CeliacSprue, the rest api complains that I'm missing one of the other ones.
Assign Edit: "No READ permission on entity e_celiacsprue"
Assign View: "No COUNT permission on entity e_celiacsprue"
Assign Count: "No READ permission on entity e_celiacsprue"

**Comment by Mark-de-Haan** [comment]
There is a permission setting story that targets problems like this.
