### ISSUE TITLE
Harmonization of datatypes in molgenis

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#185]
We have FieldType (and MolgenisFieldTypes.FieldTypeEnum) for entities.

For ObservableFeature we have [xref,string,categorical,nominal,ordinal,date,datetime,int,code,image,decimal,bool,file,log,data,exe]. But this is not enforced, DataType is just a string field. 

We must have one set of types wich we use everywere and it must be static typed and validated

**Comment by Mark-de-Haan** [comment]
Enhancement story is in the backlog
