### ISSUE TITLE
DefaultAttributeMetaData equals returns true if name matches

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1879]
DefaultAttributeMetaData.equals returns true if the attribute name matches another attribute name. So Entity1.Attribute1 always equals Entity2.Attribute1.

Solution: equals should include 'entity' in the equal comparison

**Comment by mswertz** [comment]
when is this a problem?

**Comment by dennishendriksen** [comment]
When checking if a AttributeMetaData is updated. The updated AttributeMetaData is equal to the previous AttributeMetaData while it is not.

**Comment by Mark-de-Haan** [comment]
Is this still an issue?

**Comment by dennishendriksen** [comment]
DefaultAttributeMetaData has been removed from the project.
