### ISSUE TITLE
Unnecessary query nesting in data explorer

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1883]
Queries send to the server have unnecessary nesting layers, which result in hard to read queries:
{
    "entityName": "blaat",
    "xAxisAttributeName": "materiaal",
    "yAxisAttributeName": "jaar",
    "q": [{
        "operator": "NESTED",
        "nestedRules": [{
            "operator": "NESTED",
            "nestedRules": [{
                "operator": "NESTED",
                "nestedRules": [{
                    "field": "jaar",
                    "operator": "GREATER_EQUAL",
                    "value": "1996"
                }, {
                    "operator": "AND"
                }, {
                    "field": "jaar",
                    "operator": "LESS_EQUAL",
                    "value": "1996"
                }]
            }]
        }]
    }]
}

**Comment by Mark-de-Haan** [comment]
@fdlk Does this issue then make no sense?

**Comment by mswertz** [comment]
we will revisit this question when we refactor data explorer for bookmarkable queries.
