### ISSUE TITLE
Missing name in signup mail

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#1914]
In the mail the user receives in ADMIN mode (when admin activates the account) is the name missing.

![screen shot 2014-09-25 at 16 30 12](https://cloud.githubusercontent.com/assets/116559/4406118/b837fa98-44c0-11e4-8170-5f83efba5280.png)

**Comment by dennishendriksen** [comment]
Cannot reproduce:
Last name and first name are required fields in the sign up form. Resulting e-mail:

Dear Dennis H,

your registration request for MOLGENIS was approved.
Your account is now active.
