### ISSUE TITLE
DataExplorer filters and Mysql are doing by 'Mref' attribute a 'Contain search' and not 'Equals Search' 

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#1916]
See: QueryGenerator.Java

You will expect 
(ref1, ref2)

When query  (ref1 and ref2)

In posible results: 
(ref1)
(ref1, ref2)
(ref1, ref2, ref3)

Now is result:
(ref1, ref2)
(ref1, ref2, ref3)

**Comment by mswertz** [comment]
This is as designed. Otherwise there would be no way to say you want 
(ref1, ref2)
(ref1, ref2, ref3)
