### ISSUE TITLE
Aggregation for nillable categorical/mref/xref attributes

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1937]
Aggregation for nillable categorical/mref/xref attributes is not supported, because Elasticsearch missing aggregations do not work for nested types.

**Comment by jjettenn** [comment]
There is a new ticket made for this enhancement (http://www.molgenis.org/ticket/3423)

**Comment by bartcharbon** [comment]
mentioned story is a mismatch with this issue
