### ISSUE TITLE
Aggregation with distinct nillable attributes

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1938]
Support aggregation with distinct nillable attributes. Not supported because Elasticsearch cardinality aggregation does not consider nillable values as one distinct value: https://groups.google.com/forum/#!topic/elasticsearch/v1ilYrnMNJU

**Comment by jjettenn** [comment]
There is a new ticket made for this enhancement (http://www.molgenis.org/ticket/3423)
