### ISSUE TITLE
Charts Error when selecting nillable date of date time

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#1976]
Scatterplot and boxplot give an error when selecting an billable date or date time

java.lang.NullPointerException at java.util.Calendar.setTime(Calendar.java:1106) 
at org.molgenis.charts.highcharts.convert.HighchartSeriesUtil.convertDateToMilliseconds
(HighchartSeriesUtil.java:157)

**Comment by Mark-de-Haan** [comment]
Can not reproduce
