### ISSUE TITLE
upload logo and than save results in error

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#1980]
When you upload a new logo in the menu manager, and than click save, the following error occurs:
HTTP Status 405 - Request method 'GET' not supported

**Comment by erwinwinder** [comment]
Cannot reproduce

**Comment by dennishendriksen** [comment]
Can reproduce: select a logo file, do NOT press upload, press save. error 405.

**Comment by bartcharbon** [comment]
Cannot reproduce anymore...

**Comment by dennishendriksen** [comment]
Cannot reproduce as well ;-)

**Comment by dennishendriksen** [comment]
bartcharbon reopened this 3 days ago: are you fking kidding me?! ;-)

**Comment by Mark-de-Haan** [comment]
Ghost bug...

**Comment by erwinwinder** [comment]
Only appears to be in Safari

**Comment by mswertz** [comment]
Cannot reproduce. Tested in Safari and in Chrome.

**Comment by bartcharbon** [comment]
Still fails in Safari

**Comment by Mark-de-Haan** [comment]
Can not reproduce
