### ISSUE TITLE
Data explorer data item selection tree double scrollbar IE

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#1987]
![dataitemselection_doublescrollbar](https://cloud.githubusercontent.com/assets/2477186/4554686/c24b9c5a-4eb2-11e4-9011-c2d09381b55f.png)

**Comment by mswertz** [comment]
which versions of IE does this apply?

**Comment by mswertz** [comment]
we will reimplement in data explorer 2.0

**Comment by dennishendriksen** [comment]
Cannot reproduce in 8.0.0-SNAPSHOT with IE10, IE11 or Edge.
