### ISSUE TITLE
Forgot password should force a change of password at the first login

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2004]
When you use the forgot password option to reset your password you get a new password sent by e-mail. When you first login after the reset you should be force to change the password as a security measure, since the password was mailed in clear text.

How to reproduce:
* On the login page: click the 'Forgot password' link
* Fill in your e-mail
* Go to your mail client and you will find an e-mail with your password
* Login with the new password
Result:
* You can now work with the system as normal without being asked to change your password.
Expected result:
* You are forced to change your password before being able to work with the system.

**Comment by georgebyelas** [comment]
solved
