### ISSUE TITLE
Rest API doesn't allow update of MREF attribute in MySQL repository

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2031]
When updating an MREF attribute of an entity housed in a MySQL repository, the update fails.
Looks like the new value of the attribute gets sent as a JSON String representation of the entity.
The MySQL update can handle updates containing an Entity or just the ID, not this String.

**Comment by mswertz** [comment]
does this still existing?

**Comment by dennishendriksen** [comment]
Cannot reproduce:
- Upload molgenis-app\src\test\resources\emx_all_datatypes.xlsx
- Select TypeTest entity in data explorer
- Edit a row, update xmref_value, press Save
- The row is updated.
