### ISSUE TITLE
Entity form saves false boolean properties as NULL values.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2033]
An entity with a boolean attribute with value false gets saved as value NULL by the entity form, probably since the form cannot differentiate between false and NULL values.
I'd argue that the original value of the attribute should be used.

**Comment by jjettenn** [comment]
Cannot reproduce! please provide an example

**Comment by dennishendriksen** [comment]
Reproduce:
1) Import molgenis-app\src\test\resources\emx_all_datatypes.xlsx
2) Open entity form <molgenis_server_url>/menu/entities/form.org_molgenis_test_TypeTest
3) Edit entity on first row

Expected: Edit control is a [Yes|No|N/A] control similar to edit mode of table in data explorer
Actual: Edit control for xboolnillable is a true/false checkbox, it cannot be defined when an unchecked box implies false or when it implies null.
