### ISSUE TITLE
Exception while importing entity with name containing hyphen

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2055]
When I import EMX with hyphens, I expect error message "Entity names containing '-' not allowed"
Similar, when I import EMX with '/'  I expect error message "Entity names containing '/' not allowed"

Reproduce: Import https://github.com/molgenis/molgenis/blob/e8e4827925a4f2902aadd55d880d75e83c22eb4a/molgenis-model-registry/src/test/resources/BioSample-Model.xlsx on molgenis01 results in an Exception. The same import succeeds on Erwin his laptop. Replacing all hypens in this file with underscores resolves the problem.

**Comment by mswertz** [comment]
can we please reject these imports for now?

**Comment by fdlk** [comment]
Solved if we implement http://www.molgenis.org/ticket/3498
