### ISSUE TITLE
Importing Entity meta data with hundreds of string attributes fails 

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2059]
Importing Entity meta data with hundreds of string attributes fails, because meta data is persisted in MySQL and MySQL has a maximum row size of 64K and a max of 4K cols per table.

**Comment by dennishendriksen** [comment]
The limit we are hitting is usually for variable-length columns: http://dev.mysql.com/doc/refman/5.1/en/column-count-limit.html

**Comment by mswertz** [comment]
It says TEXT data is stored outside of the row limit, right?

So these columns only add a few bytes to the row size so should not be
cause of the problem. Having 65k int columns would, right?



On Tue, Feb 24, 2015 at 8:24 AM, Dennis Hendriksen <notifications@github.com
> wrote:

> The limit we are hitting is usually for variable-length columns:
> http://dev.mysql.com/doc/refman/5.1/en/column-count-limit.html
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/2059#issuecomment-75710731>.
>



-- 
Morris A. Swertz
Associate Professor Big data in biomedicine
Lead BBMRI-NL common services for IT
Head Section Systems Genetics & Genomics Coordination Center
Dept of Genetics
University Medical Center Groningen
The Netherlands

**Comment by mswertz** [comment]
Will be fixed with the new mysql 'TEXT' feature?

**Comment by tommydeboer** [comment]
Fixed with the mysql TEXT feature. Imported 500 string columns without any problems.
