### ISSUE TITLE
Some imported VCF files report errors in data explorer

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2073]
Reproduce:
- Import Dropbox\GCC\data\chr21.imputed.head.vcf, provide name 'myVcf'
- Go to the data explorer
Expected:
- Entity 'myVcf' in data explorer dropdown
- Entity 'MyVcf.imputed.head' does not result in Unknown entity [MyVcf.imputed] error

**Comment by Mark-de-Haan** [comment]
Is this fixed now?
