### ISSUE TITLE
Upload validation should fail if an identity field is nullable

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2158]
When an identity field of an entity is nullable the entity will pass validation, but will fail to import.
The message in catalina.out is:
org.molgenis.data.MolgenisDataException: java.lang.RuntimeException: idAttribute (AnatomicalSite.ID) should not be nillable

This error should be caught and reported during validation.

**Comment by Mark-de-Haan** [comment]
This is correctly handled with a message saying id attributes can not be nillable

**Comment by dennishendriksen** [comment]
Is this message reported during validation or during import? In case it is during import then this issue is not resolved.

**Comment by djvanenckevort** [comment]
The message is reported during validation, but reported on the second page (Options) instead of the third pages (Validation).

**Comment by Mark-de-Haan** [comment]
A lot of error messages are thrown on the advanced options page instead of during validation.
Could make a story out of it because there are 4 different git issues explaining the same problem
