### ISSUE TITLE
Circular dependencies should be reported during validation

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2159]
If there is a circular dependency e.g.
entity1 -> entity2
entity2 -> entity3
entity3 -> entity1
The file will pass validation, but will not import. The issue should be caught during validation.

**Comment by Mark-de-Haan** [comment]
@tommydeboer Is this fixed now that we support circular dependencies?

**Comment by Mark-de-Haan** [comment]
In 2.0, this is checked before doing the actual import
![screen shot 2016-10-28 at 14 57 14](https://cloud.githubusercontent.com/assets/3625016/19807106/d6cb28b4-9d1e-11e6-9b52-d2718c9a26f0.png)
[circular_dep.xlsx](https://github.com/molgenis/molgenis/files/558375/circular_dep.xlsx)
