### ISSUE TITLE
Investigate and fix memory leak(s)

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2164]
Some of our servers stop working now and again because of a lack of available memory. 
When restarting a few times locally the same problem occurs.

In other words: there appear to be a (or multiple) memory leak(s)

**Comment by dennishendriksen** [comment]
This problem is will occur less often since the Java 8 upgrade since there is no perm gen space anymore.

**Comment by Mark-de-Haan** [comment]
Even with java8 this issue is still popping up in the apache-tomcat log alot.

**Comment by dennishendriksen** [comment]
Two roads to success:
1) Stop using Tomcat autoDeploy and replace with some extra Jenkins deploy scripting
2) Fix all memory leaks in our libraries and implement tricks to resolve memory leaks in third party libs

**Comment by mswertz** [comment]
Option 2 doesnt sound easy?

**Comment by Erutan409** [comment]
Bump.  I'm having similar issues.  Any progress being made on this?

**Comment by fdlk** [comment]
What's the exact issue you're having? As Dennis mentioned, Java 8 should be able to handle the memory loss of a redeploy quite easily. That leaves the vaguely worrisome complaint in the logfiles.

**Comment by fdlk** [comment]
Duplicates https://github.com/molgenis/molgenis/issues/136

**Comment by dennishendriksen** [comment]
Part of M3634 As developer I want to solve the freezing problems on Molgenis59

**Comment by Mark-de-Haan** [comment]
Part of a story, closing this.
