### ISSUE TITLE
Validation error on attribute type is reported before the validation report

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2171]
When importing a file with an illegal attribute type the validation error is reported before the validation report and stops further validation of the file. This means that you do not get a full overview of the errors in the file.

How to reproduce:
- change the attribute type of an attribute to an illegal value on two or more attributes (e.g. url instead of hyperlink is a mistake I frequently make)
- upload the file

Result:
the validation error for the first item is reported on the 'options' screen.

Expected behaviour:
- The validation error is reported on the validation screen
- The error is reported for all occurrences

**Comment by Mark-de-Haan** [comment]
Added 3432 to backlog
