### ISSUE TITLE
Validation error on illegal combination of type and options is reported before the validation screen

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2172]
When importing a file with an illegal combination of type and settings the validation error is reported before the validation report and stops further validation of the file. This means that you do not get a full overview of the errors in the file.

How to reproduce:
- create two or more mref attributes that are both aggregateable and nillable 
- upload the file

Result:
the validation error for the first item is reported on the 'options' screen.

Expected behaviour:
- The validation error is reported on the validation screen
- The error is reported for all occurrences

**Comment by Mark-de-Haan** [comment]
Added 3432 to the backlog
