### ISSUE TITLE
Catalog manager fails to show error messages.

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2216]
Ingelogd als: Datamanager
Browser: FF/Chrome
Soort: Bevinding
Priority: Blocking
Versie: version 1.2.2.1-SNAPSHOT build on 2014-11-21 14:16

Omschrijving:
Nieuwe Catalog via Utopia Web aangemaakt (Catalog 1.2 en 1.3) worden niet actief gemaakt en geven een 500 melding. Deze melding al eerder via de mail gecommuniceerd, waarbij toen wel 1.1 uiteindelijk wel actief werd.

**Comment by dennishendriksen** [comment]
Server configuration issue, we probably have to increase httpd timeout.

**Comment by fdlk** [comment]
Also happens within 5 seconds if the catalogue contains duplicate identifiers.

**Comment by fdlk** [comment]
Bug sits in the CatalogManagerController. If an unexpected exception occurs when you activate the catalog, for instance cause the validation fails when you insert the data, the exception handler goes off.

It writes the error message from the exception to the request, as an attribute, and then is annotated to return ResponseCode 500. This means the nature of the exception only makes its way into the log file, but not to the user.

See https://github.com/molgenis/molgenis/blob/1.2/molgenis-omx-protocolviewer/src/main/java/org/molgenis/catalogmanager/CatalogManagerController.java

**Comment by dennishendriksen** [comment]
Catalog manager plugin was removed from MOLGENIS.
