### ISSUE TITLE
LL TAB:"Bevindingen (2)" Nr:1

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2222]
Ingelogd als: Maakt niet uit
Browser: Chrome
Soort:
Priority:
Versie: version 1.2.2.1-SNAPSHOT build on 2014-11-21 14:16

Omschrijving:
Zodra je ingelogd bent met een account op molgenis en je bent niet actief op de site, dan wordt je na een bepaalde tijd automatisch uitgelogd. Maar daar krijg je geen melding van, je merkt het als gebruiker pas als je weer wat wilt doen en dan zie je een error melding. Ook krijg je geen nieuwe prompt om in te loggen (Al bij de testen van de Molgenis 31 opgemerkt)

**Comment by dennishendriksen** [comment]
10-12-2014: Bevinding lijkt opgelost te zijn in de nieuwe versie voor straat2
