### ISSUE TITLE
JavaScript error in the DataExplorer with IE 9 on Windows 7

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2225]
When using Internet Explorer 9 on Windows 7 (downloaded the VM provided by Microsoft at http://www.modern.ie/) I get the following errors on the data explorer and no data is shown:

Error! An error occurred. Please contact the administrator.
Unable to get value of the property 'setAttributes': object is null or undefined

In the console I see the following JavaScript errors:
SCRIPT5009: 'ArrayBuffer' is undefined 
jquery-1.8.3.min.js?HvHQDQ, line 2 character 14219
SCRIPT5007: Unable to get value of the property 'setAttributes': object is null or undefined 
jquery-1.8.3.min.js?HvHQDQ, line 2 character 38250

Tested on Molgenis-1.2.0

**Comment by dennishendriksen** [comment]
Fixed in latest version on master branch.
