### ISSUE TITLE
Default Entity reports not working for some entities

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2255]
When enabling the entity reports I get the following error in catalina.out when I try out the feature on the samples entity of the RD-Connect catalogue.

1293782 ERROR [freemarker.runtime] Template processing error: "Method public java.lang.String org.molgenis.data.elasticsearch.ElasticsearchEntity.getString(java.lang.String) threw an exception when invoked on org.molgenis.data.elasticsearch.ElasticsearchDocumentEntity@29bcc8e2"

Method public java.lang.String org.molgenis.data.elasticsearch.ElasticsearchEntity.getString(java.lang.String) threw an exception when invoked on org.molgenis.data.elasticsearch.ElasticsearchDocumentEntity@29bcc8e2
The problematic instruction:
----------
==> ${entity.getString(key)!?html} [on line 32, column 69 in view-entityreport-generic-default.ftl]
in include viewName+".ftl" [on line 5, column 25 in view-entityreport.ftl]
—————

**Comment by dennishendriksen** [comment]
Cannot reproduce with data set provided by @djvanenckevort

**Comment by djvanenckevort** [comment]
The issue was present in 1.3, but verified that it has been resolved in 1.4-SNAPSHOT.
