### ISSUE TITLE
Model input="file" not working with JPA

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#231]
Model input="file" is not working with JPA because of the problem described in:
http://stackoverflow.com/questions/14771399/hibernate-4-calls-setbinarystream-that-is-not-supported-in-c3p0

The most recent hibernate-c3p0 is still based on 0.9.1 so upgrading to 0.9.2 as suggested in article above is not possible.

**Comment by mswertz** [comment]
This is partly addressed in the user story about 'file'. Await until this story is completed to revisit this issue

**Comment by dennishendriksen** [comment]
Story is completed, please revisit.

**Comment by bartcharbon** [comment]
JPA has been removed
