### ISSUE TITLE
Internationalization of description is broken.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2319]
It's somewhat unclear what ought to happen.

When selecting a catalog item (not folder), the description of the item gets shown in the top right of the screen. It sometimes shows the same translation for en and nl (configuration error?).

When downloading the selected variables, no description is listed in the description column.

**Comment by dennishendriksen** [comment]
Move to molgenis-lifelines repo?

**Comment by Mark-de-Haan** [comment]
Moved
