### ISSUE TITLE
Descriptions of Catalog Folders are not shown

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2320]
When selecting a catalog folder in the catalog plugin, the folder gets selected in the tree.
The description of variable in the top right does not get updated. It keeps showing the last selected catalog item.

**Comment by mswertz** [comment]
still valid?

**Comment by mswertz** [comment]
Ideally we fix this *after* we merged this branch back into master

**Comment by dennishendriksen** [comment]
The branch is based on the OMX data model and cannot be merged automatically.

**Comment by dennishendriksen** [comment]
Move issue to molgenis-lifelines repo?

**Comment by Mark-de-Haan** [comment]
Moved
