### ISSUE TITLE
Uploading file without extensions when submitting order results in an undefined file at the data manager mailbox

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2322]
Example
File test should be test.txt

Re result of sending test file without extension is: LifeLines-request_1421334046336 (2).null

**Comment by dennishendriksen** [comment]
What is the expected result?

**Comment by dennishendriksen** [comment]
@jjettenn move issue to the molgenis-lifelines repository?

**Comment by Mark-de-Haan** [comment]
Moved
