### ISSUE TITLE
Concurrent use of the StudyManager causes browsers to hangup.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2323]
Quite unsure what's going on.

When two browsers log in as admin on molgenis31 and start using the study manager concurrently, they can cause lifelines to hang.
Simple requests, even for the css files, end up taking hundreds of seconds.
Ordinary users cannot reach the catalog.

netstat and kill -quit threaddumps show lots of ajp activity

**Comment by fdlk** [comment]
netstat shows plenty lines like this:
tcp        0      0 localhost:8009              localhost:49537             ESTABLISHED
tcp        0      0 localhost:8009              localhost:49563             ESTABLISHED
tcp        0      0 localhost:8009              localhost:49655             ESTABLISHED
tcp        0      0 localhost:49588             localhost:8009              ESTABLISHED
tcp        0      0 localhost:8009              localhost:49601             ESTABLISHED
tcp        0      0 localhost:49622             localhost:8009              ESTABLISHED
tcp        0      0 localhost:49701             localhost:8009              ESTABLISHED
tcp        0      0 localhost:8009              localhost:49481             ESTABLISHED
tcp        0      0 localhost:39053             localhost:mysql             ESTABLISHED
tcp        0      0 localhost:49592             localhost:8009              ESTABLISHED
tcp        1      0 localhost:49031             localhost:8009              CLOSE_WAIT
tcp        0      0 localhost:49611             localhost:8009              ESTABLISHED
tcp      743      0 localhost:8009              localhost:49798             CLOSE_WAIT
tcp        0      0 localhost:49625             localhost:8009              ESTABLISHED

**Comment by fdlk** [comment]
Thread dumps give 

"ajp-bio-8009-exec-85" daemon prio=10 tid=0x00007fd9fc04f800 nid=0x5c1a runnable [0x00007fd9c1c46000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.apache.coyote.ajp.AjpProcessor.read(AjpProcessor.java:309)
        at org.apache.coyote.ajp.AjpProcessor.readMessage(AjpProcessor.java:364)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:128)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        - locked <0x00000000d0bbeed8> (a org.apache.tomcat.util.net.SocketWrapper)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by fdlk** [comment]
At a time when the server was still hung up, I checked the mysql processes, they were all sleeping.

**Comment by fdlk** [comment]
We managed to reproduce by concurrently editing the same study on two different clients.
Mysql has no tables in use.

**Comment by mswertz** [comment]
Only fix after migration to master

**Comment by dennishendriksen** [comment]
Specific for molgenis-lifelines? If yes, move to issue tracker of molgenis-lifelines repo.

**Comment by Mark-de-Haan** [comment]
Moved
