### ISSUE TITLE
Query with multiple NOT clauses not working

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2326]
A Query with multiple NOT clauses results in a RuntimeException in the Query generator.
Reproduce: new QueryImpl().eq("a0", "v0").and().not().eq("a1", "v1").and().not().eq("a2", "v2")
The query new QueryImpl().eq("a0", "v0").and().not().eq("a1", "v1") does work however.

**Comment by fdlk** [comment]
I'd expect one more and() between v1 and v2. typo?

**Comment by dennishendriksen** [comment]
Indeed, fixed.
