### ISSUE TITLE
Study Manager allows checking of empty CatalogFolders

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2327]
In catalog Release 2, select a submitted study.
You can check the folder Child 0-3 years / Baseline.

Expected:
The folder cannot be selected, possibly shows the red forbidden sign like in the catalog browser.

When saving, the checkmarks are not persisted (which is okay, I suppose)

**Comment by dennishendriksen** [comment]
Specific for molgenis-lifelines? If yes, move to issue tracker of molgenis-lifelines repo.

**Comment by Mark-de-Haan** [comment]
Moved
