### ISSUE TITLE
o	Adding non-nillable attributes is not currently supported message is reported after the validation page

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2338]
When I change a model and add a new attribute that is not nullable the message that this is not supported is not reported on the validation page, but only during the import.

How to reproduce:
- Upload an EMX file
- Change the data model and add a new attribute to a field and set it nullable to FALSE
- Upload the modified file

Result:
- The wizard passes the validation page without error messages and an error is given on the last page

Expected result:
- An error is given on the validation page

**Comment by Mark-de-Haan** [comment]
Added 3432 to the backlog
