### ISSUE TITLE
Importing a CSV which was exported by MOLGENIS itself results in a no suitable importer found error

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2341]
Wrong Error message or is our CSV export incorrect?

**Comment by dennishendriksen** [comment]
How did you export the CSV? With the dataexplorer download CSV button? In that case:
It is not possible to import an exported CSV. The exported CSV shows content as displayed to the user (displaying labels for columns and referenced entity values). You can choose during download to export attribute ids, this could be extended to export ids for all referenced values as well.

Don't forget that the CSV file name should match the fully qualified entity name.

**Comment by Mark-de-Haan** [comment]
Yes by using the download button.
I can imagine the column names, referenced entities, and file name to be wrong. But is the format wrong?

The error should say which of the two because now it looks like we either export wrong CSV or our importer doesnt really know how to handle CSV.

**Comment by mswertz** [comment]
What would be needed to make this roundtrip possible?

**Comment by djvanenckevort** [comment]
I would also like to have the option to download the file with all the options set right to be able to upload it again.

**Comment by fdlk** [comment]
Some kind of documentation for the user would be nice too, when fixing this. So that he knows which export options make the file importable again.

**Comment by mswertz** [comment]
Probably this is all fault: what defaultoption would be needed for easy
round trip?

M

**Comment by mswertz** [comment]
Just noticed that there is also issue that xrefs/mrefs export labels instead of ids. I will close this as duplicate with that other, more specific, story.
