### ISSUE TITLE
Elasticsearch all shards failed error

### ISSUE THREAD

**Issue by brammiedema** [molgenis/molgenis#2351]
After I ran the test to check if the filter fix of Tommy was fixed I switched over to another dataset.
In this data set I applied a filter as well and it shows the following error:

'''
Error! Failed to execute phase [query], all shards failed; shardFailures {[-KbHlF7BQRitq-9NCbmFWw][molgenis][0]: SearchParseException[[molgenis][0]: from[0],size[10000]: Parse Failure [Failed to parse source [{"from":0,"size":10000,"query":{"filtered":{"query":{"match_all":{}},"filter":{"term":{"geneSymbol.raw":[""]}}}}}]]]; nested: NullPointerException; }'''

To reproduce:
1. Apply filter to a data set
2. Click disease matcher tab in the data explorer
3. Remove filter/add filter

**Comment by tommydeboer** [comment]
Can not reproduce
