### ISSUE TITLE
XREF or MREF columns in the download as CSV are incorrect

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2354]
When I download an entity as CSV from the Data Explorer the XREF and MREF columns are incorrect, e.g.
Sample Collection ID,"Sample Collection Acronym","Description","Sex","Age Low","Age High","Age Unit","Diseases","Data Categories","Material Type","Storage Temperature","Collection Type","Contact Information","Data Manager","Biobanks"
9c8f1c71-2608-43b6-97c4-0ec77cb5742d,"EC-DEEP","Example Cohort Deep","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@4c1a19de, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@6e22d70f]","0","114","Years","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@26a3d8a2, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@67ff9ebc, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@7bb7af74, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3d585a2]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3b8b2bb2, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@201a5801, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@66908f79, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@49c7fe9c, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2b739aad]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@59db1592, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3b52b297, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@4d17987f, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@7a06c582, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@7bf028d5, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5598eb36, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@24bd459a, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@685bbe5a, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@12179504, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@c40d2b, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@4e9b093c, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@7b07d7db, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5516c20a, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@759b30d6, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@635f05b0]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2623bf0f]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@45c63f53]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@6977aabd]","van Enckevort","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@729e40a6]"
3003506b-28fd-418a-aa57-e78431d8cc1d,"EC-ADOLESCENTS","Example Cohort adolescents","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@49fe523d, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3db6d0f6]","13","17","Years","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@69c0a7bf, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@69db5151]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@528f89ed, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@59b5d22a, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@35a47bfc]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@646e5c0, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@28a8c404, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5f7b67b9, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@49969c31]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@78cf1826]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@16297bdf]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@126b900c]","van Enckevort","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@6fe1f164]"
82c7d1dd-a326-4dcb-a7d5-5095aadb18ce,"EC-BABIES","Example Cohort birth cohort","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@6fefca96, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3245a337]","0","3","Years","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@7ce0ae83, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@1c6a0aaa]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@d40c8cb, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@12839e4f, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@6beebe2a]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@279dc6a7, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2c10440f, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@226fd624]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3cee23ad]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@750f6269]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5b9170fb]","van Enckevort","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@713535b]"
dad38a5f-5060-42b5-a6eb-64c07522007f,"EC-ADULTS","Example Cohort adults","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@4a2deb5f, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@44bfc459]","18","65","Years","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@1479729d, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@96d62c2]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2cbf07a3, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@16988361, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@492af6b5]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2b33f620, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@7fe56efa, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2db469ec, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3335bdb1]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@703df01]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@53c5f3a5]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5d300b38]","van Enckevort","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@43f6ed1a]"
2fadff25-d2d3-48c8-82b6-ae724d5ed77d,"EC-CHILDREN","Example Cohort children","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5a14c9b2, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2630418e]","8","12","Years","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@7b84e7bb]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@fee5bec, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@734b5afa, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@57d3492c]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@bb6c552, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@76fadef3, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5fcfd65c, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@12986ea0]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2f39b5f4]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@f14eba6]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2e48b12e]","van Enckevort","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@7ff42729]"
05744e5d-990c-4a06-92ab-b7896a9c5c84,"EC-TODDLERS","Example Cohort toddlers","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@1d00bb36, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@35613aeb]","4","7","Years","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5e4b2ca8]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@d88527, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@18995701, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2493909b]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@23bad6cd, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@678f9e20, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@35fcfc8f, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@d53b5e3]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@78aa063a]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@634ff991]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@310569f3]","van Enckevort","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@21693e9d]"
6cbbf792-09f3-474a-9782-bce6e5ce1ea4,"EC-ELDERLY","Example Cohort Eldery","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@95a675c, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@15c59497]","65","114","Years","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@f952d2d]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@67e06794, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3d5a9cb3, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@402d6a3]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@22586f4b, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@46606053, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@2f36d328, org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@3d93bfa3]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@5cd0bd6d]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@19f73c5c]","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@4113d9]","van Enckevort","[org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@200fcad5]"

To reproduce:
- Upload an EMX file with a dataset with XREF or MREF columns
- Go to the data explorer and select the entity
- Click Download as CSV
- Select to give the column names

Expected result:
- I have a CSV with the label or ID value of the referenced entities

Actual result:
- I have a CSV with identity fields for the referenced entities (e.g. [org.molgenis.data.elasticsearch.ElasticsearchDocumentNestedEntity@200fcad5])

**Comment by tommydeboer** [comment]
FIxed
