### ISSUE TITLE
'File did not pass validation' error while validation output seems ok.

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2380]
Everything is green or yellow, but still the file will not pass validation.

To reproduce:
- Upload the example_emx.xls file from an older version (for example MOLGENIS 1.2)
- Go to validation tab. 
- Error should be shown while the output does not show the cause of the problem.

**Comment by mswertz** [comment]
I used https://github.com/molgenis/molgenis/blob/v14.10/molgenis-app-omx/src/test/resources/example_emx.xls

Indeed. Big error but no information on 'why'.

**Comment by Mark-de-Haan** [comment]
Is this still relevant? 1.2 feels like a long time ago

**Comment by dennishendriksen** [comment]
@tommydeboer ?
