### ISSUE TITLE
In editable DataExplorer can't select null

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#2390]
On nillable xref, once chosen a value you can't select null.

**Comment by dennishendriksen** [comment]
Cannot reproduce. Import emx_all_datatypes.xlsx and select the TypeTest entity in the data explorer. Switch to edit mode and select label2 in the xxrefnillable_value column. Press the 'x' to clear the value. Reload the page and find the same row, the value is null as expected.
