### ISSUE TITLE
Chart error

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#2394]
Create chart: 
TypeTest; Title: box, select feaure: id, Outliers scale: 1.5, Split to series: xcategorical_value:

org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query_fetch], all shards failed; shardFailures {[2g6VNl6GS0WLlJroWtGjCA][molgenis][0]: QueryPhaseExecutionException[[molgenis][0]:

**Comment by dennishendriksen** [comment]
Both Erwin and myself cannot reproduce
