### ISSUE TITLE
Make add() work for Stream or Iterator

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2402]
When adding a stream of entities, they are all inspected by the RepositoryValidationDecorator before they get inserted.
Therefore, you need to provide an Iterable, rather than a Stream or an Iterator.
This makes for awkward programming and is inefficient memory wise.
Also, some repositories (think databases) are pretty good at handling these kind of validations themselves.

It'd be nice to have an additional add() method that does not check uniqueness and xref/mref consistency, filters out entities that have invalid attribute values and efficiently performs index and bulk insert.

**Comment by jjettenn** [comment]
There is a new ticket made for this enhancement (http://www.molgenis.org/ticket/3405)
