### ISSUE TITLE
Deleting VCF data set does not remove references

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2427]
Reproduce:
- Import molgenis-app\src\test\resources\mutations\test_samples.vcf with name <name of entity>
- Select entity <name of entity>Sample in data explorer and press delete
- Select entity <name of entity> in data explorer

Expected:
- Empty sample column

Actual:
- Error! Unknown entity [vcf_Sample]

**Comment by mswertz** [comment]
Samples should not be deleted if still referenced from the VCF data (is foreign key constraint). So I expect behavior: 'delete of Sample failed: reference from test_samples' or something like that

**Comment by dennishendriksen** [comment]
DataService and/or MetaDataService should check if delete is allowed.

**Comment by dennishendriksen** [comment]
VCF data is now stored in PostgreSQL, delete fails and results in an error.
