### ISSUE TITLE
Importer rejects aggregatable for nillable category/xref/mrefs

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2446]
Error! Error validating import file: attributes.aggregatable error on line 83 (Publications.Journal): aggregatable nillable attribute cannot be of type categorical

Reproduce set aggregetable to "TRUE" and datatype to "categorical", than try to import.

**Comment by Mark-de-Haan** [comment]
Is this a bug? Our code checks for this and throws the error, or are we throwing the error because we can not support it yet?

**Comment by dennishendriksen** [comment]
we are throwing the error because we do not support it yet.

**Comment by mswertz** [comment]
If the error is clear than this is a feature :)
