### ISSUE TITLE
Boxplot split to series broken with mref

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2454]
When I create a box plot and split to series on a mref the data is not correctly split into series and the labels for the series show a identity string (something with org.molgenis…).
![schermafbeelding 2015-02-10 om 13 45 17](https://cloud.githubusercontent.com/assets/1942445/6127435/2c2c3532-b12b-11e4-9bc3-1defc829bf5b.png)

**Comment by Mark-de-Haan** [comment]
Labels are correctly shown and mrefs are correctly split (used TypeTest)
