### ISSUE TITLE
When deleting an entity that still has foreign key constraint I get an unhelpful error message

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2456]
When I try to delete an entity that still has foreign key constraint and cannot be deleted I get an error with the exception message text, which says:

```
Error! PreparedStatementCallback; SQL [DELETE FROM `entities` WHERE `fullName` = ?]; Cannot delete or update a parent row: a foreign key constraint fails (`molgenis`.`attributes`, CONSTRAINT `attributes_ibfk_2` FOREIGN KEY (`refEntity`) REFERENCES `entities` (`fullName`)); nested exception is java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`molgenis`.`attributes`, CONSTRAINT `attributes_ibfk_2` FOREIGN KEY (`refEntity`) REFERENCES `entities` (`fullName`))
```

This message is not helpful. It would be better if there was a message that tells me exactly why the table cannot be deleted and which entities block deletion.

**Comment by erwinwinder** [comment]
The SQL error message is back again.

**Comment by dennishendriksen** [comment]
Cannot reproduce:
```Error! Cannot delete entity 'TypeTestRef' because it is referenced by the following entities: [org_molgenis_test_TypeTest]```
