### ISSUE TITLE
Inactive user can still request a new password (which doesn't work)

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2459]
Ticket http://www.molgenis.org/ticket/3404

To reproduce:
Set a user (for example admin) to active = 0.
Request a new password at login.
A new password is sent to to the admin email address. 
Password will not be valid.

A message telling the user the account is inactive should be shown.

**Comment by jjettenn** [comment]
There is a new ticket made for this enhancement (http://www.molgenis.org/ticket/3404)
