### ISSUE TITLE
JPA importer cannot update values

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2461]
Reproduce:
Import an excel with for examle RuntimeProperties, if the property already exists de importer errors, even if the "add/update" option is chosen

**Comment by bartcharbon** [comment]
same goes for "update"

**Comment by dennishendriksen** [comment]
Can be reproduced: "Tried to add existing RuntimeProperty elements as new insert ..."

**Comment by dennishendriksen** [comment]
Fixed when we drop support for JPA.

**Comment by bartcharbon** [comment]
JPA has been removed
