### ISSUE TITLE
Fix configuration jetty in molgenis/pom.xml and application poms

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2463]
Related to pull request "Move jetty plugin to pluginManagement block #1890"

When using the configuration of molgenis-app pom.xml in moilgenis-ase pom.xml the omx molgenis.home directory is used.

<pluginManagement>
	<plugins>
		
		<plugin>
			<groupId>org.mortbay.jetty</groupId>
			<artifactId>jetty-maven-plugin</artifactId>
			<configuration>
				<stopPort>8079</stopPort>
				<stopKey>jetty-stop</stopKey>
				<systemProperties>
					<systemProperty>
						<name>molgenis.home</name>
						   <value>${user.home}${file.separator}.molgenis${file.separator}omx</value>
					</systemProperty>
					<systemProperty>
						<name>log4j.configuration</name>
						<value>log4j-molgenis.properties</value>
					</systemProperty>
				</systemProperties>
			</configuration>
		</plugin>
	</plugins>
</pluginManagement>

It seems that the configurations in the pluginManagement block in the app pom is not used. The configuration in the Molgenis pom.xml is used.

The second problem is that when using de following configuration in the ase app:
<plugin>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-maven-plugin</artifactId>
            <version>9.2.6.v20141205</version>
            <configuration>
                <stopPort>8079</stopPort>
                <stopKey>jetty-stop</stopKey>
                <reload>manual</reload>
                <systemProperties>
                    <systemProperty>
                        <name>molgenis.home</name>
                        <value>${user.home}${file.separator}.molgenis${file.separator}ase</value>
                    </systemProperty>
                </systemProperties>
            </configuration>
        </plugin>
The clean install is also starting the jetty server.

**Comment by mswertz** [comment]
how often/when do we encounter this bug?

**Comment by dennishendriksen** [comment]
@tommydeboer is this the same issue you encountered for bbmri-eric?

**Comment by tommydeboer** [comment]
Yes it's the same issue (see #4113). Also, when doing a clean install for the bbmri-eric app it doesn't start the jetty server so I can't reproduce that part of the problem, which makes me think that's fixed too (see #4114 and #4118).
