### ISSUE TITLE
Search on lifelines catalog not working properly

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2477]
Renier zegt: Het lijkt dat zoeken op itemcode niet meer werkt in Molgenis18/36?
Bijv zoeken op “DEMO4A” levert geen zoekresultaten op.

Eerste bevindingen na e.e.a geprobeerd te hebben:
curl localhost:9200/molgenis/protocolTree-257811/_search?q=DEMO4A
levert op de server(ssh) resultaat, via de MOLGENIS web interface niet

Het lijkt fout te gaan met zoektermen met getallen en cijfers gemixt, tokenizer issue?

**Comment by mswertz** [comment]
is this done with this commit?

**Comment by mswertz** [comment]
tested at http://catalogue.lifelines.nl 
Cannot reproduce anymore.
