### ISSUE TITLE
The R api does not take into account the types of each column when using the R read.csv

### ISSUE THREAD

**Issue by mark-de-haan** [molgenis/molgenis#2486]
As a result a string Allele which is 'T' will be interpreted as TRUE.

**Comment by fdlk** [comment]
How does this relate to https://github.com/Mark-de-Haan/molgenis/commit/434e8a0ee9cba40de81c7b05b7d44eb21edeea3d ? Did that fix this?

**Comment by Mark-de-Haan** [comment]
No, this can be fixed in molgenis.R.ftl
There are some fixme comments and an example on how to fix. We just need to loop through the attribute meta data and get every type to create a vector. This can then be added to the csv read method.
