### ISSUE TITLE
Update through REST api disgregards existing attributes

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2492]
Based on the api docs, I'd expect to be able to update a runtime property's value by sending

    PUT api/v1/RuntimeProperty/29
    { "Value" : true }

But the updateInternal method in the RestController disregards all existing attributes of the existing entity and therefore complains that the non-nillable attribute "Name" is not being updated.

**Comment by dennishendriksen** [comment]
To update one entity attribute:
```
PUT api/v1/RuntimeProperty/29/Value
true
```

**Comment by fdlk** [comment]
so which of the both should be corrected? the docs or the code?

**Comment by mswertz** [comment]
By the looks of the reply of Dennis the code?

**Comment by mswertz** [comment]
Huh, comment to myself: by the looks of reply Dennis the docs :-)

**Comment by mswertz** [comment]
I updated the docs
