### ISSUE TITLE
Importing workflow from the same directory into DB

### ISSUE THREAD

**Issue by georgebyelas** [molgenis/molgenis#2497]
N.B. wait until compute UI stories have been completed.

When importing workflow into DB, it is call as the name of folder, where it leaves. If user imports from the same directory, the import fails, existing in DB workflow also disappears. DB should be dropped, because nothing works even after restart - > Danger! PreparedStatementCallback

**Comment by dennishendriksen** [comment]
Not on the master branch but on the [Compute UI plugin branch](/molgenis/molgenis/tree/feature/molgenis-compute-ui).

**Comment by Mark-de-Haan** [comment]
ComputeUI branch is stale, closing this.
