### ISSUE TITLE
MySQL database contains MyISAM tables for tags and script tables

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2512]
'attributes_tags', 'MyISAM', '10', 'Dynamic', '0', '0', '0', '281474976710655', '2048', '0', NULL, '2015-02-23 10:50:54', '2015-02-23 10:50:54', NULL, 'latin1_swedish_ci', NULL, '', ''
'entities_tags', 'MyISAM', '10', 'Dynamic', '0', '0', '0', '281474976710655', '2048', '0', NULL, '2015-02-23 10:50:54', '2015-02-23 10:50:54', NULL, 'latin1_swedish_ci', NULL, '', ''
'packages_tags', 'MyISAM', '10', 'Dynamic', '0', '0', '0', '281474976710655', '2048', '0', NULL, '2015-02-23 10:50:54', '2015-02-23 10:50:54', NULL, 'latin1_swedish_ci', NULL, '', ''
'script_parameters', 'MyISAM', '10', 'Dynamic', '0', '0', '0', '281474976710655', '2048', '0', NULL, '2015-02-23 10:50:58', '2015-02-23 10:50:58', NULL, 'latin1_swedish_ci', NULL, '', ''

**Comment by mswertz** [comment]
AFAIK it is fixed now.
