### ISSUE TITLE
Importing VCF allows NaN as a valid Float value, but data explorer hangs on it

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#2528]
When encountering NaN, rendering of the table stops and this error is thrown:

10:41:00.822 [qtp2022171123-27] ERROR o.molgenis.data.rest.RestController - 
java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
	at com.google.gson.Gson.checkValidFloatingPoint(Gson.java:296) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson.access$000(Gson.java:97) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson$3.write(Gson.java:264) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson$3.write(Gson.java:250) ~[gson-2.2.4.jar:na]

Mini VCF file to reproduce bug:
```
##fileformat=VCFv4.1
##INFO=<ID=TDT,Number=1,Type=Float,Description="Test statistic from Wittkowski transmission disequilibrium test.">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	880639	rs113796517	TC	T	1553.49	.	TDT=NaN;
```

**Comment by fdlk** [comment]
NaN isn't valid JSON, so storing it does not seem wise.
Elasticsearch will convert to 0 if it encounters it, MySQL won't accept it either.
Shall we convert to 0 instead or to null?
