### ISSUE TITLE
Uninformative error message when choosing an Entity name that's already in use.

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2530]
Ticket: http://www.molgenis.org/ticket/3403

When uploading a VCF file, you can input an Entity name. When this name has already been used, validation fails with the standard error: "File did not pass validation see results below. Please resolve the errors and try again."
No further information is specified to explain what went wrong.

**Comment by jjettenn** [comment]
There is a new ticket made for this enhancement (http://www.molgenis.org/ticket/3403)
