### ISSUE TITLE
Loading OBO ontology file the ontology IRI will be wrong

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#2534]
When loading the OBO file, the ontology IRI extracted from ontology using OWLAPI will  give a wrong IRI, the ontologymananger takes the name of the file and replace last part of the ontology IRI with it. It is probably due to the reason that OWLAPI does not work well with OBO file because Protege cannot read some of the OBO files probably either. 

E.g. 
Filename ----> test.obo.zip
IRI ------------->www.purl.ontology/obo/hp 
OntologyManager replaces the www.purl.ontology/obo/hp with www.purl.ontology/obo/test.obo

How to reproduce:
Upload obo.zip file (molgenis-ontology/src/test/resources/molgenis.test.obo.zip) into the generic importer

**Comment by mswertz** [comment]
I thought we wouldn't support OBO?

**Comment by dennishendriksen** [comment]
@ChaoPang could you please reply to the support OBO question?

**Comment by ChaoPang** [comment]
In theory we would like to support OBO, but technically the resulting ontology might not be correct as the issue describes the problem above. It's not really a showstopper but it'd be great to fix it one day.

**Comment by dennishendriksen** [comment]
@ChaoPang Did uploading ```molgenis-ontology/src/test/resources/molgenis.test.obo.zip``` work before?

**Comment by ChaoPang** [comment]
@dennishendriksen The issue is, it used to work (probably still works) for some OBO ontologies (the real ontologies that I used), but it did not work for the demo ontology we created sometime ago. Because we are using the third-party library (OWL-API), it's not really within our power if the the read ontology by this API yields a wrong IRI/URI, the problem still needs to be investigated.

**Comment by dennishendriksen** [comment]
Cannot reproduce in 8.0.0-SNAPSHOT, the IRI for our only obo example is correct.
