### ISSUE TITLE
IOException while loading persisted sessions

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2540]
Reproduce:
- Start Tomcat
- Log in
- Restart Tomcat
 
Produces: 
SEVERE: IOException while loading persisted sessions: java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.molgenis.data.FileRepositoryCollectionFactory
java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.molgenis.data.FileRepositoryCollectionFactory

**Comment by mswertz** [comment]
duplicate with other session bugs or is this a seperate issue? If duplicate it can be closed

**Comment by mswertz** [comment]
how often does this result in problems?

**Comment by mswertz** [comment]
duplicate with #2763
