### ISSUE TITLE
Searching for chr:pos-pos or chr:pos in the dataexplorer throws errors

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2541]
Reproduce:
- Import a mutation test set
- In the dataexplorer search, search for 1:10050000 or 1:10050000-10050004

Expected:
Either an exact hit or a range of items

Observed:
Error saying: Expected String but found BEGIN_OBJECT

**Comment by mswertz** [comment]
What is this applied to? How about chromosome?

On Thu, Feb 26, 2015 at 11:36 AM, Mark de Haan <notifications@github.com>
wrote:

> Reproduce:
>
>    - Import a mutation test set
>    - In the dataexplorer search, search for s1: 1:10050000 or s2:
>    1:10050000-10050004
>
> Expected:
> Either an exact hit with s1 or a range of items for s2
>
> Observed:
> Error saying: Expected String but found BEGIN_OBJECT
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/2541>.
>



-- 
Morris A. Swertz
Associate Professor Big data in biomedicine
Lead BBMRI-NL common services for IT
Head Section Systems Genetics & Genomics Coordination Center
Dept of Genetics
University Medical Center Groningen
The Netherlands

**Comment by Mark-de-Haan** [comment]
If you have a chromosome column and a position column (like every genomic
dataset) you can query a range with the chr:pos or chr:pos-pos format.
Patrick wanted this for ASE and its a working bit of javascript in the
master now as well.

Underwater it sets filters for the chromosome and pos columns

On 26 February 2015 at 11:59, Morris Swertz <notifications@github.com>
wrote:

> What is this applied to? How about chromosome?
>
> On Thu, Feb 26, 2015 at 11:36 AM, Mark de Haan <notifications@github.com>
> wrote:
>
> > Reproduce:
> >
> > - Import a mutation test set
> > - In the dataexplorer search, search for s1: 1:10050000 or s2:
> > 1:10050000-10050004
> >
> > Expected:
> > Either an exact hit with s1 or a range of items for s2
> >
> > Observed:
> > Error saying: Expected String but found BEGIN_OBJECT
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/molgenis/molgenis/issues/2541>.
> >
>
>
>
> --
> Morris A. Swertz
> Associate Professor Big data in biomedicine
> Lead BBMRI-NL common services for IT
> Head Section Systems Genetics & Genomics Coordination Center
> Dept of Genetics
> University Medical Center Groningen
> The Netherlands
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/2541#issuecomment-76159206>.
>



-- 
Mark de Haan
Genomics Coordination Centre
Genetics Department
University Medical Centre Groningen

**Comment by mswertz** [comment]
perfect.

On Thu, Feb 26, 2015 at 12:24 PM, Mark de Haan <notifications@github.com>
wrote:

> If you have a chromosome column and a position column (like every genomic
> dataset) you can query a range with the chr:pos or chr:pos-pos format.
> Patrick wanted this for ASE and its a working bit of javascript in the
> master now as well.
>
> Underwater it sets filters for the chromosome and pos columns
>
> On 26 February 2015 at 11:59, Morris Swertz <notifications@github.com>
> wrote:
>
> > What is this applied to? How about chromosome?
> >
> > On Thu, Feb 26, 2015 at 11:36 AM, Mark de Haan <notifications@github.com
> >
> > wrote:
> >
> > > Reproduce:
> > >
> > > - Import a mutation test set
> > > - In the dataexplorer search, search for s1: 1:10050000 or s2:
> > > 1:10050000-10050004
> > >
> > > Expected:
> > > Either an exact hit with s1 or a range of items for s2
> > >
> > > Observed:
> > > Error saying: Expected String but found BEGIN_OBJECT
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/molgenis/molgenis/issues/2541>.
> > >
> >
> >
> >
> > --
> > Morris A. Swertz
> > Associate Professor Big data in biomedicine
> > Lead BBMRI-NL common services for IT
> > Head Section Systems Genetics & Genomics Coordination Center
> > Dept of Genetics
> > University Medical Center Groningen
> > The Netherlands
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/molgenis/molgenis/issues/2541#issuecomment-76159206
> >.
> >
>
>
>
> --
> Mark de Haan
> Genomics Coordination Centre
> Genetics Department
> University Medical Centre Groningen
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/2541#issuecomment-76162344>.
>



-- 
Morris A. Swertz
Associate Professor Big data in biomedicine
Lead BBMRI-NL common services for IT
Head Section Systems Genetics & Genomics Coordination Center
Dept of Genetics
University Medical Center Groningen
The Netherlands
