### ISSUE TITLE
Unable to view dataexplorer with "view" permissions if "editable dataexplorer" is true

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2546]
Current behaviour: If the RTP for the editable dataexplorer is true, a "view-only" user gets a login screen for the dataexplorer.

Expected behaviour: the dataexplorer should be shown for this user without the edit controls.

For example for the mutationsdatabases we would like to have a system where admins can enter and update data, and anonymous uses viewing the data.

**Comment by jjettenn** [comment]
This happens only with an anonymous user
