### ISSUE TITLE
The integrated dataset with the same name is not properly created second time using the same mapping project once the attribute mapping has updated

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#2587]
How to reproduce:
- Generate integrated data with name test
- Update of the attribute mappings
- Generate integrated data again with name test
- the integrated data is not updated and the old data is shown

**Comment by Mark-de-Haan** [comment]
It is not possible to create an entity with the same name.
![screen shot 2015-07-22 at 16 08 11](https://cloud.githubusercontent.com/assets/3625016/8827246/e2b95ab6-308b-11e5-8e0e-961bf361bc28.png)
