### ISSUE TITLE
New data api breaks in-place annotation of entities

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2599]
When you run the annotator on an entity in the mysql repository without checking the copy checkmark, a NullPointer exception is thrown.
The new attribute gets added as a compound attribute but somehow the repository tries to determine its MySQL datatype, which does not exist for compound attributes.

**Comment by mswertz** [comment]
How often does this happen? If always then this bug should be labeled as 'critical'

**Comment by mswertz** [comment]
await redesign of the annotators?

**Comment by bartcharbon** [comment]
Cannot reproduce, annotated multiple EMX sets with the "latest and greatest" molgenis without any problems. It was probably broken between releases. But there in all recent releases the annotation without copying works fine.
