### ISSUE TITLE
Filterwizard shows wrong fields for COMPOUND attribute

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#2610]
When you have a COMPOUND attribute the wizard should show a  separate tab containing the attribute parts of the COMPOUND attribute but it shows the root attributes
![screen shot 2015-03-10 at 12 43 29](https://cloud.githubusercontent.com/assets/116559/6574296/8c2d4648-c723-11e4-9688-07aa73a35754.png)
.

**Comment by Mark-de-Haan** [comment]
Only the first time it correctly displays the attribute parts.
