### ISSUE TITLE
Missing refEntity while uploading, even though refEntity metadata is present

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2613]
To reproduce:

Upload the DICOM model https://github.com/molgenis/molgenis/blob/master/molgenis-model-registry/src/test/resources/DICOM_MODEL.xlsx. 

It will not upload due to a mising refEntity (dicom_IssuerOfPatientID), even though it's described in the entities tab.

**Comment by fdlk** [comment]
Check makes no sense anymore now that the attributes get imported before the entities.

**Comment by mswertz** [comment]
I have just succesfully imported DICOM in current build.
I conclude 'cannot reproduce anymore'.
