### ISSUE TITLE
GAF list --- after validation error after pushing the back button. 

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2614]
Reproduce:
Upload the file gaflist_demodata_EMX_v20141111_FlowExport_correct_incorrect.csv
After validation push the back button. 

Error:
HTTP ERROR 404
Problem accessing /plugin/gaflistimporter//menu/plugins/gaflistimporter. Reason:
    Not Foun

URL: http://localhost:8080/menu/plugins/gaflistimporter/%2Fmenu%2Fplugins%2Fgaflistimporter

**Comment by dennishendriksen** [comment]
The Gaf list importer plugin was removed in MOLGENIS 2.0
