### ISSUE TITLE
When mapping xref attributes, the test method reports 0 valid entries even though the actual mapping works fine.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2616]
To reproduce:

Upload chao's original dataset with xrefs (see https://github.com/molgenis/molgenis/pull/2615)
molgenis/molgenis-data-mapper/src/test/resources/example_data_bbc.xlsx

Map lifelines gender to hop using the mapping formula
1-$('LifeLines_GENDER');

Push the test button, it'll say "Error! There are no values generated for this algorithm".
But when you create the integrated dataset, the values are filled properly.

**Comment by bartcharbon** [comment]
Problem was that the algorithm gives you a Double, the toString is than 0.0 or 1.0, while the identifier of the xref should be 0 or 1. 
Fixed by using the import org.mozilla.javascript.Context helper class to construct the String, just like when actually converting the dataset...
