### ISSUE TITLE
Cannot delete entities in some cases

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2688]
Entities cannot be deleted even if the concrete entities that refer to them are deleted first when the reference is defined in an abstract entity. The abstract entity cannot be deleted.

How to reproduce
- Upload an EMX file that has entities B and C, where entity B extends entity A and entity A contains a reference to entity C.
- Delete entity B
- Try to delete entity C

Actual result:
- SQL error when trying to delete entity C

Expected result:
- The abstract entity A is deleted when entity B is deleted and it is possible to delete entity C.

**Comment by erwinwinder** [comment]
Could not be reproduced by David in 1.5.0
