### ISSUE TITLE
If you set a menu item with a query string as first plugin, on logging in that query string is ignored

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2692]
Reproduce:

1. Upload TypeTest dataset
2. Create a data explorer plugin with the query string: entity=org_molgenis_test_TypeTest and name it it TypeTest
4. logout and login.

Result: TypeTest is higlighted, the data explorer is shown, but the url is is not correct so TypeTest is not shown

**Comment by mswertz** [comment]
cannot reproduce. I tested in Chrome using  1.7.0-SNAPSHOT and using entity=LifeLines
