### ISSUE TITLE
Javascript error when the import reports a data validation error

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#2704]
When you upload an EMX file and the importer reports a validation error you get a javascript error.
![screen shot 2015-03-27 at 14 05 56](https://cloud.githubusercontent.com/assets/116559/6868285/a48b3924-d48a-11e4-9952-f6e4d09ef3ca.png)

**Comment by mswertz** [comment]
I cannot reproduce. Can you provide specific example file?
