### ISSUE TITLE
Max input length is not validated in forms

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2706]
Things break when the maximum input length is exceeded in text fields. Should be validated at client and server side.

**Comment by tommydeboer** [comment]
Things break when the maximum input length is exceeded in text fields. Should be validated at client and server side.

**Comment by dennishendriksen** [comment]
Remaining issues:
- Validation should occur both on client and server (e.g. this will enable validation during import)
- Validation should occur for multiple data types, not string only
- Max length should be defined on data type, not hardcoded
