### ISSUE TITLE
Pathways plugin does not show uploaded VCF

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2740]
On a server with multiple uploaded VCF's, none are shown in the dropdown for the pathways module.

The samples and no_samples VCFs from the molgenis git were used.

Tested with IE9

**Comment by Mark-de-Haan** [comment]
This is because the pathway plugin needs to have an EFFECT parameter inside the INFO field. Else it cannot use colours. We should make it so it does something with numbers to show how many variants are in a gene when no EFFECT parameter is available.

**Comment by bartcharbon** [comment]
Fix by explaining this in the text on the VCF selection page and create a separate enhancement for the solution Mark suggests?
