### ISSUE TITLE
In IE9 all content under the table is increasingly pushed down on hover of an x/mref

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2755]
select typeTest

hover over an x/mref link
- the scrollbar will change, and content under the table will be pushed down, an increasing region of whitspace will be shown...

**Comment by fdlk** [comment]
SCROLLLLbar

**Comment by fdlk** [comment]
Extremely annoying, it pushes the pagination away.

**Comment by bartcharbon** [comment]
http://stackoverflow.com/questions/7445750/ie9-link-hover-css-color-change-vertical-shift
