### ISSUE TITLE
If user logs out while uploading an ontology, ontology gets partly imported, transaction does not get rolled back.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2757]

**Comment by Mark-de-Haan** [comment]
Can not reproduce

**Comment by Mark-de-Haan** [comment]
Same comment as on #2758
We are going to take a look at the technical implementation of Ontology uploading and storing in the comming sprints so do not think this issue should be resolved for the comming release

**Comment by fdlk** [comment]
Possibly due to #2793 ?

**Comment by dennishendriksen** [comment]
Cannot reproduce.
1) Downloaded http://purl.obolibrary.org/obo/hp.owl and zipped as hp.owl.zip
2) Start import of hp.owl.zip
3) Log out after import has been running for a while
No entries added to Ontology* entities and no entries added to entities/attributes tables.
