### ISSUE TITLE
Large ontology import is excruciatingly slow

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2758]
Download HPO owlfile from http://www.human-phenotype-ontology.org/contao/index.php/hpo_home.html ,zip it and upload to the server.

File is 28MB, contains 13078 ontology terms, zipped it is 1.7MB.

Importer reads the file just fine, but importing takes 1780 seconds / half an hour

**Comment by fdlk** [comment]
Unsure of the cause, could be the switch to TEXT datatype?
Could be that molgenis62 is too slow?
Used to work on my laptop.

**Comment by mswertz** [comment]
Where is the time lost? Do we have logging to unravel this?

On Wed, Apr 8, 2015 at 3:43 PM, Fleur Kelpin <notifications@github.com>
wrote:

> Download HPO owlfile from
> http://www.human-phenotype-ontology.org/contao/index.php/hpo_home.html
> ,zip it and upload to the server.
>
> File is 28MB, zipped it is 1.7MB.
>
> Importer reads the file just fine, but importing takes > 15 minutes.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/2758>.
>



-- 
Dr. Morris A. Swertz
Associate Professor - Big data in biomedicine
Coordinator BBMRI-NL common services for IT
Coordinator Health sector in DTL/ELIXIR-NL
Head Section Systems Genetics & Genomics Coordination Center

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by fdlk** [comment]
The logfile stays silent after "Import started"

**Comment by mswertz** [comment]
Right, so unclear if this has to do with
- parsing of the OWL
- batching of the inserts,
- writing to disk
etc

On Wed, Apr 8, 2015 at 3:51 PM, Fleur Kelpin <notifications@github.com>
wrote:

> The logfile stays silent after "Import started"
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/2758#issuecomment-90922952>.
>



-- 
Dr. Morris A. Swertz
Associate Professor - Big data in biomedicine
Coordinator BBMRI-NL common services for IT
Coordinator Health sector in DTL/ELIXIR-NL
Head Section Systems Genetics & Genomics Coordination Center

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by fdlk** [comment]
cranked up the amount of logging and now I see a lot of
16:02:20.776 [pool-2-thread-15] DEBUG o.m.d.e.ElasticSearchService - Searched Elasticsearch 'Ontology_OntologyTermNodePath' docs using query [QueryImpl [rules=[], pageSize=1000, offset=108000, sort=null]] in 1ms
(though 1ms is fast, I'd think :) )

**Comment by fdlk** [comment]
Had to reboot the server before I could access OntologyTerms again.

**Comment by fdlk** [comment]
Is also slow on my laptop now, I think we changed something. CPU is low, memory too, only threads that are active are elasticsearch.

**Comment by fdlk** [comment]
Insertion of the OntologyTerms is the slow one. The repository searches the already imported repositories through the dataService for the entities to use. Could be that that's the slow bit. Not sure.

**Comment by fdlk** [comment]
The importer suffers from the [n+1 selects problem](http://stackoverflow.com/questions/97197/what-is-the-n1-selects-issue). When importing the OntologyTerms, the references to synonyms, nodepath, dynamicAnnotations and ontology are retrieved using separate selects for each OntologyTerm.

When inserting, several decorators iterate over the terms to insert.

For each of these iterations, for each OntologyTerm, 4 selects are executed.

I made the lookup lazy by switching from MapEntity to DefaultEntity. That helped a bit. But all in all we're killing our performance here in an attempt to be memory-efficient.

**Comment by Mark-de-Haan** [comment]
We have a story in the backlog to look at how we deal with ontology imports and ontology deletions. Might be an idea to exclude this problem from the comming release

**Comment by fdlk** [comment]
I don't think it's all that hard to fix.
