### ISSUE TITLE
Sessions are not properly serialized when restarting tomcat

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2763]
When restarting tomcat, deserializing of serialized sessions fails.
In catalina.out, I see a java.io.NotSerializableException: org.molgenis.data.FileRepositoryCollection.

**Comment by Mark-de-Haan** [comment]
Cannot reproduce by simply restarting tomcat

**Comment by fdlk** [comment]
You have to log in first, I think.

**Comment by fdlk** [comment]
Importer writes security context to your session.

    session.setAttribute("SPRING_SECURITY_CONTEXT", securityContext);

**Comment by mswertz** [comment]
duplicate bug

**Comment by mswertz** [comment]
how often does this happen, i.e., is this a problem we face regularly?

**Comment by dennishendriksen** [comment]
> how often does this happen, i.e., is this a problem we face regularly?
@jelmerveen ran into this issue on a MOLGENIS deployed on the edge cluster.

Due to the nature of the current deployment ecosystem (kill something if it isn't ok and fire up a new instance) I expect it to happen more often.
