### ISSUE TITLE
Importer permissions panel Save button does not look like a button

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2765]
The save button for the new permissions dialog you get after importing is not a proper button, but looks more like a link.

Probably happens cause it has no border? Looks nicer on the screenshot than in reality :)

![screen shot 2015-04-08 at 16 41 02](https://cloud.githubusercontent.com/assets/1523838/7047637/146e3a8e-de0e-11e4-86ac-77c8b6172693.png)

**Comment by Mark-de-Haan** [comment]
Simple fix is to set the class to btn-primary or btn-default
