### ISSUE TITLE
Disabled scrollbar in mapping service

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2766]
Create a mapping project with target entity HOP.
You'll see a disabled scrollbar to the right of the attributes table.

![screen shot 2015-04-08 at 16 48 24](https://cloud.githubusercontent.com/assets/1523838/7047795/1ffdea92-de0f-11e4-995c-2b702fbc0b43.png)

**Comment by Mark-de-Haan** [comment]
Not reproducible in Chrome

**Comment by fdlk** [comment]
Screenshot is in safari

**Comment by jjettenn** [comment]
Test on your own laptop, not with the external screens

**Comment by jjettenn** [comment]
See PR
