### ISSUE TITLE
When CHROM / POS columns are hidden and you click a genetic data row, you get "viewFeatures called with silly scale"

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2768]
Happened right now after deleting TypeTest entity on molgenis62, when data explorer responded by returning to testSamples_KEGG entity.

Also seen it during the automated annotator test.

No clear way to reproduce it yet.

**Comment by Mark-de-Haan** [comment]
Can not reproduce

This is probably a timing issue between getting the entity 
information and loading the genome browser.

**Comment by mswertz** [comment]
cannot reproduce

**Comment by fdlk** [comment]
Managed to reproduce it now.
On molgenis62, open appelflap_clinvar.
Deselect all.
Select SAMPLES.
Click the first sample.

viewFeatures called with silly scale

**Comment by bartcharbon** [comment]
Still broken if column is shown but with an empty value

**Comment by fdlk** [comment]
Saw this again today, selenium test manages to provoke it when swapping between entities and tabs.
