### ISSUE TITLE
Migration does not update menu (entity instead of dataset)

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2769]
Dataexplorer urls in the older versions have an url param "dataset", this has been changed to "entity"

**Comment by fdlk** [comment]
Where do we think this should be changed?
The migration code is intended as a metadata migration, but does have the whole mechanism in place to do it.

**Comment by fdlk** [comment]
Low-cost alternative would be to add it to a yet-to-be-created upgrade howto.
