### ISSUE TITLE
As user I get obscure error messages if I try to upload an EMX file that has already been uploaded by someone else

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2814]
As normal user, upload the all datatypes file that the admin user has also uploaded (but that you have no rights for)

You'll get an error message saying

"Unable to get value of the property 'length': object is null or undefined"
And a somewhat more informative message
"No COUNT permission on entity org_molgenis_test_TypeTestRef"

I'd expect the validation to check this sort of thing before the actual import starts.

**Comment by Mark-de-Haan** [comment]
The first error is caused by the javascript trying to create the permission box. It will check the length of the importedEntities but if the import failed then importedEntities is undefined.
