### ISSUE TITLE
HTTP status 500 hiccups when Safari 8 or 9 surfs to molgenis.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2816]
When testing with multiple developers on a molgenis target vm, the server has more than once become unreachable.
When I send a kill -quit to the tomcat process, all threads look to be waiting for work.
However, Apache is sending out 500 errors with 1 minute delays in between.

Restarting both httpd and tomcat7 helps.

This has happened more than once.

**Comment by fdlk** [comment]
In /etc/httpd/logs/error_log, repeatedly:
````
[Tue Apr 14 12:48:31 2015] [error] (70007)The timeout specified has expired: ajp_ilink_receive() can't receive header
````

In /etc/httpd/logs/ssl_error_log, repeatedly:
````
[Tue Apr 14 12:48:31 2015] [error] ajp_read_header: ajp_ilink_receive failed
[Tue Apr 14 12:48:31 2015] [error] (70007)The timeout specified has expired: proxy: read response failed from [::1]:8009 (localhost)
````

Threaddump was at 12:48:59.
Shows the full 200 ajp-bio-8009-exec threads all doing
````
"ajp-bio-8009-exec-200" #2776 daemon prio=5 os_prio=0 tid=0x00007f2a2c1a4800 nid=0x1b18 runnable [0x00007f298f1dd000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:150)
        at java.net.SocketInputStream.read(SocketInputStream.java:121)
        at org.apache.coyote.ajp.AjpProcessor.read(AjpProcessor.java:312)
        at org.apache.coyote.ajp.AjpProcessor.readMessage(AjpProcessor.java:367)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:118)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        - locked <0x0000000085b4dc60> (a org.apache.tomcat.util.net.SocketWrapper)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
````

**Comment by fdlk** [comment]
People seem to advise adding a timeout to the AJP connector pool:
````
<!-- Define an AJP 1.3 Connector on port 8009 -->
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443"
connectionTimeout="300000" />
````

**Comment by fdlk** [comment]
Trying that out on molgenis62 now.

**Comment by mswertz** [comment]
Apparantly a showstopper. How often does this load happen? If often, than this becomes a critical bug

**Comment by fdlk** [comment]
The log lines still occur on molgenis62.

**Comment by fdlk** [comment]
Something else to look at: INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib

**Comment by fdlk** [comment]
APR might actually help, see http://tomcat.apache.org/tomcat-5.5-doc/apr.html#AJP:
> When APR is enabled, the AJP connector will use a socket poller for keepalive, increasing scalability of the server.

**Comment by fdlk** [comment]
Since AJP is becoming more and more suspect, here's some background information:

![ajp](https://cloud.githubusercontent.com/assets/1523838/9106981/4753ad52-3c24-11e5-9649-ae90d80de743.png)
# Official documentation for the components
## AJP protocol
http://tomcat.apache.org/connectors-doc/ajp/ajpv13a.html

Explains that the AJP connections are supposed to be established once and kept open forever.
A connection can be in one of two states: Idle or Assigned.
When assigned, the connection handles one specific request.
This ends when the servlet container is done sending the response body and sends END_RESPONSE

## mod_proxy_ajp
http://httpd.apache.org/docs/2.2/mod/mod_proxy_ajp.html

There’s one alternative, namely [mod_jk](http://tomcat.apache.org/connectors-doc/).

## Tomcat AJP connector
https://tomcat.apache.org/tomcat-7.0-doc/config/ajp.html

Explains that there are three different implementations
We use the blocking Java version of the AJP connector, since there is no native APR present on our machines.
There’s two alternative implementations, namely a java nio and an APR version.
https://tomcat.apache.org/tomcat-7.0-doc/apr.html

# Our VM configuration

The [Molgenis new VM SOP](http://www.molgenis.org/wiki/GccSopCreateMolgenisVM) lists the Apache config that sysops install when creating a new VM.

The most AJP-specific bit is
```
#
# Forward everything @ port 443 to Tomcat AJP connector running @ port 8009
#
ProxyPass        / ajp://localhost:8009/
ProxyPassReverse / ajp://localhost:8009/
#
# Identify the originating protocol of an HTTP request as HTTPS
#
RequestHeader set X-Forwarded-Proto "https" 
```
(The mod_proxy_ajp documentation claims that default configuration should work fine and says that ProxyPassReverse should not be necessary.)

But there's also other possibly relevant specific configuration in there, for instance we also install mod spdy and enable compression.

The molgenis SOP lists the AJP connector configuration:
```
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" maxPostSize="33554432" URIEncoding="UTF-8" scheme="https" proxyPort="443”/>
```

Without root access we can only execute the following two commands to get apache logging:

    /usr/bin/less /var/log/httpd/ssl_error_log
    /usr/bin/less /var/log/httpd/error_log

Stumbled upon VMWare KB article on how to configure this setup:
http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2007800

**Comment by fdlk** [comment]
Ran into a bugging molgenis01 this morning and ran netstat. There's 251 connections to 8009. 200 of them ESTABLISHED and 51 CLOSE_WAIT. That seemed off but a little googling shows that it is normal for mod_proxy to only check connection status when it is about to reuse one and to keep them open regardles of if tomcat has closed them.

**Comment by fdlk** [comment]
We can set debug attribute on the AJP Connector, tomcat-side.

**Comment by fdlk** [comment]
Yes! It's quite easily reproducible: Go to the dataexplorer and spam the reload button.

**Comment by fdlk** [comment]
can add more debugging tomcat-side by adding lines to `apache-tomcat/conf/logging.properties`
e.g.
```
org.apache.level = FINEST
org.apache.catalina.loader.level = INFO
org.apache.jasper.level = INFO
org.apache.tomcat.util.digester.level = INFO
org.apache.tomcat.util.file.level = INFO
org.apache.tomcat.util.scan.level = INFO
org.apache.naming.level = INFO
org.apache.catalina.startup.level = INFO
```

Make sure to also set the in-between logger's levels to FINEST:
```
1catalina.org.apache.juli.FileHandler.level = FINEST
java.util.logging.ConsoleHandler.level = FINEST
```

**Comment by fdlk** [comment]
Found it!! https://bz.apache.org/bugzilla/show_bug.cgi?id=53173

**Comment by fdlk** [comment]
The issue goes away if I switch to the nio protocol:
`protocol="org.apache.coyote.ajp.AjpNioProtocol"`
Unfortunately, then the amount of open connections keeps going up. After 1160 requests, the latch is now at 1160 and netstat gives me 1160 ESTABLISHED connections which seems a bit much.

**Comment by fdlk** [comment]
Latch only, and reliably, increases when I surf to molgenis using Safari, not when I surf using Chrome.

**Comment by fdlk** [comment]
So, for some reason, when safari surfs to molgenis some (not all) of the resource requests break the AJP connection that serves them. This means more and more connections are made until maxConnections is reached.

**Comment by fdlk** [comment]
It's definitely not in the molgenis source code. I've created a sample app on molgenis01 with a file blah.html
```
<html>
<head>
<link rel="stylesheet" href="blah1.css" type="text/css">
<link rel="stylesheet" href="blah2.css" type="text/css">
</head>
</html>
```
The .css files need not exist. When I surf to the site using safari, the latch goes up 1 step.

**Comment by fdlk** [comment]
I've found what I'd call a workaround. Adding a keepAliveTimeout to the connector

```
    <!-- Define an AJP 1.3 Connector on port 8009 -->
    <Connector port="8009" protocol="AJP/1.3" keepAliveTimeout="1000" redirectPort="8443" maxPostSize="33554432" URIEncoding="UTF-8" scheme="https
" proxyPort="443"/>
```

I can see the latch going down to zero again one second after the request.

**Comment by fdlk** [comment]
Wireshark shows that Safari only creates one SSL connection for all three requests. So I thought it's perhaps due to mod_spdy. When I run chrome from the command line with --use-spdy it also begins to leave lingering AJP connections. So my bet is that mod_proxy_ajp doesn't play nice with mod_spdy and disabling mod_spdy will properly solve this issue.

**Comment by fdlk** [comment]
Disabled mod_spdy on molgenis01, everything works like a charm. So all that's left to do is to disable mod_spdy on our servers and the golden vm image.

**Comment by dennishendriksen** [comment]
Issue was reported here: https://code.google.com/p/mod-spdy/issues/detail?id=98
