### ISSUE TITLE
Wizard stores too much info in the user's session

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2825]
The ImportWizard (and all other wizards that extend from the general molgenis Wizard class) get stored entirely into the user session, including their controller-like pages.

It should only be user state that ends up in the session. So the page number and the details of the specific import job (file name, validation report, stuff like that).

The user won't notice all that much difference, to be honest. But it does mean that we cannot serialize sessions because they contain references to singleton services. See #2763 .

**Comment by Mark-de-Haan** [comment]
Story for refactoring / reimplementing importer is in the [backlog](http://wiki.gcc.rug.nl/ticket/5302)
