### ISSUE TITLE
When I need to login to view a dataset I do not return to the same page

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2826]
When you follow a URL to a specific dataset in the data explorer and you are not allowed to see it you will get a message that you might have to log in. When you log in you return to the home page instead of the page you came from.

How to reproduce:
- Setup a dataset for which you need to be logged in to view it in the data explorer.
- Setup the rights so the anonymous user can view the data explorer, but not the dataset. 
- Go to the data explorer and select the dataset.
- Copy the link to your clipboard
- Log out
- Paste the link in the address bar of your browser
- Click login & log in.

Actual result:
After logging in you are at the home page

Expected result:
After logging in you are at the data explorer and can see the data set

**Comment by Mark-de-Haan** [comment]
Can not reproduce
- I copy the URL with dataexplorer?entity=
- Logout
- Paste the url
- Login again when prompted too
- I see the data explorer

**Comment by djvanenckevort** [comment]
This happens when the anonymous user has rights to the data explorer, but not the dataset, I have updated the how to reproduce.

**Comment by Mark-de-Haan** [comment]
- I upload typetest as admin
- I set rights for anonymous users to dataexplorer to view
- I copy the URL dataexplorer?entity=org_molgenis_test_TypeTest
- I log out 
- Enter the URL

Result: I see the data explorer with an error saying I do not have permission

**Comment by djvanenckevort** [comment]
When you then try to login you will return to the main page instead of getting back at the page you were.

**Comment by Mark-de-Haan** [comment]
This does not have anything to do with the data explorer. This happens with every plugin sadly.

**Comment by mswertz** [comment]
Sounds annoying but not urgent. I suppose users can just re-click their link or browse to the dataset by hand.

**Comment by Mark-de-Haan** [comment]
Can not reproduce. You get a nice message saying you do not have permission to the dataexplorer, but you do not get redirected to the home plugin
