### ISSUE TITLE
When there are only compound attributes in an entity the data explorer starts empty

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2827]
Ticket: http://www.molgenis.org/ticket/3402

When you open an entity in the data explorer only the attributes at the root are selected. When you only have compound attributes in the data explorer this means that the data explorer starts out empty.

How to reproduce:
- Upload a data set that has only compound attributes at the root of the entity
- Go to the data explorer and select the entity

Actual results:
The DataExplorer shows an empty table

Expected results:
The DataExplorer shows the actual data

**Comment by Mark-de-Haan** [comment]
We only select first level attributes and leave compounds closed on purpose. I do not see how this would be an improvement, even if the entity only has compound attributes.

**Comment by djvanenckevort** [comment]
It confuses the user when the data explorer is empty.
Note this is about what is visible in the table, not about the tree being open or closed.

**Comment by jjettenn** [comment]
There is a new ticket made for this enhancement (http://www.molgenis.org/ticket/3402)
