### ISSUE TITLE
Bookmarkable link does not select compound attributes

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#2828]
A bookmarkable link does not select compound attributes that are specified in the link.

How to reproduce:
- Use an entity that has compound attributes
- Go to the data explorer and select the entity
- Select one of the compound attributes
- Copy the link to the clipboard
- Open a new browser window
- Paste the link in the address bar

Actual result:
The data explorer opens with the selected entity, but the compound attribute is not selected

Expected result:
The data explorer opens with the selected entity and the compound attribute is selected

**Comment by mswertz** [comment]
I don't see the link. Do I need to set runtime property?
