### ISSUE TITLE
User can see import jobs of other users

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2830]
## Reproduce
- Upload file as admin
- Upload file as normal user
- Go to data explorer ImportRun entity
## Expected
- I see only my imports
## Observed
- I see all imports

**Comment by fdlk** [comment]
If you don't want to expose this internal administration to normal users, you should simply not hand out read privileges to them, I'd think?

**Comment by Mark-de-Haan** [comment]
You do want to see imports you did yourself, problem is everything is in
one table so if you can see your own, you can see everything

On 15 April 2015 at 16:14, Fleur Kelpin <notifications@github.com> wrote:

> If you don't want to expose this internal administration to normal users,
> you should simply not hand out read privileges to them, I'd think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/2830#issuecomment-93419411>.
>



-- 
Mark de Haan
Genomics Coordination Centre
Genetics Department
University Medical Centre Groningen

**Comment by bartcharbon** [comment]
I'm fixing it, simply adding a Decorator will do the trick

**Comment by mswertz** [comment]
I suppose users can only see imports, but cannot see the actual data. If yes, then this is not critical.

**Comment by dennishendriksen** [comment]
@bartcharbon are you still fixing this?

**Comment by bartcharbon** [comment]
no, I'm not working on this.

**Comment by dennishendriksen** [comment]
ImportRun should be a Entity that extends from OwnedEntityMetaData to enable correct behaviour.

**Comment by jjettenn** [comment]
Tested with anonymous user

**Comment by jjettenn** [comment]
Tested with anonymous user, anonymous user can see ImportRun of admin
