### ISSUE TITLE
Search in forms is not working

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2834]
Select from menu entities RuntimeProperty
Search on "plugin.dataexplorer.mod.diseasematcher"
Select no column name.

By all three possibilities equals; search and like I get problems:
Equals: KaBOOM!!
---- Error! An error occurred. Please contact the administrator.
---- TypeError: null is not an object (evaluating 'n.items')
Search: all results
Like: all results

I except only one result.

**Comment by mswertz** [comment]
I propose we will not fix because the forms will be replaced with data explorer soon
