### ISSUE TITLE
POS filter is broken

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2844]
To reproduce
Browser: SAFARI
Plugin: Data Explorer
Dataset loaded: molgenis-app/src/test/resources/mutations/test_samples.vcf
Action:
1. First remove the "genomebrowser.data.chromosome" and "genomebrowser.data.start" runtime properties
2. click on attribute POS and create a filter 1=< 2
Expected: all rows
Result: 
![screen shot 2015-04-16 at 12 59 48 pm](https://cloud.githubusercontent.com/assets/5586255/7179496/c4314378-e438-11e4-90b4-38ee4f6d6ec5.png)

**Comment by mswertz** [comment]
do we expect users to encounter this bug?

**Comment by Mark-de-Haan** [comment]
no, not if we are talking about genome browser usage

**Comment by dennishendriksen** [comment]
Cannot reproduce
