### ISSUE TITLE
Updated rows are moved to the end of the list.

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#2849]
## Reproduce
- Browser: SAFARI
- Plugin: Data Explorer
- Dataset loaded: molgenis-app/src/test/resources/mutations/test_samples.vcf
- Mode: edit
- update a value in a row
- click on done
## Expected
- The updated row will stay on its position
## Observed
- The updated row is moved to the end of the list.

**Comment by mswertz** [comment]
how difficult is this to fix?

**Comment by mswertz** [comment]
ouch, very annoying. Put it on the 'first' shortlist

**Comment by fdlk** [comment]
How to fix this then? Paging order is left up to the repository and that apparently lists last updated entities last.

**Comment by dennishendriksen** [comment]
Add a sort ascending on the id attribute when requesting data.

**Comment by fdlk** [comment]
Not sure if our auto IDs are alphabetically ascending.

**Comment by dennishendriksen** [comment]
The nice fix is to under the hood append a creation date timestamp to every entity and sort on this timestamp if no sort is defined.

**Comment by mswertz** [comment]
this timestamp is also desired for other purposes.

**Comment by Mark-de-Haan** [comment]
Sounds like a feature request, added a [story](http://wiki.gcc.rug.nl/ticket/5491#ticket)
