### ISSUE TITLE
Closure compiler treats unicode javascript incorrectly

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2883]
Reproduce: Start MOLGENIS in release environment, edit a RuntimeProperty in the data explorer
Actual: The close button of the modal is rendered as 'Ã—'
Expected: The close button of the modal is rendered as 'x'

All works fine in development mode. The closure compiler replaces '\u00D7' with 'Ã—'. Workaround is to use String.fromCharCode(...) instead of specifying unicode chars.

**Comment by tommydeboer** [comment]
Still an issue on my machine with environment=production

**Comment by Mark-de-Haan** [comment]
No longer an issue with modals. + we do not edit RuntimeProperties in the data explorer anymore
