### ISSUE TITLE
Forms: xref_unique won't validate when original value is chosen

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2885]
### To reproduce:
1. Import **all_datatypes.xlsx**.
2. Open the entity and open an edit form
3. For the xxref_unique field, choose something different
4. Now change it back to its original value

### Expected:
Field validates.

### Actual:
It doesn't.

**Comment by mswertz** [comment]
If I cancel my editing, close the form and then re-open, can I then continue?

**Comment by tommydeboer** [comment]
Yes you can. Not optimal though if you just edited 50 values.

**Comment by Mark-de-Haan** [comment]
No longer an issue with react forms
