### ISSUE TITLE
Error with slashes in  entity name

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#2887]
- Upload a EMX file with an entity with slashes in the name.
- Goto the form of this entity.

Result:

![screen shot 2015-04-23 at 09 10 51](https://cloud.githubusercontent.com/assets/116559/7292111/fd1ced3a-e998-11e4-94d9-b70a5a17b56b.png)

**Comment by mswertz** [comment]
Duplicate with #2055. Solve by giving error messages "Entity names containing '-' not allowed"
