### ISSUE TITLE
Script without results extension 400 error

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2898]
Reproduce: Create the following script
![image](https://cloud.githubusercontent.com/assets/2477186/7297491/9a37c740-e9c9-11e4-89ee-50a304ae1fd4.png)

Expected: png image displayed in new tab

Actual: HTTP 400 error page with Freemarker stacktrace displayed in new tab

Editing the script and setting a result extension resolves the problem.

**Comment by Mark-de-Haan** [comment]
In the updated Script Job system, the error still persists.
Cause: not specifying a Result file extension causes the ${outputFile} parameter to be null
