### ISSUE TITLE
Static content can only be edited by super user

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2909]
Reproduce: 1) Register new user in vanilla molgenis 2) As admin give edit permissions on home plugin 3) Login as user and go to home plugin
Expected: User can edit static content
Actual: User can see but not edit static content

**Comment by dennishendriksen** [comment]
By design, but should be changed.

**Comment by mswertz** [comment]
Bad design so I call it a bug :-)

**Comment by marieke-bijlsma** [comment]
Created story for this issue (#4454).
