### ISSUE TITLE
Submit not possible with valid captcha after captcha reset

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2913]
Reproduce: 1) Navigate to Sign In --> Sign up 2) Fill in form with invalid captcha 3) Press submit 4) Reset captcha by clicking on captcha 5) Enter valid captcha
Expected: Submit button is enabled so I can sign up
Actual: Submit button is disabled

**Comment by Mark-de-Haan** [comment]
Can not reproduce
