### ISSUE TITLE
Sign up with existing username or mail address: unfriendly messages

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2914]
Reproduce: 1) Sign up with an existing username or email address
Expected: An account with username '<username>' already exists / An account with email address <emailaddress> already exists
Actual:Error! Duplicate value 'dennis3' for unique attribute 'username' from entity 'MolgenisUser' (row 2) / Error! Duplicate value 'dennis.hendriksen+dennis3@gmail.com' for unique attribute 'Email' from entity 'MolgenisUser' (row 2)

**Comment by fdlk** [comment]
Duplicates #1913.
