### ISSUE TITLE
Tag wizard tries to combine tags it finds to one big tag

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#2916]
Upload HPO ontology and the BBC test data EMX file.
Create a mapping project for entity HOP.
Run the tag wizard.

Expected: the HOP entity's attributes will be tagged with HPO terms.

Actual: Tag wizard tries to tag with a combined tag of about 25 ontology terms and fails because the combined description is too long.
Shows error message: Value must be less than or equal to 255 characters.

**Comment by tommydeboer** [comment]
The same thing happens when I try to tag MolgenisUser with HPO terms. It tries to tag it with ~90 terms.
