### ISSUE TITLE
Change default Freemarker number formatting

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#292]
The default Freemarker number formatting requires the user to add "?c" after each number variable in order for it to displayed as "1.000" for thousand. Change the default Freemarker configuration in WebAppConfig such that numbers are always displayed as "computer" numbers

**Comment by mswertz** [comment]
when is this an issue?

**Comment by dennishendriksen** [comment]
When 1) you use ${id} where id is a java int/long 2) and the number is larger than 1000 3a) and you construct a URL in freemarker (e.g. /api/v1/myentity/${id}) or 3b) construct a html id that your refer to from js.
