### ISSUE TITLE
Self referencing entity StackOverflowError

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2920]
Reproduce:
Create the following EMX file and import:

entities:
![image](https://cloud.githubusercontent.com/assets/2477186/7317758/874d1d54-ea84-11e4-8eb1-2de7b4367f59.png)
attributes:
![image](https://cloud.githubusercontent.com/assets/2477186/7317750/79a62600-ea84-11e4-81e6-2210f2b8fce3.png)
Entity:
![image](https://cloud.githubusercontent.com/assets/2477186/7317767/9246785e-ea84-11e4-8fb3-8543ab2af5c8.png)
Reference:
![image](https://cloud.githubusercontent.com/assets/2477186/7317771/98eb1f5c-ea84-11e4-98ed-eb9daa82c477.png)
NestedReference:
![image](https://cloud.githubusercontent.com/assets/2477186/7317773/a0095aa6-ea84-11e4-8e38-ed697ed6bc86.png)
SelfReference:
![image](https://cloud.githubusercontent.com/assets/2477186/7317777/a5efa70e-ea84-11e4-9dff-1c01e3d85b8d.png)

Expected: Imports successfully
Actual: 
StackOverflowError:
...
at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
...

**Comment by tommydeboer** [comment]
Fixed with #4281
