### ISSUE TITLE
Forms: int not validated when first character is invalid

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2929]
### To reproduce:
1. Upload *all_datatypes.xlsx*
2. Go to *Entities > org_molgenis_test_TypeTest*
3. Open edit form for a row
4. Empty the xcompound_int field and type some text

### Expected:
Validation message is shown and form cannot be submitted.

### Actual:
No message is shown and the form can be submitted (the field will be empty when saved).

**Comment by Mark-de-Haan** [comment]
No longer an issue
