### ISSUE TITLE
Mapping Service gives error when making/opening a project

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2932]
### To reproduce:
1. Open the Mapping Service
2. Create a new project

### Expected:
Project overview will be shown.

### Actual:
New page is opened with: ```{"errors":[{"message":"An error occurred. Please contact the administrator.<br />Message:null"}]}```

**Comment by dennishendriksen** [comment]
Cannot reproduce.

**Comment by tommydeboer** [comment]
Can reproduce again: use *tags*, *entities* or *attributes* as target entity when creating a new project.

**Comment by mswertz** [comment]
wontfix if this only relates to metadata tables
