### ISSUE TITLE
Form plugin: delete entity error IE9

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2975]
Reproduce:
- In IE9 delete RuntimeProperty in form plugin

Expected:
- Delete ok

Actual:
- Popup with the following error

Line: 1
Character: 2332
Code: 0
Error Message: Invalid character
URL: https://molgenis62.target.rug.nl/js/molgenis-form-list.min.js?ZuvDXw

**Comment by Mark-de-Haan** [comment]
Still an issue?

**Comment by dennishendriksen** [comment]
5.2.0 was the last release supporting IE9.
