### ISSUE TITLE
Form plugin: bool checkbox layout

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2976]
![image](https://cloud.githubusercontent.com/assets/2477186/7414912/f1d0cb64-ef55-11e4-8c9e-15bf77bcf9c9.png)

**Comment by fdlk** [comment]
Fixed in #3006

**Comment by dennishendriksen** [comment]
I think this fix breaks the vertical form layout (e.g. used in the questionnaire plugin).

**Comment by jjettenn** [comment]
Why do you think that it will break the vertical view?
I have tested it by changing the layout in the render method to vertical
and it works.

**Comment by dennishendriksen** [comment]
Did you test with a checkbox with and without label?
