### ISSUE TITLE
Disappearing validation error message

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#2982]
- Load emx_all_datatypes.xlsx
- Goto entities -> org_molgenis_test_TypeTest
- In the xint_unique field type an existing int (for example 2)
- You get a validation messages saying the value is not unique
- Click on the form outside the inputs
- The validation message disappears
  Saving the form fails but you don't get a validation message.

**Comment by mswertz** [comment]
Don't we get error message from the server?

**Comment by Mark-de-Haan** [comment]
Can not reproduce, React forms probably fixed this
