### ISSUE TITLE
Mapping service: summary statistics not cleared when resetting an attribute mapping

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2983]
## To reproduce
1. Go to the Mapping Service and create a mapping (for example MolgenisUser vs. MolgenisUser)
2. Edit one of the attribute mappings
3. Test the mapping by clicking Test (summary statistics will be shown at bottom of page)
4. Click Reset

## Expected
Summary statistics reset too.

## Actual
They don't

**Comment by Mark-de-Haan** [comment]
We no longer have summary statistics in the mapping service
