### ISSUE TITLE
Data mapper does not show the auto-generated algorithms until you refresh.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3020]
Go to the data mapper, create a mapping project, add tags, add a source with relevant attributes.

Expected: the generated tags will be shown.
Actual: the generated tags are only shown after you refresh the page.

This is a remnant of us trying to do it asynchronously, but since that does not work yet, it's way better to wait for the auto-generation to finish.

**Comment by Mark-de-Haan** [comment]
Fixed in the upcomming 1.8.0 release and in the master
