### ISSUE TITLE
Importer shows inconsistent markup in validation step

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3021]
In all steps, the data is shown in lovely panels, except for the validation step, which shows tables that do not have the nice panel headers.

**Comment by Mark-de-Haan** [comment]
@mswertz wontfix? We will redesign the importer soon anyway

**Comment by Mark-de-Haan** [comment]
Will be changed in importer [rewrite](http://wiki.gcc.rug.nl/ticket/4510)
