### ISSUE TITLE
After adding a runtime property the name input value is cleared

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3022]
Reproduce:
1. add a runtime property: 'app.trackingcode.header' with value alert('TEST PIWIK');
2. click create
3. name is empty

Expected: that the name will still be filled

**Comment by dennishendriksen** [comment]
The bug is the other way around. After creating an entity all inputs should be cleared to allow creation of a new entity.

**Comment by mswertz** [comment]
Indeed. So the form should be empty to create another.
Or alternively: you should see no form at all but a button: add another one?

**Comment by jjettenn** [comment]
Not relevant anymore
