### ISSUE TITLE
AutoId in MappingService fails for numeric ID's

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3033]
If your target metadata contains a numeric Id Attribute, the mapping will fail because it tries to store a UUID in an numeric field

**Comment by mswertz** [comment]
why UUID? Is this not autoid?

**Comment by fdlk** [comment]
The mapping service needs to create an ID attribute that matches the target type's entitymetadata. That probably can be done using the autoID feature of the importer but right now it always generates a uuid.

**Comment by Mark-de-Haan** [comment]
@bartcharbon How to reproduce? Mapping TypeTest to TypeTest seems to work

**Comment by Mark-de-Haan** [comment]
in v5: When validating your mapping, trying to insert a UUID into an INT field will give you the clean error message stating that the UUID can not be converted to an INT
