### ISSUE TITLE
AttributeMapping must be < 255 characters

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3038]
Reproduce:
- Create a valid algorithm with > 255 chars in the mapping service
- Press save
Expected:
- No error
Actual:
Error: Value must be less than or equal to 255 characters

**Comment by fdlk** [comment]
This'll make it impossible to map large code sets.

**Comment by mswertz** [comment]
Ah, so bugfix is other way around? Not the error message is issue but the fact that we store this in <255 string. This brings priority of this issue to 'first'
