### ISSUE TITLE
EMX silently ignores invalid references to entities

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3044]
Reproduce:
- Import [this data set](https://drive.google.com/file/d/0B_An6CB5WwrvTWtzeU4za09sRjQ/view?usp=sharing)

Expected:
- Validation error stating each missing reference

Actual:
- Import succeeds, missing references silently ignored

**Comment by Mark-de-Haan** [comment]
This is already fixed in the current version of the master
![screen shot 2015-07-22 at 15 30 00](https://cloud.githubusercontent.com/assets/3625016/8826405/8bc703f2-3086-11e5-860f-ef6ac8c1c896.png)
