### ISSUE TITLE
404 error if trying to edit an entity with a dash (-) in the ID attribute value

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#3047]
If I try to edit an entity with a dash in the ID attribute value I get a 404 error in the forms. Entities that do not have dashes in the entity can be edited.

**Comment by tommydeboer** [comment]
Can't reproduce. Tried multiple string id's with dashes, they all seem to work. Can you show the exact steps to reproduce?

**Comment by djvanenckevort** [comment]
Issue is visible on molgenis21, entity rdconnect_Biobank

**Comment by tommydeboer** [comment]
Seems to be a one-off error that happened while adding one row. Not reproducible right now. Will close until we encounter it again.
