### ISSUE TITLE
Migration 1.4.1 to 1.6.x broken

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3064]
Reproduce:
- Deploy MOLGENIS 1.4.1 with empty database
- Deploy MOLGENIS 1.6.0

Expected:
- Schema migration succesfull

Actual:
- Unknown column 'this.visibleExpression' in 'field list'

**Comment by dennishendriksen** [comment]
After fix we need to release 1.6.2.

**Comment by dennishendriksen** [comment]
Workaround: migrate from 1.4.1 to 1.5.0 and then migrate from 1.5.0 to 1.6.1

**Comment by dennishendriksen** [comment]
Previous commit doesn't fix the problem because in Step1UpgradeMetaData:
RunAsSystemProxy.runAsSystem(() -> metaData.setDefaultBackend(undecoratedMySQL));
uses the current version of AttributeMetaDataMetaData under the hood.

**Comment by fdlk** [comment]
I don't really see a general fix for this, it's more of a feature request I think.

**Comment by dennishendriksen** [comment]
The proper solution is to migrate your data store(s) on a lower level without using the data API.

**Comment by mswertz** [comment]
lets discuss if we can revamp migration as discussed to enable the intermediate updates as well...

**Comment by dennishendriksen** [comment]
We decided to only support version-to-version migration at the moment, which resolves this issue.
