### ISSUE TITLE
A REST API request with a logged out token gives error message in HTML instead of JSON

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3068]
Reproduce: 
Execute the automated REST API test. Last step will fail.

**Comment by jjettenn** [comment]
Fix "RestAPITest.java" test "testLogoutInvalidatesToken"

**Comment by fdlk** [comment]
Jonathan investigated, this happens in the `org.molgenis.security.token.TokenAuthenticationFilter`

**Comment by fdlk** [comment]
Fix is simple, let the filter disregard invalid tokens and proceed anonymously as if they were not present, rather than become angry and send html unauthorized status code
