### ISSUE TITLE
Unable to delete entities with self-reference

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3072]
The fix introduced for #2456 makes it impossible to delete entities with self-reference (it is unclear if this was a problem before that fix). 

Relevant code: https://github.com/molgenis/molgenis/blob/b940842b7e8f2745fc5c3fc6c8727fb8a34b7d08/molgenis-data-mysql/src/main/java/org/molgenis/data/mysql/MysqlRepository.java#L112-L125

**Comment by Mark-de-Haan** [comment]
@tommydeboer This is fixed right?

**Comment by tommydeboer** [comment]
Fixed in PR #3127 on June 8th, 2015
