### ISSUE TITLE
Hyperlink validator reports MalformedUrl validation error as invalid length

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3074]
## Reproduce
Upload a file containing an URL attribute with the value ftp.sra.ebi.ac.uk/vol1/fastq/DRR000/DRR000897/DRR000897.fastq.gz

## Expected
Molgenis either understands the URL or it reports it as being malformed

## Actual
Importer incorrectly reports that the length is too long.
```
Invalid hyperlink value 'ftp.sra.ebi.ac.uk/vol1/fastq/DRR000/DRR000897/DRR000897.fastq.gz' for attribute 'fastq_ftp_1' of entity 'rnaseq_ENA'.Value must be less than or equal to 255 characters.Invalid hyperlink value 'fasp.sra.ebi.ac.uk/vol1/fastq/DRR000/DRR000897/DRR000897.fastq.gz' for attribute 'fastq_aspera_1' of entity 'rnaseq_ENA'.Value must be less than or equal to 255 characters
```

**Comment by tommydeboer** [comment]
This just cost me 20 minutes, so I'll take a look :) Same error message with invalid email addresses, btw.
