### ISSUE TITLE
Gson media type JSON should not contain charset

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3078]
GsonMessageConverter defines content-type "application/json; charset=utf-8” instead of the valid content-type "application/json" (see http://www.iana.org/assignments/media-types/application/json).

**Comment by fdlk** [comment]
Spring added the charset on purpose, see https://jira.spring.io/browse/SPR-13600 , as a workaround for https://bugs.chromium.org/p/chromium/issues/detail?id=438464
