### ISSUE TITLE
No User friendly error message at "Sign in" page

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3084]
1. sign up with existing username
Expected: User friendly error message
Error! Duplicate value 'admin' for unique attribute 'username' from entity 'MolgenisUser' (row 2)

2. sign up with existing email address
Expected: User friendly error message
Error! Duplicate value '<your email address>+user@gmail.com' for unique attribute 'Email' from entity 'MolgenisUser' (row 2)

**Comment by fdlk** [comment]
Yet another duplicate of #1913 We report this bug every sprint ;-)

**Comment by jjettenn** [comment]
; ) then we should fix it!

**Comment by fdlk** [comment]
I fully agree, cause of the time it's taking us to keep reporting and closing the issues is probably longer than just to add the check to the code. (But heavens forbid if it then breaks :) )
