### ISSUE TITLE
MappingService: it is possible to save when no source attribute is selected

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3092]
MappingService: it is possible to save when no source attribute is selected
Note that pushing the save button with a static content is allowed.. The problem is when the algorithm and the selection are empty.

**Comment by mswertz** [comment]
What is expected behavior: in the main mapping view listing all mappings, you expect an empty mapping (because mapping has no value whatsoever?)

**Comment by fdlk** [comment]
What is the exact problem? That it leaves an empty string algorithm which displays differently than no mapping at all?

**Comment by mswertz** [comment]
In the UI, when you have an 'empty' mapping it displays different from a 'non-existing' mapping 
I would expect it says 'missing' just like the other missing mappings.
