### ISSUE TITLE
Two down arrows in the mref filters

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3093]
## Reproduce:

In TypeTest, open the filter dialog for the xmref_value attribute.

Push the plus to get two select2s. Notice the double down arrow in the AND/OR select between the inputs.

![screen shot 2015-05-28 at 15 04 07](https://cloud.githubusercontent.com/assets/1523838/7860606/cebc37f2-054a-11e5-9d03-6d90aa42476d.png)

**Comment by Mark-de-Haan** [comment]
Fixed in react forms
