### ISSUE TITLE
Mref select2 pulldown gets the striping wrong

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3095]
In the pulldown, the selected rows are filtered out, but the odd/even style appears to be computed based on their position before filtering. Note how the rows are colored white, white, grey, white instead of white, grey, white, grey
![screen shot 2015-05-28 at 15 06 29](https://cloud.githubusercontent.com/assets/1523838/7860644/2c3b78fc-054b-11e5-8303-eea15e3ac75d.png)

**Comment by mswertz** [comment]
Proposal: simply remove the row coloring.
M

On Thu, May 28, 2015 at 3:07 PM, Fleur Kelpin <notifications@github.com>
wrote:

> In the pulldown, the selected rows are filtered out, but the odd/even
> style appears to be computed based on their position before filtering. Note
> how two white rows are adjacent to each other in the screenshot.
>
> [image: screen shot 2015-05-28 at 15 06 29]
> <https://cloud.githubusercontent.com/assets/1523838/7860644/2c3b78fc-054b-11e5-8303-eea15e3ac75d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3095>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl
