### ISSUE TITLE
MappingService: after running the automatic tagging service trying to edit results in error (Mappings for the <Name project> project)

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3099]
To reproduce:
1. Upload the hp.owl.zip ontology
2. Upload the small_test_data.owl.zip file
3. Create a project with target model Person
4. Use the Person also as source
5. Run tag wizard
6. Run Automatic Tagging use the hp ontology
7. Mortality/Aging   Middle age onset   Age-dependent penetrance  will be added
8. Go back to mapping project and click on pencil
9. You will get an error: {"errors":[{"message":"An error occurred. Please contact the administrator.<br />.........

**Comment by bartcharbon** [comment]
Problem seems to be originating from the "/" in the tag
