### ISSUE TITLE
simplecaptcha cannot be found in the Maven repository 

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#310]
When trying to deploy a server the log states:

Downloading: http://repo1.maven.org/maven2/nl/captcha/simplecaptcha/1.2.1/simplecaptcha-1.2.1.pom
Downloading: http://repo1.maven.org/maven2/nl/captcha/simplecaptcha/1.2.1/simplecaptcha-1.2.1.pom
Downloading: http://repo1.maven.org/maven2/nl/captcha/simplecaptcha/1.2.1/simplecaptcha-1.2.1.pom
Downloading: http://repo1.maven.org/maven2/nl/captcha/simplecaptcha/1.2.1/simplecaptcha-1.2.1.jar
Downloading: http://repo1.maven.org/maven2/nl/captcha/simplecaptcha/1.2.1/simplecaptcha-1.2.1.jar
[ERROR] Artifact: nl.captcha:simplecaptcha:jar:1.2.1 has no file.
org.apache.maven.artifact.resolver.ArtifactNotFoundException: Could not find artifact nl.captcha:simplecaptcha:jar:1.2.1 in central (http://repo1.maven.org/maven2)

Try downloading the file manually from the project website.

Then, install it using the command: 
    mvn install:install-file -DgroupId=nl.captcha -DartifactId=simplecaptcha -Dversion=1.2.1 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
    mvn deploy:deploy-file -DgroupId=nl.captcha -DartifactId=simplecaptcha -Dversion=1.2.1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  nl.captcha:simplecaptcha:jar:1.2.1

**Comment by sidohaakma** [comment]
Need to use remoteRepositories configuration property instead of project.remoteArtifactRepostories. But is crashed on build.
Caused by: java.lang.InstantiationException: org.apache.maven.artifact.repository.ArtifactRepository

You can also define third-party repositories in the repository tag in the pom.xml. Maybe this is a solution?

<repositories>
   <id>enonic</id>
   <name>Enonic repository</name>
   <url>http://repo.enonic.com/maven</url>
</repositories>

**Comment by dennishendriksen** [comment]
> You can also define third-party repositories in the repository tag in the pom.xml. Maybe this is a solution?
 enonic Enonic repository http://repo.enonic.com/maven

molgenis-security/pom.xml:
```
    <repositories>
        <repository>
            <id>enonic</id>
            <url>http://repo.enonic.com/public/</url>
        </repository>
    </repositories>
```

**Comment by sidohaakma** [comment]
Weird that the "mvn site"-goal does not pickup the right repo then.

**Comment by sidohaakma** [comment]
Reopened #6805
