### ISSUE TITLE
VCF with REF with multiple bases can't be imported 

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3108]
Reproduce: 
- Import 1000G_CardioPanel_nogenotypes.vcf

Expected:
- Successful import

Actual:
- Some variants for which the ID starts with 'esv' the REF columns contains values longer than 255 characters (InDels). Since the REF attribute is of type STRING this data can't be imported.

**Comment by dennishendriksen** [comment]
Fixed by #3351?

**Comment by Mark-de-Haan** [comment]
Fixed
