### ISSUE TITLE
Migration from 1.5 to 1.7 tries to alter table for abstract entities

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#3116]
During migration an alter table statement is generated for abstract entities. Abstract entities however do not exist as tables in the database and generate an error in the log.

### How to reproduce:
* Start with molgenis 1.5.0
* Load an entity model that uses an abstract entity that has a string attribute
* Update molgenis to 1.7.0

### Expected result:
The database is migrated without errors

### Actual result:
For each abstract entity string attribute the following exception is logged:
```
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ALTER TABLE `abstract_entity_name` MODIFY COLUMN `label` TEXT;]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'molgenis.abstract_entity_name' doesn't exist
```

**Comment by tommydeboer** [comment]
Fixed in (upcoming) 1.8.0
