### ISSUE TITLE
Version service eats up commented out properties when updating the version

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3132]
I commented out the property that activates the dev profile in molgenis-server.properties, and started molgenis. The VersionService saw fit to update the molgenis version property and in doing so rewrote the entire file, removing the commented out entry.

**Comment by dennishendriksen** [comment]
It also changes the order of properties, a bit annoying.

**Comment by Mark-de-Haan** [comment]
Can not reproduce, added a #TEST LINE at the top which is not overwritten
