### ISSUE TITLE
Excel import fails with exactly 2 mref integer ids

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3134]
problem:
entity1 with an mref to entity2
entity2 had an integer as identifier
a line in entity one refers to 2 values in entity2, value of the cell in excel is in that case 3,4

expected:
references to entities of type entity2 with id's 3 and 4 are added

actual:
error because there is no entity2 with value "3,4"

note:
this only breaks for exactly 2 values, 1 or 3 or more works fine

**Comment by dennishendriksen** [comment]
Cannot reproduce on branch 1.2 or master branch with following EMX excel file:

Tab: entities
![image](https://cloud.githubusercontent.com/assets/2477186/8951256/1e6b4e58-35cc-11e5-9621-1f8f1c956a0e.png)
Tab: attributes
![image](https://cloud.githubusercontent.com/assets/2477186/8951264/2ec17e80-35cc-11e5-9884-a7137ff4c3c5.png)
Tab: Entity0
![image](https://cloud.githubusercontent.com/assets/2477186/8951268/3884c8d2-35cc-11e5-8805-aa99397589c4.png)
Tab: Entity1
![image](https://cloud.githubusercontent.com/assets/2477186/8951270/41733438-35cc-11e5-85cf-2f36c06a125c.png)

Result: Import successful

**Comment by bartcharbon** [comment]
With the set Dennis mentioned I cannot reproduce either. 
however I have put a set in: /Data/3134/ on the google drive with which it still gives an error. What the difference is is unclear to me, we should look into it.

**Comment by dennishendriksen** [comment]
Is this really critical?

**Comment by Mark-de-Haan** [comment]
@bartcharbon Is this still an issue?

**Comment by bartcharbon** [comment]
still and issue in 1.21...

**Comment by dennishendriksen** [comment]
Issue can be reproduced in 8.0.0-SNAPSHOT with Apache POI 4.0.1.

It turns out that the issue is actually in the example dataset: the column containing the comma-separated integer identifiers contains cells that are formatted as numbers instead of strings. This results in issues when there is exactly one comma in the value.

Formatting the column as text resolves this issue.
