### ISSUE TITLE
Error shown when I click an xref with ID containing a /

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3139]
Error! An error occurred. Please contact the administrator.
TypeError: null is not an object (evaluating 'd.get(t.href)[r.idAttribute]')

**Comment by fdlk** [comment]
Occurs when uploading the IBD plink file.

**Comment by mswertz** [comment]
do we have rules for IDs or do we allow any character. In the latter case we need proper escaping

**Comment by tommydeboer** [comment]
Seemingly this bug does not occur in 1.9.0-SNAPSHOT anymore, so I'll close it.
