### ISSUE TITLE
creating a integrated dataset when a JPA entity is the target results in "repository is null"

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3143]
### Reproduce
- Create mapping project with for example UserAuthority as target
- Map UserAuthority to it
- Click "create integrated dataset"

### Expected
- Integrated set

### Actual
- error repository is null

**Comment by bartcharbon** [comment]
in addition: error is shown as separate screen, should be the standard error bar used elsewhere in MOLGENIS

**Comment by dennishendriksen** [comment]
In 1.13.0-RC the following error is displayed:
"Failed to create integrated entity."

**Comment by bartcharbon** [comment]
JPA has been removed
