### ISSUE TITLE
Restarting after dropping the index only breaks the app

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3156]
## Reproduce
- Drop de database and index
- Start the app
- Stop the app
- Drop de index
- Start the app

## Expected
The app starts normally

## Observed
```
o.s.w.c.s.AnnotationConfigWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webAppConfig': Invocation of init method failed; nested exception is org.molgenis.data.MolgenisDataException: Could not resolve dependencies of entities [FileMeta] are there circular dependencies?
```

**Comment by tommydeboer** [comment]
Reindexing after migration causes the same bug (without dropping the database).

**Comment by tommydeboer** [comment]
DependencyResolver breaks when there are now more than one extension of an abstract entity. Current situation: FileMeta extends Owned, Questionnaire extends Owned. Also confirmed with two other entities extending one abstract.

**Comment by Mark-de-Haan** [comment]
Fixed
