### ISSUE TITLE
After deleting entities plus metadata, they still remain visible in the model registry

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3157]
Upload an EMX file, delete the entities in the data explorer.
Then access the package in the model registry.

Expected:
The package is empty

Actual:
The entities that got deleted, and their attributes, are still listed.
And an error message is shown in the alert: Error! An error occurred. Please contact the administrator.

**Comment by Mark-de-Haan** [comment]
If you restart, the packages are listed but the entities and attributes are gone.
Seems like the index is not refreshed correctly or not at all

**Comment by Mark-de-Haan** [comment]
Refreshing the caches does not work if executed within a transaction. Bug within the TransactionManager?? @erwinwinder @fdlk
