### ISSUE TITLE
Substring search broken?

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#3160]
Substring search does not work as expected:

How to reproduce:
- On molgenis35, search for MMCI in the BBMRI-ERIC catalogue.

Expected result"
MMCI biobank is found

Actual result:
Nothing is found, when searching for CZ_MMCI it does find the MMCI biobank.

**Comment by dennishendriksen** [comment]
What needs to happen is to change the configuration of the default tokenizer in ElasticsearchIndexCreator. By default it splits on underscores, but in MOLGENIS it is configured to split  only on whitespace characters (I do not know why).

Ps. The SEARCH query operator does not perform substring search, you can use the LIKE query operator for this. The SEARCH query operator performs a smart language-aware (stemming, synonyms, etc.) search.
