### ISSUE TITLE
Max file upload size cannot exceed 2047 (mb)

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3161]
Higher values will internally roll over max int when computing the max file upload size in bytes since it gets stored in an int.

**Comment by mswertz** [comment]
I suppose it is nearly fixed?

**Comment by fdlk** [comment]
I have a fix, it turned out not to be needed for Palga since the palga files are only 200MB in compressed form(!)

**Comment by mswertz** [comment]
double bonus

On Thu, Jun 25, 2015 at 5:31 PM, Fleur Kelpin <notifications@github.com>
wrote:

> I have a fix, it turned out not to be needed for Palga since the palga
> files are only 200MB in compressed form(!)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3161#issuecomment-115294398>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl
