### ISSUE TITLE
Uploading twice the test "TypeTest" file with selecting different packages fails!

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3174]
To reproduce:
1. Upload emx_all_datatypes.xlsx "TypeTest" in package "org_molgenis_test" --> OK
2. Upload emx_all_datatypes.xlsx "TypeTest" in package "org_molgenis" --> ERROR

Message:
Import failed
Changing existing attributes is not currently supported. You tried to alter attribute [xcategorical_value] of entity [org_molgenis_test_TypeTest]. Only adding of new attributes is supported.

**Comment by fdlk** [comment]
This is not a bug, I think.
You effectively import a new TypeTestRef entity
The existing typetest entity's xref/mref attributes suddenly refer to this new TypeTestRef entity, so they effectively change which is not supported.

**Comment by jjettenn** [comment]
Its a bug because it should not be posible to get into that page. It must
give a proper error message!
Op 18 jun. 2015 17:01 schreef "Fleur Kelpin" <notifications@github.com>:

**Comment by fdlk** [comment]
When should the error be thrown? Or should the importer perhaps not ask multiple choice questions that have only one correct answer? :)

**Comment by mswertz** [comment]
The upload should succeed, am I wrong?

**Comment by fdlk** [comment]
The second time you choose to upload TypeTestRef to a different package. That makes it a different entity and therefore the xref and mref attributes are modified. This is not allowed.

**Comment by mswertz** [comment]
I still don't get it: if I upload into a new package all attributes should
also be considered new? And not updates?

On Thu, Jun 18, 2015 at 7:49 PM, Fleur Kelpin <notifications@github.com>
wrote:

> The second time you choose to upload TypeTestRef to a different package.
> That makes it a different entity and therefore the xref and mref attributes
> are modified. This is not allowed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3174#issuecomment-113234821>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by fdlk** [comment]
In the 'attributes' sheet of the all-datatypes excelfile, the `entity` column is fully qualified, i.e. `org_molgenis_test_TypeTest`. The `refEntity` column lists entity name only, i.e. `TypeTestRef`. Therefore the package tab gives the user a choice where to import to. The org_molgenis_test_TypeTest already exists and already has an `xcategorical_value` attribute that refers to `org_molgenis_test_TypeTestRef`. Now it looks like you want it to refer to `org_molgenis_TypeTest`, which would be an attribute update.

**Comment by mswertz** [comment]
No, I still don't think it is not an attribute update.

I think you are adding adding new attribute
org/molgenis/TypeTest.xcategorical_value

However, I could imagine that we would get an error because the refEntity
property is now ambiguous. Do I understand that the importer assumes that
the refEntity is in the same package?

M

M

On Thu, Jun 18, 2015 at 8:17 PM, Fleur Kelpin <notifications@github.com>
wrote:

> In the 'attributes' sheet of the all-datatypes excelfile, the entity
> column is fully qualified, i.e. org_molgenis_test_TypeTest. The refEntity
> column lists entity name only, i.e. TypeTestRef. Therefore the package
> tab gives the user a choice where to import to. The
> org_molgenis_test_TypeTest already exists and already has an
> xcategorical_value attribute that refers to org_molgenis_test_TypeTestRef.
> Now it looks like you want it to refer to org_molgenis_TypeTest, which
> would be an attribute update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3174#issuecomment-113245203>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by fdlk** [comment]
You're updating (amongst others) the attribute `org_test_molgenis_TypeTest.xcategorical_value`. Its original signature was xref to `org_test_molgenis_TypeTestRef`. Its new signature is xref to `org_test_TypeTestRef`.

The `org_test_molgenis_TypeTest` entity remains in the package `org_test_molgenis`, since it's fully qualified on the entities tab. The `TypeTestRef` entity got imported into `org_test_molgenis_TypeTestRef` in the first import. Now in the second import it's getting imported into `org_test_TypeTestRef`.

**Comment by mswertz** [comment]
Sorry, I still not understand.

I would expect we have TWO entities with name "TypeTest" after the second
import? And these are completely unrelated except having the same name and
signature.


On Thu, Jun 18, 2015 at 9:38 PM, Fleur Kelpin <notifications@github.com>
wrote:

> You're updating (amongst others) the attribute
> org_test_molgenis_TypeTest.xcategorical_value. Its original signature was
> xref to org_test_molgenis_TypeTestRef. Its new signature is xref to
> org_test_TypeTestRef.
>
> The org_test_molgenis_TypeTest entity remains in the package
> org_test_molgenis, since it's fully qualified on the entities tab. The
> TypeTestRef entity got imported into org_test_molgenis_TypeTestRef in the
> first import. Now in the second import it's getting imported into
> org_test_TypeTestRef.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3174#issuecomment-113268202>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by fdlk** [comment]
We don't since the TypeTest entity is unambiguously specified on the entities tab as being part of the org_test_molgenis package.

name | package
--------|------------
TypeTest | org_molgenis_test
TypeTestRef |

**Comment by jjettenn** [comment]
Correct behavior throwing exception: You are trying to upload entities that are not compatible with the already existing entities: [org_molgenis_test_TypeTest]
