### ISSUE TITLE
Delete of an entity with a file attribute does not delete file from filestore

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3217]
When you have an entity with a file attribute and you delete that entity in the dataexplorer the associated file is not removed from the filestore.

**Comment by dennishendriksen** [comment]
@tommydeboer is working on entity decorators (reintroduced in a elegant way from the compute-branch). we could use this to solve the issue

**Comment by Mark-de-Haan** [comment]
@dennishendriksen Are these decorators used now?

**Comment by dennishendriksen** [comment]
Deleting an entity with file attribute should only delete file if a cascading delete (not yet implemented) is defined. Deleting the file meta entity should delete the file.
