### ISSUE TITLE
Not able to map MREF attributes to MREF attributes in the mapping service with the help of the Map tab

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3218]
## Reproduce 
  - Upload all_datatypes
  - Create a mapping project with the TypeTest entity
  - Map TypeTest to TypeTest
  - Try to edit an MREF or a categorical_mref attribute

## Expected
I can create a script for this attribute or use the map tab

## Observed
No map tab available and an error

**Comment by erwinwinder** [comment]
- Fixed preview error
- Removed 'map tab' for mref because this is not usefull
