### ISSUE TITLE
Fix screen text overflow in the result table

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3219]
![screen shot 2015-06-25 at 9 46 07 am](https://cloud.githubusercontent.com/assets/5586255/8349732/93dcecea-1b1f-11e5-9e52-f31d0b9cadc3.png)

**Comment by jjettenn** [comment]
Please test the mapping-service at 1280 * 800 resolution

**Comment by jjettenn** [comment]
I have tested this screen at 1280 * 800 resolution and the next problem appears
![screen shot 2015-06-26 at 2 20 17 pm](https://cloud.githubusercontent.com/assets/5586255/8377150/f544bdec-1c0e-11e5-8243-3c86ea68cfb0.png)

**Comment by fdlk** [comment]
What is going wrong? no vertical scroll bar?

**Comment by jjettenn** [comment]
The tables are too large

**Comment by fdlk** [comment]
I get it, thanks!
