### ISSUE TITLE
Table collapsing nested entities broken

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3225]
Reproduce:
- Load data set with entity with xref attribute that refers to an entity that contains an xref attribute
- Expand xref attribute and expand xref attribute of the expanded attribute
- Collapse expanded attribute of expanded attribute

Expected:
- Expanded entity of expanded attribute is collapsed

Actual:
- Nothing happens

**Comment by Mark-de-Haan** [comment]
Using the deep nesting emx molgenis-app/src/test/resources/xls I can use TestXref_2 entity to open an mref that opens a categorical. Closing the mref also closes the categorical.

So collapsing seems to work
