### ISSUE TITLE
Empty page with error message in JSON format

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3230]
Difficult to reproduce (Ask JJ).
You can try: Adding a source entity, Creating a new project.
Clicking around in the mapping service plugin pages can result in the next error:

Example 1
{
  "errors": [
    {
      "message": "An error occurred. Please contact the administrator.<br />Message:Mapping already present for source MappingTarget"
    }
  ]
}

Example 2
![screen shot 2015-06-25 at 3 04 43 pm](https://cloud.githubusercontent.com/assets/5586255/8354872/a98c1b66-1b4b-11e5-9b8f-3ac02dc506bb.png)

**Comment by jjettenn** [comment]
Related to: No spinner when using mapping-service #4082

**Comment by Mark-de-Haan** [comment]
Resolved according to commits
