### ISSUE TITLE
Mapping results: Mapping should also work for categoricals with String IDs

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3232]
Reproduce:
- Create mapping project with target RuntimeProperty and add a source RuntimeProperty
- Edit Name mapping and select Map tab in the Mapping column

Expected:
- Content, but no error

Actual:
- Error! An error occurred. Please contact the administrator.

**Comment by fdlk** [comment]
```
For "?c" left-hand operand: Expected a number or boolean, but this evaluated to a string (wrapper: f.t.SimpleScalar):|==> targetEntity.get(targetAttributeIdAttribute)  [in template "view-advanced-mapping-editor.ftl" at line 64, column 74]
```

**Comment by fdlk** [comment]
The ?c incorrectly assumes that the result is of numerical type.
