### ISSUE TITLE
Javascript files (and other static resources) get encoded wrong

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3252]
The select 2 box displays an encoding error:
![searching](https://cloud.githubusercontent.com/assets/1523838/8391183/b901337e-1cb8-11e5-93d5-aa9e5613b65a.png)

The javascript file contains an UTF-8 character: `return "Searching…";`.
In the browser (Safari and Chrome tested) you see it interpreted as iso-latin, `Searchingâ€¦`

**Comment by mswertz** [comment]
Does this also relate to master? What are example use cases, i.e., is this a rare bug?

**Comment by fdlk** [comment]
Yes, this is also in the master. I've fixed the specific flagrant instance of it occurring in the mref select box by escaping the character but it occurs whenever people write unescaped non-ascii text in static resources that get served to the client.

**Comment by fdlk** [comment]
Duplicates #4296
