### ISSUE TITLE
'endPostable already set' on installing molgenis on windows 7/8.1

### ISSUE THREAD

**Issue by ArjanDraisma** [molgenis/molgenis#3265]
An error occurs when installing on windows (versions 7 and 8.1)

> An exception has occurred in the compiler (1.8.0_31). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
> java.lang.IllegalStateException: endPosTable already set

**Comment by bartcharbon** [comment]
I have the same problem now and again on Mac OD Mavericks, cleaning and than installing again fixes the problem in my case.

**Comment by dennishendriksen** [comment]
Running into this issue multiple times a day, very annoying. Someone mentioned it might be related to the google autovalue library. There is a more recent version available, we might want to look into updating this lib.

**Comment by dennishendriksen** [comment]
Updating to jdk 1.8.0_60 did not resolve issue.

**Comment by Mark-de-Haan** [comment]
Update to jdk 1.8.0_71 did not resolve issue. Maybe look into google autovalue library version?

**Comment by Mark-de-Haan** [comment]
@dennishendriksen I have not run into this problem for some time now. Does windows still suffer?

**Comment by dennishendriksen** [comment]
@Mark-de-Haan This is not a Windows-specific issue and commonly occurs when executing the ```install``` goal without ```clean```.

**Comment by fdlk** [comment]
@dennishendriksen So you do still run into it? I’ve not seen it either doe ages.

**Comment by dennishendriksen** [comment]
>So you do still run into it?
Yes

**Comment by fdlk** [comment]
@Mark-de-Haan and I thought we fixed it in 1b60620.

**Comment by dennishendriksen** [comment]
I'll post it here the first time I encounter the issue again. There is a possibility that I've only encountered this issue when working on other older ```molgenis-app-*``` modules or branches. Lets close before the end of the year in case of no updates from me.

**Comment by dennishendriksen** [comment]
Haven't seen this in 2018, case closed!
