### ISSUE TITLE
Testing of mysql fails on windows 8/8.1

### ISSUE THREAD

**Issue by ArjanDraisma** [molgenis/molgenis#3267]
An error occurs when installing molgenis on windows 8/8.1:

>Exception in thread "main" java.util.MissingResourceException: Resource '5-5-9/Windows_8.1-amd64/mysqld.exe' not found

**Comment by dennishendriksen** [comment]
See https://github.com/molgenis/molgenis/pull/2787/files for how to fix.

________________________________
