### ISSUE TITLE
The importer always uses MySQL backend if the package info is present in the EMX file

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3280]
Choosing backend for entities works when package is not present. As soon as the package information is added the EMX file, regardless whether or not the backend is specified as 'ElasticSearch', the data will be imported to MySQL database. 

If you want to reproduce the problem, 

Method 1: check if the data ends up in MySQL or ElasticSearch with/without package info
Method 2: just add as many categorical attributes and their corresponding refEntities as possible in an excel sheet, specify the backend to be 'ElasticSearch', it should work. Then add package information, it should fail. If you want to get example data please approach Chao.

**Comment by dennishendriksen** [comment]
In 2.0-RC data is written to the backend defined for existing entities in the database, for new entities defined in the EMX source (the default backend is set in case no backend is supplied), 2.0-RC does not have a MySQL and Elasticsearch backend.
