### ISSUE TITLE
Javascript error in dataexplorer when user has only count permission on xreffed entity

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3286]
- Create a user and give it 'edit' permission on entity1 and 'count' permission on entity2. 
- Log in as user and goto dataexplorer
- Select entity2 and then entity1 

Result:
 Invariant Violation: unmountComponentAtNode(...): Target container is not a DOM element.

**Comment by mswertz** [comment]
is this a bug or a feature?

**Comment by Mark-de-Haan** [comment]
Issue no longer occurs.
