### ISSUE TITLE
Wrong dataexplorer filter representation

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3289]
![screen shot 2015-07-01 at 09 28 36](https://cloud.githubusercontent.com/assets/116559/8453013/932194ba-1ff0-11e5-916d-f41fc59db048.png)

**Comment by mswertz** [comment]
part of react refactoring?

**Comment by Mark-de-Haan** [comment]
Unable to reproduce, likely there is a certain pattern that you have to follow to reach this point but it will not happen during simple filtering operations
