### ISSUE TITLE
When plugin.dataexplorer.mod.data property is set to false, you can't edit RuntimeProperties anymore

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3294]
Whe the data tab of the dataexplorer is hidden (with RuntimePorperty plugin.dataexplorer.mod.data) there is no way of changing the runtime properties (or any other entity) because the forms are removed.

So when you hide the data tab you can't unhide it.

**Comment by dennishendriksen** [comment]
Closed, now it can still be changed through the settings cog.
