### ISSUE TITLE
Move InMemoryRepository and InMemoryRepositoryCollection to test module

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3297]
org.molgenis.data.mem.InMemoryRepository and org.molgenis.data.mem.InMemoryRepositoryCollection in molgenis-data should be used for test purposes, so we should move them to molgenis-data-test module and a add dependencies with scope test in modules that want to use InMemoryRepository.

**Comment by Mark-de-Haan** [comment]
Why wontfix? It is not really urgent but it would be nice to clean up the code.

**Comment by Mark-de-Haan** [comment]
Bump question @mswertz

**Comment by Mark-de-Haan** [comment]
Bump

**Comment by dennishendriksen** [comment]
InMemoryRepository is used in production code and we decided that we want to keep using it. The current implementation is not suitable for use in production code, these issues are registered independently.
