### ISSUE TITLE
Error when user has no permission on home plugin

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3299]
- Create user and add to 'All users' group
- Give permission on dataexplorer
- Remove permission on 'home' plugin
- Log in as user

-> Error! An error occurred. Please contact the administrator.

**Comment by Mark-de-Haan** [comment]
This occurs when the dataexplorer is the first plugin after the home plugin. Permission denied on getting Javascript bundles. Moving to another plugin and then going back fixes the missing js.

**Comment by Mark-de-Haan** [comment]
No longer happens. You navigate to data explorer at the start without any errors
