### ISSUE TITLE
When setting ROOT logging to ALL, the app is completely broken and restarting will not help anymore

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3304]
## Reproduce
- As admin go to Log manager
- Set ROOT logging to ALL
- Try to navigate to the data explorer
## Expected

I go to the dataexplorer and can see nice extensive logging in my console / catalina.out
## Observed

The entire application is broken and even restarting does not help anymore
You need to drop the database to get things working again

**Comment by mswertz** [comment]
this is an admin feature so therefore priority less high (because admins can be trained)

**Comment by dennishendriksen** [comment]
Logs are not persisted in Elasticsearch anymore reducing the system load when generating huge amounts of logs.
