### ISSUE TITLE
Creating a mapping project with the entities entity will break the app

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3315]
## Reproduce
- Go to the mapping service
- Create a new entity with a name and the entity entities

## Expected
I go the the next screen with the entities attributes shown in the table

## Observed
I get an error screen

**Comment by mswertz** [comment]
is there a use case for using entities as target?

**Comment by Mark-de-Haan** [comment]
No I don't think so, so I agree with the wontfix label

**Comment by fdlk** [comment]
migration sounds like a valid use case :)

**Comment by mswertz** [comment]
ah, that is indeed an interesting one

On Thu, Jul 2, 2015 at 10:35 AM, Fleur Kelpin <notifications@github.com>
wrote:

> migration sounds like a valid use case :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3315#issuecomment-117958018>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by Mark-de-Haan** [comment]
No longer an issue because I can not select the entities entity in the dropdown anymore
