### ISSUE TITLE
Using UTF-8 characters like ∆ for names in the mapping service will render a question mark in the interface

### ISSUE THREAD

**Issue by mark-de-haan** [molgenis/molgenis#3319]
![screen shot 2016-02-12 at 15 52 43](https://cloud.githubusercontent.com/assets/3625016/13010136/af42cc7e-d1a0-11e5-9eb3-a592cd145a89.png)

**Comment by mswertz** [comment]
unclear desired behavior

**Comment by fdlk** [comment]
I’d suggest rendering the name. :)

**Comment by dennishendriksen** [comment]
Fixed by 854928a10b317d1d371ee035c8386bd257db98b9 in ≥ 1.15
