### ISSUE TITLE
REST API for adding rows to entity returns wrong error information with enums

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis#3376]
When adding a row to an entity through the REST API, if one of the columns is of type ENUM and a value is added that is not in the ENUM option list, the error will say:

Invalid enum value for attribute 'foo' of entity 'bar'.Value must be less than or equal to 255 characters

Instead would expect something like

Invalid enum value for attribute 'foo' of entity 'bar'. Enum options are: example, other_example

**Comment by fdlk** [comment]
Reminds me of #3074 so should be easy to fix, probably
