### ISSUE TITLE
Expanding a categorical in an mref breaks that column

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3413]
## To reproduce
1. Import a dataset with an mref having a categorical
2. Go to the data explorer and expand the mref in the table
3. Now expand the categorical

## Expected
The categorical is expanded OR no buttons are shown if the expansion is not possible.

## Actual
A blank column appears which cannot be closed.

**Comment by erwinwinder** [comment]
Test dataset:
https://drive.google.com/open?id=0B4_AOpOI8V7GSDBjVGdYbl8zbDA
