### ISSUE TITLE
In the matching result page on SORTA, the search function only works in the first page. 

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3419]
## How to reproduce
- Go to https://molgenis19.target.rug.nl
- Login as the admin with the famous password
- Click on Sorta option in the top menu
- Retrieve the exiting matching task called "example"
- Click on Show button for the matched items
- Copy the first term in the first page (brain stem glioma)
- Click on the page number 2 to go to next page
- Paste the term (brain stem glioma) in the search box above the table and click search button
## Expected

To see the mapping result for the term 'brain stem glioma'
## Actual

In the result page, it shows 'There are no results' (however we just copied this term from the first page and we know it exists)
## Comment

The search function only works if you stay in the first page (pager = 1)

**Comment by dennishendriksen** [comment]
Please provide How to reproduce, Expected result and Actual result.

**Comment by mswertz** [comment]
bump

**Comment by dennishendriksen** [comment]
@ChaoPang Could please provide How to reproduce, Expected result and Actual result?

**Comment by ChaoPang** [comment]
This is not really data-mapper related story. The SORTA code still lives outside the master and it can be reproduced on the demo server (molgenis19) though, do you want me to describe this?

**Comment by dennishendriksen** [comment]
@ChaoPang Yes, please describe how to reproduce this on molgenis19 as well as including a link to the GitHub branch that build the web application on molgenis19. Else we might not be able to reproduce it in the future.

**Comment by mswertz** [comment]
not in master, close
