### ISSUE TITLE
Annotator target entity meta data misses new attributes

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3433]
Reproduce:
- For any annotator that adds a new attribute to target entities, supply a source.

Expected:
- The target entity meta data contains the new attribute

Actual:
- The target entity meta data is a reference to the source entity meta data

The problem is in AnnotatorImple.annotateEntity:
Entity target = new MapEntity(source, source.getEntityMetaData());

**Comment by mswertz** [comment]
what is the functional drawback of this?

**Comment by dennishendriksen** [comment]
None directly. Indirectly it complicates unit testing, is confusing when developing new annotators and will result in problems building functionality on top of the output resulting in time wasted that could be spend on developing other features.

**Comment by Mark-de-Haan** [comment]
Code no longer excists
