### ISSUE TITLE
Annotators command-line missing value not according VCF specification 

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3439]
When there is a missing value in the VCF info column there should be added a "." otherwise the second annotation iteration will cause the VCF tabix reader to run out of bound.

How to reproduce:
1. Use bram's testset (has a missing value) annotate once with GoNL, Exac, Clinvar or 1000g annotator.
2. Use the annotated testset with any other annotator.

**Comment by joerivandervelde** [comment]
Already fixed, see https://github.com/molgenis/molgenis/commit/5bf92d24d4bfa511e6b1772ad83edebddc8a1d9a

**Comment by joerivandervelde** [comment]
Example:

This (valid) VCF line, with a '.' in the INFO column:
```
21	46924425	rs149296338	CGGCCCCCCA	C	.	.	.	GT	0|1	0/1
```

Gets transformed to this line, with no value (so 2 separators right after eachother) where the INFO column should be:
```
21	46924425	rs149296338	CGGCCCCCCA	C	.	.		GT:AD:DP:GQ:PL	0|1:.:.:.:.	0/1:.:.:.:.
```

The vcf-validator tool will complain about this as well:
```
The column INFO is empty at 21:46924425.
```

Incidentally, another bug (#3458) ties into this. If there is only a flag-field present in the INFO column, it's also treated as missing and the same behaviour occurs. Also, the effect of #3460 can be seen in the example. (bloating of the FORMAT field)
