### ISSUE TITLE
Genome browser info popup shows id instead of label

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3452]
Reproduce:
- Import genome_browser_test_emx.xls
- Select g_genomic_all in dataexplorer
- In g_genomic_all genome browser track click on mutation

Expected:
- Info pop up displays "<name> (<description>)" as header

Actual:
- Info pop up displays "<identifier>" as header

See createGenomeBrowserInfoPopup in dataexplorer-data.js

**Comment by Mark-de-Haan** [comment]
V5: Genomebrowser popup info is now configurable.
