### ISSUE TITLE
Annotators always print all FORMAT fields

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#3460]
When writing to VCF, every FORMAT field is printed, even though this is not necessary. Missing values can be present using '.' as a value, mixed in with regular values, this is fine. But after annotating, all format fields, even when not originally present, are written out with even more missing values. This is a waste of space and may greatly bloat the output VCF. The VCF spec shows that FORMAT is allowed to be 'compact': https://samtools.github.io/hts-specs/VCFv4.2.pdf . A clear example, where we start with some values including missing values:

```
GT:AD:DP:GQ:PL  2|3:.:.:3:33,3,0
GT:AD:DP    0|0:.:.
GT:AD   0/1:.
```

This gets transformed into:

```
GT:AD:DP:GQ:PL  2|3:.:.:3:33,3,0
GT:AD:DP:GQ:PL  0|0:.:.:.:.
GT:AD:DP:GQ:PL  0/1:.:.:.:.
```

**Comment by fdlk** [comment]
Do you mean that trailing :. s should not be written out?
