### ISSUE TITLE
React error changing data set after selecting invalid data set

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3462]
Reproduce:
- Go to data explorer with query string ?entity=MeNoExist
- Use dropdown to select valid data set

Expected:
- Valid data set is displayed

Actual:
- Error is displayed
  - minified environment: Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  - non-minified environment:
```
Error: Invariant Violation: unmountComponentAtNode(...): Target container is not a DOM element.
```

**Comment by fdlk** [comment]
Happens also at times when just surfing to the dataexplorer
