### ISSUE TITLE
Questionnaire-specific code in MySQL repository implementation

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3464]
if (!att.isNillable() && !EntityUtils.doesExtend(metaData, "Questionnaire")

**Comment by fdlk** [comment]
In Questionnaires, when an attribute is nillable=false AND has a visibleExpression that evaluates to false, its value may be null. The constraint is then enforced in the validation decorator and not in the database. This is implemented in a Questionnaire-specific way which looks sort of horrible.

**Comment by dennishendriksen** [comment]
I suspect this causes problems when specifying another backend for entities that extend from Questionnaire.

**Comment by mswertz** [comment]
indeed, this should be solved in middleware, not backend otherwise we cannot switch backends

**Comment by dennishendriksen** [comment]
MySqlRepository does not exist in 2.0-RC, PostgreSqlRepository does not contain any Questionnaire specific hacks
