### ISSUE TITLE
Opening the Disease Matcher makes the DataTable header change color

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3465]
## Reproduce
1. Go to data explorer
2. Open the Disease Matcher tab
3. Go to another entity or go to the Data tab
4. In the data tab, the table header is now coloured!

## Expected
The table header doesn't let others tell him what colours to wear.

## Actual
It does. 
*Before:*
![image](https://cloud.githubusercontent.com/assets/5362890/9250381/bf5aab04-41cc-11e5-8786-813214510df8.png)

*After:*
![image](https://cloud.githubusercontent.com/assets/5362890/9250385/cc456322-41cc-11e5-9866-bf5d7438fe54.png)

**Comment by mswertz** [comment]
who is using disease matcher? If there are no users we should discontinue this plugin

**Comment by tommydeboer** [comment]
Closed due to discontinuation of plugin.
