### ISSUE TITLE
IE8 alert not displayed in IE8 for https://molgenis??.target.rug.nl

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3481]
Reproduce:
- In IE8 go to MOLGENIS home page

Expected:
- Confirm alert

Actual:
- Script error alerts

**Comment by erwinwinder** [comment]
Convirmed by Edith: we do not support IE9 in compitibility mode.

**Comment by jjettenn** [comment]
Works via FireFox with add-on User Agent Switcher.
Does not work on Molgenis01.target.rug.nl on IE8 via WOA

**Comment by dennishendriksen** [comment]
Problem is that our HTTPS configuration does not work with IE8, since we do not support protocols/cipher suites that Ie8 supports. @fdlk provided the following link for a possible workaround: http://serverfault.com/questions/389806/redirect-to-ssl-only-if-browser-supports-sni

**Comment by dennishendriksen** [comment]
@mswertz I propose to accept the current behavior and close this issue
