### ISSUE TITLE
Remove duplicate OntologyService and OntologyServiceImpl

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3488]
Both the ontology and the ontology-core modules contain an OntologyService interface and OntologyServiceImpl implementation, this is confusing. Rename or merge.

**Comment by Mark-de-Haan** [comment]
@ChaoPang Could you clean up?

**Comment by dennishendriksen** [comment]
OntologyService interface and OntologyServiceImpl implementation were removed from the ontology module.
