### ISSUE TITLE
Default R roc script does not run on MOLGENIS VM

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3492]
Reproduce:
- Go to script plugins on molgenis01 and execute roc scripts

Expected:
- Scripts runs succesfully

Actual:
HTTP Status 500 - Request processing failed; nested exception is org.molgenis.r.MolgenisRException: Error running [...].Error in library(gdata) : there is no package called 'gdata'

The gdata and ggplot2 libraries are not available by default (see http://www.molgenis.org/wiki/GccSopCreateMolgenisVM).

**Comment by fdlk** [comment]
The algorithm editor got a complete redo since this script got added. Is it being used at all? Chao should know.

**Comment by fdlk** [comment]
Asked Chao and he uses it in SORTA to compute how well the matching algorithm is doing.

**Comment by dennishendriksen** [comment]
Ok, then we need to add the gdata and ggplot2 libraries to all VMs and update the create VM SOP.
