### ISSUE TITLE
Footer analytics message displayed when analytics disabled

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3504]
Reproduce:
- Go to Admin --> Settings menu
- Clear 'Google analytics tracking ID' and 'Google analytics tracking ID (MOLGENIS)'
- Set 'IP anonymization' to 'Yes'
- Save changes and reload page

Expected:
- No Google analytics message displayed in footer

Actual:
- Google analytics message displayed in footer

**Comment by erwinwinder** [comment]
Cannot reproduce, already fixed.
