### ISSUE TITLE
Ontology tree plugin reports error when loaded

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3506]
Reproduce:
- Op ontology tree plugin (you might have to add it to a menu using the menu manager)

Expected:
- No error

Actual:
Error! An error occurred. Please contact the administrator.
Uncaught TypeError: molgenis.OntologyTree is not a function

Chao suspects this plugin is based on an old data model.

**Comment by Mark-de-Haan** [comment]
@mswertz @dennishendriksen @ChaoPang Still fails, Fix or remove from code base?

**Comment by dennishendriksen** [comment]
Ontology tree plugin removed in MOLGENIS 2.0.
