### ISSUE TITLE
Ontology annotator match results in error

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3508]
Reproduce:
- Import unit ontology 
- Open ontology service plugin (you might have to add it to the menu in the menu manager)
- Select new task and type a unique name
- As input use the exampe that is used in the placeholder
- Press match

Expected:
- Matching finishes succesfullly

Actual:
- Error: The task name should be case insensitive, the task name test2 has existed and created by user :

**Comment by Mark-de-Haan** [comment]
V5: ontology service plugin no longer exists
