### ISSUE TITLE
Chr6 error at runtime on 1.8.1(worked on 1.8.snapshot)

### ISSUE THREAD

**Issue by EdithAdriaanse** [molgenis/molgenis#3515]
Actual
I uploaded an EMX from chromosome6 on Molgenis69 (1.8.1). When filling in the questionnaire i get  errors: "Error! An error occurred. Please contact the administrator."

Expected:
Works the same as on Molgenis109 (1.8.snapshot), where there were no errors.
 
Reproduce:
- login on Molgenis69 as admin
- uplaod the EMX: "Chromosome 6 survey Part A - C"
- fill in the questionnaire

EMX: 
https://drive.google.com/open?id=0B1cmeDEcv7mLVHNIN1JQa1pvWWc

**Comment by dennishendriksen** [comment]
Fixed
