### ISSUE TITLE
TabixReader is not thread-safe

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3520]
If two methods use the same TabixReader concurrently, they'll get each other's results.
The TabixReader's Iterators share one and the same InputStream. Therefore if you read from them concurrently, the results will influence each other.

We already synchronize access to the query() methods of the tabix Repository classes which means only one query() method is ever active per repository. But I am not sure if that's completely fool proof.
One mistake that I do see is that TabixRepository's iterator() method calls readLine() on the repository which will eat up results from people who are annotating. (Plus I don't see where the iterator is reset to begin with! I suspect it just feeds you increasing pages from the repository even if you use it single-user mode)

The TabixReader checks if the position matches so most often you get less results than you should or duplicate results.
But I *do* at times see results that are combinations of two rows, so some of the columns are invalid!

**Comment by fdlk** [comment]
See https://github.com/fdlk/molgenis/tree/demo/3520 for a demo.

**Comment by bartcharbon** [comment]
The problem does not occur in the annotators I think, since they are using the Repositories instead of the reader directly. The repository's functions that interact with the TabixReader are synchronized, so we should be fine right?

The " https://github.com/fdlk/molgenis/tree/demo/3520" test looks promising when using TabixRepository instead of TabixReader

**Comment by fdlk** [comment]
Yes. I think so too.
The query() methods are synchronized in both TabixRepository and TabixVcfRepository. So they'll only ever have one Iterator active on the TabixReader and cannot hurt each other's annotations.

But if one person surfs to the dataexplorer and browses the TabixRepository, he gets a new iterator from the reader which "eats" up results from the iterators that are created for the query() calls.
