### ISSUE TITLE
OntologyTermSynonym lookup attribute undefined

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3538]
Reproduce:
- Import molgenis-ontology\src\test\resources\molgenis.test.obo.zip
- In data explorer open ontologyTermSynonym filter

Expected:
- I can search in the dropdown

Actual:
- Dropdown shows message "no lookup attributes defined"

**Comment by dennishendriksen** [comment]
Add migration step when fixing.

**Comment by Mark-de-Haan** [comment]
ID attribute is now set as lookUp attribute through new idAttribute ROLE
