### ISSUE TITLE
DataService does not work with Autovalue classes

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3539]
DataService with Class argument (e.g. ``<E extends Entity> Iterable<E> findAll(String entityName, Query q, Class<E> clazz);``) don't work in clazz is a ``@Autovalue`` annotated class. This is a developer annoyance.

**Comment by fdlk** [comment]
Entities aren't value objects, they can be updated.

**Comment by dennishendriksen** [comment]
Ah, you are right.
