### ISSUE TITLE
In the AttributeMapping screen, the algorithm cannot be properly removed

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3541]
In the AttributeMapping screen, if the algorithm is more than the name of the attribute e.g. $(attribute).map(2:1,1:0), when I uncheck the selected attribute in the source mapping table, only the name of the attribute is removed and the rest of the algorithm will remain in the algorithm editor. 

How to reproduce:
- In algorithm editor, paste in **$('attr').map({"1":"0","2":"1"}, null, null).value();**
- In the attribute mapping table, unselect the attribute used in the algorithm
- Only the name of the attribute is removed, the remaining part **.map({"1":"0","2":"1"}, null, null).value();** will be still in the algorithm editor

**Comment by Mark-de-Haan** [comment]
The entire algorithm is now removed
