### ISSUE TITLE
Delete all entities button does not work

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3543]
Marije ran into this.
She uploads rows through the rest api (not sure if this is needed to reproduce)
Then as admin presses the delete all entities button in the data explorer.
The rows then are gone.
But when you try to upload them again through the rest api, the insert fails.
Closer inspection shows that the rows still exist in the database and therefore the database complains when you re-insert them.

**Comment by dennishendriksen** [comment]
Delete data or delete data + meta data? Which version? I've been using the delete data + meta data feature a lot over the last week on the master branch without problems, so it might be nice to add a link  to the dataset causing this issue.

**Comment by fdlk** [comment]
No, as stated, delete data only.

**Comment by dennishendriksen** [comment]
Cannot reproduce:
- Start MOLGENIS with empty database/no index.
- Go to data explorer, select RuntimeProperty, Delete --> Data
- Check database: select count(*) from RuntimeProperty --> 0

**Comment by fdlk** [comment]
Cannot reproduce it either.
