### ISSUE TITLE
Error: Invariant Violation: unmountComponentAtNode(...): Target container is not a DOM element.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3553]
Not sure when exactly this happens but occasionally, most often while loading the page, I get the following alert:

```
Error: Invariant Violation: unmountComponentAtNode(...): Target container is not a DOM element.
```

Console says it happens in dataexplorer.js while calling
```
			React.unmountComponentAtNode($('#data-table-container')[0]); // must occur before mod-data is loaded
```
Happens on safari, surfing to local molgenis instance, master.

**Comment by dennishendriksen** [comment]
Same as #3462, this is the error in a non-minified environment.
