### ISSUE TITLE
Categorical filters are broken

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3557]
Reproduce:
- go to the dataexplorer
- check TypeTest, and filter for one of the categorical fields

expected:
- filter dialog shows checkboxes

actual
- filter shows textfield

It seems the filter uses the type of the referenced field in the xREF. (header of the filter dialog also mentions this field, for e.g. Exon.exon)

Seen in 1.9.0-SNAPSHOT of (3 september) and 1.8.2

**Comment by dennishendriksen** [comment]
![image](https://cloud.githubusercontent.com/assets/2477186/9727969/ed55fee0-5604-11e5-9f36-ad8121e15084.png)

Cannot reproduce in 1.9RC

**Comment by bartcharbon** [comment]
not broken. I clicked the filter icon of an attribute belonging to the categorical. However the behaviour is not really intuitive...
