### ISSUE TITLE
The Molgenis Rest API becomes slower the longer you use it in time

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3558]
Molgenis becomes slower the longer you use it in time. After deleting the database and restarting 

To reproduce:
1. Delete the database and restart Molgenis.
2. Add some rows into Molgenis via the Rest API ( it will take 0.6 seconds for one row).
3. Delete the data via the Rest API
4. Try step 1 again. (it becomes slower).

Context:
This problem is found after adding and deleting rows via the Python API that uses the Rest API

**Comment by dennishendriksen** [comment]
Review issue after implementing http://www.molgenis.org/ticket/3642

**Comment by Mark-de-Haan** [comment]
@jjettenn Is this still the case?

**Comment by jjettenn** [comment]
@Mark-de-Haan I don't know

**Comment by fdlk** [comment]
I believe that Niek and Dennis concluded that it's due to validation taking increasingly long the more records are present in the entity?

**Comment by jjettenn** [comment]
This issue is not relevant anymore
