### ISSUE TITLE
Unknown xref value for molgenisTransactionLog

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis#3566]
Rarely when adding rows to Molgenis (1.9.0-snapshot) through the REST API I get the error:

    Unknown xref value 'aaaact4tvy5he7v3ina5bgyaae' for attribute 'molgenisTransactionLog' of entity   'MolgenisTransactionLogEntry'. (row 2)

It seems to happen at random, adding the exact same data after the error without changing anything does not give the error again. I have not found how to reproduce it yet.

**Comment by Mark-de-Haan** [comment]
@npklein Does this still happen?

**Comment by npklein** [comment]
@Mark-de-Haan I have not seen this happen for a few months

**Comment by Mark-de-Haan** [comment]
Allright then im closing this.
