### ISSUE TITLE
Settings plugin edit form when user can only read settings

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3589]
Reproduce:
- Create non-superuser user and assign view permission on settings_app entity to user
- Login as user go to settings plugin in admin menu

Expected:
- App settings pre-selected in dropdown, "view" form displayed for settings

Actual:
- App settings pre-selected in dropdown, "edit" form displayed for settings. Trying to edit settings results in error.

**Comment by erwinwinder** [comment]
Nothing is pre-selected.
When you click in the dropdown you get redirected to login screen

**Comment by dennishendriksen** [comment]
Cannot be reproduced in v1.17.0, behavior is as expected.
