### ISSUE TITLE
Charts scatterplot missing values

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3591]
Reproduce:
- Import TypeTest, go to data explorer
- Set filter on xint 1<=x or x>= 5
- select charts module
- Create scatterplot with x-axis xint and y-axis xint
- Remove filter

Expected:
- Scatterplot with dots at (1,1), (2,2), (3,3) and (5,5)

Actual:
- Scatterplot with dots at (1,1) and (5,5)

![image](https://cloud.githubusercontent.com/assets/2477186/9728329/5a398854-5607-11e5-8345-183cce9139c3.png)

**Comment by dennishendriksen** [comment]
According to test plan this is desired behavior. Is this what we want?

**Comment by jjettenn** [comment]
![screen shot 2015-09-08 at 9 35 30 am](https://cloud.githubusercontent.com/assets/5586255/9729096/1c9b09ae-560d-11e5-98a8-dcfab2176f22.png)
I have tried this at Molgenis01 and it works. Which browser are you using? Tried with Chrome

**Comment by dennishendriksen** [comment]
Firefox 40

**Comment by jjettenn** [comment]
40.0.3 working on version
