### ISSUE TITLE
Genome browser popup missing information

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3597]
Reproduce:
- As non-superuser import genome_browser_test_emx.xls
- In data explorer, in genome browser click on item in track (see image)

![genomebrowser-popup-vraag](https://cloud.githubusercontent.com/assets/2477186/9731353/af87d27e-561c-11e5-8092-5a390de9a247.png)

Expected:
- Popup with more information

Actual:
- See image

**Comment by bartcharbon** [comment]
The information is actually there, only with the stylesheet applied on the test server the textcolor is white.
With the default stylesheet the text is shown.

<img width="936" alt="genomebrowser" src="https://cloud.githubusercontent.com/assets/3714029/9762713/894751f4-5705-11e5-8f9c-955bc702188b.png">

**Comment by dennishendriksen** [comment]
Works in 5.2.0
