### ISSUE TITLE
Importer should accept .obo and .owl files

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#3598]
The importer can import .obo or .owl files, but when you upload them without zipping them first you will get an error message saying that the extension is not supported.

## How to reproduce
1. Go to "upload" and select an .owl file
2. Press next

## Actual result
You get an error message saying that the file extension .owl isn't supported

## Expected result
The file is accepted

## Work-around
Create a zipfile with the ontology file and upload the ontology as such.

**Comment by Mark-de-Haan** [comment]
Can you create a story for it or should I?

**Comment by dennishendriksen** [comment]
Feature request, please add story to backlog.

**Comment by djvanenckevort** [comment]
Already added a story.
