### ISSUE TITLE
Annotating as a normal user will result in no permission on attributes and entities. Using the copy function will fail on no write permissions for packages

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3599]
Can be worked around with permissions.
RunAsSystem would be nice

**Comment by mswertz** [comment]
What would be the expected behavior? Annotation produces a dataset with the same permission as the source dataset?

**Comment by Mark-de-Haan** [comment]
No this is about you having to manually set permissions on entity classes
before a user can do anything. It should be runAsSystem so If a user has
edit rights on an entity he/she can annotate that entity without problems

On 14 September 2015 at 20:59, Morris Swertz <notifications@github.com>
wrote:

> What would be the expected behavior? Annotation produces a dataset with
> the same permission as the source dataset?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3599#issuecomment-140176347>.
>



-- 
Mark de Haan
Genomics Coordination Centre
Genetics Department
University Medical Centre Groningen

**Comment by mswertz** [comment]
Clear

On Mon, Sep 14, 2015 at 9:13 PM, Mark de Haan <notifications@github.com>
wrote:

> No this is about you having to manually set permissions on entity classes
> before a user can do anything. It should be runAsSystem so If a user has
> edit rights on an entity he/she can annotate that entity without problems
>
> On 14 September 2015 at 20:59, Morris Swertz <notifications@github.com>
> wrote:
>
> > What would be the expected behavior? Annotation produces a dataset with
> > the same permission as the source dataset?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/molgenis/molgenis/issues/3599#issuecomment-140176347
> >.
> >
>
>
>
> --
> Mark de Haan
> Genomics Coordination Centre
> Genetics Department
> University Medical Centre Groningen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3599#issuecomment-140180109>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl
