### ISSUE TITLE
OntologyTerm does not have a lookup attribute

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#3605]
If I use OntologyTerm as a referenced entity in my model I get a warning that OntologyTerm doesn't have a lookup attribute when I try to filter on the OntologyTerm in the data explorer.

## How to reproduce
1. Create a data model that has an entity with a reference to OntologyTerm
2. Upload this model
3. Select the entity in the data explorer and filter on the OntologyTerm

## Expected Result
I can filter on the OntologyTerm using the label as the lookup for the term

## Actual Result
I get a warning message that OntologyTerm doesn't have a lookup attribute

**Comment by dennishendriksen** [comment]
Very similar to #3538

**Comment by dennishendriksen** [comment]
Add migration step when fixing.

**Comment by Mark-de-Haan** [comment]
Caused by #3538, and fixed because OntologyTerm ID attributes are now set to LookUp attributes
