### ISSUE TITLE
Mapping script cannot exceed 255 characters

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#3618]
When a complex mapping needs to be made with many values mapped to something else the 255 character limit is problematic.

## How to reproduce
1. Create a new mapping project
2. Create a mapping with an extensive .map() function exceeding 255 characters
3. Save the mapping

## Expected result
The mapping is saved

## Actual result
I get an error telling that the value must be less than or equal to 255 characters.

**Comment by dennishendriksen** [comment]
Which version? Fixed when migrating from version 13 to 14.

**Comment by djvanenckevort** [comment]
Clean install of version 1.8.2 showed this issue.

**Comment by Mark-de-Haan** [comment]
Algorithm Metadata is already set to TEXT, so it should support scripts of more then 255 characters...

**Comment by Mark-de-Haan** [comment]
Confirmed: Fixed in version 1.9.0 and higher
