### ISSUE TITLE
As a non-admin user, I can not navigate from an entity with only count rights to another entity

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3621]
## Reproduce
  - Create a user
  - Set entity A to count permission
  - Go to the data explorer and open entity A
  - Try to go to another entity

## Expected
I navigate to another entity

## Observed
![screen shot 2015-09-09 at 15 30 54](https://cloud.githubusercontent.com/assets/3625016/9763061/c0939058-5707-11e5-9f5a-66e744330749.png)

**Comment by dennishendriksen** [comment]
Duplicate, see #3462 and #3553
