### ISSUE TITLE
DataExplorer filter error

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3622]
Filtering on a mref value of an attribute that is nested in two compound attributes gives an error.
![screen shot 2015-09-09 at 16 32 52](https://cloud.githubusercontent.com/assets/116559/9764717/daa36460-5710-11e5-9677-b2281aec1ae5.png)
![screen shot 2015-09-09 at 16 31 17](https://cloud.githubusercontent.com/assets/116559/9764720/dca4eaae-5710-11e5-94e0-5ba1fa92eabc.png)

**Comment by fdlk** [comment]
Cannot reproduce with homemade dataset. I've added a compound attribute that's part of a compound attribute and in there have tried a categorical mref, a normal mref, and even an xref and an enum. All are properly filterable.

**Comment by fdlk** [comment]
Cannot reproduce with the chr6 questionnaire either.
