### ISSUE TITLE
When mapping a numeric source attribute to a categorical target attribute, the advanced category mapping editor throws an error

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3623]
How to reproduce:
- Go to https://drive.google.com/open?id=0B7qHi41THTs_flRxcmRlLUwxYWx2ZDZ5YXJxc19BdmtZWVl4SmZTSXdndWJKNDJNN201Y2M
- Download HOP-10-attribute.xls and lifelines-emx-demo.xls, and load them into molgenis
- Start a new mapping project with HOP as the Target and lifelines as the Source
- Go to the AttributeMapping screen for the target attribute History of Stroke in lifelines
- Select the SourceAttribute Have you ever had a stroke? (Repeat) (1)
- Click on 'Map' tab in the Algorithm editor, error will be thrown

**Comment by dennishendriksen** [comment]
Is this really critical?

**Comment by mswertz** [comment]
Indeed not critical but scaring the user. What would be the desired behavior? In my mind either don't show the mapping editor at all (easiest solution), or make the mapping editor cope with the case where the source is not a categorical (e.g. by allowing user to type a value to be mapped).

**Comment by bartcharbon** [comment]
When I try to import lifelines-emx-demo.xls I get an error:
Exception in thread "Thread-11" org.springframework.dao.CannotAcquireLockException: PreparedStatementCallback; SQL [INSERT INTO `MolgenisTransactionLogEntry` (`id`, `molgenisTransactionLog`, `entity`, `type`) VALUES (?, ?, ?, ?)]; Lock wait timeout exceeded; try restarting transaction; nested exception is java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction

I'll file this as a separate bug, but for now it blocks my attempt to reproduce and fix the issue.

**Comment by fdlk** [comment]
Map tab no longer appears.

**Comment by Mark-de-Haan** [comment]
This is still an issue
