### ISSUE TITLE
Creating an integrated dataset after mapping two entities either fails, or takes a very long time

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3630]
## Reproduce
- Map two entities
- Click the Create integrated dataset
## Expected

A new entity to be created with the produced mapping in a reasonable amount of time
## Observed

The mapping takes a very long time, resulting in internal server error on molgenis62. If you use System entities, you get a repository = null error.

These things make it virtually impossible to create a new dataset after mapping large entities.

**Comment by tommydeboer** [comment]
The mapping service does continue integrating the datasets after this error.

**Comment by bartcharbon** [comment]
This probably is a server timeout like we also experience during annotations sometimes. The functionality should be async to fix this.

workaround is configuring the server with an extreme timeout.

**Comment by fdlk** [comment]
@ChaoPang has been working on this I believe.

**Comment by dennishendriksen** [comment]
Replacing the Rhino JavaScript engine with Nashorn resulted in this operation being very fast.
