### ISSUE TITLE
When running multiple annotators, a failing annotator will prevent subsequent annotators from running

### ISSUE THREAD

**Issue by mark-de-haan** [molgenis/molgenis#3631]
## Reproduce
- Upload test_mutation_emx
- Use Molgenis62 to annotate with cadd, clinvar, and snpeff
## Expected

Clinvar is broken at the time of this bug, but I expect cadd and snepff to be added
## Observed

Only cadd is added, and the metadata of clinvar. Snpeff is nowhere to be found

**Comment by dennishendriksen** [comment]
Communicate to users which annotators failed and which annotators succeeded.

**Comment by dennishendriksen** [comment]
How to reproduce? I get the following in the annotator tab when selecting the entity test_mutation_emx:
```cadd (annotation datasource unreachable)
CGD (missing required attribute)
dann (annotation datasource unreachable)
clinvar (annotation datasource unreachable)
hpo (missing required attribute)
exac (annotation datasource unreachable)
fitcon (annotation datasource unreachable)
snpEff (annotation datasource unreachable)
thousand_genomes (annotation datasource unreachable)```

**Comment by fdlk** [comment]
See the test plan for annotation config and resource data

**Comment by dennishendriksen** [comment]
We should add info about the required resources to:
- the readme https://github.com/molgenis/molgenis
- the create molgenis vm sop such that all molgenis instances can run annotators
