### ISSUE TITLE
Clicking the 'map'-tab gives an error when no xref attribute has been selected yet

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3637]
## To reproduce:
1. Make a mapping project with at least one xref in it
2. Edit the xref mapping
3. Don't select an attribute yet in the mapping screen, but go the the 'map'-tab

## Expected:
Empty tab is shown or tab is not clickable.

## Actual:
![image](https://cloud.githubusercontent.com/assets/5362890/9787295/d1e133b4-57c1-11e5-8ad5-7d3ca8bdc7fc.png)

**Comment by mswertz** [comment]
I would expect that the mapping editor would not be shown unless a source is chosen?
This bug is related to #3623

**Comment by jjettenn** [comment]
When selecting a category in the "Category mapping editor" then the mapping tab disappears.

**Comment by fdlk** [comment]
Still borked.
![screen shot 2015-10-20 at 17 09 16](https://cloud.githubusercontent.com/assets/1523838/10611655/5e82887c-774d-11e5-8993-fae3a28763e7.png)

**Comment by fdlk** [comment]
If you map Script to Script and then open the algorithm editor for the Type attribute you can easily muck things up if you play around a bit with the select box and the map tab.
