### ISSUE TITLE
An error will occur if one clicks on the mapping service while importing a dataset

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3657]
- How to reproduce,

- create a mapping project with any target entities and source entities. 
- import a relatively large data set, e.g. download lifelines-emx-demo.xls at https://drive.google.com/open?id=0B7qHi41THTs_WV9xUlNWVjNHT3c
- navigate to Mapping Service and error occurs 

{"errors":[{"message":"An error occurred. Please contact the administrator.<br />Message:Unknown entity [SEX_Ref]"}]}

**Comment by Mark-de-Haan** [comment]
Can not reproduce
