### ISSUE TITLE
Annotators refuse to run for EMX files with string type ALT attribute

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3686]
When I upload an EMX file with string type ALT attribute, the annotator refuses to run. It claims that the required attribute has the wrong type.

This is regression introduced by the fix for #3351 .

**Comment by Mark-de-Haan** [comment]
Suggesting multiple type support?
Else EMX alt and refs must be defined as text

**Comment by fdlk** [comment]
text > string and somehow the check should know this?
