### ISSUE TITLE
Table attribute expand not working if attribute in compound

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3693]
- Load Chr6 questionnair:
https://drive.google.com/open?id=0B4_AOpOI8V7GZV8wSll6emxjYW8

- Goto the questionnair plugin and fill (part of it) in.
- Goto the dataexplorer
- Clcik on a 'expand column' button in a column header

Expected: Column is expanded.
Observed: nothing happens

![screen shot 2015-09-16 at 14 07 54](https://cloud.githubusercontent.com/assets/116559/9904330/2a16cfac-5c7d-11e5-8574-1ac7cce4dcba.png)

**Comment by dennishendriksen** [comment]
Needs to be fixed in 1.10?

**Comment by bartcharbon** [comment]
maybe related to #3949. probably uses the same variable with a list of attributes?

**Comment by dennishendriksen** [comment]
Can reproduce in v1.17.0-SNAPSHOT. Note that the attribute that you try to expand is in a compound attribute.

**Comment by dennishendriksen** [comment]
Minimal example to reproduce this issue: [emx-xrefincompound.xlsx](https://github.com/molgenis/molgenis/files/113638/emx-xrefincompound.xlsx)

**Comment by dennishendriksen** [comment]
@bartcharbon this fix does not fix #3949
