### ISSUE TITLE
Mapping service freemarker exception on mapping edit

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3698]
Reproduce:
- Log in with a superuser
- Create a mapping project with target MolgenisGroupMember
- Add source RuntimeProperty
- Press edit icon on molgenisUser mapping row

Expected:
- Navigation to mapping edit screen

Actual:
- Error screen:
  `Request processing failed; nested exception is freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
  ==> category[attributeName]  [in template "view-attribute-mapping.ftl" at line 105, column 75]`

**Comment by fdlk** [comment]
Still seeing this.
```
org.molgenis.data.UnknownEntityException: entity [test_HOPGENDERRefSelenium] with code [168] does not exist)
```

**Comment by Mark-de-Haan** [comment]
V5: Issue no longer reproducible
