### ISSUE TITLE
Failing snpEff will not roll back the adding of metadata

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3707]
## Reproduce

I encountered this bug before #3655 was fixed, the snpEff annotator failed on large fields because it was string not text.
- Upload vcf
- annotate with snpEff
- it fails because the HGSV.c field is string so >255 characters will make it crash
- annotate again
## Expected

It will fail again with the same error
## Observed

StatementCallback; bad SQL grammar [ALTER TABLE `test_mutation_emx` ADD `Annotation` TEXT;]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'Annotation'

Apparently the metadata that was added by the snpEff annotator was not removed when it failed the first time.

**Comment by dennishendriksen** [comment]
How to reproduce now that #3655 is fixed?

**Comment by Mark-de-Haan** [comment]
Hmm only way to reproduce is to break an annotator manually at a point where it will update entities in the database, like it happend with the >255 into string field here.

If our annotators all work, then this is no longer an issue.

**Comment by dennishendriksen** [comment]
Do you know a trick how to do this by manipulating a resource file?

**Comment by Mark-de-Haan** [comment]
Maybe,
- Use the CADD resource
- Go to a row that you know will be matched with a chrom/pos/ref/alt pair
- Change its CADD_Scaled values to a string like 'test' or something

Now if the annotator matches that row, it will try to add the value 'test' to an attribute with a double data type.

Should produce the same effect

**Comment by fdlk** [comment]
I think the underlying issue is that the in-memory cache of the metadata is not transactional. It should get refreshed if à transaction geta rolled back.

**Comment by dennishendriksen** [comment]
Fixed in MOLGENIS 2.0.
