### ISSUE TITLE
FreemarkerTemplate entities read from MySQL instead of Elasticsearch

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3709]
Reproduce:
- Enable query logging in MySQL:
  - Execute SET GLOBAL log_output = 'TABLE';
  - Execute SET GLOBAL general_log = 'ON';
- Open molgenis home page
- Take a look at the table mysql.general_log
- **Restart mysqld to disable query logging**

Expected:
- No select statements on entities (Elasticsearch handles reads)

Actual:
- Statements such as: `SELECT DISTINCT id, Name, Value FROM FreemarkerTemplate WHERE (Name = 'view-menumanager_en_US.ftl')`

**Comment by mswertz** [comment]
I am not sure this is a bug because our current distribution of storing in mysql but retrieving from ES is weird

**Comment by dennishendriksen** [comment]
This is a bug, because the behavior is different from other entities that have MySQL as backend. Regardless of the desired behavior there should be no differences between entities that have the same backend.

**Comment by mswertz** [comment]
I agree it is a bug, because inconsistent. I am just not clear which part needs fixing. I.e. unclear on expected behavior

**Comment by dennishendriksen** [comment]
FreemarkerTemplate entities always read from PostgreSQL, not from Elasticsearch since MOLGENIS 2.0.
