### ISSUE TITLE
Rollback is not working

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3713]
The original issue (#3663) is solved but the Rollback problem is not solved and may give problems in the future. 

To reproduce:

Import the "test questionnaire" file
Try to import the latest version of the Chromosome 6 questionnaire (Can also use an old one if it contains a Gender entity).
Wait until you think that it is taking to long. (~3 minutes)
Push the "Restart" button.
Expected: import is correctly rolled back

Actual: data-explorer is returning a 500 exception saying that the Gender Entity does not exists.

Expected: rollback is down bij clicking on the reset button

**Comment by dennishendriksen** [comment]
Related to #3707? What do you thnk @jjettenn?

**Comment by jjettenn** [comment]
I cannot reproduce the problem because of fix #3663.

The assumption that pushing the restart button will case a roll-back is incorrect.
The only action that this button does is stopping the session. The import job is not synchronized and will continue with importing.
