### ISSUE TITLE
Home page editor escapes / completely removes spans without text

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3718]
## Reproduce
- Edit home page
- Go to tools -> edit source code
- create an html element ```<button><span class="glyphicon glyphicon-search"></span></button>```
- save and close

## Expected
My home page now contains a button with the search icon

## Observed
The button is never created because it contains no text.

Creating a similar construction with text inside the span or button WILL render it.

**Comment by dennishendriksen** [comment]
Appears to be a bug in TinyMce, see http://stackoverflow.com/questions/14962819/prevent-tinymce-from-removing-span-elements
