### ISSUE TITLE
Data table's scroll bar obscures data table in IE10 and IE11

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3722]
![image001](https://cloud.githubusercontent.com/assets/1523838/10017787/97637ff2-6131-11e5-8d45-9fc92b481ae0.png)

**Comment by fdlk** [comment]
Seen on Edith's laptop.
Also, the icon does not appear on the table-only button in the top right.

**Comment by dennishendriksen** [comment]
Cannot reproduce in 1.9 on IE11. What does Tools --> Compatibility view settings say on Edith's laptop? Which resolution? Does the problem occur for all data sets?

**Comment by dennishendriksen** [comment]
@fdlk see previous comment

**Comment by fdlk** [comment]
cannot reproduce
