### ISSUE TITLE
Selecting a package in the third screen of the advanced importer does nothing

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3723]
### Reproduce
- Import [this file](https://drive.google.com/open?id=0B3D6LFtvxTarbVBhQmJrcmhzbG8)
- Select gids as a package at the third screen

### Expected
Imported gids_biobank
Imported gids_protocol

### Observed
Imported base_biobank
Imported base_protocol

**Comment by erwinwinder** [comment]
Cannot reproduce in master and not in 1.10
@fdlk can you confirm?

**Comment by Mark-de-Haan** [comment]
I could reproduce in 1.9

**Comment by fdlk** [comment]
The version on google drive had no package column on the entities, it should have one, set to gids, to reproduce the problem. I don't know if it got updated or if I uploaded the wrong version of the file.

That said, the issue changed a bit in 1.10.
In 1.9 the importer lists 4 entities on the validation sheet.
In 1.10 it lists only 2 entities, as expected.

Unfortunately, it does still throw an exception:
```
org.molgenis.data.MolgenisDataException: Missing idAttribute for entity [gids_bloodbank]
Add column package on the entities sheet.
```

**Comment by Mark-de-Haan** [comment]
Proposed fix: Give a clear error message when there is an inconsistency between entity packages and attribute entity packages when working with the extends parameter

**Comment by Mark-de-Haan** [comment]
Proposed to fix when redesigning the importer. Current code does not allow for a quick fix

**Comment by mswertz** [comment]
so what is the behavior now? An error message?

On Mon, Oct 19, 2015 at 4:33 PM, Mark de Haan <notifications@github.com>
wrote:

> Proposed to fix when redesigning the importer. Current code does not allow
> for a quick fix
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3723#issuecomment-149233107>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by Mark-de-Haan** [comment]
Only with some nasty hacks would we be able to throw an error message at the right time and place. A lot of things don't feel right, even when an entity extends from the correct metadata MySQL will throw an error. I think we would be introducing more buggy behaviour if we try to change anything in the current EmxMetaDataParser

**Comment by mswertz** [comment]
okay, than this should be added to the documentation instead.

Or, bold suggestion, disable 'package' for users ATM?
As it doesn't work? Or is it not soo bad?


On Mon, Oct 19, 2015 at 4:57 PM, Mark de Haan <notifications@github.com>
wrote:

> Only with some nasty hacks would we be able to throw an error message at
> the right time and place. A lot of things don't feel right, even when an
> entity extends from the correct metadata MySQL will throw an error. I think
> we would be introducing more buggy behaviour if we try to change anything
> in the current EmxMetaDataParser
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3723#issuecomment-149239743>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by Mark-de-Haan** [comment]
So far as I know you can work around this problem by not extending entities which are in a package

**Comment by fdlk** [comment]
I think the problem only occurs if you
* specify the package column on the entities sheet AND
* use non-qualfied entity name in the extends column

**Comment by dennishendriksen** [comment]
Cannot reproduce in 8.0.0-SNAPSHOT with the file linked in the issue description.

>The version on google drive had no package column on the entities, it should have one, set to gids, to
>reproduce the problem. I don't know if it got updated or if I uploaded the wrong version of the file.

Adding a column ```package``` to sheet ```entities``` and setting all values to ```gids``` (see [gh3723_with_package.xlsx](https://github.com/molgenis/molgenis/files/2802793/gh3723_with_package.xlsx))
results in:
```
Error! Your import failed:
Missing super entity protocol for entity bloodbank on line 3
```
as I would expect.

@fdlk Can you provide a file to reproduce this issue?

**Comment by fdlk** [comment]
@dennishendriksen Behavior has changed in two breaking ways:
* The extends column used to allow you to specify the *name* of the entity, even if you added a package column. It no longer allows that. Which I'd say is clearer for the user even if it's a bit naughty that we broke the spec. But it does mean that this how-to-reproduce route is simply no longer allowed.
* The packages you add on the package sheet are no longer listed as options to import to in the third step. This I'd say is a bug, but not the current one. The good news is that that bug effectively hides this bug by blocking the other how-to-reproduce route. I propose to close this.

**Comment by dennishendriksen** [comment]
Thanks for your detailed answer.

> The packages you add on the package sheet are no longer listed as options to import to in the third step. This I'd say is a bug, but not the current one.
I think so too, but might be by design. @mswertz ?
