### ISSUE TITLE
SecurityError/InvalidStateError when trying to edit the description of a File entity

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3736]
## To reproduce:
1. Upload file_datatype-test.xlsx (in molgenis-app)
2. In the data explorer, go to the File entity and add a new entity
3. Try to edit the description
## Expected:

The description changes.
## Actual:

In Chrome:
![image](https://cloud.githubusercontent.com/assets/5362890/10048781/e07fba78-6214-11e5-9a35-0b9e94966811.png)

In Firefox:
![image](https://cloud.githubusercontent.com/assets/5362890/10048791/ec433f6a-6214-11e5-8a52-7ca3638aa789.png)

**Comment by tommydeboer** [comment]
Fix together with #3739 ?

**Comment by Mark-de-Haan** [comment]
Fixed in v5.3.0-SNAPSHOT
