### ISSUE TITLE
'Save and continue later' will remove all current answers when one of the inputs doesn't validate

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3742]
## To reproduce:
1. Upload *Chr6_vragen_emx_testimport10 (2).xlsx* (see IssueData on Google Drive)
2. Answer a few questions
3. Invoke a validation error on one of the fields
4. Click 'Save and continue later' at the bottom of the page

## Expected:
The form will not submit and scrolls you to the invalid answer OR the form submits and saves the valid answers.

## Actual:
You lose all the answers you gave in that session. When it is the first time you've opened the questionnaire, the status will not change to 'Open' but is still 'Not started yet'. If you've saved it before, those answers will not be lost. Losing answers will only happen for the session in which you invoke a validation error.

**Comment by mswertz** [comment]
Ouch, that sounds quite critical!

On Thu, Sep 24, 2015 at 11:08 AM, tommydeboer <notifications@github.com>
wrote:

> To reproduce:
>
>    1. Upload *Chr6_vragen_emx_testimport10 (2).xlsx* (see IssueData on
>    Google Drive)
>    2. Answer a few questions
>    3. Invoke a validation error on one of the fields
>    4. Click 'Save and continue later' at the bottom of the page
>
> Expected:
>
> The form will not submit and scrolls you to the invalid answer OR the form
> submits and saves the valid answers.
> Actual:
>
> You lose all the answers you gave in that session. When it is the first
> time you've opened the questionnaire, the status will not change to 'Open'
> but is still 'Not started yet'. If you've saved it before, those answers
> will not be lost. Losing answers will only happen for the session in which
> you invoke a validation error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3742>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by tommydeboer** [comment]
Agreed!

Similar problem has been encountered before but couldn't be reproduced: #3658

**Comment by erwinwinder** [comment]
This bug was already fixed.
Maybe reappeared because of issue #3737

**Comment by tommydeboer** [comment]
Fixing #3737 did indeed also fix this!
