### ISSUE TITLE
Conditional questions aren't closed correctly when you change your answer

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3743]
## To reproduce:
1. Upload *Chr6_vragen_emx_testimport10 (2).xlsx* (see IssueData on Google Drive)
2. Answer question *B1.a An abnormal head size?* with **Yes**
3. Answer the conditional question *What kind?* with **Microcephaly**
4. A new conditional question will appear: *Please specify*
5. Change your answer for question *B1.a* to **No**

## Expected:
The two conditional questions will disappear.

## Actual:
The *Please specify* question will remain and it can't be removed, whatever your answer is.

![image](https://cloud.githubusercontent.com/assets/5362890/10069843/18f04c16-62af-11e5-9d4c-b6d5fcbda9cc.png)

**Comment by erwinwinder** [comment]
Won't fix.
Can be resolved by the correct visibleExpression in the EMX file.
Most visible expression are correct in the questionnaire file, tis one we missed.
