### ISSUE TITLE
Tag Wizard: auto complete does not work in the "Select ontologies to add as tags" modal

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3748]
To reproduce:

Download the folder (real_examples) at: https://drive.google.com/drive/folders/0B7qHi41THTs_T3BnaHY2TGJ1Mzg  
"Demo target data: 
1. HOP-attributes-testing.xls"  Upload via the upload page  
"Demo source data: 
1. lifelines-emx-demo-1-row.xls
2. prevend-emx-demo-4-rows.xls" Upload via the upload page  
"Demo ontology files:
1. biobank_ontology.owl.zip
2. uo.owl.zip"  Upload via the upload page  
"Demo magma script type and algorithm template file:
1. test-javascript_magam.xls" Upload via the upload page  

Navigate to the TagWizard located under the Data Integration Menu You should see two ontologies (biobank_ontology and uo) pre-selectaed
Select the entity HOP from pulldown 
Press the 'edit' button for the attribute that is called Body_Mass_Index  A modal will popup with an empty select box
Edit Modal  
- In the input box search for height  It will find the ontology term Height

"Select ontologies to add as tags"
Auto complete does not work: - In the input box search for height

Expected:
type: h --> suggestion Height

Actual:
type: h --> No Height is suggested

**Comment by Mark-de-Haan** [comment]
No this is working as it should, it only starts suggesting after typing 2-3 characters.
@ChaoPang ?
