### ISSUE TITLE
Annotators are willing to annotate data that has columns that overlap with the ones they add

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3750]
When running the annotator regression test, select snpEff.
It'll try to add the GeneName column which is already present in the dataset.

```
Error! An error occurred. Please contact the administrator.
Message:org.molgenis.data.MolgenisDataException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ALTER TABLE `mrRznbhheslMaFCxxxTHBCNJeOOZVV` ADD `Gene_Name` TEXT;]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'Gene_Name'
```

I'd expect it either refuses to run or it'll add the GeneName attribute with a slightly different name.

**Comment by Mark-de-Haan** [comment]
I thought we just updated the values...

**Comment by mswertz** [comment]
I think this behavior is as desired (i.e. if you run an annotator twice it updates the existing values). However, I do understand the danger of this when applied to an existing dataset (you might overwrite your manually entered data). So a warning is in order? Or what alternatives do we have?

**Comment by bartcharbon** [comment]
Closed my duplicate report, some notes from that one:

"unclear what we expect, I think we would not want to overwrite the original data right?

So maybe disable the annotator is a column is already present?
Do we want to distinguish between original columns and columns added by a previous annotation run?
Prefix column ID's with the annotator name (might not be nice for the commandline version)

I think we can assume that sooner or later this will result in overwriting a users data, or we'll run into this with columns added by mutiple annotators with different values. We need to discuss how to fix"
