### ISSUE TITLE
Mapping Service algorithm editing is slow

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#3776]
Mapping Service is very slow when writing a mapping script and seems to re-evaluate the script after each keystroke in the script editor.

How to reproduce:
- Create a new mapping project on molgenis21
- Select rdconnect_sample as the target model
- Select eurobiobank_samples as a source
- Try to write a mapping for the MIABIS attribute type

Expected result:
- I can type a script and immediately see the results on the example columns

Actual result:
- The example columns are lagging behind on what I change. It seems like it is re-evaluating after every keystroke. (And reports an invalid script most of the time)

**Comment by dennishendriksen** [comment]
The mapping service validation functionality was changed to manual triggering instead of automatic in MOLGENIS 1.21. Furthermore the mapping service performance was improved in MOLGENIS 2.0.
