### ISSUE TITLE
Mapping Service --- "Error converting value [DNA] to XREF at "

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3777]
To Reproduce:

1. Upload dataset: Dateset-Template-V14.xlsx and RING_14_9sept2015_EMX.xlsx (You can find them hier https://drive.google.com/a/dtls.nl/folderview?id=0ByRB-nsJAvkrfnBnOGNQNGpvREdNQlRmWFFud2hma2RGb3NQNkVtbVJOOWdTUkFrRVlYaHc&usp=sharing)
2. Preform reindex the data from biobanks (Add via menu the idcard plugin).
3. Use mapping service to map both datasets: You can find the mapping on molgenis21.
4. Try to create a now dataset  "Create integrated dataset"

Actual: You will get the following error message:
java.lang.RuntimeException: Error converting value [DNA] to XREF at org.molgenis.data.mapper.service.impl.AlgorithmServiceImpl.convert(AlgorithmServiceImpl.java:337) at org.molgenis.data.mapper.service.impl.AlgorithmServiceImpl.apply(AlgorithmServiceImpl.java:284) at

**Comment by fdlk** [comment]
Probably means that the row with id "DNA" is missing?

**Comment by bartcharbon** [comment]
- "map both datasets" which entities?
- molgenis21 does not contain mappings
- I cannot import Dateset-Template-V14.xlsx in a clean MOLGENIS build from the RD-Connect branch

**Comment by jjettenn** [comment]
Dateset-Template-V14.xlsx is an old version. In the current Molgenis21 trying to create integration data set is not working but in not related to this issue.  
<img width="1277" alt="screen shot 2015-11-12 at 9 54 00 pm" src="https://cloud.githubusercontent.com/assets/5586255/11131930/5a48a55a-898d-11e5-9c3f-956c5c721b1b.png">
