### ISSUE TITLE
Uploaded logo gone after MOLGENIS upgrade

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3779]
Reproduce:
- On molgenis01 as admin go to Admin -> Menu manager plugin and upload a logo
- Login on molgenis01, stop Tomcat and remove ~molgenis/apache-tomcat/webapps/ROOT
- Start Tomcat

Expected:
- Uploaded logo is used in the application

Actual:
- Broken link to logo used in the application

Problem typically occurs when updating a MOLGENIS installation. Uploaded logos should be stored/retrieved using the file store instead of the war folder.

**Comment by Mark-de-Haan** [comment]
in v5: Logos are now stored in the file store
