### ISSUE TITLE
Adding a description to attributes via the data explorer editor does not work for tree or filter wizard

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3781]
## Reproduce
* Upload TypeTest
* Go to attributes as admin
* Search for xbool and press edit
* Add a description
* Save
* Go to TypeTest
* Hover over xbool item / click xbool to open filter window

## Expected
I see the description in a on hover
I see the description in the filter window

## Observed
The description is nowhere to be seen.

It is however located in the attributes table

**Comment by tommydeboer** [comment]
This belongs to the 'changing meta data' story, and isn't really a bug because you're not supposed to edit the attributes table.
