### ISSUE TITLE
Filter dialog does not appear when completely zoomed in on genome browser

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3787]
Select a genomic dataset in the data explorer.
The genome browser will show.
Click a row in the data table.
The genome browser zooms in on the selected row.

Try to click the selected mutation letter in the data track.

Expected:
Popup pops up where you can select a filter for the selected mutation.
Actual:
The grey vertical selection bar completely overlaps the clickable mutation letter and the popup doesn't appear.

**Comment by Mark-de-Haan** [comment]
I reported this issue to the github of the GB creator. I do not think it is something we should or can fix

**Comment by tommydeboer** [comment]
I'll close this because it is something we can not fix ourselves.
