### ISSUE TITLE
Aggregates view does not update when you edit the data

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3788]
Go to TypeTest.
Select aggregates, aggregate xbool x xdate

Edit row 1, change the date attribute.

Go back to the aggregates
Expected:
Aggregates get updated

Actual:
Aggregates show the previously computed aggregate values.

**Comment by Mark-de-Haan** [comment]
Fix; it should recompute every time the tab is selected. With a page refresh the values are updated

**Comment by mswertz** [comment]
wontfix
