### ISSUE TITLE
JSON structure of api/v1 and api/v2 are not comparable, causing errors when using react components that do rest calls

### ISSUE THREAD

**Issue by mark-de-haan** [molgenis/molgenis#3793]
The attributes of api/v1 can be called by .attributes
The attributes of api/v2 can be called by .meta.attributes

This causes problems for react components, if they receive attributeMetaData with a v2 href and proceed to do a rest call to get refEntityMetaData, then the rest of the function is going to fail because the v2 response has a different structure.

**Comment by dennishendriksen** [comment]
The reason it is v2 of the api is that it is not compatible with v1. Is v2 refering to v1 resources?

**Comment by Mark-de-Haan** [comment]
the AttributeMetaDataResponseV2 was using the RestControllerV1 base uri.
This caused things to go right.

When I changed it to use the RestControllerV2 base uri, problems started showing up for react components doing a rest call with a href containing api/v2

**Comment by dennishendriksen** [comment]
@Mark-de-Haan How to reproduce?

**Comment by mswertz** [comment]
apis of different major versions don't need to be compatible, that is the point.
