### ISSUE TITLE
Filtering string values with a pipe sign or underscore fails

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3814]
When using the filter (so not google search) on for example a gentype field, searching for "1|0" returns all values containing  either a 0 or a 1.
1|1 returns al values containing a 1, 0|0 al values containg a 0.

For the filter we would expect it to be exact.

tried escaping the pipe with a backslash but than the behaviour remains the same.

UPDATE: Same is happening for underscores, for example in biobank identifiers. BIOBANK_1 will find BIOBANK_2 as well, because it searches for "BIOBANK" and "2" because of the way we tokenize.

**Comment by Mark-de-Haan** [comment]
Wouldn't fixing this require changes to the way our elastic search behaves? Feels more like a story then a bug fix.

**Comment by bartcharbon** [comment]
Getting the lines that conform to your filterstring sound more like a bugfix than a story to me

**Comment by bartcharbon** [comment]
http://www.molgenis.org/ticket/3714 seems to be more about "searching" (SEARCH) than "filtering" (EQUALS)

**Comment by bartcharbon** [comment]
Different solutions are optimal for different use cases. Need to discuss -> removed from sprint 74
