### ISSUE TITLE
Galaxy API key visible

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3815]
For users to be able to use the DataExplorer he needs READ permission on entity 'settings_dataexplorer'.

But in that settings the Galaxy API key is saved, so it can be seen by everyone.

PS
Wouldn't it be better if normal users don't see the settings at all?

**Comment by erwinwinder** [comment]
![screen shot 2015-10-01 at 16 08 35](https://cloud.githubusercontent.com/assets/116559/10223031/569edb2e-6857-11e5-8f54-0ce5bff90afb.png)

**Comment by mswertz** [comment]
Indeed.

Settings that can be editted by admin only should generally only be visible
by them too

Or do we see exceptions

(I can imagine we will move to per-user settings at some point)

On Thu, Oct 1, 2015 at 4:13 PM, Erwin <notifications@github.com> wrote:

> For users to be able to use the DataExplorer he needs READ permission on
> entity 'settings_dataexplorer'.
>
> But in that settings the Galaxy API key is saved, so it can be seen by
> everyone.
>
> PS
> Wouldn't it be better if normal users don't see the settings at all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3815>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by erwinwinder** [comment]
You get an exception 'No READ permission on settings_dataexplorer' when a user without READ permission on that entity opens the dataexplorer.

Maybe use 'runAsSystem'  when getting the settings?
Then you don't need to give users explicit READ permissions.

**Comment by mswertz** [comment]
I suppose; should the settings repository (that I suppose exist) solve this
centrally?

On Thu, Oct 1, 2015 at 4:17 PM, Erwin <notifications@github.com> wrote:

> You get an exception 'No READ permission on settings_dataexplorer' when a
> user without READ permission on that entity opens the dataexplorer.
>
> Maybe use 'runAsSystem' when getting the settings?
> Then you don't need to give users explicit READ permissions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3815#issuecomment-144741008>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by dennishendriksen** [comment]
Settings can be retrieved by the client and used in JavaScript to build/configure the UI. Not showing the settings to users doesn't solve the problem. In this case we could create a seperate galaxy settings entity (or move the galaxy api key setting to app settings), not assign permissions to users and use it server side using the runAsSystem method.
