### ISSUE TITLE
Something weird happens when you download xmref_value

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3816]
## Reproduce
- Import and look at TypeTest in the data explorer
- Only select id, xbool, and xmref_value in the tree
- Set filter for xbool to true
- Select download
- Choose attribute labels, entity values labels, xlsx

## Expected
I get an xlsx file with all the values

## Observed
I get some weird values in the xmref_value list

![screen shot 2015-10-01 at 16 31 58](https://cloud.githubusercontent.com/assets/3625016/10223641/6d9a2c7c-685a-11e5-89bf-226288d5d3aa.png)

![screen shot 2015-10-01 at 16 36 15](https://cloud.githubusercontent.com/assets/3625016/10223681/8fc6aa82-685a-11e5-9289-7af3e87e23ed.png)

**Comment by tommydeboer** [comment]
Actually, I made the RefEntity *TypeTestRefTestTypeTestRefTestTypeTypeTestRef*. Fooled ya! This is not a bug.
