### ISSUE TITLE
Forms/Questionaires render slowly in Safari

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3822]
When you have a large questionnair/form (like Chomosome6) in Safari it takes a lot of time before the whole form is rendered.

**Comment by tommydeboer** [comment]
For me this happens in all browsers (more than 8 seconds at least). Semi-related to #3754 Inputs are very slow in large forms. Forms need speed improvements.

**Comment by Mark-de-Haan** [comment]
Wontfix: Issue will be addressed in the [VueForms](https://github.com/Mark-de-Haan/molgenis-vue-forms)

**Comment by sidohaakma** [comment]
Is rewritten in VUE in MOLGENIS 7.0.0. This behavior is not observed anymore.
