### ISSUE TITLE
Cannot import RuntimeProperty.csv

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3825]
When trying to import molgenis-app/src/test/resources/csv/RuntimeProperty.csv
This is the result:

![screen shot 2015-10-02 at 10 45 55](https://cloud.githubusercontent.com/assets/116559/10242714/187a2e74-68f3-11e5-8b82-2438d6f65aa1.png)

**Comment by fdlk** [comment]
Known bug, delete the existing properties first

**Comment by fdlk** [comment]
Duplicates #2461
