### ISSUE TITLE
When referencing a foreign key twice in my EMX, the importer works, and they are stored in the elastic search document as duplicates

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3829]
## Reproduce
- Create an EMX with an mref
- From the referencing table, put the same foreign key twice into one row

myEntity        
ID mref
1  a, a, b

myRefEntity
ID
a
b

- Import

## Expected
The importer complains

## Observed
EMX is imported, and the entry is duplicated in the elastic search document
/api/v2/myEntity/1 will return myRefEntity[{ID: a}. {ID:b}, {ID:a}]

This is not really nice when using the rest API for example, because you get duplicate values back. Quick work around is dropping the index and restarting because MySQL handles it correctly.

**Comment by bartcharbon** [comment]
I say: feature. If this is not possible homozygote patients cannot be stored with a mref.

**Comment by fdlk** [comment]
Working as intended!
