### ISSUE TITLE
The mapping category editor does not show up for categorical target attributes

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3839]
How to reproduce:
- go to molgenis01
- create a new mapping project with HOP as the target and add the finrisk biobank as the source
- in the mapping overview screen, click on the cell that is located in the row "History of Stroke" and column 'finrisk'
- the mapping category editor is not in the mapping screen
- unselect the top suggested attribute "Cerebrovascular accident" and select it again, the mapping category editor shows up

**Comment by Mark-de-Haan** [comment]
Question: Was there an attribute selected when you first opened up the attribute mapping editor? It is supposed to work this way because you can not generate the values for the mapping category editor if you do not have an attribute selected

**Comment by dennishendriksen** [comment]
@ChaoPang why did you reopen this issue?

**Comment by ChaoPang** [comment]
It was a problem that re-appeared sometime ago, it was a famous timing issue in the Javascript. I found it again whereas it was claimed to be fixed, therefore I reopened it. I talked with others developers and they took this over and worked on the issue, I am pretty it's been fixed but for some reason this issue was not closed, but I was not really in the loop anymore.

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Does Chao his message ring a bell?

**Comment by Mark-de-Haan** [comment]
If I recall correctly this has been fixed already.
