### ISSUE TITLE
Entity class permissions not deleted when an entity metadata is deleted

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3842]
- Click delete entitymetadata + data in the dataexplorer
- Goto Admin > Permisison Manager > Entity Class Permissions

Expected: The Permissions for the deleted entity are gone.
Observed: Permissions stil exist.

If you then upload an entity with the same name it automatically gets the permissions set for the deleted entity

**Comment by Mark-de-Haan** [comment]
Can not reproduce
