### ISSUE TITLE
Selecting computed ref entities in table displays empty modal

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3850]
To reproduce:
1. Upload the emx_all_datatypes.xlsx https://drive.google.com/open?id=0B902kZCFbOw1ZkRITGlJaUVDZGM
2. Click on link to xref xcomputedxref
Bug: Information of the xcomputedxref entity is missing.
Expected: show xcomputedxref info

**Comment by fdlk** [comment]
What package did you choose?

**Comment by jjettenn** [comment]
org_molgenis_test

**Comment by dennishendriksen** [comment]
Expanding the entity in the table does show data.

**Comment by dennishendriksen** [comment]
Computed ref entity values only exist in the context of the entity that refers to them, they are not actual entities in the ref entity table. I removed the modal links for computed ref entities.
