### ISSUE TITLE
ElasticSearchRepository implements findAll() incorrectly

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3854]
The JavaDoc in the ```DataService``` interface states that all implementations of ```findAll()``` should return an empty ```Iterable<Entity>``` when no matches are found. However, ```ElasticSearchService```'s ```findAll()``` returns an ```Iterable``` containing ```null``` values for each entity it couldn't find.

This makes the standard way of checking for empty result sets useless:
```java
Iterable<Entity> resultEntities = dataService.findAll("target_entity", ids);

if (!resultEntities.iterator().hasNext())
{
	// this code is never reached
}
```

The culprit is the ```get()``` method in ```ElasticSearchService``` in [these lines of code]
(https://github.com/molgenis/molgenis/blob/f958fdfa7b91f404bc28c38353729e37e5ee412a/molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/ElasticSearchService.java#L648-L671)

If this is intended behaviour, the JavaDoc should be updated.

**Comment by dennishendriksen** [comment]
Related to #3868
