### ISSUE TITLE
SnpEff annotator assumes resultfile is same order and size as input

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3855]
When using the SnpEff annotator the resultfile is parsed line by line while iterating over the source repository to be annotated, assuming that the order and size of the file SnpEff returns is the same as the repository to be annotated.

This can potentially lead to mismatched data! Result from SnpEff should result in a repository or resource that can than be queried for the correct CHROM/POS/REF/ALT for the entity to be annotated.

**Comment by fdlk** [comment]
When will the lengths differ? If SnpEff cannot find one or more variants?

**Comment by bartcharbon** [comment]
I think, not entirely sure, that it is possible that one line of input generates multiple outputs (in case of multiple Alt allele's). But more importantly, we saw a difference in order before. A check was build in for this, but is now gone, probably after the switch to the new framework.

Furthermore in EMX we can have lines missing one of the required attributes, those will cause error's, but if you'll omit them the output VCF and input repository differ in length

**Comment by mswertz** [comment]
Has been clarified what the expected behavior is?
