### ISSUE TITLE
When clicking the dropdown in the settingsscreen I get a error

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3887]
![screen shot 2015-10-13 at 14 54 35](https://cloud.githubusercontent.com/assets/3714029/10455265/89f4c6de-71ba-11e5-89a3-29a4a6bb7a80.png)

**Comment by dennishendriksen** [comment]
Not in v1.10.0

**Comment by bartcharbon** [comment]
The bug occurs because of an truncation in the MySQL query. 
The possible solutions:
1) do not retrieve all mref entities
2) increase group_concat_max_len on all servers

First option is the preferred one.

**Comment by fdlk** [comment]
Option 3: Don't do the order by clause in mysql but afterwards in-memory.
