### ISSUE TITLE
Cannot add entities with File type attributes if I don't have permissions for the FileMeta entity

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3888]
Create normal user.
Give user write access to an entity with file type attribute.
Try to add new entity instance through the form in the data explorer

Expected:
Works fine

Actual:
Fails and I get a login dialog

**Comment by dennishendriksen** [comment]
Before the login dialog is shown you shortly see a message stating that you do not have READ permissions on FileMeta.

**Comment by dennishendriksen** [comment]
MOLGENIS creates a default group authority for the 'All users' group for FileMeta on clean install since MOLGENIS 2.0.
