### ISSUE TITLE
Old permissions, after saving new permissions, are not removed from screen.

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3891]
To reproduce:
1. Plugin Permission
2. Click Groups: "All Users"
3. Change the permission for the Home plugin from edit to count (If it is no edit first change it to edit)
4. Push the save button.
5. You see the next screen: 
    a. Home: Count
    b. inherited from hierarchy: Read
    c. inherited from hierarchy: Count

![screen shot 2015-10-13 at 3 16 51 pm](https://cloud.githubusercontent.com/assets/5586255/10455766/8bff2886-71bd-11e5-8ed9-829d4a7a1686.png)

Expected:
"inherited from rows" should disappear!

N.B. 
Maybe is the text "inherited from hierarchy" unnecessary.
It is not consistent with the "Users view" where not all permissions that are inherited from one group are shown.

**Comment by Mark-de-Haan** [comment]
Can not reproduce in 1.17.0-SNAPSHOT: When I am changing permissions, the inherited from rows are added or removed as expected
