### ISSUE TITLE
Too much and unexplained  "Inherited from hierarchy" permissions on ImportRun

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3894]
To reproduce:

1. Select: Entity Class Permissions
2. Click Groups: "All Users"
3. Change the permission for the ImportRun plugin from none to read (If it is not none first change it to none)
4. Push the save button.
5. You see the next screen: 
a. inherited from hierarchy: Edit
b. inherited from hierarchy: Read
c. inherited from hierarchy: Count
d. inherited from hierarchy: Count

![screen shot 2015-10-13 at 3 52 42 pm](https://cloud.githubusercontent.com/assets/5586255/10456682/ef0d822e-71c2-11e5-838e-413ea0b769dd.png)

1. Inherited from hierarchy is shown 4 time. Why are there four and not three?
2. Where are the other three permissions (three *  inherited from hierarchy) coming from?

**Comment by dennishendriksen** [comment]
Cannot reproduce in 1.11.0-RC and 1.10.0.
