### ISSUE TITLE
REST API entity create NPE

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3897]
Reproduce:
- ```POST http://localhost:8080/api/v2/RuntimeProperty {"key": "createsingleentity", value: "test"}```

Expected:
- One RuntimeProperty entity is created

Actual:
- ```java.lang.NullPointerException: null
	at org.molgenis.data.rest.v2.RestControllerV2.generalChecksForBachOperations(RestControllerV2.java:356) ~[classes/:na]```

Creating a single resource using POST /api/v2/<resource> is part of a RESTful architecture, API users will expect this to work.

**Comment by dennishendriksen** [comment]
When fixing please fix typo in generalChecksForBachOperations.

**Comment by jjettenn** [comment]
Single create and update are not yet implemented!
I will fix the typo

**Comment by fdlk** [comment]
But the message could and should be friendlier than the NPE.
It should check for missing entities attribute.

**Comment by jjettenn** [comment]
So you will take it over from me?

**Comment by jjettenn** [comment]
On the master branch:
message: "Call to TraversableResolver.isReachable() threw an exception"

**Comment by fdlk** [comment]
Same here, if entities attribute is not sent an invalid instance of the request gets created by the gson deserializer. It has null value for entities and its hashCode subsequently throws a nullpointer exception. See also https://hibernate.atlassian.net/browse/HV-1013 .
