### ISSUE TITLE
Saving changed in edit form gives Unspecified error.

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3898]
Reproduce:
- Import molgenis-app\src\test\resources\xls\emx_all_datatypes.xlsx
- Open TypeTest in data explorer
- Select edit icon on row with id 1
- Press Save changes in form

Expected:
- Success message

Actual:
- ```Error! An error occurred. Please contact the administrator.
Unspecified error.```

**Comment by erwinwinder** [comment]
Cannot reproduce this

**Comment by tommydeboer** [comment]
Confirmed irreproducible by reporter. Will close this issue.
