### ISSUE TITLE
Correctly configured annotators do not pick up changes in configuration

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3899]
If I have for example a correctly configured snpEff, but I have another snpEff instance I wish to use, the new configuration is only picked up after restart.

**Comment by jjettenn** [comment]
Which configuration? Can you be more specific about it?

**Comment by jjettenn** [comment]
Cannot reproduce.

**Comment by bartcharbon** [comment]
there is only on config item for snpEff, and it is still broken.

1) Correctly cofigured snpEff
2) change config to a exisiting file, but not the snpEff jar

expect:
trouble

actual:
Succesful annotation with the previously configured jar.

The new config is picked up after restart

**Comment by jjettenn** [comment]
Fixed in MOLGENIS 2.0
