### ISSUE TITLE
Api v2 returns internal server error when validation fails

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3902]
Do a POST:
url: http://molgenis62.target.rug.nl/api/v2/org_molgenis_test_Location
body: {entities: [{Chromosome: 42, Position: 42}]}

First time: ok

Second time:
Expected: 400 Bad Request
Observed: 500 internal server error

**Comment by erwinwinder** [comment]
JSON validation message is ok:
{
  "errors": [
    {
      "message": "Duplicate value '42' for unique attribute 'Position' from entity 'org_molgenis_test_Location' (row 2)"
    }
  ]
}

**Comment by erwinwinder** [comment]
(row 2) is also nood good

**Comment by jjettenn** [comment]
"(row 2) is also nood good" is related to issue: Molgenis validation exception count a row too much. #3849
