### ISSUE TITLE
Selenium importer test failures

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3905]
Selenium importer test:
- Failed on 2015-10-07
- Succeeded on 2015-10-08
- Failed on 2015-10-09 until 2015-10-14

**Comment by dennishendriksen** [comment]
Locally the Selenium tests start running but 'hangs' at random times.

**Comment by bartcharbon** [comment]
I get a "401" exception during the importer test, after a previous login was succesfull...
This differs from the online jenkins problems.

Continuing on another issue first.

**Comment by fdlk** [comment]
The 401 is due to #4122 and I've solved it by removing the cookie manager in the rest client http connections in molgenis-selenium. See https://github.com/fdlk/molgenis-selenium/commit/ddcf9312f6c2a237b6a76817e077c983aaaee4cf#diff-d7728f56aa2f10aa295557de12355ed8R20

**Comment by fdlk** [comment]
Fixed the rest in a rewrite using WebElement proxys that get instantiated by the PageFactory based on FindBy annotations. See https://github.com/fdlk/molgenis-selenium/commit/71119412a44581881f55a58f3a8a861cfba4c2fa

**Comment by dennishendriksen** [comment]
Test succeed again: https://molgenis50.target.rug.nl/jenkins/job/selenium-molgenis-test/314/
