### ISSUE TITLE
Annotator timeout results in: Error! An error occurred. Please contact the administrator.

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3906]
If a annotation takes longer than the request timeout this results in:
"Error! An error occurred. Please contact the administrator."

This gives the impression that the annotation failed, which is not the case, it is still running fine.

The user should get a clearer error message, or even better, the annotators should be asynchronous.

**Comment by Mark-de-Haan** [comment]
@bartcharbon Solved by asynch annotators??

**Comment by bartcharbon** [comment]
annotators are now async
