### ISSUE TITLE
When trying to import big questionnaire as a user, I get permission errors

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3911]
## Reproduce
- As a user, import the Chr6_vragen_emx_testimport10 (should be on drive)
## Expected

Its a valid EMX, I should be able to import
## Observed
- No READ permission on entity packages
- No READ permission on entity MolgenisGroupMember

**Comment by fdlk** [comment]
at least partially duplicates #3885 I think.

**Comment by fdlk** [comment]
Yes, duplicates #3885, now that I've fixed it I can no longer reproduce this one.

**Comment by fdlk** [comment]
Mark reports getting the entities permission error when importing the questionnaire. I don't think that I've fixed that.

**Comment by dennishendriksen** [comment]
the current version (11.6) of the same dataset can be successfully imported by a non-superuser in MOLGENIS 2.0.
