### ISSUE TITLE
Table sort JPA entities not working

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3912]
Reproduce:
- Select MolgenisUser in data explorer
- Sort on Username column

Expected:
- Table sorted

Actual:
- Nothing happens

Sorting on TypeTest works (MySQL backend), MolgenisUser is stored in JPA backend

**Comment by dennishendriksen** [comment]
JpaRepository Iterable<Entity> findAll(Iterable<Object> ids) does not return entities in the requested order (and does not what the Repository interface says it should do).

Unfortunately JPA does not support ORDER BY FIELD, which is used in MySQLRepository to guarantee order: http://stackoverflow.com/a/21690520

**Comment by mswertz** [comment]
again reason to discontinue JPA. I would propose we don't fix JPA bugs
unless we really have too.
M

On Wed, Oct 14, 2015 at 2:40 PM, Dennis Hendriksen <notifications@github.com
> wrote:

> JpaRepository Iterable findAll(Iterable ids) does not return entities in
> the requested order (and does not what the Repository interface says it
> should do).
>
> Unfortunately JPA does not support ORDER BY FIELD, which is used in
> MySQLRepository to guarantee order: http://stackoverflow.com/a/21690520
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3912#issuecomment-148037086>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by dennishendriksen** [comment]
We should discontinue JPA and until that time fix the bugs because most time is spend is figuring out that the bug is in JPA, not in fixing bug.

**Comment by mswertz** [comment]
Ok
