### ISSUE TITLE
LoggingEvents aren't retrieved

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3913]
## Reproduce
- Have a LoggingEvent entity with ~2000 rows
- Look at it as admin (chrome)

## Expected
I can see if perfectly fine

## Observed 
![screen shot 2015-10-14 at 10 26 34](https://cloud.githubusercontent.com/assets/3625016/10478469/0c2e1bd4-725e-11e5-9095-157af2622a83.png)

**Comment by dennishendriksen** [comment]
Suggestion to look into the location where the LoggingEvent mappings are created (ElasticsearchService.createMappings). Here 'stored' should be true.

**Comment by tommydeboer** [comment]
Some extra info: the LoggingEvents aren't stored in MySQL, but are stored in ElasticSearch. However, the REST API returns 0 results.
