### ISSUE TITLE
Inserting an email for a password reset should always give a message "Success! Password reset..."

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3914]
To reproduce:
- Click on sign in button
- Click on Forgot password?
- Enter a valid email address but a one that is not familiar to the Molgenis.
- You will see the next page:

<img width="674" alt="screen shot 2015-10-14 at 10 13 13 am" src="https://cloud.githubusercontent.com/assets/5586255/10478244/6d6a5fc2-725c-11e5-9287-292727d63332.png">

Expected:
When a email address is valid, alway show the message: Success! Password reset, an email has been sent to you. Otherwise you are reveling too much info for non-authorized persons

**Comment by fdlk** [comment]
I see how you mean but this is a tradeoff between usability and security.

I would be pretty annoyed to see the success message and wait for an hour for the email to arrive only to find out that I typed the wrong email address in the first place.

Most websites I have seen/used let the usability argument win and go for a revealing success/fail message in the password reset dialog.

**Comment by mswertz** [comment]
Do we have users that reported this as a bug?

For the long run, and if users want this, I would make this an optional
setting for the admin to decide.
But for know I wontfix in light of more urgent issues.

On Wed, Oct 14, 2015 at 5:07 PM, Fleur Kelpin <notifications@github.com>
wrote:

> I see how you mean but this is a tradeoff between usability and security.
>
> I would be pretty annoyed to see the success message and wait for an hour
> for the email to arrive only to find out that I typed the wrong email
> address in the first place.
>
> Most websites I have seen/used let the usability argument win and go for a
> revealing success/fail message in the password reset dialog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3914#issuecomment-148078744>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by jjettenn** [comment]
We don't have users that reported this bug.

**Comment by Mark-de-Haan** [comment]
@mswertz wontfix so close? We can always open again if users start reporting this as unwanted behavior
