### ISSUE TITLE
When categorical tables are not rolled back, their permission is set to count. This makes it impossible to use add/update while importing

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3918]
## Reproduce
- Import the chr6 big questionnaire as a user
- Import fails because of #3911, no read permission on packages
- Set permission correctly for user
- Import again with 'add / update' option

## Expected
Data is imported correctly

## Observed
I do not have write permissions for the categorical tables that were not rolled back. I have to drop all my data before I am capable of correctly uploading my file

**Comment by erwinwinder** [comment]
Fixed when https://github.com/molgenis/molgenis/pull/3944 is merged
