### ISSUE TITLE
Others: removing elasticsearch file and restarting Molgenis does not work

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3920]
To reproduce:

1. First make a backup of your elasticsearch folder
2. Stop application
3. Remove the ElasticSearch index from ~/.molgenis/omx/data/elasticsearch
4. Start appilication

Result: index recreated but Molgenis does not work

Expected: index recreated and Molgenis works

**Comment by dennishendriksen** [comment]
Did your Elasticsearch index contain entities for which the backend is ElasticSearch? In that case you've thrown away your source data and rebuilding of the index is impossible.

**Comment by jjettenn** [comment]
But then Molgenis should be able to repair it self, ignoring that part data.
I could not even log in.

**Comment by jjettenn** [comment]
After the test, I have restored the old elasticsearch index and then it worked.

**Comment by Mark-de-Haan** [comment]
Can not reproduce

When I drop the index, then all mysql based entities are restored fine. Vcf based entities however only have their meta data, and have lost all data.

I guess its more of a feature request to have two separate indices

**Comment by Mark-de-Haan** [comment]
Also not reproducible on server
