### ISSUE TITLE
In the attribute mapping screen, the checkbox for source attributes cannot be selected

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3922]
## Reproduce
- Go to molgenis62
- Create a new mapping project with the AttributeMapping as the target entity as well as the source entity (Yes mapping the entity to itself!)
- Click the edit button for target attribute targetAttributeMetaData
- De-select the selected source attribute 'targetAttributeMetaData' in the attribute table

## Expected
The checkbox for this source attribute should be selected

## Observed
The checkbox cannot be selected

## Comment
This is bug cannot be reproduced locally

**Comment by Mark-de-Haan** [comment]
Caused by same bug as #3923 
Can be reproduced when javascript is minified
