### ISSUE TITLE
In the attribute mapping screen, any key strokes in the algorithm editor will cause the selected source attributes unchecked automatically

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3923]
## Reproduce
- Go to molgenis62
- Create a new mapping project with the AttributeMapping as the target entity as well as the source entity (Yes mapping the entity to itself!)
- Click the edit button for target attribute targetAttributeMetaData
- In the algorithm editor, remove the semi-colon from the existing algorithm

## Expected
Only semi-column character should be removed

## Observed
The algorithm is completely wrong and the selected source attribute is automatically unchecked

## Comment
This is bug cannot be reproduced locally

**Comment by Mark-de-Haan** [comment]
Yeah cannot reproduce locally, and even after a fresh start up m62 still shows this behavior... No errors either. How to fix then?
