### ISSUE TITLE
HPO annotator breaks VCF format

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#3924]
The HPO annotator has whitespace in its output, which is not allowed in VCF info fields. This prevents further tools from being ran on the data. Possible also goes for CGD annotator?

**Comment by Mark-de-Haan** [comment]
This indeed happens for any annotator adding fields with white space (hpo, cgd, omim, etc..)
Might be we want to replace all whitespace with underscores? This should be fixed application wide.
