### ISSUE TITLE
TabixReader throws error on chromosome not found

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#3931]
The TabixReader throws an exception when a chromosome is not found. This is because it keeps the String-Int mapping in an internal mapping object that returns an ArrayIndexOutOfBoundsException when a non existant chromosome is queried. This is a bit silly because it should not be an error, but simply a "no results returned" scenario. Same as when a position is queried for which there is no data. Example:

12:31:48.987 [main] ERROR o.m.d.a.resources.impl.ResourcesImpl - Error querying Resource EXACTabixResource.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
at org.molgenis.data.annotator.tabix.TabixReader.query(TabixReader.java:400)

**Comment by Mark-de-Haan** [comment]
@bartcharbon didnt we fix this already?

**Comment by fdlk** [comment]
Duplicate of #3838.
