### ISSUE TITLE
Contig annotations removed by annotators

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#3932]
One of our users reports that the CONTIG information in the VCF headers is gone after using the ExAC annotator. We should build a test for this and investigate this behaviour, and fix it if this is indeed the case.

**Comment by Mark-de-Haan** [comment]
Can not reproduce, waiting for data for which this bug occurred to properly reproduce

**Comment by mswertz** [comment]
@joerivandervelde what is the status?

**Comment by Mark-de-Haan** [comment]
@joerivandervelde bump
