### ISSUE TITLE
MySqlRepository exposes ref entities for which user has no permissions

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3966]
Reproduce (not checked, no time!):
- Import molgenis-app\src\test\resources\xls\emx_all_datatypes.xlsx
- Create non-super user with read permissions on data explorer plugin and TypeTest entity
- Login with user and view TypeTest in data explorer

Expected:
- Permission error because user is not allowed to see TypeTestRef

Actual:
- User can see TypeTestRef column and expand entity

**Comment by mswertz** [comment]
ah, this is a tricky question. I suppose expected behavior is:
- I can see the xref label
- I can not expand 
?

**Comment by dennishendriksen** [comment]
This is fixed in 1.16.1
