### ISSUE TITLE
filter wizard does not show description

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3983]
Test plan states for the filter wizard:
"description displayed"

This is not the case. (assuming the description of the entity is meant?)

**Comment by Mark-de-Haan** [comment]
Test plan has been updated.
It now mentions that on hover of an attribute it should show the description
https://docs.google.com/spreadsheets/d/17KTnwRdwwtTUBuqzUSXUSPFH1IfQB8YovbFptGrRkBU/edit#gid=0
