### ISSUE TITLE
Import of MIABIS model fails locally with error message `Table definition has changed, please retry transaction`

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#3985]
### To reproduce:
1. Ask Tommy for data
2. Upload EMX

### Expected:
No problemo.

### Actual:
```
PreparedStatementCallback; uncategorized SQLException for SQL [SELECT this.`id`, this.`name` 
FROM `bbmri_nl_countries` AS this WHERE this.`id` IN (?,?,?,?,?) LIMIT 1000]; SQL state [HY000]; 
error code [1412]; Table definition has changed, please retry transaction; nested exception is 
java.sql.SQLException: Table definition has changed, please retry transaction
```

## Notes

- This only happens locally and not on any servers (09 and 62)
- Not present in 1.10
- Removing the tags from the EMX file removes the problem
Changing the statement to 

```mysql
SELECT this.`id`, this.`name` FROM `bbmri_nl_countries` AS this WHERE this.`id` IN (?,?,?,?,?) LIMIT 1000 FOR UPDATE
```

fixes the problem, but its a bit of a hack.

> A SELECT ... FOR UPDATE reads the latest available data, setting exclusive locks on each row it reads. Thus, it sets the same locks a searched SQL UPDATE would set on the rows.

Requires time to investigate further and to fix

**Comment by tommydeboer** [comment]
Note: this only happens locally and not on the (test) server

**Comment by Mark-de-Haan** [comment]
Not present in 1.11

**Comment by fdlk** [comment]
The EMX importer does both the metadata and data changes in one transaction:
* Insert the tags
* Insert the packages
* Insert the entities
* Create the tables and foreign key constraints in separate transactions
* Insert the data into the tables, in the right order of dependency

During this last data insert, the validators do selects on the referenced tables to make sure the data is valid.

Before 1.11, these selects got their data from the elasticsearch, now they retrieve the data from mysql.
One of those selects that suddenly notices that the table was created or updated after this transaction started and loudly complains that the transaction should be re-run.

I think our importer should create or update the tables before doing the rest of the work and take compensating actions if the data import fails.

**Comment by dennishendriksen** [comment]
@tommydeboer could you send me the data that reproduces this issue?

**Comment by dennishendriksen** [comment]
Received the data (including tags) from Tommy and successfully imported the data in 2.0-RC.
