### ISSUE TITLE
In the mapping service, the algorithm is overwritten when any suggested source attribtues are selected after a search action is performed

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#3999]
## How to reproduce
- Upload the files mappingservice-test.xlsx, biobank_ontology.owl.zip from https://drive.google.com/drive/folders/0B7qHi41THTs_T3BnaHY2TGJ1Mzg
- Go to the MappingService
- Create a new mapping project with HOP as the target and Lifelines as the source
- Click on cell that is located in the row Gender and column Lifelines
- Now the generated algorithm is $('GENDER').map({"1":"0","2":"1"}, null, null).value();
- Search 'height' in the searchbox and now the suggested source attributes should be updated
- Check the suggested source attribute Height in cm
## Expected

$('GENDER').map({"1":"0","2":"1"}, null, null).value();$('HEIGHT').unit('cm').value();
## Actual

$('HEIGHT').unit('cm').value();

**Comment by dennishendriksen** [comment]
Did you mean 1.12.0-RC instead of 1.2.0?

**Comment by Mark-de-Haan** [comment]
@ChaoPang Is this really a bug?

**Comment by Mark-de-Haan** [comment]
Can no reproduce in v5.3.0-SNAPSHOT
