### ISSUE TITLE
Import error when running annotators

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4011]
Reproduce:
- Start long running annotator job in the data explorer
- Import data set with meta data through import wizard

Expected:
- Import successful

Actual:
`PreparedStatementCallback; SQL [INSERT INTO `entities_attributes` (`order`,`fullName`,`attributes`) VALUES (?,?,?)]; Lock wait timeout exceeded; try restarting transaction; nested exception is java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction`

**Comment by Mark-de-Haan** [comment]
Can not reproduce in 1.17.0-SNAPSHOT on molgenis 62.

Annotating a 1000 line file with all annotators, while importing TypeTest multiple times.
Error does not occur.

**Comment by dennishendriksen** [comment]
We dropped support for MySQL in MOLGENIS 2.0 in favor of PostgreSQL, hence the error does not occur anymore.
