### ISSUE TITLE
No COUNT permission on entity during import

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4013]
Reproduce:
- Login as non-superuser with permission on importwizard
- Import [prevend-emx-workshop-20-rows-with-package.xlsx](https://github.com/molgenis/molgenis/files/20901/prevend-emx-workshop-20-rows-with-package.xlsx) with default settings

Expected:
- Import successful

Actual:
```No COUNT permission on entity DRINK_1_Ref```

**Comment by dennishendriksen** [comment]
Cannot reproduce with empty database.

**Comment by Mark-de-Haan** [comment]
This only occurs when the entity is already in the database.
To reproduce import emx_all_datatypes.xlsx as admin.

Then try importing emx_all_datatypes.xlsx with add / update or just add as a user
You will get the same error:

No COUNT permission on entity TypeTestRef

**Comment by dennishendriksen** [comment]
I'm quite sure that I did not import the data set as superuser.

**Comment by erwinwinder** [comment]
In the ImportRun table i saw that it was imported by admin before
