### ISSUE TITLE
SQL Can't create table import error

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4014]
Reproduce:
- Import 
[target-dataSchema-emx-with-package.xlsx](https://github.com/molgenis/molgenis/files/20905/target-dataSchema-emx-with-package.xlsx)

Expected:
- Import successful

Actual:
```org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [ALTER TABLE `Target_TargetSchema` ADD FOREIGN KEY (`DIS_CVA`) REFERENCES `DIS_CVA_Ref`(`code`)]; SQL state [HY000]; error code [1005]; Can't create table 'omx.#sql-5e9_2b' (errno: 150); nested exception is java.sql.SQLException: Can't create table 'omx.#sql-5e9_2b' (errno: 150)```

**Comment by dennishendriksen** [comment]
Cannot reproduce when importing as superuser with clean database.

**Comment by erwinwinder** [comment]
Can reproduce:
 - Import HOP-10-attributes.xls (https://drive.google.com/drive/u/0/folders/0B7qHi41THTs_flRxcmRlLUwxYWx2ZDZ5YXJxc19BdmtZWVl4SmZTSXdndWJKNDJNN201Y2M)

- Import target-dataSchema-emx-with-package.xlsx

Error caused by same entity name in two different backends: ElasticSearch and MySQL
