### ISSUE TITLE
Corner_cases vs corner_cases when uploading a vcf file

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4016]
To reproduce:

1. Try to upload the cornaer_cases.vcf file (/Molgenis/Release test plans/testData/corner_cases.vcf)
2. Give it the name corner_cases
3. It will fail!

Error! Your import failed:
null

Corner_cases will work! Strange :(

**Comment by bartcharbon** [comment]
I've seen the describued behaviour on Jonathans screen. However I now get null with both upper and lowercase 'C'. 
A totally different name, whether containing underscore or not succeeds (tested "harry" and "harry_")

**Comment by bartcharbon** [comment]
Somehow it nullpointers on the file, while the entity name should have nothing to do with the filename...

**Comment by bartcharbon** [comment]
Seems to be going wrong if chosen entityname is identical as the filename. Casing may be platform/database specific?
