### ISSUE TITLE
Attribute mapping result panel displays int results in dutch comma notation.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4048]
Found by (visual inspection of) the selenium test!!

![screen shot 2015-10-27 at 11 00 16](https://cloud.githubusercontent.com/assets/1523838/10754822/7d663c8c-7c9a-11e5-81c2-ebc5e9d11638.png)

When creating the integrated data set, everything is fine, but the result looks weird.

**Comment by Mark-de-Haan** [comment]
Can not reproduce
![screen shot 2017-11-21 at 12 49 48](https://user-images.githubusercontent.com/3625016/33071071-7e327bca-ceba-11e7-8bb1-315ad54c993d.png)
