### ISSUE TITLE
Cannot import RuntimeProperty.csv

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4073]
Import /molgenis-app/src/test/resources/csv/RuntimeProperty.csv

Expected: Import ok, entities imported
Actually:
![screen shot 2015-10-28 at 11 26 06](https://cloud.githubusercontent.com/assets/116559/10788650/2ea1fdf4-7d79-11e5-859f-99b8db2ba141.png)

**Comment by fdlk** [comment]
Duplicates #3825 which duplicates #2461 :)
