### ISSUE TITLE
Importing an entity without the right permissions results in an Eternal Spinner

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4074]
### To reproduce:
1. Make a new user (and give permissions for importer)
2. Log in with that user
3. Import [test-javascript_magma.xlsx](https://github.com/molgenis/molgenis/files/22429/test-javascript_magma.xlsx)

### Expected:
A friendly message telling me I am not permitted to import scripts.

### Actual:
The import spinner will be visible indefinitely without any feedback that things went wrong.

**Comment by erwinwinder** [comment]
Now user is logged out when inporting entity without permission.

**Comment by erwinwinder** [comment]
Cannot reproduce. Errormessage:
No WRITE permission on entity 'ScriptParameter'. Is this entity already imported by another user who did not grant you WRITE permission?
