### ISSUE TITLE
Extremely Slow MappingService

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4075]
Extreem Slow OntologyTagServiceImpl.java method: "findAttributeEntity(String entityName, String attributeName)"

To reproduce:
Upload the next files into the server: (https://drive.google.com/drive/folders/0B902kZCFbOw1eTlyTFR6aDhMNkk)
biobank_ontology.owl.zip
HOP-attributes-testing.xls
lifelines-emx-demo-1-row.xls
prevend-emx-demo-4-rows.xls
test-javascript_magma.xls
uo.owl.zip

1. Create a project with target lifelines and source prevend.
2. Click on link to open the project.

While enquiring an other issue I have mentioned that the mapping service is extremely slow!
I have found one method that causes this problem: "findAttributeEntity(String entityName, String attributeName)".

So I have asked myself why does it takes so much time to search for an entity and created a test. I tried to time the executing time and found (Time in milliseconds):

Time:429 attributeName: FOOD71A1 entityName: lifelines
count: 316, timeWed Oct 28 14:09:48 CET 2015
Time:502 attributeName: FOOD75A1 entityName: lifelines
count: 317, timeWed Oct 28 14:09:49 CET 2015
Time:395 attributeName: FOOD76A1 entityName: lifelines
count: 318, timeWed Oct 28 14:09:49 CET 2015
Time:399 attributeName: FOOD77A1 entityName: lifelines
count: 319, timeWed Oct 28 14:09:50 CET 2015
Time:392 attributeName: FOOD78A1 entityName: lifelines
count: 320, timeWed Oct 28 14:09:50 CET 2015
Time:397 attributeName: FOOD79A1 entityName: lifelines
count: 321, timeWed Oct 28 14:09:50 CET 2015
Time:433 attributeName: FOOD80A1 entityName: lifelines
count: 322, timeWed Oct 28 14:09:51 CET 2015
Time:388 attributeName: FOOD81A1 entityName: lifelines
count: 323, timeWed Oct 28 14:09:51 CET 2015

== Molgenis cannot get an attribute entity from the dataservice layer. ==

Code for controlling the length of executing:

	private Entity findAttributeEntity(String entityName, String attributeName)
	{
		Date start = new Date();
		Entity entityMetaDataEntity = dataService.findOne(ENTITY_NAME, entityName);
		Optional<Entity> result = stream(entityMetaDataEntity.getEntities(ATTRIBUTES).spliterator(), false).filter(
				att -> attributeName.equals(att.getString(AttributeMetaDataMetaData.NAME))).findFirst();
		Date end = new Date();
		System.out.println("Time:" + (end.getTime() - start.getTime()) + " attributeName: " + attributeName
				+ " entityName: " + entityName);
		return result.isPresent() ? result.get() : null;
	}

There something fundamentally wrong with this method. I would expect that the dataservice can manage this for me. Why is hat not possible to get the attribute entity from the dataservice at once?

Possible solution:  I cannot use the identifier of the AttributeMetaData to create a query and get the entity.

**Comment by fdlk** [comment]
Have you checked which part of the method is slow?
It's always dangerous to guess about performance but I suspect it's entity.getEntities() and that it's become slower for all mrefs because we fetch the entities by ID from the source.

Since we cache the metadata relations in-memory, we can look it up in this particular instance.

**Comment by mswertz** [comment]
Will be fixed with M3730
