### ISSUE TITLE
Updating permissions for users requires them to log out and in

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4080]
### To reproduce:
1. Make a new user
2. Log in with that user (don't log out!)
3. In a separate session as an admin, give the user permissions for the data explorer
4. As the user, refresh the page.
### Expected:

The user can now see the Data Explorer.
### Actual:

The Data Explorer is not visible until the user logs out and in. This goes for entity permissions as well.

**Comment by fdlk** [comment]
This is a more general Spring Security "feature" that the user's permissions are cached in their session. The reverse is actually much worse of a problem! See http://spring.io/blog/2009/01/03/spring-security-customization-part-2-adjusting-secured-session-in-real-time for a discussion.

**Comment by tommydeboer** [comment]
This issue has come to light again in a slightly different way when we were testing RC 8.3.x

How to reproduce:
_Execute as admin:_
1. Add a package in the Navigator
2. Log out
3. Log in
4. Remove the package
5. Go to the Mapping Service, User Manager or Permission Manager

Now these plugins are broken because they are looking for roles that no longer exist. 

**Note:** Because of the fix in #8914 the plugins mentioned above shouldn't crash anymore. You should be able to debug and inspect the user's session to see that it still contains roles that don't exist anymore.
