### ISSUE TITLE
No spinner when using mapping-service

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4082]
To reproduce:
- Upload the emx_all_datatypes.xlsx file
- Create project with target TypeTest
- Add source TypeTest 
- Click multiple time on the "add source" button.

Result:
The mapping service will hang

Error message:
{
  "errors": [
    {
      "message": "An error occurred. Please contact the administrator.<br />Message:PreparedStatementCallback; SQL [UPDATE `AttributeMapping` SET `identifier` = ?, `targetAttributeMetaData` = ?, `sourceAttributeMetaDatas` = ?, `algorithm` = ?, `algorithmState` = ? WHERE `identifier`= ?]; Lock wait timeout exceeded; try restarting transaction; nested exception is java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction"
    }
  ]
}

Expected to see a spinner. That I will be not able to click again on the button if it is executed.

**Comment by jjettenn** [comment]
Fixed in #3230

**Comment by jjettenn** [comment]
PR is not accepted

**Comment by mswertz** [comment]
what is status of PR?

**Comment by dennishendriksen** [comment]
Support for MySQL was dropped in MOLGENIS 2.0 in favor of PostgreSQL, hence this exception won't occur anymore.
