### ISSUE TITLE
Importer spends silly amounts of time copying the imported entities attribute by attribute

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4084]
Context: 
Marije wants to import a sheet with a single entity with a couple hundred attributes and a couple thousand instance rows.
We aborted the import after half an hour when not a single entity had reached the point yet where it got indexed in elasticsearch.

Debugging showed that the time is spent in the ImportWriter which copies each entity instance to a DefaultEntityImporter instance. The `DefaultEntity#set(Entity)` method that gets called by the DefaultEntityImporter constructor is taking up a lot of time. Most of the time is probably spent figuring out what the atomic attributes of the DefaultEntity are.

Which is extra silly since the answer is of course the same for each entity instance, even if this entity has a great lot of them.
Also, the entity doesn't even have self-references but resolving self-references are the only reason that the DefaultEntityImporter gets created.

**Comment by mswertz** [comment]
propose to select http://www.molgenis.org/ticket/3365 to address this
