### ISSUE TITLE
Model registry data explorer links if no permission

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4085]
Reproduce:
- Login as non-superuser with permission on 'standardsregistry' and 'importwizard' plugins
- Upload molgenis-model-registry\src\test\resources\MIAME-ENV_data.xlsx
- Open 'Model registry' plugin located under 'Plugins' menu
- Search for 'Miame'

Expected:
- 'Select an entity' select and 'View data' button are not displayed, because the user has no permission to view the data explorer

Actual:
- 'Select an entity' select and 'View data' button are displayed. Selecting an entity in the entity select and selecting 'View Data' results in an error 'HTTP Status 403 - Access is denied'

**Comment by mswertz** [comment]
I expect us to rebuild the model registry and then this issue should be part of the story
