### ISSUE TITLE
Non-super users need READ permission on "entities" to use Mapping Service

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4087]
### To reproduce:
1. Make a new user
2. Give the user permissions for the _Mapping Service plugin_ and _Ontology entities_.
3. Log in as the user and go to the Mapping Service
4. Make a new project and add a source
5. Edit one of the Attribute Mappings.
### Expected:

I can edit the mapping.
### Actual:

**Error!** An error occurred. Please contact the administrator.
Message:No READ permission on entity entities

**Comment by fdlk** [comment]
Plugin roles should be able to imply entity roles

**Comment by tommydeboer** [comment]
Agreed. That would also remove the need to give rights to all those settings entities when exposing plugins.

**Comment by dennishendriksen** [comment]
Fixed in MOLGENIS 2.0 which by default assigns read permission on the ```entity type``` entity to the ```All users``` group.
