### ISSUE TITLE
Mapping Service could use more logging

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4088]
At the moment, the Mapping Service gives (almost) no feedback to developers about the actions it's taking. Example: since the creation of an integrated dataset can take a long time, it would be nice if we could see that the Mapping Service actually started the process (because there have been situations in which you *think* it's working, but in actuality it is not).

**Comment by mswertz** [comment]
This is related to the general need to accomodate long running processes. We need a general way to wrap a long running process in a progress bar and show that in the user interface. My suggestion would be to make this a central UI component that is always visible and that will pop larger when a user process is running (i.e. only 'my' processes, such as importer, mapping service, R script, etc). Do we already have a framework for that?

**Comment by tommydeboer** [comment]
I'll close this then because it is a feature request. In the meantime, I've added some developer logging to the Mapping Service so you can at least see if the mapping is running (as an admin/developer) see #4338
