### ISSUE TITLE
Cannot select items in dataexplorer with small view width

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#4090]
When the view width of the screen is 985 px or smaller, the data explorer drop down does not work anymore. (probably has something to do with objects moving everywhere to fit on the screen)
<img width="1269" alt="screen shot 2015-10-29 at 12 42 41" src="https://cloud.githubusercontent.com/assets/10075439/10817513/903ebe82-7e3a-11e5-84a3-14d21583743f.png">

**Comment by mswertz** [comment]
good point; this issue should be part of redesign of explorer

**Comment by bartcharbon** [comment]
I do not understand the issue.

While not pretty it still works fine. The table is moved underneath the data item selection area.

**Comment by dennishendriksen** [comment]
Works in MOLGENIS 1.21 and 2.0. Note that the lowest support resolution by MOLGENIS is 1280x720.
