### ISSUE TITLE
GoNL annotator writes out INFO field with '.' when no results are found

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#4098]
When no results are found within GoNL, the INFO fields should remain untouched. However, 'null' strings are written out as such:

```
AC=1;AF=0.5;AN=2;set=variant38;GoNL_GTC=.,.,.;GoNL_AF=.;
```
This should be:

```
AC=1;AF=0.5;AN=2;set=variant38;
```

**Comment by bartcharbon** [comment]
Strange that this is annotator specific since the GoNL annotator does not do the writing itself, it just fills out columns like every other annotator. 
Does it also add a dot or space in the UI version to the entity?
