### ISSUE TITLE
Annotator results not reproducible if more than one annotator selected in UI

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4099]
When preparing the BMB workshop we discovered that when running:
CGD/Clinvar/CADD in one run, the results for Clinvar were inconsequent. (Clinvar was the last annotator to run for this run).

The first run only annotated only one entity, when running the annotator again, but now with only Clinvar selected, a lot of entities were annotated.

**Comment by tommydeboer** [comment]
Do you have data to reproduce with?

**Comment by bartcharbon** [comment]
The bmb workshop data, I only saw this happen on the demoVM from SurfSara, hope we can reproduce on our own.
https://molgenis26.target.rug.nl/downloads/BMB_Workshop2015/
annotation resources used are also in this folder.
