### ISSUE TITLE
The label of mrefs in an xref is not shown in the expanded column in the dataexplorer

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4104]
For data ask me, dataset used to find the bug is not "open"
I have an entity with an xref to another entity with mrefs.

Expected
When I expand the xref I expect to see all columns of the xref with their values

Actual:
When I expand the xref I get al the columns but the mref columns are empty

Note:
When I click the xref instead of expanding, I get the popup voor the xref entity, and this popup is showing the values for the mrefs, so the data is there. Also when I select the xref entity in the explorer the values of the mrefs are shown correctly.

**Comment by bartcharbon** [comment]
Ah, the labelattribute is "visible=false"

**Comment by dennishendriksen** [comment]
Reproduce with the following public data set:
[nested-example.xlsx](https://github.com/molgenis/molgenis/files/31116/nested-example.xlsx)
