### ISSUE TITLE
Failed login prevents the login dialog from being closed

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4123]
The close button disappears if the login fails.
I'm told this is a feature for servers where you've no page to fall back to until you log in, but in the normal case this is weird behavior.

**Comment by JanTimmermans** [comment]
There is indeed no fall back page.  

Case:
failed login attempt
redirect / return view by [MolgenisLoginController]( https://github.com/molgenis/molgenis/blob/d644d659dad33e9078e2b49b3fb893b22c999fab/molgenis-security/src/main/java/org/molgenis/security/login/MolgenisLoginController.java)
--> [serverurl]/login?error (including login view)
*button won't disappear (suppose)*
click on button
--> [serverurl]/login?error 
--> user on blank page

@fdlk what is the desired behavior?

**Comment by fdlk** [comment]
I think navigating back in the browser, i.e. `window.history.back();` would be best.
Two alternatives I can think of:
* Opening the context root of the application (but it's harder to determine on the client side where that is)
* Or simply surfing to '/'.
cc @mswertz

**Comment by JanTimmermans** [comment]
@fdlk
Thank you for your quick and clear response.
We (a group of students from the TU Delft) tried fixing the issue with window.history.back().
However, that option will only work once. When the user has multiple login failures the .back will be to the login modal.
Therefore, we propose (via a pull request #[4679](https://github.com/molgenis/molgenis/pull/4679)) the use of simply surfing back to ’/’.
