### ISSUE TITLE
List of source attributes mapped to target attribute contains duplicates

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4141]
I'd expect the collection to behave like a set but it behaves like a list instead, listing the same attribute more than once if it appears more than once in the algorithm.
<img width="555" alt="screen shot 2015-11-11 at 15 18 29" src="https://cloud.githubusercontent.com/assets/1523838/11092959/92fef900-8887-11e5-8061-cff8665c4469.png">

**Comment by Mark-de-Haan** [comment]
Can not reproduce in version 5.3.0-SNAPSHOT
