### ISSUE TITLE
When adding a row through the API that invalidates "validationExpression" it returns Unknown error, should be more informative

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis#4142]
When adding a row through the API that invalidates "validationExpression" it returns Unknown error. This should be more informative, for example by returning the JavaScript that was invalidated.

To reproduce:
Have an entity with columns A and B. In the EMX set validationExpression to $(‘A').isNull(). 

POST http://your.molgenis.url/api/v1/entity
Content-Type: application/json

{
    "A": "test",
    "B": test
}

The response will have "Unknown Error".

Would be more informative if it had "validationExpression error: $(‘A').isNull() not satisfied" or something like that.

**Comment by dennishendriksen** [comment]
Fixed in MOLGENIS 2.0:
Importing [emx_4142.xlsx](https://github.com/molgenis/molgenis/files/624804/emx_4142.xlsx) results in error: ```Invalid [string] value [value0] for attribute [attr0] of entity [0] with type [base_expression4142]. Offended expression: $(‘attr0').isNull()```
