### ISSUE TITLE
Deleting data or metadata (unsure) causes Couldn't find UserAuthority for id [...] warnings.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4143]
16:38:10.879 [qtp1089772914-324] WARN  o.m.data.support.AbstractRepository - Couldn't find UserAuthority for id AAAACUHXFNKWE5V73B7V6IIAAE.

Perhaps the deletion failed and got rolled back, I am unsure.

But when running the selenium tests, which do a lot of uploading and deleting of the same entity, I get an increasing amount of these messages.

**Comment by erwinwinder** [comment]
This is ok.
One process is hammering the server to try to get the ImportRun status every 100msec.
It uses a token for this, molgenis gets the user and queries the index to get the the UserAuthorities for this user. 
In the mean time another process has deteted repositories with its asscociated UserAuthorities. When the UserAuthorities are retrieved from the database they are gone.

Set the sleep from 100 to 200 msec so it will happen less often and give the server some respite.
