### ISSUE TITLE
Building MOLGENIS doesn't cleanup embedded databases

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4149]
Reproduce:
- Run ```mvn clean install```

Your OS tmp dir now contains a folder with the embedded database created while executing unit tests. On my machine this accumulated to 1GB of data.

**Comment by Mark-de-Haan** [comment]
@dennishendriksen This looks like the bug we fixed with the embedded elastic search database not deleting the file

**Comment by dennishendriksen** [comment]
We're not using embedded databases anymore in 2.0-RC, instead we require a running PostgreSQL to run integration tests.
