### ISSUE TITLE
JavaScript error applying categorical filter

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4155]
- Load emx_all_datatypes.xlsx
- Goto dataexplorer and select the TypeTest entity
- Click 'xcategorical_value' in the 'Data item selection' tree
- In the dialog select 'label1' and 'label2'

Result:

![screen shot 2015-11-17 at 10 32 12](https://cloud.githubusercontent.com/assets/116559/11207679/efce3dc4-8d16-11e5-9b8e-56ec7c776b04.png)

**Comment by jjettenn** [comment]
I cannot reproduce:

1. Tried on Molgenis62 (1.13.1-SNAPSHOT) with user and admin.
2. Tried locally with admin. With and without (environment=development)

Which browser did you use? Which version of emx_all_datatypes.xlsx did you used?

**Comment by jjettenn** [comment]
Could not reproduce.
