### ISSUE TITLE
Error running tag wizard

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4162]
- Load lifelines-emx-demo.xls from Google drive/GCC/projects/M3R/biobank_demo_data/Develop_complex_algorithms
- Load uo.owl.zip and biobank_ontology.owl.zip (from Google drive/GCC/projects/M3R/biobank-demo-data/develop_complex_algorithms
- Select menu 'Data Integration' / 'Tag wizard'
- Select entity 'lifelines'
- Wait until loaded
- Select ontologies 'uo' and 'biobank_ontology'
- Click 'Run automatic Tagging'

Result:
After a while you get message 'An error occurred'.
Nothing to see in the logfiles

**Comment by tommydeboer** [comment]
Possibly caused by time-out in httpd. If that's the case, let's not fix it now and use the job scheduler framework.

**Comment by mswertz** [comment]
@ChaoPang do we still use tag wizard?
