### ISSUE TITLE
Error selecting same tag twice in Tag Wizard

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4163]
- Goto the menu Data Integration / Tag wizard
- Select an entity to tag
- Select an ontology 
- Click an edit button 
- Add aTag
- Add the same tag again
  -> error 'TypeError: k is undefined'
  I think you should not be able to select a tag twice at all.

**Comment by Mark-de-Haan** [comment]
In version 5.3.0-SNAPSHOT, you can not select the same tag twice
