### ISSUE TITLE
Tree in model registry contains all entities twice

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4167]
- Upload model mage-tab
- Goto Model registry
- Select mage tab
- Tree shows entities twice›
![screen shot 2015-11-18 at 11 48 53](https://cloud.githubusercontent.com/assets/116559/11239148/6376b4e4-8dea-11e5-9757-ea718d6372b4.png)

**Comment by tommydeboer** [comment]
The image shows the miabis model, not the mage-tab model. Tried both datasets but couldn't reproduce.

**Comment by erwinwinder** [comment]
Cannot reproduce
