### ISSUE TITLE
Algorithm in Mapping Service is invalid

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4175]
To reproduce follow the instructions in the test plan:
Tab: "Mapping service with specific data"
Section: "Check taking the average value of multiple numeric source attributes"

Expected the algorithm to be valid

Problem (See picture): 
<img width="1269" alt="screen shot 2015-11-19 at 1 02 06 pm" src="https://cloud.githubusercontent.com/assets/5586255/11271526/ad980578-8ec6-11e5-865e-1d176b573486.png">

**Comment by dennishendriksen** [comment]
@jjettenn How to reproduce? Please provide input dataset(s) as well as input algorithm (which is truncated in your screenshot)

**Comment by mswertz** [comment]
close because unclear
