### ISSUE TITLE
Improved error message when more than 10000 rows requested with Get

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis#4177]
When requesting more than 10000 rows 

`GET http://localhost:8080/api/v1/public_rnaseq_4_CRMetrics%0A
Accept: application/json
User-Agent: python-requests/2.8.1
Accept-Encoding: gzip, deflate
Connection: keep-alive
x-molgenis-token: 38f618bc4c004637b325241a9f908123
Content-type: application/json
{'num': 10001}`

The response is 
`[...]
<title>Error 400 Bad Request</title>
<body><h2>HTTP ERROR 400</h2>
<p>Problem accessing /api/v1/public_rnaseq_4_CRMetrics%0A. Reason:
<pre>    Bad Request</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>
[...]`

Would be QOL improvement if in the body it would say that it is a bad request because more than 10000 rows were requested.

**Comment by fdlk** [comment]
We should add BindingResult bindingResult parameter to the methods with `@Valid` annotations
