### ISSUE TITLE
Aggregates fail for INT type attribute in vcf

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4181]
On molgenis62, select entity workshopvcf. (or upload a new vcf with POS attribute)
Go to aggregates tab, select attribute POS in one of the pulldowns.

Also cannot sort on the POS attribute so this is probably related to, or even a duplicate of, the integer ID sort bug #2754 ?

> Error! Failed to execute phase [query_fetch], all shards failed; shardFailures {[UxaGOCw0Q0yBXqwLi3q1Bg][molgenis][0]: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }

**Comment by erwinwinder** [comment]
Fixed with issue #2754
