### ISSUE TITLE
Entities no longer by default sorted in the order in which they were imported

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4192]
Import TypeTest, go to TypeTest
Expected: Rows are ordered with ascending IDs, at the very least until you update one.
Actual: The rows appear in a different order.

**Comment by mswertz** [comment]
good call to prioritize this one

**Comment by dennishendriksen** [comment]
Fixed in 2.0-RC where data is requested from PostgreSQL instead of Elasticsearch. The fundamental issue remains that we have no way to define order of rows. For now we are lucky that PostgreSQL produces rows in the order they were inserted.
