### ISSUE TITLE
"Message:null" when running annotator with wrongly configured resource

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4194]
## To reproduce:
1. Upload test VCF from _molgenis-data-vcf_
2. Go to annotators
3. Set CADD resource to _<your_resource_location>/cadd/cadd.tsv.gz.tbi_
4. Run the CADD annotator
## Expected:

Message saying the resource isn't configured properly (or even better: "please use **cadd.tsv.gz** instead of **cadd.tsv.gz.tbi**")
## Actual:

```
Error! An error occurred. Please contact the administrator.
Message:null
```

**Comment by bartcharbon** [comment]
disagree with the "expected" here, if the resource is not configured properly it should not be "active" if should be in the unavailable list.
