### ISSUE TITLE
If one attribute is selected in a compound the table shows all columns

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4212]
- select any entity with a compound with multiple attributes. (VCF is an easy example)
- select one attribute within the compound, and leave the rest unselected.

the dataexplorer table now shows all attributes instead of just the selected one.

**Comment by bartcharbon** [comment]
this is not present in 1.12

**Comment by tommydeboer** [comment]
Probably the same bug as #4202 **Compounds with only compounds are not shown in data explorer**

**Comment by tommydeboer** [comment]
Not the same, but related. Observations so far:

1. *Selecting an attribute in a (first level) compound will render all column headers in that compound (including sub-compounds), but only the data for the selected attributes.* I have confirmed that the REST API returns meta data for all these attributes.
![image](https://cloud.githubusercontent.com/assets/5362890/11498167/1032ae94-981e-11e5-892f-fc80dd3783ac.png)

2. *Selecting only an attribute in a sub-compound will render nothing.*
![image](https://cloud.githubusercontent.com/assets/5362890/11498251/94c8915a-981e-11e5-9aa7-b28b09a52679.png)

3. *Selecting an attribute in the first compound, and an attribute in the sub-compound will render all columns, the data for the selected first-level compound and all the data for the sub-compound.*
![image](https://cloud.githubusercontent.com/assets/5362890/11498259/a8be2850-981e-11e5-8fb0-20193d28b99b.png)
