### ISSUE TITLE
As User/Developer I do not want unexpected results when using ElasticSearch services in Molgenis

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4213]
Discovered by solving issue: #2754

The problem is, that according to the documentation of ElasticSearch, all fields that have the same name should also have the same mapping and it is currently not the case in Molgenis. That means that field names must be uniek in the Molgenis index.

From documentation:
Mapping types are used to group fields, but the fields in each mapping type are not independent of each other. Fields with:

the same name
in the same index
in different mapping types
map to the same field internally,
and must have the same mapping.
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#field-conflicts

Solution:
The perfect solution is to have unique field names, either UUIDs or by using the type name (and index name?) as a prefix.

**Comment by dennishendriksen** [comment]
Elasticsearch 2.0 will not allow different mapping types with the same name, solutions are provided:
https://www.elastic.co/blog/great-mapping-refactoring

**Comment by jjettenn** [comment]
Great blog. However we will still need to implement the above mentioned solution into MOLGENIS.

**Comment by jjettenn** [comment]
From the blog:

> To resolve this problem, we first considered prefixing field names with the document type name, to make each field completely independent. The advantage of this approach is that document types would behave as real tables.

Unfortunately, it comes with a number of disadvantages:

* Fields would always require a document type prefix to disambiguate a field in one type from another, or a wildcard to query the same field in multiple types.
* Querying the same field name across document types would be slower as each field would have to be queried separately.
* Most searches would require using multi-field queries instead of the simpler match and term queries, which would break most existing queries.
* Heap usage, disk usage, and I/O would increase as there would be more sparsity and poorer compression.
* Aggregations across document types would become much slower and more memory hungry as they wouldn’t be able to take advantage of global ordinals."

**Comment by jjettenn** [comment]
We should create a plan before working on this issue. The blog suggests some solutions but the question is: do these solutions meet our system demands?

**Comment by Mark-de-Haan** [comment]
Fixed when updating to Elastic search version 5+

**Comment by dennishendriksen** [comment]
@Mark-de-Haan not related to the Elasticsearch version, but fixed when switching to index-per-entity-type.
