### ISSUE TITLE
Freemarker issues different Iterable implementations

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4227]
Reproduce:
- Open default entity report by clicking the loop icon in the dataexplorer table for MolgenisUser
- Open default entity report by clicking the loop icon in the dataexplorer table for an entity that extends from an entity

Expected:
- Works for both reports

Actual:
- Feels for the second report because DefaultEntityMetaData.getAtomicAttributes() returns another Iterable implementation.

**Comment by Mark-de-Haan** [comment]
Not fixed yet

**Comment by fdlk** [comment]
Current fix by Mark is very patchy, we'd like to try for a better one.

**Comment by dennishendriksen** [comment]
After the Freemarker version update calling iterator() for a Iterable should not be required anymore. Does removing iterator() calls resolve the issue?

**Comment by Mark-de-Haan** [comment]
After the version update I observe the same behavior. Without iterator() works for entities that extend, but it does not work for entities that do not extend
