### ISSUE TITLE
When setting filters, the aggregate view resets to its initial selected attributes

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4231]
## Reproduce
- Import and view TypeTest in the data explorer
- Go to the aggregate view
- Aggregate on xint vs xstring
- Filter 1 to 2

## Expected
Table is updated

## Observed
Table is reset to initial xbool vs xboolnillable selection.
Filter is applied correctly though!

**Comment by jjettenn** [comment]
Do you mean that the aggregate selection is not saved when changing tabs?
That is so as designed!
If this is the case please make a feature request! It is not a bug.

**Comment by Mark-de-Haan** [comment]
No this is if you select two attributes, and set a filter, your attribute selection is reset.
