### ISSUE TITLE
Save changes message in forms is not shown

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4273]
To reproduce:

Open an existing form from the DataExplorer (TypeTest entity) and click on "Save changes"

Result: No succes message

Expected: "TypeTest changes have been saved."

**Comment by dennishendriksen** [comment]
I would expect the form to close and not see a message.

**Comment by jjettenn** [comment]
According to the test plan we should see it.
I will expect it in the alert messages in the data-explorer.

**Comment by tommydeboer** [comment]
is it a bug in the software or the testplan?

**Comment by tommydeboer** [comment]
After some discussion:
- You expect 'save changes' to work so a confirmation is unnecessary 
- We should update the testplan (I will put notes for this in the PR)

I'll close this issue
