### ISSUE TITLE
Remove value xdecimal, try to add x.xx (example: 1.00) will not be possible

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4283]
To reproduce:
1. Upload TestType
2. Create a new or try to update a row attribute xdecimal with value 1.00 after removing the old value.
3. Result: 100
4. Expected 1.00

**Comment by jjettenn** [comment]
After fix please update Selenium Test: FormsTest.java
From:
FormsUtils.changeValueNoncompoundAttribute(driver, model.getModalBy(), "xdecimal", "555");
To:
FormsUtils.changeValueNoncompoundAttribute(driver, model.getModalBy(), "xdecimal", "5.55");

**Comment by Mark-de-Haan** [comment]
Fixed in 5.3.0-SNAPSHOT
