### ISSUE TITLE
Aggregates with threshold smaller than rendered wrong

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4296]
Reproduce:
- Set 'Aggregate threshold' to 10 in App Settings, Save changes
- Go to Data explorer plugin, Select MolgenisUser entity, Select Aggregates tab

Expected:
- Smaller than symbol is rendered

Actual:
- Smaller than symbol is rendered incorrectly
![bug_aggregates](https://cloud.githubusercontent.com/assets/2477186/12108708/ea289786-b37a-11e5-8fa2-4ded73054712.png)

**Comment by fdlk** [comment]
Happens only on the server, looks like it happens when the react component gets minified.

**Comment by fdlk** [comment]
Yup! molgenis-component.min.js, line 753:

    - 1 === g && (g = "â‰¤" + this.props.threshold);

**Comment by fdlk** [comment]
AggregateTable.js correctly says

    cellCount = '\u2264' + this.props.threshold;

**Comment by fdlk** [comment]
Duplicates #3252

**Comment by fdlk** [comment]
The issue is that the web pages are served with a different charset and the javascript is interpreted accordingly.

    Content-Type	text/html;charset=ISO-8859-1
