### ISSUE TITLE
Remove Questionnaire hack from RepositoryValidationDecorator

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4308]
Remove the following hack from org.molgenis.data.validation.RepositoryValidationDecorator:

```
// Do not validate if Questionnaire status is not SUBMITTED
if (EntityUtils.doesExtend(getEntityMetaData(), "Questionnaire") && "SUBMITTED".equals(entity.getString("status")))
{
   ...
}
```

**Comment by mswertz** [comment]
How should it work? And does this hinder functionality?

**Comment by dennishendriksen** [comment]
> How should it work?
In such a way that the molgenis-data module is not depending on the molgenis-questionnaires module,  e.g. by registering the Questionnaire entity with different or differently configured repository decorators.

> And does this hinder functionality?
No, but this functionality will easily break due to this hack
