### ISSUE TITLE
Newline missing for expanded categoricalmrefs in table 

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4321]
Reproduce:
select an entity with an categoricalmrefs, and at least one instance with multiple values for this categoricalmrefs. 
hit the expand button in the table header

expected result(same as mref):
label2
label3

actual result:
label2label3

**Comment by dennishendriksen** [comment]
Minimal example: 
[emx-categoricalmref.xlsx](https://github.com/molgenis/molgenis/files/116268/emx-categoricalmref.xlsx)
