### ISSUE TITLE
Entity with DateTime IdAttribute cannot be deleted

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4322]
See org.molgenis.integrationtest.data.AbstractDatetimeDatatypeTest in molgenis-integration-tests.

Remove these methods so the normal AbstractDatatypeTest test sequence is executed.:

@Override
protected void delete(Entity entity)
{
}
@Override
protected void verifyEntityDeleted(Entity entity)
{
}

Now the ElasticseachDatetimeDatatypeTest fails.

Make all test pass.

**Comment by mswertz** [comment]
wontfix? because we want to get rid of custom id types?

**Comment by dennishendriksen** [comment]
Fixed in 2.0-RC where DATE_TIME is not allowed as ID attribute (see AttributeMetaDataUtils.isIdAttributeTypeAllowed)
