### ISSUE TITLE
Buttons the data explorer show their technical names

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#4334]
The buttons in the data explorer show their technical names on the button, such as #dataexplorer_wizard_cancel# and #dataexplorer_wizard_apply# instead of what is supposed to be there.

**Comment by fdlk** [comment]
This is a feature, allowing you to quickly figure out the keys needed to translate them.

**Comment by mswertz** [comment]
This is not desired except temporarily
Please undo/fix

On Thu, Jan 21, 2016 at 7:50 PM, Fleur Kelpin <notifications@github.com>
wrote:

> This is a feature, allowing you to quickly figure out the keys needed to
> translate them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/4334#issuecomment-173671823>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by fdlk** [comment]
In a way, it is temporary, only shown if the translation is missing.
What I mean is that afaik it was coded intentionally so if it's not desired, we need to specify the desired behavior.

**Comment by Mark-de-Haan** [comment]
Switching to english will replace these keys with the proper text.

On 21 January 2016 at 20:10, Fleur Kelpin <notifications@github.com> wrote:

> In a way, it is temporary, only shown if the translation is missing.
> What I mean is that afaik it was coded intentionally so if it's not
> desired, we need to specify the desired behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/4334#issuecomment-173677052>.
>



-- 
Mark de Haan
Genomics Coordination Centre
Genetics Department
University Medical Centre Groningen

**Comment by tommydeboer** [comment]
Whilst it might come in handy for translators/developers, I think missing translations should default to english. This is how Facebook, Google, etc. do it.

**Comment by mswertz** [comment]
This really needs fixing asap because it now results in unusable state. So I added it to current sprint list for its priority to be evaluated against currently selected bugs
