### ISSUE TITLE
InMemoryRepository findAll() includes nulls

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4336]
According to the specs, ```findAll()``` should return an empty stream when no entities were found. 

```java
/**
  * find entities based on a stream of ids.
  * 
  * @return (empty) Stream where the order of entities matches the order of ids, never null
  */
Stream<Entity> findAll(Stream<Object> ids);
```

The ```InMemoryRepository``` adds a null value for each unfound entity:

```java
    @Override
	public Stream<Entity> findAll(Stream<Object> ids)
	{
		return ids.map(id -> entities.get(id));
	}

	@Override
	public Stream<Entity> findAll(Stream<Object> ids, Fetch fetch)
	{
		return ids.map(id -> entities.get(id));
	}
```

These values should be filtered out (for example with ```.filter(Objects::nonNull```).

This might influence tests + code that is tested so beware...

**Comment by mswertz** [comment]
what is the desired behavior?
Because I can imagine you want to know if a particular id resulted in
'null'?

On Thu, Jan 21, 2016 at 3:08 PM, Tommy de boer <notifications@github.com>
wrote:

> According to the specs, findAll() should return an empty stream when no
> entities were found.
>
> /**  * find entities based on a stream of ids.  *   * @return (empty) Stream where the order of entities matches the order of ids, never null  */Stream<Entity> findAll(Stream<Object> ids);
>
> The InMemoryRepository adds a null value for each unfound entity:
>
>     @Override
>     public Stream<Entity> findAll(Stream<Object> ids)
>     {
>         return ids.map(id -> entities.get(id));
>     }
>
>     @Override
>     public Stream<Entity> findAll(Stream<Object> ids, Fetch fetch)
>     {
>         return ids.map(id -> entities.get(id));
>     }
>
> These values should be filtered out (for example with
> .filter(Objects::nonNull).
>
> This might influence tests + code that is tested so beware...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/4336>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by tommydeboer** [comment]
Related to #3854
Having to deal with nulls in a stream after I do a query is not what I'd expect. If it is intended behaviour we should update the javadoc, but we already did the same fix for ```ElasticSearchRepository.findAll()```

**Comment by mswertz** [comment]
Ok

**Comment by dennishendriksen** [comment]
@tommydeboer The behavior for requesting a single entity by id is returning null. The behavior of requesting multiple entities by id is thus consistent and I propose to a) keep it that way  b) revert the ```ElasticSearchRepository.findAll()``` fix c) mention this behavior in the ```DataService``` and ```Repository``` docs.

**Comment by tommydeboer** [comment]
+1 for consistency :) 
We should double-check if the other repositories implement it correctly, then, too.

**Comment by dennishendriksen** [comment]
@tommydeboer adding a test case to the data API integratation tests perhaps

**Comment by tommydeboer** [comment]
Did some research, here are the findings:

1. ```MysqlRepository``` and ```ElasticsearchRepository``` don't return ```null```s for unfound ids in the current implementation.
2. Changing this behaviour would mean adding ```null``` checks everywhere ```findAll(Stream ids)``` is used.
3. I tried changing the behaviour in ```ElasticsearchService``` but I got various NPEs at unexpected places where ```findAll(Query)``` was used. The impact of these changes is hard to predict.
4. The [Spring docs for the various repositories](http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findAll-java.lang.Iterable-) say that ```findAll(ids)``` should "return all instances of the type with given ids". In contrast, ```findOne(id)``` should return ```null``` if no entry was found. 
5. If you really want to know which ids weren't found you can always compare the input and output. This seems neater than having to deal with ```nulls``` each time you do a query.

This was discussed at standup and we propose the following:

1. Leave ```MysqlRepository``` and ```ElasticsearchRepository``` *as is* and fix ```InMemoryRepository```.
2. Update docs to clearly state that unfound entities are not reported as ```null```.

**Comment by fdlk** [comment]
Sounds great to me!
