### ISSUE TITLE
deleteEntityPermissions in metadataservice should be streaming, now the single delete is called with a Iterable as ID

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4347]
private void deleteEntityPermissions(String entityName)
	{
		List<String> authorities = SecurityUtils.getEntityAuthorities(entityName);

		// User permissions
		if (dataService.hasRepository("UserAuthority"))
		{
			Iterable<Entity> userPermissions = dataService.query("UserAuthority").in("role", authorities).findAll();
			dataService.delete("UserAuthority", userPermissions);
		}

		// Group permissions
		if (dataService.hasRepository("GroupAuthority"))
		{
			Iterable<Entity> groupPermissions = dataService.query("GroupAuthority").in("role", authorities).findAll();

			dataService.delete("GroupAuthority", groupPermissions);
		}
	}

**Comment by erwinwinder** [comment]
Is already fixed
