### ISSUE TITLE
i18n - Add a new language, code 'nl' name 'Nederlands'

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4352]
Do the step "Add a new language, code 'nl' name 'Nederlands'" from the test plan.
Expected: new label-nl
Result: 
1. In the Data Explorer error message: Error! org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ALTER TABLE `attributes` ADD `label-nl` TEXT;]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'label-nl'
2. In the Modal: languages could not be created.

Also when uploading: molgenis-data-questionnaires/src/test/resources/test-questionnare.xls in add/update mode

**Comment by erwinwinder** [comment]
Was artifact of previous test
