### ISSUE TITLE
User with edit permission on home plugin can't edit

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4354]
Reproduce:
- Login with a non-superuser user with 'edit' permission on 'home' plugin
- Select the MOLGENIS logo to navigate to the 'home' plugin

Expected:
- 'Edit page' button displayed on page

Actual:
- No 'Edit page' button is displayed on page

**Comment by mswertz** [comment]
Does this relate to story about that for a plugin to be enabled you also need permissions on its setting entities?

**Comment by fdlk** [comment]
@Mark-de-Haan I think this is due to how the menu is organized? Did you look into this lately?

**Comment by Mark-de-Haan** [comment]
No, the check to see if a user can edit is based on if the user is authenticated and the user is a super user. So code wise this is expected behaviour.

```java
> StaticContentServiceImpl.java, line 67

@Override
public boolean isCurrentUserCanEdit()
{
	return SecurityUtils.currentUserIsAuthenticated() && SecurityUtils.currentUserIsSu();
}
```
@mswertz what do you expect? Anyone can edit home page? or only admins and super users?
