### ISSUE TITLE
Unable to upload test-edgecases.vcf

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4368]
the molgenis-annotators/src/test/resources/test-edgecases.vcf gives the following error when trying to import:

org.molgenis.data.MolgenisDataException: Validation error in entity [testEdgecases_Sample]: Invalid characters in: [.] Only letters (a-z, A-Z), digits (0-9), underscores (_) and hashes (#) are allowed.

**Comment by erwinwinder** [comment]
Duplicate of https://github.com/molgenis/molgenis/issues/4331 ?

**Comment by Mark-de-Haan** [comment]
No I don't think so. This is probably an old vcf test file that was never migrated to work with the newer validation rules or something

**Comment by bartcharbon** [comment]
We support uploading VCF's it strike me as "odd" if we need to migrate the actual file...

**Comment by mswertz** [comment]
If its wrong format then this is a 'wontfix'?

**Comment by tommydeboer** [comment]
Fixed in #4395
