### ISSUE TITLE
i18n - Change language to Deutsch results in 500 exception

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4369]
To reproduce:

1. Log in as user (Not admin)
2. Import molgenis-data-questionnaires/src/test/resources/test-questionnare.xls
3. Start the questionnaire	
4. Change language to Deutsch																			

Result:
HTTP Status 500 - Request processing failed; nested exception is freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "questionnaire_back_button"; see cause exception! The type of the containing value was: method+extended_hash (org.molgenis.data.i18n.MolgenisResourceBundleControl$MolgenisResourceBundle wrapped into f.e.b.ResourceBundleModel)

Expected to see labels with ## where there is no translation.

**Comment by erwinwinder** [comment]
User must have permission on i18nStrings
