### ISSUE TITLE
Manual adding and removing tag in tagging service is not working.

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4380]
## Reproduce

Download the folder (real_examples) at: https://drive.google.com/drive/folders/0B7qHi41THTs_T3BnaHY2TGJ1Mzg
"Demo target data and source data 
1. mappingservice-test.xlsx" Upload via the upload page 
"Demo ontology files:
2. biobank_ontology.owl.zip
3. uo.owl.zip" Upload via the upload page
"Demo magma script type and algorithm template file:
4. test-javascript_magam.xls" Upload via the upload page

Go to the "Tag Wizard"
Select an entity to tag: HOP_selenium
Select an ontology: biobank_ontology; uo;
add manually the tag "Weight" to attribute "Body_Mass_Index_1"
remove the tag "Weight".

Go to the "Mapping Service"
Add the a new mapping project with HOP_selenium as target.
### Expected:

No tagging Weight exists
### Result:

Tagging "Weight" exists

**Comment by mswertz** [comment]
@ChaoPang is this desired behavior? I mean, I though we stopped the manual tagging!!!

**Comment by fdlk** [comment]
I think it would definitely be a bug if the tags you remove in the tag wizard still show in the mapping service. But I cannot reproduce.

**Comment by Mark-de-Haan** [comment]
Fixed in v5.0.0
