### ISSUE TITLE
Remove Questionnaire hack from MySqlRepository

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4425]
Remove the following hack from MySqlRepository:
```
private void getAttributeSql(StringBuilder sql, AttributeMetaData att) throws MolgenisModelException
{
  ...
  // not null
  if (!att.isNillable() && !EntityUtils.doesExtend(metaData, "Questionnaire")&& (att.getVisibleExpression() == null))
  {
    sql.append(" NOT NULL");
  }
  ...
}
```

molgenis-data-mysql should not depend on molgenis-questionnaires

**Comment by fdlk** [comment]
Hear hear!
(But how will we solve required fields in an optional questionnaire section?)

**Comment by dennishendriksen** [comment]
@fdlk Validation in a questionnaire decorator that is applied for all entities extending from questionnaire?

**Comment by fdlk** [comment]
@dennishendriksen If questionnaire results are stored in mysql, the save will fail if the optional section is not filled in, cause the required attributes in that section are not nillable and the column is NOT NULL.
I think the most elegant way to fix this is by making optional sections nillable xrefs to separate entities with non-nillable attributes for the required fields.
But that's not how it's currently implemented and it'd mean the model changes.

**Comment by mswertz** [comment]
I would think we need to clarify where these constraints are handled and then update repository framework to enable this parameterization. I would not want remodeling to be required as users (data modelers) will not understand

**Comment by fdlk** [comment]
How about *if there's a visibleExpression* the mysql repository delegates the validation to the decorator, whether it's a Questionnaire or not. If there isn't, the mysql still enforces it by making the column NOT NULL.

**Comment by dennishendriksen** [comment]
MySqlRepository does not exist in 2.0-RC, PostgreSqlRepository does not contain any Questionnaire hacks.
