### ISSUE TITLE
When an uploaded VCF has multiple SNPs with a '.' in its ID column, it will trigger duplicate key entry

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4437]
## Reproduce
Import the modified test_samples vcf file in this zip [test_samples.vcf.zip](https://github.com/molgenis/molgenis/files/117501/test_samples.vcf.zip)

## Expected
If the ID column is '.' then a unique key based on chrom_pos_ref_alt is generated

## Observed
`org.molgenis.data.validation.MolgenisValidationException: Duplicate value '' for unique attribute 'ID' from entity 'test_samples7' (entity 6)`

**Comment by Mark-de-Haan** [comment]
@mswertz This bug has been introduced in the last few days and is also blocking the selenium test. So I would propose to fix it now.

**Comment by fdlk** [comment]
Plus it falls within the 5 second rule. I.e. looks like it's very easy to fix.
