### ISSUE TITLE
Unable to retrieve XREF values for a single ID through the python REST API.

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis#4449]
In molgenis.py.ftl, quote_plus of the url in get() when called with a query changes a / into %2F,  because of this I can not retrieve data of hrefs.

The part of code that gives the error:
```
response = self.session.post(self.url + "v1/" + quote_plus(entity),
                headers = self._get_token_header_with_content_type(),
                params={"_method":"GET", "attributes":attributes, "num": num, "start": start, "sortColumn":sortColumn, "sortOrder": sortOrder},
                data=json.dumps({"q":q}))
```

To reproduce:
```
>>> import molgenis.py
>>> session = molgenis.Session('molgenis39.target.rug.nl')
>>> session.login('*******', '**************')
>>> session.get("public_rnaseq_3_Samples/example_ID/input_file_paths/", [{'field': 'sample_id', 'operator': https://molgenis39.target.rug.nl/api/v1/public_rnaseq_3_Samples%2F%2Fexample_ID%2Finput_file_paths%2F?start=0&_method=GET&num=100
```

After replacing the %2F with / the data gets correctly retrieved.
```
response = self.session.post(self.url + "v1/" + quote_plus(entity).replace('%2F','/'),
                headers = self._get_token_header_with_content_type(),
                params={"_method":"GET", "attributes":attributes, "num": num, "start": start, "sortColumn":sortColumn, "sortOrder": sortOrder},
                data=json.dumps({"q":q}))
```

**Comment by fdlk** [comment]
I think this is working as intended, but you're trying to use the get method to retrieve something more specific. What exactly are you trying to do here? I think we need to add more arguments to allow it.

**Comment by npklein** [comment]
As an example, I have the  ID for the entity public_rnaseq_3_Samples (in above example example_ID) and I want to get the information that is in the public_rnaseq_3_Input_file, to which public_rnaseq_3_Samples has an mref. I don't know which ID in public_rnaseq_3_Input_file is linked to example_ID of public_rnaseq_3_Samples, but if I request

public_rnaseq_3_Samples/example_ID/input_file_paths/

I get the mref data from Input_file_paths that is lined to example_ID. 
What would be a better way to get this?

**Comment by npklein** [comment]
In ```delete()``` ```quote_plus(id)``` is used, some id's might have ```/``` in them, will also give an error.

**Comment by fdlk** [comment]
@npklein correct, that's #4117 , a very nasty bug cause it's in the way spring mvc interprets the URLs.

**Comment by npklein** [comment]
@fdlk Thanks for the pointer, I'll wait for autoid to be standard.

**Comment by fdlk** [comment]
@npklein I'd suggest not to use / in entity ids to begin with :)

**Comment by fdlk** [comment]
I've taken a look at the get() method and how it can be used to retrieve this xref.
I noticed the expand argument was missing and also that it was sending the attributes argument in the wrong way if you are providing a query

**Comment by fdlk** [comment]
@npklein Hi Niek, can you take a look if this solves things for you?

**Comment by npklein** [comment]
@fdlk I will look at it this weekend

**Comment by npklein** [comment]
@fdlk Works, thanks!
