### ISSUE TITLE
molgenis.py.ftl .get() method expects an 'items' key in response.json(), not always there

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis#4450]
In molgenis.py.ftl, get() tries to return response.json['items'], but when getting data from hrefs there is not always an 'items' key in response.json().

The part of code that gives the error:
```
if response.status_code == 200:
    return response.json()["items"]
```

To reproduce (after fixing the %2F error from https://github.com/molgenis/molgenis/issues/4449):
```
>>> import molgenis.py
>>> session = molgenis.Session('molgenis39.target.rug.nl')
>>> session.login('*******', '**************')
>>> session.get("public_rnaseq_3_Samples/BIOS-LLS-1935-1/input_file_paths/", [{'field': 'sample_id', KeyError: 'items'
```

Possible fix 
```
if 'items' in response.json():
    return response.json()["items"]
else:
    return response.json()
```

**Comment by fdlk** [comment]
It will be there when the method is used as intended ;-)

**Comment by fdlk** [comment]
Shouldn't call get() with entity name "public_rnaseq_3_Samples/BIOS-LLS-1935-1/input_file_paths/".
Let's take a look how to query for those input_file_paths instead.
