### ISSUE TITLE
When I have view rights on the questionnaire as an anonymous user, the sign in button does not work

### ISSUE THREAD

**Issue by mark-de-haan** [molgenis/molgenis#4488]
## Reproduce
- Grant view permissions for the questionnaire plugin to anonymous users
- Log out and go to the questionnaire plugin, My questionnaires screen
- Press the Sign In button
## Expected

Modal asking for name and password
## Observed

Nothing happens

**Comment by Mark-de-Haan** [comment]
Note: Sign in data-toggles #login-modal div
#login-modal div is inside the molgenis-footer.ftl
Questionnaire does not contain a footer

**Comment by tommydeboer** [comment]
Can't reproduce in the latest build. Maybe because the questionnaire has a footer now?

**Comment by tommydeboer** [comment]
This issue doesn't exist in the new questionnaire
