### ISSUE TITLE
I cannot edit entries in the File entity

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4505]
## Reproduce
- Import file_datatype-test.xlsx
- Add a row via the data explorer
- Try and edit that row
  * Edit description

## Expected
I can edit the description

## Observed
`Error! The attribute 'attachment' of entity 'File' can not be null. (entity 1)`
- There is no attachment mentioned in the modal popup

**Comment by tommydeboer** [comment]
Related to / same as #3736 ?

**Comment by Mark-de-Haan** [comment]
Yes, closing as duplicate
