### ISSUE TITLE
Creating a copy on the same entity with the same annotator multiple times results in a lot of entities with the same label in the dropdown

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4511]
![screen shot 2016-02-16 at 16 28 15](https://cloud.githubusercontent.com/assets/3625016/13080742/4ea17c94-d4ca-11e5-9c57-80be3ad1177d.png)

**Comment by bartcharbon** [comment]
not a bug I'd say, you create a copy so you get one.
in real life there seems no to do this, the fact that you can does not sound like a bug to me

**Comment by Mark-de-Haan** [comment]
Yes I agree, normally you would not copy the same entity with the same annotator over and over again

**Comment by tommydeboer** [comment]
We agreed this is not a bug
