### ISSUE TITLE
Integration tests cannot build concurrently

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4530]
We should be able to run them concurrently, if we want to run them for each pull request / for each change to the master.

**Comment by dennishendriksen** [comment]
Can you elaborate? How to reproduce? Which concurrent executed Jenkins builds show a problem?

**Comment by fdlk** [comment]
The pull request builder ran the integration tests for a while and then the builds started failing even if their contents were fine.
The TAP results publisher was one of the causes, it waits for all concurrent builds to have finished before it dares to publish its results. So I removed that.
But then the integration tests still kept failing. I suspect that the cleanup of one running build shares (YUCK) and removes(OUCH) the elasticsearch index files used by another build.

**Comment by dennishendriksen** [comment]
Fixed by #5705
