### ISSUE TITLE
REST API V2 get resource collection: id null when id attr not selected

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#4542]
Using this query: http://localhost:8080/api/v2/chromosome6_a_c?attrs=id,ownerUsername, i get: 
{
      "_href": "/api/v2/chromosome6_a_c/AAAACUQ4BI3UC6BRYG6QQIAAAE",
      "ownerUsername": "Vlckova_patient1",
      "id": "AAAACUQ4BI3UC6BRYG6QQIAAAE"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/AAAACUQ4EQS6M6BRYG6QQIAAAE",
      "ownerUsername": "Vlckova_patient2",
      "id": "AAAACUQ4EQS6M6BRYG6QQIAAAE"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/AAAACURAGFFPC6BRYG6QQIAAAE",
      "ownerUsername": "Woo",
      "id": "AAAACURAGFFPC6BRYG6QQIAAAE"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/AAAACURBHC3WI6BRYG6QQIAAAE",
      "ownerUsername": "Wang_patient5",
      "id": "AAAACURBHC3WI6BRYG6QQIAAAE"
    }
Using this query: http://localhost:8080/api/v2/chromosome6_a_c?attrs=ownerUsername, i get: 
 {
      "_href": "/api/v2/chromosome6_a_c/null",
      "ownerUsername": "Wentzel_14_deletion"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/null",
      "ownerUsername": "Wentzel_14_duplication"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/null",
      "ownerUsername": "Wentzel_10_patient1"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/null",
      "ownerUsername": "Wentzel_10_patient2"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/null",
      "ownerUsername": "van_Esch_patient3"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/null",
      "ownerUsername": "van_Esch_patient1"
    },
    {
      "_href": "/api/v2/chromosome6_a_c/null",
      "ownerUsername": "van_Esch_patient2"
    }

Something is broke, I guess... 
Using version 1.16.3-SNAPSHOT (this is the stable version of 1.16.3, with D3 in it's head)

**Comment by Mark-de-Haan** [comment]
Can not reproduce in v5.3.0-SNAPSHOT
