### ISSUE TITLE
MapEntity has illegal constructors

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4547]
```MapEntity``` has multiple constructors that allow instantiating an ```Entity``` without ```EntityMetaData```:

```java
	public MapEntity()
	{
	}

	public MapEntity(String idAttributeName)
	{
		this.idAttributeName = idAttributeName;
	}

	public MapEntity(Map<String, Object> values)
	{
		this.values = values;
	}

	public MapEntity(String attributeName, Object value)
	{
		values.put(attributeName, value);
	}
```

This leads to inconsistent behaviour. When you remove these constructors, there are 300+ problems to fix (in tests as well as production code).

**Comment by mswertz** [comment]
originally this was supposed to also work without metadata, so we need discuss desired behavior

**Comment by dennishendriksen** [comment]
MapEntity was replaced by DynamicEntity in 2.0-RC which doesn't suffer from this issue
