### ISSUE TITLE
searching through settings entities broken

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4551]
Go to the settings page, enter a search term in the selection box.

java.lang.UnsupportedOperationException: Query with operator [LIKE] and data type [TEXT] not supported

**Comment by dennishendriksen** [comment]
Cannot reproduce 
![cannotreproduce_4551](https://cloud.githubusercontent.com/assets/2477186/20011089/bc1e879a-a2aa-11e6-8689-ffd1a10ea62b.png)
