### ISSUE TITLE
Converters not added to FormatterRegistry in integration tests

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4554]
#### Reproduce
- Uncomment these lines in `AbstractDatetimeDatatypeIT`:

``` java
@Override
    public EntityMetaData createMetaData()
    {
        ...

        entityMetaData.addAttribute("col3").setDataType(DATETIME);// .setDefaultValue("2010-09-29T18:46:19UCT");

        ...
    }

    ...

    @Override
    public void verifyTestEntityAfterInsert(Entity entity) throws Exception
    {
        ...
        // assertEquals(entity.getUtilDate("col3"), sdf.parse("2010-09-29 18:46:19"));
    }
```
- Run the test (Mysql or Elasticsearch)
#### Expected

Test succeeds.
#### Actual

```
org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type java.util.Date
```

The issue is that `DateToStringConverter` and `StringToDateConverter` are not added to the `FormatterRegistry` in the context.

In the app this is done in `MolgenisWebAppConfig.addFormatters()`.

**Comment by dennishendriksen** [comment]
Both the test and the integration module do not exist anymore.
