### ISSUE TITLE
Data conversion test failure when running with EDT timezone

### ISSUE THREAD

**Issue by smbatchou** [molgenis/molgenis#4573]
I have tried to build the molgenis software using v1.17.0 release tag. But I am facing the following test error:

Tests run: 495, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.532 sec <<< FAILURE! - in TestSuite
convertDate(org.molgenis.data.DataConverterTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected [Wed Jun 03 18:00:00 EDT 2015] but found [2015-06-04]
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.failNotEquals(Assert.java:494)
    at org.testng.Assert.assertEquals(Assert.java:123)
    at org.testng.Assert.assertEquals(Assert.java:165)
    at org.molgenis.data.DataConverterTest.convertDate(DataConverterTest.java:28)

**Comment by fdlk** [comment]
When we release 1.17, we also build it including these tests, so perhaps we're seeing machine-specific behavior?

**Comment by djvanenckevort** [comment]
This is an issue with the Date settings in the tests that are not locale aware.

**Comment by dennishendriksen** [comment]
Cannot reproduce when executing DataConverterTest with JVM option ```-Duser.timezone=EDT```, both the actual and expected arguments of the assert use a default timezone.
