### ISSUE TITLE
Mapping Service interrupts user interaction when evaluating results in the background.

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#4575]
When I try to enter a mapping script the mapping service fires the script after each keystroke, making for an unusable interface. Instead the script should only be run when I leave the entry field or press a button to test it.
(Tested on molgenis10, with Safari)

**Comment by fdlk** [comment]
This used to be a (working :) ) feature, the script used to run in the background and not cause trouble to the person editing it. If it was not valid, you'd just get an error and when it became valid again the error would go away. So what precisely makes it unusable now?

**Comment by djvanenckevort** [comment]
The script will interfere with typing, making it very slow or steal the focus with a overlay div.

**Comment by fdlk** [comment]
I think the issue should be then that it shouldn't interfere with typing while evaluating the script in the background.

**Comment by fdlk** [comment]
Duplicates #3776
