### ISSUE TITLE
Problems finding Rscript in El Capitan (R Api)

### ISSUE THREAD

**Issue by mlisad** [molgenis/molgenis#4577]
When executing an R script via the API an error occurs when the OS is El Capitan.
The error shows that /usr/bin/Rscript doesn't exists, the new directory on El Capitan is /usr/local/bin/Rscript 

Quick Fix: sudo ln -s /usr/local/bin/Rscript /usr/bin/

**Comment by fdlk** [comment]
I took a look and the location of the Rscript executable is actually configurable through the property `r_script_executable`. Set it to the proper value in molgenis-server.properties
