### ISSUE TITLE
Genome browser gives error offline

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4581]
To reproduce:
Run the selenium test **offline**: AnnotatorTest.testRunCaddTwiceOnEMXWithCopy

File cannot be found
importScripts("https://www.biodalliance.org/release-0.13/worker-all.js?version=0.13.6");

Expected: Genome browser works

Actual:
<img width="961" alt="screen shot 2016-03-01 at 9 39 30 am" src="https://cloud.githubusercontent.com/assets/5586255/13421951/f0a3b7ce-df91-11e5-81d5-8fcb540bfdaf.png">

**Comment by Mark-de-Haan** [comment]
Some tracks are fetched from the internet. So the expected is wrong here. Working as intended
