### ISSUE TITLE
Support updating of a single attribute of an entity 

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis#4589]
For entities with many xref attributes updating a single attribute is slow as all unchanged attributes are also validated. It would be great if the DataService would also support attribute updates, so that only changed attributes have to be validated.

**Comment by npklein** [comment]
@fdlk Is this correct?

**Comment by fdlk** [comment]
@npklein Yes! Though I'd imagine the story belongs in trac, not github.

**Comment by dennishendriksen** [comment]
In MOLGENIS 2.0 reference validation is performed by PostgreSQL which is much faster than validating in the business layer. @npklein If the performance is still not good enough then please create a story in the MOLGENIS backlog.
