### ISSUE TITLE
The xlsx and xls file importer does not recognize an empty string as null

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#4595]
Importing an xlsx and xls file with empty cells (which are linked through xref, but not filled in because the visible expression is false) produces an error because empty strings: '' are not seen as null. When saving the same file again in excel, it works again. 

![screen shot 2016-03-03 at 14 11 16](https://cloud.githubusercontent.com/assets/10075439/13495238/d1f6db30-e149-11e5-9d97-bd1d458c18b5.png)

**Comment by marikaris** [comment]
This dataset was created using a python script, that caused empty cells to have empty strings inside them, which is not the same as a complete empty cell. Fixing this in molgenis could cause issues with other projects.

**Comment by fdlk** [comment]
[complete_EMX_model_AT.xlsx](https://github.com/molgenis/molgenis/files/913400/complete_EMX_model_AT.xlsx)

**Comment by fdlk** [comment]
I've taken a look and the cell is perfectly empty.

**Comment by fdlk** [comment]
Deep inside, it says `<xml-fragment r="O2" t="s" />`
So the cell is indeed filled with the empty string.

**Comment by fdlk** [comment]
Taken a look at the original bbmri_eric_041117.xslx file, it *also* contains empty string cells.

**Comment by fdlk** [comment]
So I think the download tool (Is that how it was created?) incorrectly turns null into empty string.

**Comment by fdlk** [comment]
pandas is particular about missing values. It allows you to specify how to treat them.
If I update the conversion script as follows, things go well:

Parsing: `workbook.parse("...", na_values='')`
Writing:  `sheet.to_excel(writer, sheet_name='...', index=False, na_rep=None)`

**Comment by fdlk** [comment]
So to sum it up: 
An empty excel cell is something else than a cell filled with the empty string.
The ExcelRepository handles both cases differently and correctly.
The empty cell becomes attribute value `null`, the cell filled with the empty string becomes attribute value `''`.

The importer could be updated to have an option that you want it to interpret cells filled with the empty string as null. We could create a cell processor that does that. I'd imagine this is then an advanced setting in the importer.

I don't know a use case for that setting yet. Cause in this particular case I'd advise to simply adapt the script to write empty cells.
