### ISSUE TITLE
Import of ZIP/TAR.GZ compressed VCF is not possible

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#4598]
It is not possible to import a zipped (.vcf.zip) VCF. The error thrown:
```
Error! Your import failed:
Can not import file. No suitable importer found
```
Importing a gzipped TAR (.vcf.tar.gz) does not work either. The error thrown:
```
Error! Your import failed:
Unknown extension for file 'myfile.tar.gz'
```
NOTE: Just gzipping the file does work! the extension becomes ".vcf.gz" in that case.

**Comment by fdlk** [comment]
Does this need to be documented rather than fixed? Or do we need to support zip/tar.gz always? And in that case, is it a feature request?
