### ISSUE TITLE
Cannot import emx_all_datatypes.xlsx

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4600]
* import emx_all_datatypes.xlsx
* Error message:
Failed to convert from type java.lang.String to type java.sql.Date for value '2014-08-01T00:00:00+0200'; nested exception is java.lang.IllegalArgumentException

**Comment by Mark-de-Haan** [comment]
Part of the problem: Default value is used whilst there is a value available

**Comment by fdlk** [comment]
Fixed by reverting the defaultValue fix.
