### ISSUE TITLE
Date and DateNillable always use the DefaultValue, even when there is a value present

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4602]
## Reproduce
- Import emx_all_datatypes
- Go to the data explorer and look at TypeTest
- Select xdate and xdatenillable
## Expected

xdate shows 1985 dates, xdatenillable has some 1985, and some 2015 dates.
## Observed

all xdate values are 2014
all xdatenillable values are 2015

Introduced by #4572 
Fix was reverted on master
Now on tommydeboer/fix/defaultvalue

**Comment by fdlk** [comment]
We temporarily fixed this by reverting the default value pull request. Let's revisit this after releasing 1.18
