### ISSUE TITLE
entity select no longer finds exact matches

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4603]
For instance, the FileIngest, when I try to select the "city" entity finds it up to the point where I've typed "cit". When I add the "y", it has no matches.

Probably because "city" gets tokenized to "cit" in elasticsearch?

**Comment by dennishendriksen** [comment]
How to reproduce? I cannot select entities in the file ingest plugin.

**Comment by mswertz** [comment]
unclear, propose to close.

**Comment by dennishendriksen** [comment]
@fdlk?

**Comment by dennishendriksen** [comment]
@fdlk?

**Comment by fdlk** [comment]
Happens in any entity select box. It doesn't respond to the complete name of the entity when the entity is tokenized.

**Comment by fdlk** [comment]
Cannot reproduce anymore.
