### ISSUE TITLE
importer reports index within the batch instead of actual line number on fail.

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4608]
If an import fails on line 8848 for example, the reported line is 848, this seems to be caused by the import being batched in batches of a thousand.

Example data: ask Marije or Bart.

**Comment by Mark-de-Haan** [comment]
Notes:
This only occurs when doing an add / update
This only occurs when dealing with the remainder of numberOfRows % 1000

With 2100 rows, an error on line 1983 will give a proper message (entity 1983)
an error on row 2100 will give the wrong count (entity 100)
