### ISSUE TITLE
menu manager edit button gives "empty" popup

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4609]
expected:
edit button shows current values

actual:
see screenshot

![menu](https://cloud.githubusercontent.com/assets/3714029/13571155/5cda08fe-e473-11e5-9ef4-36a627186819.png)

**Comment by bartcharbon** [comment]
probably caused by: https://github.com/molgenis/molgenis/issues/4613

**Comment by Mark-de-Haan** [comment]
Fixed by fixing #4613
