### ISSUE TITLE
When hitting "tab" immediately after typing the focus switches back to previous field

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4617]
Reproduce:
- type a username in the "add user" form in the user manager
- after the last character immediately hit "tab"

Expected
Focus switches to next field and stays there

Actually:
Focus switches to next field and then immediately back to previous field.

Note: seems to happen only with validated fields

**Comment by fdlk** [comment]
Selenium Forms test fails because of this.

**Comment by fdlk** [comment]
Input.js has a componentDidUpdate that calls this._focus().
So when the validation result comes in, the validated input gets focussed, even if there's nothing wrong with the validation.
