### ISSUE TITLE
Creating a copy of an entity can result in foreign key names that are too long

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4623]
## Reproduce
- Import TypeTest
- Go to the data explorer and create a copy
- Name it TypeTest_test_copy
## Expected

My copy is created
## Result

![screen shot 2016-03-08 at 10 59 15](https://cloud.githubusercontent.com/assets/3625016/13598181/d4f5853a-e51c-11e5-9853-0c39fc4f1d5e.png)

**Comment by tommydeboer** [comment]
You can also recreate this issue by importing TypeTest with longer package, entity or attribute names. It's the combination that will become too long quite quickly and because MySQL auto-generates the foreign key names, there's not much else to do than choose shorter table/attribute names.

**Comment by tommydeboer** [comment]
I propose to add a nicer error message for now and let this be fixed automatically when we switch to generated entity and attribute names.

**Comment by fdlk** [comment]
The automatic FK names in MySQL are buggy when > 64 chars long. See https://bugs.mysql.com/bug.php?id=13942 .

But we need not use those since MySQL allows you to explicitly specify the name you'd like to use for the FK constraint. https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html

**Comment by mswertz** [comment]
this limiation should be overcome if we use internal identifiers next to user readible names

**Comment by dennishendriksen** [comment]
The maximum identifier length in [PostgreSQL](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) is 63 bytes.

**Comment by mswertz** [comment]
is this now sorted?

**Comment by dennishendriksen** [comment]
@mswertz issue resolved when technical identifiers were implemented
