### ISSUE TITLE
importByUrl returns content-type application/json but is raw text

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4624]
* POST /plugin/importwizard/importByUrl?notify=false&entityName=demo&url=https://raw.githubusercontent.com/bartcharbon/molgenis/feature/importService/molgenis-app/src/test/resources/vcf/test.vcf
* Returns /api/v2/ImportRun/AAAACU2V6GVNOATAPVHJR3AAAE", Content-Type application/json
  This is not json, so change response body or change ContentType to text/plain

**Comment by fdlk** [comment]
Actually, it does return JSON, a single string in "".
