### ISSUE TITLE
when there are failing annotators the job status is SUCCESS

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4626]
this line in the AnnotationJobExecution should not be possible:
SUCCESS	annotators	2016-03-08T10:41:19+0100	2016-03-08T10:41:19+0100	2016-03-08T10:41:19+0100	8	8	Failed annotators: cadd,dann,clinvar,gonl,exac,fitcon,snpEff,thousand_genomes

**Comment by bartcharbon** [comment]
should be fixed by PR https://github.com/molgenis/molgenis/pull/4622

**Comment by fdlk** [comment]
The annotator set the status to FAILED but should've throw an exception instead.
