### ISSUE TITLE
Switching between entities in de Data Explorer does not refresh the language dropdown

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4629]
To reproduce:
1. Goto dataexplorer and select i18nstrings entity
2. 36 rows and column 'en' present
3. Select languages entity, english is present
4. Try delete English, message is shown that it cannot be deleted
5. Add a new language, code 'nl' name 'Nederlands'
6. Goto dataexplorer and select i18nstrings entity
7. Extra attribute 'nl' is present

Expected
8. Next to 'Sign out' button there is a dropdown with options 'English' and 'Nederlands'

Actual
no dropdown with options 'English' and 'Nederlands' (Switching entities does not reload the free marker master template)

**Comment by Mark-de-Haan** [comment]
Hmm because the page needs to be reloaded to update the freemarker model, the only way of fixing this would be to get the available languages via a rest call. But that would still require a page refresh, or a trigger of some kind..
