### ISSUE TITLE
running script on entity without proper permissions gives empty plot rather than error

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4636]
I run:

```
     library(RCurl)
     eval(expr = parse(
     text = 
     getURL("https://molgenis62.gcc.rug.nl/molgenis.R?molgenis-token=${molgenisToken}")))
      df <- molgenis.get("Rtest")
      df2 <- apply(df, 1,as.numeric)
      is.na(df2) <- sapply(df2, is.infinite)
      df2[is.na(df2)] <- 0
      df2[is.nan(df2)] <- 0
      png('${outputFile}')
      heatmap(as.matrix(df2),symm=FALSE,trace="none")
     dev.off()
     molgenis.logout()
```

from the testplan for a non-admin without Rtest permissions

Expected:
"Error no read permissions on entity Rtest" or something similar

actual:
screenshot attached
![r_no_permission](https://cloud.githubusercontent.com/assets/3714029/13602741/bb7ce2da-e538-11e5-8b82-e038d278654a.png)

**Comment by bartcharbon** [comment]
happened after I
- had no permissions on the Rtest entity
- gave permissions, and ran the script successful as a user
- than set the permissions to "none" again

**Comment by Mark-de-Haan** [comment]
Scripts are now run as a Job. The Job will fail due to No permissions
