### ISSUE TITLE
File download broken

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4641]
While doing the Forms test in Firefox, the File download is broken.
I get a 404.

**Comment by Mark-de-Haan** [comment]
As Admin, I get a **HTTP Status 500 - Request processing failed; nested exception is org.molgenis.data.MolgenisDataAccessException: No READ permission on entity FileMeta**

**Comment by dennishendriksen** [comment]
Works in MOLGENIS 2.0 for both superuser and non-superuser in Firefox 50.0.2
