### ISSUE TITLE
lookupAttribute is missing

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#4643]
In MOLGENIS 1.18-SNAPSHOT lookupAttribute is missing from the attributes table, which means that looking up any XREF / MREF doesn't work anymore (see molgenis10 for example).

**Comment by Mark-de-Haan** [comment]
Where is the EMX for the data uploaded to molgenis10?

**Comment by Mark-de-Haan** [comment]
Reproduce: Upload emx_all_datatypes
lookup attributes are present

Restart server

lookup attributes are gone

Seems to be an entitymetadata caching problem..
