### ISSUE TITLE
ElasticSearch backend repositories claim to be INDEXABLE and get reindexed when import fails

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4673]
Seems silly to me. I'd expect that the decorator that wraps a MysqlRepository with an ElasticSearch index should declare that the result is INDEXABLE and that the other repositories aren't INDEXABLE.

Or am I missing something?

**Comment by dennishendriksen** [comment]
Fixed in 2.0-RC where Elasticsearch is not a backend anymore.
