### ISSUE TITLE
Plugin Permissions shows "Edit metadata" permission

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4676]
### How to Reproduce
- Select the 'Permission manager' plugin the 'Admin' menu

### Expected behavior
- The permission panel consists of plugins and checkboxes that define whether or not a user has permissions to access plugins

### Observed behavior
- Edit meta data, edit, view, count permissions can be assigned to plugins

**Comment by tommydeboer** [comment]
@mswertz Not easily fixed without creating code duplication or changing the plugin API. I suggest to fix this when reimplementing in Vue.

**Comment by Mark-de-Haan** [comment]
Wontfix: Changed in [SecurityUI story](http://wiki.gcc.rug.nl/ticket/5466)

**Comment by dennishendriksen** [comment]
Fixed in 626d505c7ae7873c4a89c387e350ad65733b4b5a
