### ISSUE TITLE
deleting an entity does not remove its permissions

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4690]
reproduce:
- remove an entiy in the dataexplorer

expected:
- the permissions are deleted as well
- uploading a new entity with the same name does not inherit the permissions from its predecessor

actual:
- the permissions are not deleted
- uploading a new entity with the same name does inherit the permissions from its predecessor

**Comment by dennishendriksen** [comment]
@bartcharbon which version?

**Comment by dennishendriksen** [comment]
This has been fixed, cannot reproduce.
