### ISSUE TITLE
CADD annotator is not multi-allelic

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#4693]
When annotating a multi-allelic VCF line, you only get back 1 CADD result, not knowing to which alternative allele it belongs. For example:
```
22	25599848	.	C	T,TA	.	.	.
```
Gets annotated as
```
22	25599848	.	C	T,TA	.	.	CADD=6.956883;CADD_SCALED=33.0;
```
But should be
```
22	25599848	.	C	T,TA	.	.	CADD=6.956883,.;CADD_SCALED=33.0,.;
```

**Comment by Mark-de-Haan** [comment]
Fixed in #4696
