### ISSUE TITLE
Error when calling RestClientV2 without '/api/v2/' in URI

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4699]
#### Reproduce:
Create a piece of javascript with a call to the REST client without the '/api/v2' prefix:

```javascript
import RestClientV2 from "rest-client/RestClientV2";

var api = new RestClientV2();
var data = api.get('TestEntity', {});
```

#### Expected:
No problems, the client should take care of it:
```javascript
if(!resourceUri.startsWith('/api/')) {
    // assume that resourceUri is a entity name
    resourceUri = apiBaseUri + htmlEscape(resourceUri);
}
```

#### Actual:
```Uncaught ReferenceError: htmlEscape is not defined```

**Comment by dennishendriksen** [comment]
@tommydeboer which MOLGENIS version?

**Comment by bartcharbon** [comment]
This happens because the code gets fired before molgenis.js is loaded. molgenis.js provides the htmlEscape.
putting the code withing "(function($, molgenis) {});" solves the problem.

Do we consider this a bug? Fix by adding a htmlEscape function to RestClientV2?

**Comment by dennishendriksen** [comment]
Why isn't molgenis.js loaded before this code? This js contains the core functions that can be used by other js.
