### ISSUE TITLE
Molgenis-HTTP status 404 error

### ISSUE THREAD

**Issue by pinki999** [molgenis/molgenis#4710]
Hi,

I am trying to install Molgenis. I followed maven cargo method described here: https://molgenis.github.io/download#1usingmavencargo

When I run the below command, everything looks fine and tomcat is started on the port 8080. But when I try to access molgenis from localhost:8080, I get HTTP 404 error. 

mvn clean resources:resources org.codehaus.cargo:cargo-maven2-plugin:run

Can anyone please help me to rectify this issue?

Thanks,
Geetha

**Comment by Mark-de-Haan** [comment]
Hi Geetha!

When I run the `mvn clean resources:resources org.codehaus.cargo:cargo-maven2-plugin:run` or `mvn org.codehaus.cargo:cargo-maven2-plugin:run` commands, I am able to run and access molgenis  via localhost:8080

Could you give some additional information?
What OS are you running on?
What version (I assume 1.18.0) of molgenis-cargo are you running?
Is your MySQL database installed correctly?
Do you have the correct maven (3 and up) and Java (1.8.0_71 and up)?

Cheers,
Mark

**Comment by pinki999** [comment]
Hi Mark,

I am running it on ubuntu 12.04. Molgenis-cargo version is 1.18.0. I had MySQL already installed and I ran the following commands in MySQL:

create database omx;
    grant all privileges on omx.* to molgenis@localhost identified by 'molgenis';
    flush privileges;

**Comment by dennishendriksen** [comment]
Hi Geetha,

Apologies for not coming back to you with an answer. I'm afraid @Mark-de-Haan forgot about your issue. The MOLGENIS v1.18 that you were trying to deploy can take some time to deploy depending on your hardware. According to the logs the deploy on your hardware took longer than the allowed 120 seconds. We are currently in the process of releasing cargo based on MOLGENIS v2.0 which has a much shorter bootstrap time.

Cheers,
Dennis
