### ISSUE TITLE
When uploading a file with many attributes, I get a Duplicate key attributes error even when there are no duplicate keys

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4711]
## Reproduce
- import this file: 
[attributes.xlsx](https://github.com/molgenis/molgenis/files/187811/attributes.xlsx)

## Expected
I can import

## Observed
![screen shot 2016-03-24 at 13 18 36](https://cloud.githubusercontent.com/assets/3625016/14016832/f07c15fa-f1c2-11e5-9004-b72b3fef439e.png)

**Comment by fdlk** [comment]
Possibly related to #4702 ?

**Comment by tommydeboer** [comment]
After this fix I still can't import the file in this issue's description:

```
SQL state [HY000]; error code [1117]; Too many columns; nested exception is java.sql.SQLException: Too many columns
```

Was this the intended 'fix'? (A better error message)
