### ISSUE TITLE
AUTO id columns overwrite specified id value

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4713]
If you specify an ID value for an AUTO id column, the value gets overwritten when you call dataservice.add().

I'd expect the AUTO id only to work when you specify NULL as a value.

**Comment by mswertz** [comment]
This is expected behavior: autoid should be readonly.

**Comment by fdlk** [comment]
It's very annoying to say the least. Who benefits from it?
In MySQL autoIDs allow you to specify the id if you like and will only fill it in if you don't provide it.

**Comment by tommydeboer** [comment]
I tested auto ids when they were introduced and you could use your own ids if you wanted. It was supposed to work like that then. If we didn't change the requirements later on, this is a bug I think.
