### ISSUE TITLE
Bootstrap fileupload library is ancient

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4721]
bootstrap-fileupload.min.js and .css contain an ancient version of the jasny bootstrap fileupload that isn't compatible with jquery 2.

We run into this cause the delete button in SORTA that you use to remove an already selected file is broken. I'm upgrading locally in SORTA now but we should upgrade everywhere or stop using it altogether.

http://www.jasny.net/bootstrap/javascript/#fileinput

**Comment by Mark-de-Haan** [comment]
Phasing it out via reactifying our application sounds like the way to go. React has some nice file upload components

**Comment by dennishendriksen** [comment]
Use the React component Input.js for file inputs which does not depend on the bootstrap-fileupload plugin.
