### ISSUE TITLE
Users get redirected to the login form when they don't have rights to a ref entity

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4723]
#### To reproduce
1. Import _emx_all_datatypes_
2. Give a user permission to _TypeTest_ but not _TypeTestRef_
3. Log in as the user
4. Open _TypeTest_ entity
#### Expected

An error message that explains which permissions are missing on what entities. Data Explorer is not shown.
#### Actual

A permission error briefly appears, but then the user is redirected to the log in screen. The user is not logged out, by the way.

**Comment by dennishendriksen** [comment]
@tommydeboer If you can't reproduce an issue reported by yourself then please close it

**Comment by dennishendriksen** [comment]
@tommydeboer bump

**Comment by tommydeboer** [comment]
I clicked the wrong label when reporting this issue :)

**Comment by Mark-de-Haan** [comment]
No longer an issue in v5.3.0-SNAPSHOT
