### ISSUE TITLE
Typing in an MREF field with int identifiers throws Elasticsearch error

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4734]
#### To reproduce:
1. Import [emx_mref_int_ids.xlsx](https://github.com/molgenis/molgenis/files/204137/emx_mref_int_ids.xlsx)
2. Go to entity *author* in data explorer
3. Edit a row
4. Type some letters in the books mref select field

#### Expected:
Characters are ignored.

#### Actual:
```
Error! Failed to execute phase [query], all shards failed; shardFailures {[DQ5UTzBLQ2qbAfuHP3SpCQ][molgenis][0]: SearchParseException[[molgenis][0]: from[0],size[25]: Parse Failure [Failed to parse source [{"from":0,"size":25,"query":{"bool":{"should":[{"filtered":{"query":{"match_all":{}},"filter":{"term":{"id":"d"}}}},{"match":{"title.ngram":{"query":"d","type":"boolean","analyzer":"default"}}}],"minimum_should_match":"1"}},"sort":[{"id":{"order":"asc","mode":"min"}}]}]]]; nested: NumberFormatException[For input string: "d"]; }
```

After that you can't save your changes anymore:

```
author changes could not be saved. Could not find all referencing ids for books
```

**Comment by dennishendriksen** [comment]
Cannot reproduce in 2.0.0-SNAPSHOT:
![4734_cannotreproduce](https://cloud.githubusercontent.com/assets/2477186/19805106/b6ec5006-9d12-11e6-96d8-2ebf5f3a7df9.png)
