### ISSUE TITLE
As a user, if I try to view my SORTA results I get an error in the console: molgenis.StandardModal is not a constructor

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4737]
## Reproduce
- Use the files and ontology from [here](https://drive.google.com/drive/u/0/folders/0B7qHi41THTs_TmFjSlFhcTlTZkk)
- Import them, configure a user to use SORTA service and Ontology_Ontology
- Create a new task
- Wait till done, then go to result
## Expected

I see my results table
## Observed

I do not have a table
![screen shot 2016-04-05 at 13 49 02](https://cloud.githubusercontent.com/assets/3625016/14280778/2d67d636-fb35-11e5-8ed9-80ac7ee3173d.png)
![screen shot 2016-04-05 at 13 48 57](https://cloud.githubusercontent.com/assets/3625016/14280782/30f70f10-fb35-11e5-9759-89ce850d77e8.png)
## Note

As admin, I get the same error in the console, but i DO have a results table

**Comment by Mark-de-Haan** [comment]
Permission configuration solves it

**Comment by fdlk** [comment]
The js error looks familiar actually.

**Comment by dennishendriksen** [comment]
Fixed by #6720
