### ISSUE TITLE
Result panel fails to reappear after you've deselected all attributes.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4740]
- Open the mapping editor.
- Deselect the attributes in the left column.

Result pane disappears, Script editor is empty.
- Edit the script to something valid.

Expected:
- Result pane pops up again, displaying results

Actual:
- Result pane remains hidden.

**Comment by fdlk** [comment]
Minor issue with workaround, probably best fixed when we reactify.

**Comment by Mark-de-Haan** [comment]
The result column now appears when manually triggering the algorithm validation
Automatic validation has been disabled
