### ISSUE TITLE
Tooltips stay on screen even after switching tab. blocking parts of the screen

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4744]
In the dataexplorer table you "lock" the tooltip on the screen when clicking on a column header, if you click the header again it disappears again.

However if you have a "locked" tooltip on screen and switch to another tab than it will stay on screen without any means to remove it, except surfing back to the datatab and clicking the column again.

Screenshot below to illustrate the problem.
![tooltip_madness](https://cloud.githubusercontent.com/assets/3714029/14309493/1e62ae24-fbdd-11e5-82dd-8e6e87d510a6.png)

expected behaviour: tooltip should hide if the header it belongs to gets hidden.

**Comment by fdlk** [comment]
Doesn't this fall under the fix-witin-15 minute rule?

**Comment by fdlk** [comment]
Checked with @mswertz : Tooltip simply shouldn't lock when you sort a header row.

**Comment by fdlk** [comment]
Related: https://github.com/ryanflorence/react-training/blob/gh-pages/lessons/05-wrapping-dom-libs.md
