### ISSUE TITLE
Command line annotators do not complain if required attributes are missing

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4745]
Try to annotate corner_cases.vcf with command line annotator using omim.

Expected:
annotator complains that gene name is missing

Actual:
annotator adds empty omim annotations

**Comment by mswertz** [comment]
is this indeed required behavior?

**Comment by fdlk** [comment]
@mswertz Discussed with @bartcharbon and we think this is a bug.

**Comment by mswertz** [comment]
this is a bug inside the specific annotator
