### ISSUE TITLE
snpEff attributes have non-ASCII characters in description

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4746]
Which is not strictly forbidden, since after some debate [VCF encoding](https://github.com/samtools/hts-specs/blob/VCFv4.3/VCFv4.3.tex) ended up as UTF-8.
But single quote ascii `'` would work just as well here and looks good in all terminals.

To reproduce, annotate a vcf file with the snpEff commandline annotator.

```
java -jar CmdLineAnnotator.jar -i input/corner_cases.vcf -a snpEff -o test2.vcf -r -v Gene_Name -s annotation_resources/snpEff/snpEff.jar
```

Take a look at the vcf headers and you'll find UTF-8 in there.

![screen shot 2016-04-06 at 11 45 19](https://cloud.githubusercontent.com/assets/1523838/14312563/126ba156-fbed-11e5-94a2-fa7778b8f5da.png)

**Comment by mswertz** [comment]
except incredibly ugly and embarrassing, what is user impact?

**Comment by fdlk** [comment]
@mswertz I don't know. Possibly some downstream tools don't like UTF-8.

**Comment by mswertz** [comment]
does VCF standard say what encoding should be?
