### ISSUE TITLE
Templates not properly applied to the candidate attribute lists.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4750]
When executing the test plan, the algorithm for fasting glucose ends up as 

```
$('GLU').value();
```

Even though there's a template for fasting glucose and the fasting and glucose attributes are listed as candidates.

The BMI template _does_ get used.

**Comment by fdlk** [comment]
Not sure if this is related, but when I ran this for the first time with a non-admin user I got an exception that the user needed WRITE permissions on the TermFrequency entity.

**Comment by Mark-de-Haan** [comment]
Fixed in v5.0.0
