### ISSUE TITLE
Starting entity names with an underscore prevents importing

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4755]
I tried to import a entity _5gpm_test, the import goes well until the last step, this fails with a message that entity 5gpm_test (so without the underscore prefix) does not exist.

**Comment by dennishendriksen** [comment]
Works in 2.0: import [emx_4755.xlsx](https://github.com/molgenis/molgenis/files/624432/emx_4755.xlsx) is successful.
