### ISSUE TITLE
Error notification without logging

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#4757]
I have a javascript file located in molgenis-core-ui/src/main/resources/js, I altered it and something goes wrong, molgenis says: Error! An error occurred. Please contact the administrator. But nothing is logged in the console or eclipse.

**Comment by fdlk** [comment]
Has been like this for ages, but it's very annoying for development. If an exception occurs in an ajax call or in the general javascript, it gets handled by creating an alert, but the actual error isn't getting logged to the console.
