### ISSUE TITLE
CADD annotator cannot write scores in the web interface for multi-allelic sources

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4759]
It writes comma-separated list of scores but the metadata is still decimal.
### Reproduce

Annotate cornercases vcf with cadd.
Annotation will fail.
Look in the log of the annotation job. You'll find get a validation error

> 12:30:17.205 ERROR - Failed
> java.lang.RuntimeException: org.molgenis.data.validation.MolgenisValidationException: Invalid decimal value '.,4.530957,.' for attribute 'CADDABS' of entity 'freerkbug'..Invalid decimal value '.,24.3,.' for attribute 'CADDSCALED' of entity 'freerkbug'.

**Comment by fdlk** [comment]
Unsure how to fix this. We need a way to store lists of decimals.

We can change the data type of the added columns from decimal to string, but then sorting on the annotated cadd score will become alphabetical.

5GPM won't run into this cause they don't have multi-allelic data.
Joeri wants to see the multi-allelic scores in the command-line version.

**Comment by mswertz** [comment]
there is also a story for this right?

**Comment by fdlk** [comment]
@mswertz Depends on how you want to fix it, but the most obvious fix would use a not-yet-existing list-of-primitives data type, yes.

**Comment by Mark-de-Haan** [comment]
[Story](http://wiki.gcc.rug.nl/ticket/2681)
