### ISSUE TITLE
Inconsistence annotators default settings

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4766]
DANN
GONL
HPO
Exac
Fitcon
thousand_genomes

Are missing default settings

**Comment by bartcharbon** [comment]
the molgenis home dir is not determined by the annotators.

Do you mean that there is no default value for the dann settings?

**Comment by jjettenn** [comment]
These annotators are missing values:
DANN
GONL
HPO
Exac
Fitcon
thousand_genomes

Are missing default settings

**Comment by dennishendriksen** [comment]
@jjettenn which version?

**Comment by jjettenn** [comment]
Not relevant anymore
