### ISSUE TITLE
code for missing molgenis.version, but with populated db, is creating a unusable molgenis

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4768]
in the MolgenisVersionService we state:
`LOG.warn("No {} property found in molgenis-server.properties.", MigrationUtils.VERSION_KEY);
            if (isPopulatedDatabase(dataSource))
            {
                LOG.info("Database is populated. Setting molgenis-server.properties to 0. (Molgenis 1.4.3)");
                updateToVersion(0);
            }`

However, versions below 10 are not supported since the JPA module was removed

**Comment by Mark-de-Haan** [comment]
Current version does not have migration, closing
