### ISSUE TITLE
When mapping the biobank disease attribute to the rd-connect Disease entity (mref), the values can be generated 

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#4804]
#### Reproduce
- Upload the test data
  [test_rdconnect_model.xlsx](https://github.com/molgenis/molgenis/files/234797/test_rdconnect_model.xlsx)
  [test_biobank_source_emx.xlsx](https://github.com/molgenis/molgenis/files/234796/test_biobank_source_emx.xlsx)
- Create a mapping project with **rdconnect_Sample** the target and **test_test** as the source
- Open the mapping project and edit the algorithm for the target attribute **Disease**
- Search for the attribute **ORPHA_No** and select it
- Copy/paste the following algorithm in the algorithm editor 
   `var result = [];
  result.push('Orphanet_' + ('ORPHA_No').value().toString());
  result;`
#### Expected

See the converted values in the attribute mapping screen (you might not see directly because of the delay but at lease you shouldn't see any error messages).
#### Observed

Error messages.
#### Probable cause

In the AbstractRepository class, the private method findAllBatched returns a list of entities based on a list of Ids, it calls another method lookup to check if the entity exists in a map (line:123). During the debug model, we witnessed that the Id exist in the map but the method failed to get the entity. It's probably a type mismatch between the Id stored in the map and the Id used to retrieve the entity because the Id is typed as the generic Object instead of String.

**Comment by Mark-de-Haan** [comment]
Can no longer reproduce in v5.3.0-SNAPSHOT
