### ISSUE TITLE
Implement enums in PostgreSQL branch

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4810]
Implement http://www.postgresql.org/docs/9.1/static/datatype-enum.html enums in PostgreSQL. 
Existed in the MySQL branch. The enums are saved as strings in the PostgreSQL database

**Comment by dennishendriksen** [comment]
We decided to use check constraints instead of the enum type, see http://stackoverflow.com/questions/10923213/postgres-enum-data-type-or-check-constraint for the different posibilities to model an enum in PostgreSQL.
