### ISSUE TITLE
Deleting a dataset removes the elastic search mapping, but not the actual stored documents

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4812]
Selenium test server (31) ran out of disk space. 
Manually deleting the index folder opened up 7G of space.

This server is subjected to file imports + deletes multiple times per hour.

**Comment by fdlk** [comment]
Duplicate of #4776 ?

**Comment by Mark-de-Haan** [comment]
Hmm That issue was not fixed properly?

**Comment by fdlk** [comment]
Sounds good to me.

**Comment by Mark-de-Haan** [comment]
Closed together with  #4776

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Which version contains the problem/fix?
