### ISSUE TITLE
When editing attribute mapping for RD-Connect I get a freemarker error

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis#4824]
#### Reproduce
- Import this data 
[Dateset-Template-V19.xlsx](https://github.com/molgenis/molgenis/files/254738/Dateset-Template-V19.xlsx)
- Create a mapping project with rdconnect_Sample as a target
- Add a random source
- Edit mapping for **Hosting Biobank (xref)**

#### Expected
No error

#### Observed
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is freemarker.core._TemplateModelException: Can't convert the date-like value to string because it isn't known if it's a date (no time part), time or date-time value.
The blamed expression:
==> category[attributeName]  [in template "view-attribute-mapping.ftl" at line 103, column 76]

**Comment by fdlk** [comment]
Silly freemarker, why doesn't it show date + time, I suspect that most users will be happier with that than with an exception.
