### ISSUE TITLE
StaticContent plugin escapes, and therefor destroys, javascript

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4828]
#### Reproduce
create static content with javascript

#### Expected
this works

#### Observed
javascript get's escaped and therefor does not work

**Comment by dennishendriksen** [comment]
@bartcharbon which version?

**Comment by bartcharbon** [comment]
javascript actually seems to work fine.
Real problem was:
https://github.com/molgenis/molgenis/issues/3718
since the span that contained the button was removed the javascript was never fired.
