### ISSUE TITLE
FileIngester's EMD select box doesn't find entity if you type the exact name

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4835]
#### Reproduce
1. Go to the automatic imports plugin
2. Add a new import
3. In the Target EntityMetaData field, type "MappingTarget"
#### Expected

The entity MappingTarget is found.
#### Observed

The entity is found at first, but disappears when you complete the name.
![image](https://cloud.githubusercontent.com/assets/5362890/15138496/92396a7c-1690-11e6-99ef-a6303c709d1b.png)
![image](https://cloud.githubusercontent.com/assets/5362890/15138501/9bd95952-1690-11e6-8ecb-ba221b7f9e77.png)

It doesn't happen for all entities.

**Comment by Mark-de-Haan** [comment]
Scheduled jobs now require JSON for targets
