### ISSUE TITLE
Multiple permission issues as a non admin user

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4839]
**When clicking details of a genome browser variant:**
- No _READ_ permission on Freemarker template

**When opening up the annotators**
- No _WRITEMETA_ permission on the selected entity
- No _READ_ permission on AnnotationJob

**Comment by dennishendriksen** [comment]
> When clicking details of a genome browser variant:
> - No READ permission on Freemarker template

Fixed in MOLGENIS 2.0

> When opening up the annotators
> - No WRITEMETA permission on the selected entity
> - No READ permission on AnnotationJob

To improve the usability of annotating as a non-superuser we should have row level security. See this [story in the backlog](http://www.molgenis.org/ticket/3747).
