### ISSUE TITLE
When annotating as a normal user, I do not see the progress bar

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4840]
#### Reproduce
- As normal user, set all permissions on:
    * WRITEMETA for Entity
    * AnnotationJob

- Annotate an entity

#### Expected
I see a progress bar

#### Observed
No progress, and just a silly screen:
![screen shot 2016-05-10 at 11 13 16](https://cloud.githubusercontent.com/assets/3625016/15141464/63cf75cc-16a0-11e6-8906-088e21856f60.png)

**Comment by fdlk** [comment]
What permission is missing?

**Comment by Mark-de-Haan** [comment]
It does not say, not in cataline.out and not in the user interface

**Comment by Mark-de-Haan** [comment]
Can no longer reproduce...
