### ISSUE TITLE
As a Normal user, I am not able to see entity reports without view permissions on the FreemarkerTemplate entity

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4842]
#### Reproduce
- As a normal user, import an EMX or VCF
- Go to the data explorer
#### Expected

I can click on the lens icon to inspect the entity report
#### Observed

I can only edit or delete a row
![screen shot 2016-05-10 at 11 41 05](https://cloud.githubusercontent.com/assets/3625016/15142160/1aef8794-16a4-11e6-881c-1cc5e17885fa.png)

**Comment by mswertz** [comment]
why is this undesirable?

**Comment by marikaris** [comment]
I don't see how this is a bug?

**Comment by Mark-de-Haan** [comment]
Agree that it is not a bug
