### ISSUE TITLE
Opening the tag wizard gives error

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4843]
#### Reproduce
Open the tag wizard as admin or user.

#### Expected
The tag wizard opens.

#### Observed
```{"errors":[{"message":"An error occurred. Please contact the administrator.<br />Message:null"}]}```

**Comment by Mark-de-Haan** [comment]
If a Entity extends and entity that is not in the base package, AND it is alphabetically the first to be chosen, then this bug occurs.
