### ISSUE TITLE
Inspecting a row in the results table in the attribute mapping view throws an error

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4845]
#### Reproduce
1. As a user or admin, create a mapping project and add a source
2. Edit one of the attribute mappings and select an attribute for the algorithm
3. In the results table, click the 
![image](https://cloud.githubusercontent.com/assets/5362890/15145732/a51dfd48-16b7-11e6-89b8-bf7943b07b26.png) icon of one of the rows

#### Expected
Not sure.

#### Observed
```Uncaught TypeError: molgenis.createRsqlQuery is not a function```

**Comment by Mark-de-Haan** [comment]
Fixed
