### ISSUE TITLE
After annotation the dataexplorer becomes unavailable for users

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4861]
#### Reproduce
- create non-superuser
- give permissions on stuff needed to annotate (which does not include MolgenisUser)
- surf to dataexplorer with the user
- select entity to annotate
- annotate
- surf away
- surf back to dataexplorer
#### Expected
- I see the dataexplorer
#### Observed
- I get a login dialog, because the first, preselected, entity in the explorer is the "AnnotationExecutionLog" which contains an xref to the molgenisUser on which I do not have permissions.
#### Note:
- One could argue that it works as intended, however it's odd from a user point of view, that I initially can view the explorer and after annotation this suddenly stops working.
- when reproducing, please consider that the issue will not show if a entity which alphabetically precedes the "AnnotationExecutionLog" is available for the user, the issue does not occur.

**Comment by Mark-de-Haan** [comment]
No longer an issue since AnnotationExecutionLog table no longer exists.
