### ISSUE TITLE
When annotating with snpEff as a user, I cannot see the results until after a restart

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4862]
#### Reproduce
- annotate any suitable entity with snpEff
- try to view the results: [entityname]_EFFECTS
#### Expected
- I can see the results
#### Observed
- results are not in the data-explorer dropdown, when specified in the URL(?entity=entityname_EFFECTS) I get a permission error.
- after restart they are available
#### Note
- This might be by design? Permissions are updated on restart only? but then again, how does the importer do this?

**Comment by fdlk** [comment]
Job fails completely in 2.0rc4 if I run SnpEff as a user.

**Comment by fdlk** [comment]
I think perhaps in 1.21.1 the underlying problem is that permissions are only added to your session when you log in.

**Comment by Mark-de-Haan** [comment]
caused by #4080
