### ISSUE TITLE
Range filter is not created when no changes are made. It is possible to push the Apply button.

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4869]
#### Reproduce

MOLGENIS 1.21
Upload TypeTest
Click on range filter and click Apply
#### Expected

To see the filter
#### Observed

Filter is not made

N.B. playing with the scroll and putting it into the original value will result in making the filter.

**Comment by Mark-de-Haan** [comment]
Can not reproduce in v 5.3.0-SNAPSHOT
