### ISSUE TITLE
Missing ID attribute is not caught during validation

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#4894]
#### Reproduce
1. Create a new EMX file with an entity without an ID attribute
2. Upload the EMX file to MOLGENIS
3. The file passes validation but fails during upload with a message that the ID attribute is required
#### Expected

The validation fails
#### Observed

Validation passes, but the upload fails during the last step.

**Comment by dennishendriksen** [comment]
Fixed in 2.0: importing [emx_4894.xlsx](https://github.com/molgenis/molgenis/files/624423/emx_4894.xlsx) resulting in the following error ```Error! Your import failed: Entity [test_book] is missing required ID attribute```
