### ISSUE TITLE
Internationalisation is broken for xmref and mref labels

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4910]
#### Reproduce
- Import the test questionnaire in molgenis-questionnaire/src/test/resources
- Go the the dataexplorer and select Test questionnaire
- Add a new Row and select the Gender mref from the tree

#### Expected
The labels in the **Genders?** column should be the one from the selected language

#### Observed
The labels are always Dutch, even if you switch languages

Note: The Table component uses the label attribute to determine which label to show. So if Label (en) is your label attribute in the EMX, then only the English labels will be shown for xref/mref fields

**Comment by fdlk** [comment]
Still not quite okay when I open the form, I think:
<img width="725" alt="screen shot 2016-06-03 at 21 09 00" src="https://cloud.githubusercontent.com/assets/1523838/15790050/82b9a81c-29cf-11e6-8334-c831e4ef05b5.png">

**Comment by fdlk** [comment]
I take it all back! Works fine.
