### ISSUE TITLE
SORTA: When downloading the results items with no match not reported as N/A

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis#4929]
#### Reproduce
- Start a new SORTA task (molgenis19.gcc.rug.nl)
- Select an ontology for annotation (I used _Orphanet_1_3_)
- Add some values to match, for example:

> Name
> Cancer
> Diabetes 
- Select _'match'_
- After finishing go to the results
- Select manual match for each input term
- Select _'No  match'_
- Download the results
#### Expected

Now in the _'total number of matched items'_ for each item with no match the best candidate is 'N/A'.
In the downloaded results you would also expect 'N/A'.
#### Observed

Instead of N/A, a different value for the OntologyTermName (in my case _'Hypotonia - cystinuria type 1'_)

**Comment by dennishendriksen** [comment]
Fixed by #6720
