### ISSUE TITLE
Combination of lots of TEXT attributes and a mref results in "out of sort memory"

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4942]
#### Reproduce
add an mref column to the 5GPM template
load the data
op dataexplorer
select the entity

#### Expected
dataexplorer shows data

#### Observed
Big exception, summary: error code [1038]; Out of sort memory

**Comment by fdlk** [comment]
Is this on localhost? Need to set the sort memory in my.cnf. I think this is a bug in the documentation, shall we move it there?

**Comment by fdlk** [comment]
Introduced when fixing #4596 see comment there. Works fine on our vms

**Comment by dennishendriksen** [comment]
Solved in 2.0-RC
