### ISSUE TITLE
Settings filter is broken (again!)

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4949]
#### Reproduce
Log in as admin, go to the settings plugin, type a string into the search box

#### Expected
Settings options get filtered

#### Observed
Error message is displayed:
> Query with operator [LIKE] and data type [TEXT] not supported

Broken in master (tested on molgenis01)
Oddly enough: Works fine on 1.21.1 (tested on molgenis09)

**Comment by fdlk** [comment]
Introduced with the custom javascript fix?

**Comment by Mark-de-Haan** [comment]
No this is a datatype thing, not a js issue. Metadata changed?

On 6 June 2016 at 14:03, Fleur Kelpin <notifications@github.com> wrote:

> Introduced with the custom javascript fix?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/molgenis/molgenis/issues/4949#issuecomment-223939712>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADdQOFPtHRC0tiNBJrUD8lFi1FhL_48aks5qJAycgaJpZM4Iu0uF>
> .
>



-- 
Mark de Haan
Genomics Coordination Centre
Genetics Department
University Medical Centre Groningen

**Comment by fdlk** [comment]
Exactly! The metadata of the app settings changed for the javascript custom header feature

**Comment by Mark-de-Haan** [comment]
Yes but only a getter and setter were added... Existing types were not changed

**Comment by Mark-de-Haan** [comment]
The EntitySelectBox has a switch for the LIKE operator as well. In some cases the operator is set to EQUALS, but not for text. EntitySelectBox.js line: 123

**Comment by fdlk** [comment]
We think it's not dependent on the version, but breaks when you add languages!
