### ISSUE TITLE
Updating Diseases entity in BBMRI catalogue not possible - duplicate value error

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis#4953]
#### Reproduce
https://catalogue.bbmri.nl
[bbmri_catalogue_diseases_example.xlsx](https://github.com/molgenis/molgenis/files/304172/bbmri_catalogue_diseases_example.xlsx)

- Import _bbmri_catalogue_diseases_example.xlsx_
- Select _Add entities / update existing_

According to David the same problem occurs on the acceptation server (molgenis49), I can't login here.
I can't reproduce the problem locally. You can find the model on google drive: Projects > BBMRI - Catalogus 2.0 > catalogue-data > _bbmri-nl-final-v2-1.xlsx_

#### Expected
Diseases entity (_bbmri_nl_disease_types_) is updated with the ICD 10 codes.

#### Observed
Importer gives duplicate value error:
`Duplicate value 'urn:miriam:icd:G35' for unique attribute 'id' from entity 'bbmri_nl_disease_types' (entity 2)`
When deleting the value that fails, it will give the same error for the next value.

In the Model Registry all the attributes for this entity (and all the other entities in package _bbmri_nl_ that extend the _Ontology Term_ entity) are duplicated, it seems this is part of the problem.

**Comment by fdlk** [comment]
It's not so much a bug as mucked up metadata administration on the server due to a failed migration in the past.

**Comment by dennishendriksen** [comment]
Importing the data and add/updating with the diseases file completes successfully in 2.0-RC
