### ISSUE TITLE
ID-Card Indexer uses the system locale for the date format

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#4958]
#### Reproduce
- Setup your system with Dutch as your language
- Run molgenis
- Go to Plugins -> ID-Card
- Press on the Reindex button

#### Expected
ID-Card is indexed

#### Observed
I get an exception: java.io.IOException: java.text.ParseException: Unparseable date: "Mon Jan 12 19:37:12 GMT 2015"

**Comment by fdlk** [comment]
Fixed in #4957
