### ISSUE TITLE
EMX importer hangs/crashes on Excel files with many rows

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4961]
Importing a file with 1x392.000 rows will cause the server to constantly garbage collect because the excel sheets are stored in memory.

Importer should warn about this, and suggest that importing data as a zipped .csv would be better

**Comment by fdlk** [comment]
For the data sheets, we should use the eventmodel API to readonly stream through the data sheet rows. See https://poi.apache.org/spreadsheet/

**Comment by fdlk** [comment]
... but the importer is not particularly streaming either.

**Comment by dennishendriksen** [comment]
Would using xlsb instead of xlsx help?

**Comment by dennishendriksen** [comment]
Cannot reproduce with [392000rows1col.zip](https://github.com/molgenis/molgenis/files/946448/392000rows1col.zip). The extracted xlsx imports successfully.
