### ISSUE TITLE
Repository.stream(Fetch) uses pagination

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4963]
#### Reproduce
Reindex a large repository

#### Expected
Single select gets streamed to the caller, result set gets closed upon timeout or when entire stream is read.

#### Observed
Reindex gets increasingly slow with repository size because PostgresqlRepository returns a BatchingIterable that uses OFFSET / LIMIT.

The JdbcTemplate does not support querying for a Stream, a couple of folks have tried to implement it separately.

**Comment by dennishendriksen** [comment]
```Repository.forEachBatched``` was introduced to resolve this issue, fixed in 2.0-RC.
