### ISSUE TITLE
URL validation fails on valid URLs

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#4965]
#### Reproduce
1. Create a new record in the BBMRI-NL catalogue
2. Use the following URL for the website http://www.parelsnoer.org/page/nl/Parels?mod[Parelsnoer_Module_Pearl][n]=17
#### Expected

The record is saved
#### Observed

The record is not saved and you get a message that the URL isn't valid

**Comment by dennishendriksen** [comment]
The observed behavior is correct because square brackets are not allowed in the URI syntax:
http://stackoverflow.com/a/1016737
