### ISSUE TITLE
VCF import fails on duplicate chrom pos ref alt

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4994]
#### Reproduce
- try to load the vcf from clinvar

#### Expected
- it loads

#### Observed
- it fails because of 2 lines with the same CHROM POS REF ALT:
1	53676583	rs397509431	CAG	C
1	53676583	rs398123153	CAG	C

Is this allowed according to the VCF specs? in any case I think we want to support loading the clinvar VCF

**Comment by dennishendriksen** [comment]
> @npklein AFAIK in the official standard it is not allowed to have multiple variants with same #CHROM/#POS but I have seen it used (for example samtools mpileup output). The REF/ALT for these were different though. I don't know if it's common as I've not used VCFs from many different tools.

**Comment by dennishendriksen** [comment]
> @PatrickDeelen 
I think Niek is right about the standard not allowing it but it does happen. However, then you should have different REF or ALT alleles otherwise it really does not make sense. I would use the ref and alt alleles if you want to define an identifier and simply fail on files with exactly the same variant twice.

> I do think you should be hesitant with exposing such an identifier to the outside world. If there is no RS ID I think it is generally best to follow the VCF specification not to have an ID.

**Comment by PatrickDeelen** [comment]
Perhaps in such a case it is best to write a clinvar clean up script and not to over complicate the VCF parser.

**Comment by dennishendriksen** [comment]
Conclusion is that this is not a bug, but a feature request, hence http://www.molgenis.org/ticket/4437. Note that MOLGENIS up to version 1.21.4 unintentionally imported such files.
