### ISSUE TITLE
VCF handling has annoying SAMPLES_ENTITIES column

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#5005]
When importing VCF, a new column is created that is interfering with data browsing and exporting. 

Exhibit 1, data explorer. New column that shows technical information not uploaded by the user.
![screen shot 2016-06-29 at 4 04 38 pm](https://cloud.githubusercontent.com/assets/82420/16455078/66175f12-3e13-11e6-8367-3c9d64786303.png)

Exhibit 2, VCF writer. After running the GAVIN app on a multi-sample VCF, a new INFO field is created with NULL values:

```
SAMPLES_ENTITIES=null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
```

**Comment by dennishendriksen** [comment]
Discussed with Joeri. Cannot reproduce, probably solved.
