### ISSUE TITLE
Error executing JavaScript script with alert

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5006]
#### Reproduce

Make a simple JavaScript script. 
![screen shot 2016-06-30 at 09 14 07](https://cloud.githubusercontent.com/assets/10075439/16479831/0c4d355c-3ea3-11e6-8d49-feb33b58ad55.png)
Click run
500 error: alert not defined!
#### Expected

An alert with Hi! in it
#### Observed

![screen shot 2016-06-30 at 09 22 44](https://cloud.githubusercontent.com/assets/10075439/16480033/4240ff3a-3ea4-11e6-9700-241a4df9f237.png)

**Comment by dennishendriksen** [comment]
This is not a bug:
You are trying to call the JavaScript ```alert``` function which is not part of ECMAScript 5. The ```window``` object with ```alert``` function that you are trying to use is supported as Web API by most browsers.
