### ISSUE TITLE
Can't create filter for XREF/MREFs with integer ID in data item selection of data explorer

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5015]
#### Reproduce
1. Upload this file:
https://drive.google.com/open?id=0B8iNw4kI1MA2VHRhcl84cU1Ec0E
2. Select entity 'cohorts' in data explorer
3. Click on 'imaging data' in data item selection
4. Type 'Brain' in popup

#### Expected
A list of items filtered by the word 'Brain'

#### Observed
Error! Illegal data type [INT] for operator [LIKE]

**Comment by fdlk** [comment]
Happens cause the xrefmref search produces a query `id LIKE 'Brain'` but the id is of INT type.

**Comment by fdlk** [comment]
Going to fix it as follows: `function createQuery(lookupAttributeNames, terms, operator, search)` signature will change to one where you provide it with lookupAttributes, not just names and the operator will be changed from 'LIKE' to a boolean that indicates if the search should be exact or approximate.

**Comment by fdlk** [comment]
BUT! the v1 REST API doesn't supply the client with this information for the ref entity. It only delivers a list of attributes and the hrefs where their metadata can be retrieved.

**Comment by fdlk** [comment]
Fixed this bug, but now it fails on the next error! When you type a non-integer value, the query throws a numberformatexception. The EntitySelectBox suffers from the same error.

**Comment by fdlk** [comment]
Same bug existed in the EntitySelectBox as #3827

**Comment by fdlk** [comment]
Fixed the NumberFormatException too, but now running into the next problem, I suspect that you actually want to filter on the organName property of the ImagingData mref (Which is not supported).

**Comment by fdlk** [comment]
The NumberFormatException still does occur in the EntitySelectBox, filing a new issue for that.
