### ISSUE TITLE
Can't select wizard in data item filters of data explorer if the entity has an attribute with fieldType FILE.

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5016]
#### Reproduce
1. Upload this file: 
https://drive.google.com/open?id=0B8iNw4kI1MA2VHRhcl84cU1Ec0E
2. Go to entity imaging_data in data explorer
3. Click on 'wizard' in data item filters

#### Expected
No error...

#### Observed
Error! An error occurred. Please contact the administrator.
Uncaught Unsupported data type: FILE

**Comment by fdlk** [comment]
What's the expected behavior, is it okay if FILE type attributes are skipped in the wizard?

**Comment by fdlk** [comment]
Same happens if I explicitly open the filter wizard for the image attribute.
