### ISSUE TITLE
Can't expand empty reference attribute fields if behind an expanded MREF

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5017]
#### Note
When you expand an mref in the datatable that contains a reference type like file or xref, trying to expand that second reference fails if it has an empty value

#### Reproduce
1. Upload this file: 
https://drive.google.com/open?id=0B8iNw4kI1MA2VHRhcl84cU1Ec0E
2. Go to entity 'cohorts' in data explorer
3. Expand imaging data
4. Expand image

#### Expected
The contents of 'image' according to the entity FileMeta

#### Observed
Error! An error occurred. Please contact the administrator.
Uncaught TypeError: Cannot read property 'filename' of undefined

**Comment by Mark-de-Haan** [comment]
@fdlk I suspect this to be linked with #5016 
The File type in in the referenced entity is showing weird behavior

**Comment by fdlk** [comment]
@Mark-de-Haan I think this is different, this simply used to work.
