### ISSUE TITLE
Filtering on a value in data explorer does not give exact matches

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5018]
#### Reproduce
1. Upload this file: 
https://drive.google.com/open?id=0B8iNw4kI1MA2VHRhcl84cU1Ec0E
2. Go to entity cohorts in data explorer
3. Filter on cohorts, type 'smart-maastricht'

#### Expected
No hits.

#### Observed
Three hits: 
-SMART
-Maastricht Study
-SMART-MR Study

**Comment by fdlk** [comment]
I believe this is currently working as intended.
Story to configure search behavior per attribute sits in the trac story tracker as http://www.molgenis.org/ticket/4128
