### ISSUE TITLE
Lookup attribute, label attribute is not inherited by entities that implement an abstract entity

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5024]
#### Reproduce
1.  Create an abstract entity OntologyTerm with an attribute code that is a lookup attribute and an attribute term that is both a lookup attribute and a label attribute
2. Create an entity Disease that extends OntologyTerm
3. Create an entity Sample that has an XREF attribute disease that refers to the disease entity
4. Upload your model

#### Expected
I can filter on disease in the sample entity

#### Observed
1. When I try to set a filter on disease I get an error 'lookup attribute not specified'
2. In the model registry my Disease entity does not have the lookup attribute or label attribute set

Issue reproduced on 1.21.1

**Comment by tommydeboer** [comment]
A server restart seems to cause it.
