### ISSUE TITLE
Source attribute in the target entity of a mapping project should be hidden

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5026]
#### Reproduce
1. Create a new mapping project and map to an existing entity
2. Go to the data explorer and look at the entity
#### Expected
The entity looks exactly as it was defined.

#### Observed
There is a visible source attribute added to the entity.

**Comment by fdlk** [comment]
This is working as specified, the idea was that if you map multiple sources to a single target, you want to know which source resulted in which result row.

**Comment by djvanenckevort** [comment]
Ok, then it is a feature request to make this an option.
