### ISSUE TITLE
When setting lookupAttribute as false, it is still present in the dropdown menu

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5028]
#### Reproduce
1. Upload this file: https://drive.google.com/open?id=0B8iNw4kI1MA2SlVybjc4M05sck0
2. Go to entity 'cohorts' in data explorer
3. Click on '+' button
4. Click on the field 'Imaging data' 

#### Expected
ID should not be present in the dropdown menu.

#### Observed
ID is still present in the dropdown menu.

**Comment by fdlk** [comment]
The idAttribute is always also a lookupAttribute.

**Comment by fdlk** [comment]
Talked with Marieke, she wants to be able to have an idAttribute that is not also a lookupAttribute.

**Comment by fdlk** [comment]
Proposed:

lookupAttribute in EMX: 
* true/false to indicate that the attribute should appear in the xref/mref search dropdown in the dataexplorer.
* Default value is false. 
* An entity can have multiple lookupAttributes, all of which will be displayed in the search dropdown and can be used to search.
* An entity inherits all lookupAttributes of the entity it extends, if present.
* If no lookupAttribute is specified, the EntityMetaData and the REST service will return the empty list, but select dropdowns will use the idAttribute instead (even if it's hidden)

**Comment by fdlk** [comment]
I think I've fixed the issue, now working on a test file to test the different cases.

**Comment by fdlk** [comment]
[test-lookupAttribute.xlsx](https://github.com/molgenis/molgenis/files/411481/test-lookupAttribute.xlsx)

**Comment by Mark-de-Haan** [comment]
@fdlk With cohort file I get the following error:
Error! PreparedStatementCallback; bad SQL grammar [SELECT this.`id`, this.`organ_name`, (SELECT GROUP_CONCAT(DISTINCT(`modality_name`.`modality_name`) ORDER BY `modality_name`.`order`) FROM `imaging_data_modality_name` AS `modality_name` WHERE (this.`id` = `modality_name`.`id`) ) AS `modality_name`, (SELECT GROUP_CONCAT(DISTINCT(`MRI_sequence`.`MRI_sequence`) ORDER BY `MRI_sequence`.`order`) FROM `imaging_data_MRI_sequence` AS `MRI_sequence` WHERE (this.`id` = `MRI_sequence`.`id`) ) AS `MRI_sequence`, this.`counts`, this.`dicom_image` FROM `imaging_data` AS this GROUP BY this.`id`, this.`organ_name`, this.`counts`, this.`dicom_image` ORDER BY `label` ASC LIMIT 25]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'label' in 'order clause'
