### ISSUE TITLE
Filtering is not working correctly for hyperlinks

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5042]
#### Reproduce
1. Go to the BBMRI catalogue acceptance server
2. Click organisational structure, website to filter
3. Enter a URL

#### Expected
Only those collections with a matching URL are shown

#### Observed
All studies with a URL are shown.

Tested with build 1.21.1-BBMRI-NL.

**Comment by fdlk** [comment]
The most diversely re-re-reported issue in molgenis! We have a story to fix this, http://www.molgenis.org/ticket/4128

> As data set owner I can set in metadata per attribute indexing settings so users find what they expect when searching

Until then we use one single tokenizer for all attributes and it separates on non-letter tokens.
