### ISSUE TITLE
View button is not available on a data set if I have anonymous access

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5059]
#### Reproduce
Setup a dataset to have anonymous access to the data

#### Expected
There is a view button (magnifying glass) that when clicked gives a dialog with the data of that record.

#### Observed
There is no view button

Tested with BBMRI-NL app version 1.

**Comment by Mark-de-Haan** [comment]
The user also needs view permissions on the FreemarkerTemplate entity

**Comment by djvanenckevort** [comment]
Works indeed. Issue can be closed.
