### ISSUE TITLE
Wrong character encoding

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5065]
#### Reproduce
1. Upload this file: https://drive.google.com/open?id=0B8iNw4kI1MA2dkZ4dk1XbWl0djg
2. Go to entity 'test' in data explorer

#### Expected
These values:
Laboratoř experimentální medicíny při Dětské
Ondřej
Fingerladův

#### Observed
These values:
Laborato? experimentální medicíny p?i D?tské
Ond?ej
Fingerlad?v

**Comment by marieke-bijlsma** [comment]
Wrong encoding of the data itself, not a bug in Molgenis.

**Comment by fdlk** [comment]
@marieke-bijlsma of course not! :)
