### ISSUE TITLE
Cannot delete script on PROOF acceptance server

### ISSUE THREAD

**Issue by EdithAdriaanse** [molgenis/molgenis#5092]
#### Reproduce
- login to https://proof-acc.bbmri.nl (Edith knows name and pw)
- try to delete the script "entiteit iet.." using the delete button.
#### Expected
- script can be deleted
- Script can only be deleted in the entity itself, not on the "Scripts" page.
#### Observed
- script cannot be deleted

**Comment by Mark-de-Haan** [comment]
Closing issue as it is no longer reproducible
