### ISSUE TITLE
GAVIN plugin crash

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5124]
> Fix GAVIN plugin crash. (NPE on VcfAttributes when importing vcf)

**Comment by fdlk** [comment]
GavinJobFactory calls `new CmdLineAnnotator()` but CmdLineAnnotator has `@Autowired` fields. Hence the NPE.

**Comment by bartcharbon** [comment]
this was fixed some time ago, I'll check if it still works on the current master

**Comment by bartcharbon** [comment]
Checked in current master, fixed different bugs #5421 and #5422, then Gavin works fine.
