### ISSUE TITLE
On http://molgenis.github.io/ I have to click twice to search 

### ISSUE THREAD

**Issue by npklein** [molgenis/molgenis#5128]
#### Reproduce
Go to http://molgenis.github.io/ and click on the searchbox in the upper right corner

#### Expected
After clicking on the search box I can directly type in my query 

#### Observed
It opens up a box to type my search in but I have to click on that box to be able to type

**Comment by fdlk** [comment]
Could you file this on the https://github.com/molgenis/molgenis.org issue tracker instead?
(Also I'm not entirely sure if this behavior comes with harp or is hand-crafted by one of us)
