### ISSUE TITLE
EMX parser gets confused parsing data sheets for entities that got assigned to non-base package

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5156]
#### Reproduce

Upload [test-lookupAttribute.xlsx](https://github.com/molgenis/molgenis/files/412848/test-lookupAttribute.xlsx). Choose package org_molgenis_test as the target package for the unqualified entities.
#### Expected

File imports correctly.
#### Observed

EMX importer cannot find the ID attribute for the RefX entities when importing the data sheets and refuses to import.

If you choose the base package, the file imports correctly.
If you remove the data sheets, the file imports correctly to any target package.

**Comment by dennishendriksen** [comment]
Cannot reproduce with the latest molgenis/master code, entities like 'Ref1' have been added to the org_molgenis_test package.

**Comment by fdlk** [comment]
@dennishendriksen Yup, I can confirm that this now works!
