### ISSUE TITLE
Form entity select box misses entities

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5186]
#### Reproduce
- Import TypeTest
- Go to the attributes table in the dataexplorer
- Search for xstring, and edit the xstring attribute
- Click in the dropdown for RefEntity selection

#### Expected
If I scroll down I can find TypeTestRef
If I search TypeTestRef I can find it

#### Observed
TypeTestRef is not present, neither are any other imported entities

Edit: MolgenisUser can also not be found

**Comment by dennishendriksen** [comment]
The executed query ```Fetching [sys_md_entities] data for query [rules=['label' LIKE 'TypeTest'], pageSize=25, sort=Sort [orders=[Order [attr=label, direction=ASC]]]]``` queries the label field, which is empty for the TypeTest data set.
