### ISSUE TITLE
Unclear error message deleting referenced entity

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5187]
#### Reproduce
- Import TypeTest
- Go to TypeTestRef in the data explorer
- Delete the first row, ref1

#### Expected
Error message: Deleting this row is not allowed because it is being referenced by other entities [org_molgenis_test_TypeTest, ...]

#### Observed
Error! Unknown xref value 'ref1' for attribute 'value' of entity 'org_molgenis_test_TypeTest'.

**Comment by fdlk** [comment]
Tried on molgenis09, message used to be 
> Error! Cannot delete entity because there are other entities referencing it. Delete these first.
