### ISSUE TITLE
Transactionality of PostgreSqlRepository is incorrect in places

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5189]
Code inspection:
- findAll(Query) creates a Stream<Entity> within a ReadOnly transaction but the actual queries get executed when the stream is consumed.
- Plenty FIXMEs for commented out @Transactional annotations on inserts, updates and deletions
- Batched updates should probably execute in one single transaction.

**Comment by dennishendriksen** [comment]
How about removing read-only transactions and creating a TransactionalRepository that can be decorate another repository?
