### ISSUE TITLE
The molgenis.addAll(entityName, dataFrame) function in R is extremely slow

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5223]
#### Reproduce
- import [model_issue_5223.xlsx](https://github.com/molgenis/molgenis/files/596995/model_issue_5223.xlsx)

- Extract the R script and open it in Rstudio [rscript_issue_5223.R.zip](https://github.com/molgenis/molgenis/files/597025/rscript_issue_5223.R.zip)

- Edit the URL for fetching the molgenis.R depending on which server you are reproducing the issue

- Run the script

#### Expected
Speed is similar to importer or Rest API and it will take a few seconds

#### Observed
It inserts about 5 rows / second

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Can you add an example dataset and the accompanying R script that reproduces the issue?
