### ISSUE TITLE
Columns tooltip stays open in the Data Explorer

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5233]
#### Reproduce
Hover the column name and push the sort option.

#### Expected
After leaving the region the tooltip should be disappeared

#### Observed
Tooltips stays on

![screen shot 2016-08-31 at 5 29 35 pm](https://cloud.githubusercontent.com/assets/5586255/18142848/a919512a-6fbf-11e6-98c7-1d3001e2ce82.png)

**Comment by bartcharbon** [comment]
Duplicate of #4744
