### ISSUE TITLE
snpEff annotator creates an empty compound attribute called 'snpEff' in the EFFECTS entity

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5241]
#### Reproduce

Upload vcf.
Annotate with snpEff.
Open the effects entity
#### Expected

Effects entity contains the effect attributes
#### Observed

Effects entity also contains an empty compound attribute called 'snpEff'

**Comment by dennishendriksen** [comment]
Cannot reproduce in 1.21.5 with the VCF in this zip: [test.zip](https://github.com/molgenis/molgenis/files/596836/test.zip). Tried to reproduce in 2.0-RC with the same VCF, but ran into issue #5565

**Comment by dennishendriksen** [comment]
Fixed by #5565
