### ISSUE TITLE
download of advanced example of EMX file on molgenis.github.io produces 404

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5244]
#### Reproduce

Go to http://molgenis.github.io/documentation/ref-emx#1advancedexample
Click on download
#### Expected

The file downloads
#### Observed

A 404 shows

**Comment by dennishendriksen** [comment]
@marikaris did you resolve this issue yourself? If so, please close it.

**Comment by marikaris** [comment]
I did not fix this, but the last time I checked, it worked, so someone fixed it, I will close

________________________________
Van: Dennis Hendriksen <notifications@github.com>
Verzonden: woensdag 26 oktober 2016 11:06:42
Aan: molgenis/molgenis
CC: marikaris; Mention
Onderwerp: Re: [molgenis/molgenis] download of advanced example of EMX file on molgenis.github.io produces 404 (#5244)


@marikaris<https://github.com/marikaris> did you resolve this issue yourself? If so, please close it.

-
