### ISSUE TITLE
Create specific immutable classes for QueryRules, to validate values properly.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5248]
The QueryRule class combines all rules into one generic field, operator, value  structure.
This is nice when deserializing QueryRules sent in a REST call.
But it has as a severe disadvantage that values aren't sanity checked at compile time.
This can lead to unexpected bugs at runtime.

For instance:
- an IN query rule should have a SET of simple type values.
- a RANGE query rule should have two comparable from and to fields.
- an EQUALS query rule should have a single simple type value

Also, all QueryRule fields are mutable, they should be immutable instead.
Let's create specific subclasses for each operator that have compile time values that match the operator.

**Comment by mswertz** [comment]
has been moved to a feature request story http://www.molgenis.org/ticket/4725
