### ISSUE TITLE
Other Data explorer filters are ignored when using filters for MREF types

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5254]
#### Reproduce
Import TypeTest
Go to dataexplorer
Set filter xxref_unique : ref5
Set filter xcategoricalmref: ref1, ref2, ref3

#### Expected
I only see the datarows for xxref_unique = ref5

#### Observed
The only filter that is applied is the xcategoricalmref filter, my other filter(s) are ignored

**Comment by dennishendriksen** [comment]
The RSQL query send to the server is incorrect. The filters:
```
xxref_unique: ('label1')
xmref_value: ('label2' or 'label3')
```
result in the following RSQL string:
```
((xxref_unique=='ref1';xmref_value=='ref2'),xmref_value=='ref3')
```
