### ISSUE TITLE
An error in an entity report causes the previous one to be shown

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5258]
#### Reproduce

1 Create a custom report for an entity, make sure it is faulty and won't show
2 Select any other entity 
3 click the entity report to show the default report
4 Select the entity you create the custom report for
5 Click the report button
#### Expected

error on screen and no report showing
#### Observed

error on screen, but the report opened in step 3 shows again.

**Comment by Mark-de-Haan** [comment]
Wontfix: Issue will be addressed in [Dataexplorer 2.0](http://wiki.gcc.rug.nl/ticket/5288)
