### ISSUE TITLE
Cache L3: ERROR Recursive load

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5277]
#### Reproduce
Ask for the next query from cache L3: "rules=['Country' = 'NL0', OR, 'Country' = 'NL1'], pageSize=10, sort=Sort [orders=[Order [attr=Country, direction=ASC]]]"

#### Expected
An answer.

#### Observed
Caused by: java.lang.IllegalStateException: ERROR Recursive load of: rules=['Country' = 'NL0', OR, 'Country' = 'NL1'], pageSize=10, sort=Sort [orders=[Order [attr=Country, direction=ASC]]]

**Comment by fdlk** [comment]
We figured out why this happened. You shouldn't feed a fully decorated repository to the L3Cache to load from. Cause then it'll hit the L3 decorator when loading and disappears up in a recursive puff of logic.
