### ISSUE TITLE
SORTA not displaying jobs

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5284]
#### Reproduce

Put in a new task and run
<img width="888" alt="screen shot 2016-09-26 at 11 21 09" src="https://cloud.githubusercontent.com/assets/10075439/18829221/9579168e-83db-11e6-8bdb-7839d767ceb8.png">
Sorta says:
<img width="927" alt="screen shot 2016-09-26 at 11 21 22" src="https://cloud.githubusercontent.com/assets/10075439/18829232/a6c45b06-83db-11e6-84db-6556817173ae.png">
The output is however in the job table (also in the output table), so when I copy the id of the job
<img width="882" alt="screen shot 2016-09-26 at 11 22 25" src="https://cloud.githubusercontent.com/assets/10075439/18829231/a6c3508a-83db-11e6-914c-ec524b906ba8.png">
and past this id in the url of the page where the job should be shown, it shows
<img width="1119" alt="screen shot 2016-09-26 at 11 22 35" src="https://cloud.githubusercontent.com/assets/10075439/18829233/a6c74eec-83db-11e6-9ca6-4144eaa192bc.png">
#### Expected

When running a job, getting the results returned instead of "no jobs found"
#### Observed

I get a page with "no jobs found"

**Comment by dennishendriksen** [comment]
Fixed by #6720
