### ISSUE TITLE
Books of author are not shown correctly in the entity viewer

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5295]
#### Reproduce
Add "onetomanyentities" to your code.

Via the data-explorer
- Add two books: abook, xbook
- Add author with these two books
- Click on the magnifying glass of author

#### Expected

id	AAAACV3QSNOOUBTAQ5JKJGQAAE	label	author_book	books	[abook, xbook]

#### Observed

id	AAAACV3QSNOOUBTAQ5JKJGQAAE	label	author_book	books	[sys_Book{id=AAAACV3QSKE2EBTAQ5JKJGQAAI,<lazy attributes not loaded>}, sys_Book{id=AAAACV3QSLCL2BTAQ5JKJGQAAI,<lazy attributes not loaded>}]

**Comment by dennishendriksen** [comment]
Cannot reproduce:

![5295_cannotreproduce](https://cloud.githubusercontent.com/assets/2477186/19758377/103f810a-9c28-11e6-9205-d205ee1c7510.png)

Fixed in molgenis/molgenis#5303
