### ISSUE TITLE
Add attribute visible expression to attributes that are not allowed

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5296]
#### Reproduce

Try to update Order by in author (attributes)
#### Expected

Order by not available
Disable one-to-many functionality in the attributes forms that not supposed to work (based on requirements) 
#### Observed

Can type into Order by (Then I gat a wrong validation message: Order expression that defines entity collection order of a onetomany attribute (e.g. "attr0", "attr0,ASC", "attr0,DESC" or "attr0,ASC;attr1,DESC"
Please enter a valid value.)
### Comment

We should make a story out of it.

**Comment by Mark-de-Haan** [comment]
Is changing the order allowed? Then we should fix the ability to change it
Is not allowed? Set the attribute to visible=false in the metadata

**Comment by jjettenn** [comment]
I have tested the order by functionality and it works
