### ISSUE TITLE
Sort order not updated after changing the label of referenced attribute

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5298]
#### Reproduce
Reproduce using the Author/Book entities with sort order ASC on books attribute:
- Add two books: abook, xbook
- Add author with these two books
- Change label of xbook to axbook

#### Expected
Order is ASC

#### Observed
Order is updated when removing one of the books from author, and then re-adding it.

**Comment by dennishendriksen** [comment]
Cannot reproduce. Problem was most likely solved during the re-implementation of the one-to-many data type.
