### ISSUE TITLE
Error when sorting on ontology (string value) in molgenis52

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5316]
#### Reproduce

When i want to sort on ontology in the disease types table on molgenis 52 I get an error 
![screen shot 2016-10-06 at 13 56 17](https://cloud.githubusercontent.com/assets/10075439/19151417/da04da38-8bcc-11e6-86d5-21b5f4fd1d23.png)
#### Expected

I expect my column to be sorted
#### Observed

The column does not sort and I get an error

**Comment by Mark-de-Haan** [comment]
No longer an issue in v5.3.0-SNAPSHOT (or other latest BBMRI versions)
