### ISSUE TITLE
ID-Card repository indexed on clean install

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5319]
#### Reproduce
- Enable MOLGENIS debug logging and perform a clean install
- Inspect the logs

#### Expected
- No ID-Card repository collection repositories are indexed

#### Observed
- An attempt is made to index a ID-Card repository resulting in significantly longer startup time

**Comment by Mark-de-Haan** [comment]
Do you mean a WAR deploy, or a clean install?
Indexing happens at deployment right?

**Comment by Mark-de-Haan** [comment]
Fixed by moving ID card module to a separate repository
