### ISSUE TITLE
Mapping service does not validate when lookupattribute is label and label is empty 

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5324]
#### Reproduce

Contact me (mariska) for test dataset. 
Load the dataset, start the mapping service to map table old_model (target) to new_model (source). 
Alter the topics mapping. 
Paste this code:
`
var diagnosis = [];
if($('topics').value()){
    diagnosis.push($('topics').value());
}
diagnosis;
`

Click on validate algorithm

Now the error occurs.
![screen shot 2016-10-10 at 10 54 26](https://cloud.githubusercontent.com/assets/10075439/19231016/f5b0fdee-8ed7-11e6-90ec-6c16f65b5b61.png)
No content is shown in the preview of the validation. 
In the log the observed error can be seen. 
#### Expected

Getting a preview which tells if the algorithm is valid. 
#### Observed

08:49:47.462 [ajp-bio-8009-exec-2] ERROR freemarker.runtime - Error executing FreeMarker template
freemarker.core._TemplateModelException: The FreeMarker value exists, but has nothing inside it; the TemplateModel object (class: freemarker.ext.beans.StringModel) has returned a null instead of a S
tring. This is possibly a bug in the non-FreeMarker code that builds the data-model.
The blamed expression:
==> value  [in template "view-attribute-mapping-feedback.ftl" at line 57, column 102]

---

FTL stack trace ("~" means nesting-related):
##         - Failed at: ${value?html}  [in template "view-attribute-mapping-feedback.ftl" at line 57, column 100]

--> no content in preview, because of ftl error

**Comment by Mark-de-Haan** [comment]
This is fixed in 2.0
