### ISSUE TITLE
On molgenis52 in the collection entity, the expand button of the diagnosis available column does not work

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5334]
#### Reproduce

Go to molgenis52, click on biobank directory, select the diagnosis available symptom and click on expand. 
(I used chrome)
#### Expected

I expect to get my expanded entity
#### Observed

The columns stay empty and they are supposed to be filled (below, random 0 and 99 show, I dont know why)

**Comment by Mark-de-Haan** [comment]
This might be caused by the custom javascript that is added to the data explorer.
For example, I see a horizontal scroll bar in that mref field, which is not something that is native in molgenis.

**Comment by marikaris** [comment]
I added the scroll bar, this did not break the expand of the mref, I tested it. By altering the model this was fixed.
