### ISSUE TITLE
Categorial mref filter is causing for a wrong query (or instead of and)

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5348]
#### Reproduce

1. Load TypeTest dataset
2. Data Explorer
3. select entity TypeTest
4. Add filter: id label: (5 ≤ x ≤ 5)
5. Add filter: xcategoricalmref_value: ('label3' or 'label2')
![screen shot 2016-10-14 at 5 23 26 pm](https://cloud.githubusercontent.com/assets/5586255/19393052/72629f4c-9233-11e6-8ef2-93f260100fe5.png)

#### Expected
Only row (5		label2,label3)

#### Observed
24 items found

**Comment by dennishendriksen** [comment]
Fixed by molgenis/molgenis#5403
