### ISSUE TITLE
Nillable MREF value doesn't get validated properly by the ReadOnly validation

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5365]
#### Reproduce

Upload entity with nillable MREF, set to zero values, then update same entity again.
[5365.xlsx](https://github.com/molgenis/molgenis/files/578567/5365.xlsx)

#### Expected

Upload works
#### Observed

Upload fails with NPE

**Comment by dennishendriksen** [comment]
Cannot reproduce. I've tried importing [emx_required_readonly_mref.xlsx](https://github.com/molgenis/molgenis/files/574823/emx_required_readonly_mref.xlsx) in ADD mode followed by importing [emx_required_readonly_mref-update.xlsx](https://github.com/molgenis/molgenis/files/574825/emx_required_readonly_mref-update.xlsx) in UPDATE mode resulting in the expected exception ```The attribute 'books' of entity 'test_author' can not be changed it is readonly. (entity 2)```

@fdlk How to reproduce? (ps. next time please describe in more detail how to reproduce and always attach the dataset that reproduces the issue)

**Comment by fdlk** [comment]
@dennishendriksen Bart and I ran into this during the hackathon, didn't have our test hats on at the time. The issue is that it happens when you update a NILLABLE mref from a list with zero entries to itself.

[5365.xlsx](https://github.com/molgenis/molgenis/files/578567/5365.xlsx)

**Comment by fdlk** [comment]
@dennishendriksen Bart already fixed this during the hackathon, I'm going to "steal" this issue from you now and put up a pull request with Bart's fix.
