### ISSUE TITLE
i18n code throws NPE if refEntity has idAttribute but no labelAttribute

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5370]
#### Reproduce
Upload entity with idAttribute but no explicitly defined labelAttribute.
Refer to it in a referring entity.
Open the referring entity in the dataexplorer.

#### Expected
Entity is shown (or importer refuses to import)

#### Observed
Error while retrieving the data for the referring entity

**Comment by dennishendriksen** [comment]
EMX file that reproduces the issue: [emx_simplexref.xlsx](https://github.com/molgenis/molgenis/files/555048/emx_simplexref.xlsx)
