### ISSUE TITLE
GAVIN web app may have problems with ExAC annotations

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#5388]
We have observed strange behaviour for GAVIN web app. (http://www.molgenis.org/gavin) that we must try to reproduce, and if it is reproducible, fix it. Perhaps it is some kind of thread issue with tabix readers? Try to push multiple files at once. The peculiar thing is, that the annotators DO work correctly. (see below)

This variant is not in ExAC: `11  47371589    .   G   A`, but we have seen it annotated by GAVIN webapp as `EXAC_AF=0.472;EXAC_AC_HOM=0.472;EXAC_AC_HET=0.472;`. Note that by "not present" we mean it is not  in the ExAC downloaded VCF (ExAC.r0.3.sites.vep.vcf.gz) - it IS present on the website but as a 'low quality' variant, that's why it is probably not in the file release.

Another example: `2   179418418   .   C   A` (not in ExAC) wrongly annotated as `EXAC_AF=0.459;EXAC_AC_HOM=0.459;EXAC_AC_HET=0.459;`.

Within the same output file, we did observe a correct variant: `1 17371313    .   T   A` annotated as `EXAC_AF=4.942E-5;EXAC_AC_HOM=0;EXAC_AC_HET=6;`.

Test file:

```
##fileformat=VCFv4.1
##reference=hg19.fasta
#CHROM    POS    ID    REF    ALT    QUAL    FILTER    INFO
11    47371589    397516053    G    T    .    .    .
11    47371589    .    G    A    .    .    .
2    179418418    .    C    A    .    .    .
1    17371313    .    T    A    .    .    .
```

CmdLineAnnotator 1.21.1 and 1.21.4 do it CORRECTLY, so the expected output is:

```
##fileformat=VCFv4.1
##reference=hg19.fasta
##INFO=<ID=EXAC_AF,Number=.,Type=String,Description="The ExAC allele frequency">
##INFO=<ID=EXAC_AC_HOM,Number=.,Type=String,Description="The ExAC homozygous alternative genotype count">
##INFO=<ID=EXAC_AC_HET,Number=.,Type=String,Description="The ExAC heterozygous genotype count">
#CHROM    POS    ID    REF    ALT    QUAL    FILTER    INFO
11    47371589    397516053    G    T    .    .    EXAC_AF=8.532E-6;EXAC_AC_HOM=0;EXAC_AC_HET=1;
11    47371589    .    G    A    .    .    .
2    179418418    .    C    A    .    .    .
1    17371313    .    T    A    .    .    EXAC_AF=4.942E-5;EXAC_AC_HOM=0;EXAC_AC_HET=6;
```

Command used:
`$ java -Xmx4g -jar CmdLineAnnotator-1.21.1.jar -a exac -s /groups/umcg-pub/prm02/resources/exac/ExAC.r0.3.sites.vep.vcf.gz -i ExACannotatorTest.vcf -o ExACannotatorTest.exac.vcf`

**Comment by fdlk** [comment]
Tried just now with attached test file and the results are as expected, I think?

[5388.renameto.vcf.txt](https://github.com/molgenis/molgenis/files/549081/5388.renameto.vcf.txt)

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
11	47371589	397516053	G	T	.	.	CADD=4.91846;CADD_SCALED=25.0;EXAC_AF=8.532E-6;EXAC_AC_HOM=0;EXAC_AC_HET=1;EFFECT=T|MYBPC3|missense_variant|MODERATE|MYBPC3|transcript|NM_000256.3|protein_coding|4/34|c.481C>A|p.Pro161Thr|536/4217|481/3825|161/1274|||Pathogenic|calibrated|Variant CADD score of 25.0 is greater than 23.89 in a gene for which CADD scores are informative.;
11	47371589	.	G	A	.	.	CADD=5.279487;CADD_SCALED=25.7;EFFECT=A|MYBPC3|missense_variant|MODERATE|MYBPC3|transcript|NM_000256.3|protein_coding|4/34|c.481C>T|p.Pro161Ser|536/4217|481/3825|161/1274|||Pathogenic|calibrated|Variant CADD score of 25.7 is greater than 23.89 in a gene for which CADD scores are informative.;
2	179418418	.	C	A	.	.	CADD=28.65623;CADD_SCALED=65.0;EFFECT=A|TTN|stop_gained|HIGH|TTN|transcript|NM_001267550.2|protein_coding|334/363|c.89314G>T|p.Glu29772*|89539/109223|89314/107976|29772/35991|||Pathogenic|calibrated|Variant CADD score of 65.0 is greater than 46.59 in a gene for which CADD scores are informative.,A|MIR548N|intron_variant|MODIFIER|MIR548N|transcript|NR_031666.1|pseudogene|3/4|n.37-75097C>A|||||||Benign|genomewide|Variant is of 'modifier' impact, and therefore unlikely to be pathogenic.,A|TTN-AS1|intron_variant|MODIFIER|TTN-AS1|transcript|NR_038272.1|pseudogene|7/16|n.2043+11330C>A|||||||Benign|genomewide|Variant is of 'modifier' impact, and therefore unlikely to be pathogenic.;
1	17371313	.	T	A	.	.	CADD=6.617266;CADD_SCALED=32.0;EXAC_AF=4.942E-5;EXAC_AC_HOM=0;EXAC_AC_HET=6;EFFECT=A|SDHB|missense_variant|MODERATE|SDHB|transcript|NM_003000.2|protein_coding|2/8|c.143A>T|p.Asp48Val|294/1145|143/843|48/280|||Pathogenic|genomewide|Variant MAF of 4.942E-5 is rare enough to be potentially pathogenic and its CADD score of 32.0 is greater than a global threshold of 15.;

```

**Comment by fdlk** [comment]
@joerivandervelde exac annotators work in update mode, could it be that the source file already had an exac annotation in the case where you saw the buggy behavior?

**Comment by joerivandervelde** [comment]
Excellent suggestion but alas - using the above test file with added 'bogus' exac annotations results in the output annotations being overwritten/removed correctly, so that does not seem to be the problem.

**Comment by dennishendriksen** [comment]
Feature was removed
