### ISSUE TITLE
If I tag an attribute with a 'nonsense' tag, none of the attributes is auto mapped when adding a source

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5415]
#### Reproduce
1. Import [emx_all_datatypes.xlsx](https://github.com/molgenis/molgenis/files/599283/emx_all_datatypes.xlsx)
2. Import [small_test_data.owl.zip](https://github.com/molgenis/molgenis/files/599285/small_test_data.owl.zip)
3. In the tagwizard, tag xbool in TypeTest with weight
4. Create a mapping project with TypeTest as target
5. Add TypeTest as source
#### Expected
Attributes are mapped automatically, because I am mapping the same entities to each other
#### Observed
None of the attributes are tagged. When I try to manually map xbool to xbool, the save button is disabled. If I remove the tag again, the auto mapping works again.

**Comment by dennishendriksen** [comment]
Issue was introduced in 2.0:

**1.21**

![image](https://cloud.githubusercontent.com/assets/2477186/20422693/30ca162e-ad6c-11e6-84ea-c6273f0459b9.png)

**2.0**
![image](https://cloud.githubusercontent.com/assets/2477186/20422738/7148ffb2-ad6c-11e6-888a-8074d44df3b3.png)

**Comment by dennishendriksen** [comment]
Doesn't appear to be related to tags, for example 'enumnillable' is mapped to 'enum' in 2.0 while it 'enum' is mapped to 'enum' in 1.21.

**Comment by dennishendriksen** [comment]
Search queries are correct in both versions, search results are also both correct: both ```xbool``` and ```xboolnillable``` have exactly the same scores. The order in the response is different, probably due to different indexing order.
