### ISSUE TITLE
Editing the description of a reference EntityType fails

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5424]
### Reproduce
1. Import TypeTest + TypeTestRef
2. Go to the data explorer
3. In the EntityType table, edit the TypeTestRef entity
4. Set the description to: Cool description!!
5. Press save

### Expected
The description of the TypeTestRef is changed

### Observed

`Error! ; nested exception is org.postgresql.util.PSQLException: ERROR: cannot drop table "TypeTestRef" column value because other objects depend on it Detail: constraint org_molgenis_test_TypeTest_xcategorical_value_fkey on table "org_molgenis_test_TypeTest" depends on table "TypeTestRef" column value constraint org_molgenis_test_TypeTest_xcategoricalnillable_value_fkey on table "org_molgenis_test_TypeTest" depends on table "TypeTestRef" column value constraint org_molgenis_test_TypeTest_xxref_value_fkey on table "org_molgenis_test_TypeTest" depends on table "TypeTestRef" column value constraint org_molgenis_test_TypeTest_xxrefnillable_value_fkey on table "org_molgenis_test_TypeTest" depends on table "TypeTestRef" column value constraint org_molgenis_test_TypeTest_xxref_unique_fkey on table "org_molgenis_test_TypeTest" depends on table "TypeTestRef" column value constraint org_molgenis_test_TypeTest_xcategor_xcategoricalmref_value_fkey on table "org_molgenis_test_TypeTest_xcategoricalmref_value" depends on table "TypeTestRef" column value constraint org_molgenis_test_TypeTest_xcatmref_xcatmrefnillable_value_fkey on table "org_molgenis_test_TypeTest_xcatmrefnillable_value" depends on table "TypeTestRef" column value constraint org_molgenis_test_TypeTest_xmref_value_xmref_value_fkey on table "org_molgenis_test_TypeTest_xmref_value" depends on table "TypeTestRef" column value constraint org_molgenis_test_TypeTest_xmrefnillab_xmrefnillable_value_fkey on table "org_molgenis_test_TypeTest_xmrefnillable_value" depends on table "TypeTestRef" column value Hint: Use DROP ... CASCADE to drop the dependent objects too.`

**Comment by dennishendriksen** [comment]
Cannot reproduce on molgenis master branch. Here I get the following error:
"Entity [TypeTestRef] is missing required ID attribute"

**Comment by dennishendriksen** [comment]
Issue is caused because attributes control is disabled instead of read-only, which causes the input value to be omitted when submitting form to the server.
