### ISSUE TITLE
When changing an existing string attribute to compound and then back to string, all data is lost

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5427]
### Reproduce
1. Import TypeTest
2. Go to the data explorer Attribute table
3. Edit xstring type to compound, save
4. Edit xstring type to string, save

### Expected
I can not change to compound, but I can
I this case I can convert to compound, I expect the data for xstring to be preserved 

### Observed
All data for xstring is gone

**Comment by bartcharbon** [comment]
a compound has no column in the datatable in postgres so the data can never be preserved. I assume the appropriate behaviour is that changing to compound should not be allowed.

**Comment by Mark-de-Haan** [comment]
Yes I agree that converting to compound should not be allowed

**Comment by fdlk** [comment]
We have code in PostgreSqlRepositoryCollection that explicitly checks for this transition and we have unit tests that test the code. Everything!
If you want to prevent it, maybe have have the importer or the form issue a warning. But let's not forbid it in the data layer, cause then you might as well forbid deleting columns :)

**Comment by dennishendriksen** [comment]
This is the expected behavior, please discuss with the the PO and create a story if you would like to see different behavior.
