### ISSUE TITLE
Updating entity with id with dot char fails

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5431]
#### Reproduce
Table in which comments is an xref
![screen shot 2016-10-31 at 16 04 20](https://cloud.githubusercontent.com/assets/10075439/19858975/d1eb2300-9f83-11e6-99fa-0081d36e2d78.png)
Click on a comment (which is -, so it is clickable but not filled in)
![screen shot 2016-10-31 at 16 04 38](https://cloud.githubusercontent.com/assets/10075439/19858974/d1eadbfc-9f83-11e6-9667-87bcf9a28ab7.png)
Click on the alter button
![screen shot 2016-10-31 at 16 04 44](https://cloud.githubusercontent.com/assets/10075439/19858978/d1efe6a6-9f83-11e6-93ae-138990a07815.png)
Alter the comment and Save changes
![screen shot 2016-10-31 at 16 04 55](https://cloud.githubusercontent.com/assets/10075439/19858976/d1ece532-9f83-11e6-9f87-42643997385c.png)
ERROR!
![screen shot 2016-10-31 at 16 04 59](https://cloud.githubusercontent.com/assets/10075439/19858977/d1eec708-9f83-11e6-8f8c-abcae04cce7f.png)

#### Expected
Just an update of the ref entity

#### Observed
An error because the id is splitted on . and only the first part is taken to search for in the refEntity and this id does not exist. This is in version 1.21 (I cannot add a label?)

**Comment by fdlk** [comment]
@tommydeboer I think you looked into escaping the '.' when determining path variables?

**Comment by tommydeboer** [comment]
Spring interprets URLs with a '.' in them as file extensions (which it strips). 

There's a list of possible solutions here:
http://stackoverflow.com/questions/16332092/spring-mvc-pathvariable-with-dot-is-getting-truncated

It boils down to:
1. Change all controller request mapping urls so they include the dot, or
2. Turn of suffix matching application wide
