### ISSUE TITLE
EMX meta headers case-sensitive instead of case-insensitive

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5444]
#### Reproduce
- Import https://drive.google.com/open?id=0B8iNw4kI1MA2bXhlTmwyeWgtbU0 which imports succesfully in MOLGENIS 1.21

#### Expected
- Import successful

#### Observed
- Import fails with message attributes.datatype unknown

**Comment by bartcharbon** [comment]
I agree it should be case insensitive. However I think it was case sensitive in 1.21 as well. The difference is that all the attribute attributes were than "toLowerCase()"-ed

**Comment by dennishendriksen** [comment]
@bartcharbon @jjettenn and myself had a brief discussion and decided that case-sensitive in practice won't cause much problems. The error message in case of case mismatch is extended with 'Did you mean attributes.dataType?'
