### ISSUE TITLE
Delete package does not refresh entity select box in "Data Explorer"

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5452]
#### Reproduce
Load TypeTest dataset
go to -> package
delete package org_molgenis_test

#### Expected
Type test cannot be found in the entity select box

#### Observed
Type test can be found in the entity select box

**Comment by fdlk** [comment]
The dataexplorer entity select box is created in the freemarker template, so any JSON calls that alter it have no effect on its contents. Reloading the page updates the box. Has always been so, also in 1.x

**Comment by Mark-de-Haan** [comment]
Wontfix: Issue will be addressed in [Dataexplorer 2.0](http://wiki.gcc.rug.nl/ticket/5288)
