### ISSUE TITLE
Anonymous user entity type permissions require EntityType read permission

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5493]
#### Reproduce
Upload TypeTest, give anonymous user read permission on the TypeTestRef entity.
Make a call to api/v2/TypeTestRef (or org_molgenis_test_TypeTestRef, depending on what package you imported to)

#### Expected
I see data.

#### Observed
No [READ] permission on entity [sys_md_EntityType]

**Comment by dennishendriksen** [comment]
The call to ```api/v2/TypeTestRef``` results in accessing ```sys_md_EntityType``` to retrieve the metadata of ```TypeTestRef```. Isn't this expected behavior?

**Comment by dennishendriksen** [comment]
This issue or change of behavior was introduced in 2.0, 1.21.5 return the data in the REST API response.

**Comment by dennishendriksen** [comment]
After some pondering with @fdlk we decided that it is up to the user to assign view permissions on metadata entities (which already happens during initial bootstrapping for the 'all users' group.
