### ISSUE TITLE
When changing the name of an attribute, expressions aren't updated

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5504]
It's possible to change the name of an attribute with metadata editing, but any expressions pointing to that attribute will not be valid anymore. 

Removing attributes can also break expressions, leading to errors in the data explorer.

**Comment by tommydeboer** [comment]
Part of story [As data manager I want an improved (meta)data validation experience](http://www.molgenis.org/ticket/4623)

**Comment by mswertz** [comment]
will use of autogenerated identifiers affect this story?

**Comment by mswertz** [comment]
too advanced request for now, wontfix
