### ISSUE TITLE
Sign up is not working

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5521]
#### Reproduce
Fill in the next fields:
Username: ...
Password: ...
Repeat password: ...
Email address: ...

#### Expected
To be signed up

#### Observed
Error! An error occurred. Please contact the administrator. You are not signed up!

**Comment by dennishendriksen** [comment]
Caused by incorrect mail server configuration due to issue #5559

**Comment by jjettenn** [comment]
Can reproduce
