### ISSUE TITLE
Non-system entities can be added to system package

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5526]
#### Reproduce
- Select entity 'User' in the 'Data explorer' plugin
- Select the copy button next to the entity selection and use 'UserCopy' as name for the copy

#### Expected
- The copied entity is located in a non-system package

#### Observed
- The copied entity is located in system package sys_sec

**Comment by jjettenn** [comment]
System entities cannot be copied therefore the expected behavior is an error message:
Error! Adding entity [sys_sec_UserCopy] to system package [sys_sec] is not allowed

**Comment by Mark-de-Haan** [comment]
Current error:
`Error! Adding entity [sys_sec_UserCopy] to system package [sys_sec] is not allowed`

Where we can ask ourselves, why would we want to make copies of system entities?
