### ISSUE TITLE
Multiple attributes with same name in entity allowed

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5527]
#### Reproduce
In the Attribute table, create a nillable string attribute, "newString" 
1. Set the EntityType to TypeTest
2. Set the Sequence Order to 1

And create a new one

#### Expected
Error message

#### Observed
Both are created one is shown. Deleting one attribute and you cannot use the entity anymore

**Comment by dennishendriksen** [comment]
Solution is to implement unique constraints that can span multiple attributes on entity level in the MOLGENIS meta data model  and create PostgreSQL database constraints based on these meta data constraints. Additional cases might be required in the exception translator as well.
