### ISSUE TITLE
Changing the datatype of xstring (TypeTest) to int results in wrong error message

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5536]
#### Reproduce
LOAD: TypeTest
In the Attribute table, change the datatype of xstring (TypeTest) to int

#### Expected
Error! Value [xxx] of this entity attribute is not of type [INT or LONG].

#### Observed
exclamation-sign Attribute changes could not be saved. NumberFormatException For input string: "xstring"

**Comment by tommydeboer** [comment]
It turned out to be the default value that wasn't valid anymore! I updated the message in the PR.
