### ISSUE TITLE
Can't add account via the sign up form

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5542]
#### Reproduce
1. Activate the sign up form in the app settings
2. Add a new user with valid username, etc.

#### Expected
I can sign up.

#### Observed
Error! An error occurred. Please contact the administrator. You are not signed up!

**Comment by tommydeboer** [comment]
It seems like the mail server isn't configured properly

**Comment by dennishendriksen** [comment]
Duplicate of #5521
