### ISSUE TITLE
When having a logo above the navigation bar, saving some themes in the theme manager makes the nav bar disappear

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5546]
#### Reproduce
put logo in navigation bar
![screen shot 2016-11-15 at 16 18 15](https://cloud.githubusercontent.com/assets/10075439/20311371/db055f64-ab4f-11e6-9b64-be69629cca61.png)
Go to the theme manager
![screen shot 2016-11-15 at 16 18 26](https://cloud.githubusercontent.com/assets/10075439/20311400/f499f55c-ab4f-11e6-8770-b43e8c317e4e.png)
Select a theme (yeti for example does produce the error) and click save. 
![screen shot 2016-11-15 at 16 18 39](https://cloud.githubusercontent.com/assets/10075439/20311488/481c2ca4-ab50-11e6-9ad2-66961a422518.png)
Succes! But your nav bar is gone (well, it moved to the right upper corner), good luck! (select molgenis theme to get it back)
![screen shot 2016-11-15 at 16 18 48](https://cloud.githubusercontent.com/assets/10075439/20311540/7849e8ee-ab50-11e6-975d-b60158edfdd5.png)

#### Expected
I want to keep my nav bar where it was when saving a theme

#### Observed
The nav bar moves out of the screen

**Comment by Mark-de-Haan** [comment]
Can not reproduce in 5.3.0-SNAPSHOT
