### ISSUE TITLE
Set 'IP anonymization' to 'YES', Save changes, reload page, Accept cookies message is shown

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5547]
#### Reproduce
Go to settings ->
Set 'IP anonymization' to 'YES', Save changes, reload page.

#### Expected
Accept cookies message is not shown

#### Observed
Accept cookies message is shown

**Comment by dennishendriksen** [comment]
This is a feature, the cookie wall is only disabled if you set 'Google analytics account privacy friendly' to 'Yes' as well.
