### ISSUE TITLE
Installation manual should instruct the administrator to configure mail properties

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5555]
#### Reproduce
1. Install MOLGENIS according to the [manual](http://molgenis.github.io/develop/start)
2. create an admin with an e-mail address that is not an GMAIL address.
3. Fill in and submit the feedback form

#### Expected
The admin gets an e-mail with the feedback

#### Observed
The user gets an error telling that something went wrong.

**Comment by dennishendriksen** [comment]
Relevant [story in the backlog](http://www.molgenis.org/ticket/4678).

**Comment by mswertz** [comment]
is this now solved by this story?

**Comment by djvanenckevort** [comment]
Manual still needs to be updated.

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Due to the introduction of GitBook I was wondering whether the manual location referred to be @djvanenckevort is the location that should be updated?

**Comment by ConnorStroomberg** [comment]
@djvanenckevort We have a new link to the 'updated' documentation:

Goto: http://molgenis.github.io/ and click the "Getting Started" button.
This will open a new tab at: https://molgenis.gitbooks.io/molgenis/content/ 

On the left hand side there is a menu, click on the "Admin features" link in the "User Documentation" section. This redirects the page to https://molgenis.gitbooks.io/molgenis/content/user_documentation/guide-admin.html

The section "Mail settings" describes how to set up the mail server.

If this does not solve the reported problem please included detailed steps to reproduce the problem ( settings should not be postend on github )

**Comment by djvanenckevort** [comment]
I still have two issues:
1. The manual doesn't describe how to configure a different e-mail server than the default one. I would advise to extend this section with an example to use a different server with SSL and authentication (e.g. Office 365)
2. The installation manual should contain a link to further configuration after the basic setup, because now it is not clear for an admin that he should review those settings.

**Comment by fdlk** [comment]
@djvanenckevort The documentation had accidentally gotten removed, I've restored it.
Some providers (including google) prefer that you authenticate using an OAUTH token. Support for this is story http://wiki.gcc.rug.nl/ticket/4910
