### ISSUE TITLE
MolgenisVersionService unintentionally escapes characters in server properties

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5559]
After a migration, the ```MolgenisVersionService``` updates the ```molgenis.version``` field in the ```molgenis-server.properties```. 

Because the whole file gets rewritten, some characters can unintentionally become escaped. For example characters in passwords.

The preferred solution is to not write to the properties file anymore.

**Comment by dennishendriksen** [comment]
```molgenis-server.properties``` should be treated as read-only, molgenis.version should be stored in the database.

**Comment by fdlk** [comment]
Properties.load() then Properties.store() should work, however.
I suspect this is cause we load with UTF-8 and store with 8859_1.

**Comment by Mark-de-Haan** [comment]
We no longer migrate since v2.0

**Comment by dennishendriksen** [comment]
The migration framework is still in place and can be used, so this issue should not be closed (and we should start writing those scripts again ...).

**Comment by dennishendriksen** [comment]
Fixed in 7.0 by aa4670e6d42713371a84a9a16100a8d02a2f2eca
