### ISSUE TITLE
Sort Data type results in error

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5573]
#### Reproduce
- Import [emx_all_datatypes.xlsx](https://github.com/molgenis/molgenis/files/591236/emx_all_datatypes.xlsx) in ADD mode
- Go to data explorer and select Attribute entity.
- Search for xbool and change datatype to string. 
- Sort Data type

#### Expected
Data type is sorted

#### Observed
Error! Failed to execute phase [query], all shards failed; shardFailures {[Q32gpkcGTrK7fIF2swhC2g][molgenis][0]: SearchParseException[[molgenis][0]: query[_all:typetest],from[0],size[20]: Parse Failure [Failed to parse source [{"from":0,"size":20,"query":{"match":{"_all":{"query":"TypeTest","type":"phrase","slop":10}}},"sort":[{"type.raw":{"order":"asc","mode":"min"}}]}]]]; nested: QueryParsingException[[molgenis] [nested] failed to find nested object under path [type]]; }

**Comment by dennishendriksen** [comment]
Cannot reproduce, the 'Data type' column is sorted as expected.

**Comment by jjettenn** [comment]
need to change datatype to string

**Comment by jjettenn** [comment]
Reported to elasticsearch: Query with a search value and a sort on field name type, results in error. #21725

**Comment by jjettenn** [comment]
Related to:
Sorting on the ID attribute in the dataexplorer throws an error #2754

**Comment by jjettenn** [comment]
First quick fix for Attribute tabel.

The problem is that in the same index in elasticsearch two fields with the same name should have the same mapping.
