### ISSUE TITLE
Mapping service attributelist contains spaces in the attribute names

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5586]
#### Reproduce
- create a mapping project mapping typetest to typetest
- open the xboolnillable mapping

#### Expected
the attribute label is shown without extra spaces

#### Observed
see attached screenshot (the part in blue contains extra spaces)
![screen shot 2016-11-21 at 08 26 38](https://cloud.githubusercontent.com/assets/3714029/20473984/57ca9cb2-afc4-11e6-8b93-ed1f7724faa1.png)
[emx_all_datatypes_metadata_only.xlsx](https://github.com/molgenis/molgenis/files/602922/emx_all_datatypes_metadata_only.xlsx)

**Comment by dennishendriksen** [comment]
The nested highlight spans are not merged even though there is an algorithm that tries to do it.

**Comment by Mark-de-Haan** [comment]
Can no longer reproduce in v5.3.0-SNAPSHOT
