### ISSUE TITLE
Circular dependencies importing as non-superuser user

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5605]
### Reproduce
- Create a user with view rights on:
    - importwizard plugin
    - ImportRun entity
- Log in as user
- Import [TypeTest](https://github.com/molgenis/molgenis/files/608840/emx_all_datatypes.xlsx)

### Expected
File imports

### Observed
```
Error! Your import failed:
Could not resolve dependencies of entities [org_molgenis_test_TypeTest] are there circular dependencies?
```

**Comment by Mark-de-Haan** [comment]
This is fixed if you add VIEW rights on FileMeta

**Comment by dennishendriksen** [comment]
```FileMeta``` extends from ```Owned```, assigning these permissions in the database populator sounds like a plan.
