### ISSUE TITLE
Test vcf in molgenis-pathways can't be imported

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5613]
### How to Reproduce
1. Import [test_vcf.zip](https://github.com/molgenis/molgenis/files/613518/test_vcf.zip)

### Expected behavior
File is imported is this is indeed a valid VCF, else the observed behavior is incorrect.

### Observed behavior
```Missing attribute for VCF info field [LDAF]```

**Comment by dennishendriksen** [comment]
Works in 1.21.4
