### ISSUE TITLE
"Entity types" attribute of package base is empty

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5616]
### How to Reproduce
Inport: [emx_all_datatypes.xlsx](https://github.com/molgenis/molgenis/files/611701/emx_all_datatypes.xlsx)

select base package at the "package select step"

### Expected behavior
Go to Package in the Data Explorer: the base package has TypeTestRef in "Entity types"

### Observed behavior
"Entity types" attribute is empty

**Comment by dennishendriksen** [comment]
When fixing this issue ensure that the metadata section of the REST response for TypeTestRef is correct

**Comment by dennishendriksen** [comment]
Attribute 'Package' of 'EntityType' is nillable. In 1.21 EMX entities not assigned to a package were stored in the ```base``` package when selecting default options in the import wizard.
