### ISSUE TITLE
EMX import unclean error: For input string: "string"

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5620]
### How to Reproduce
Import a value that should be text and is categorical linked to a categorical with id type int
 
### Expected behavior
Get a proper error message that tells me what the problem is. 

### Observed behavior
For input string: "nothing"
(nothing was the value in the first row of the data, where wrong categorical type was defined)

[testWrongCategorical.xlsx](https://github.com/molgenis/molgenis/files/613006/testWrongCategorical.xlsx)

**Comment by dennishendriksen** [comment]
In MOLGENIS 2.0 both imports result in the following error message: ```Failed to convert from type java.lang.String to type java.lang.Integer for value 'nothing'```. @marikaris Is this a proper error message that would help you to fix your dataset?

**Comment by marikaris** [comment]
No it would not be a proper message in both cases. It would be helpful for the first case if I could also get a name of the attribute where the error in occurs, then I can look in the attributes sheet to see where it goes wrong. For the second case: I just want a message that there is an empty column in my dataset. Molgenis should not just skip.

**Comment by tommydeboer** [comment]
After discussion with @marikaris I rewrote the issue a bit. The other issue that was described here was #5621 
@mswertz Would you like to have #5621 in this milestone as well?
