### ISSUE TITLE
Annotation failed for corner_cases.vcf

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5622]
### How to Reproduce
Upload "corner_cases.vcf" (details in test plan) from drive
Annotate with (select all):
cadd 
dann 
clinvar 
gonl 
exac 
fitcon 
thousand_genomes
snpEff

### Expected behavior
Everything is annotated

### Observed behavior
Error: org.molgenis.data.validation.MolgenisValidationException: Duplicate value 'AAAACWE26BWHYATAPVHJR3AAAE' for unique attribute 'id' from entity 'sys_md_Attribute'.

**Comment by dennishendriksen** [comment]
Cannot reproduce with latests molgenis/2.0 code:
```Annotated "cornercases2" with cadd,dann,clinvar,gonl,exac,fitcon,snpEff,thousand_genomes (started by "admin")```

**Comment by dennishendriksen** [comment]
Cannot reproduce on RC-2 on molgenis62 after a clean/install: ```Annotated "cornercases2" with cadd,dann,clinvar,gonl,exac,fitcon,thousand_genomes (started by "admin")```
