### ISSUE TITLE
Weird behaviour in categorical refentity outside package and entity in package

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5634]
### How to Reproduce
https://drive.google.com/drive/folders/0B7QjWv5iC182QmllTjQzWkNZQ0k

I loaded this dataset on molgenis46 (1.21.1) and local (1.21.5). Local DEM1, ROK1 and CISAVINFO were in a package: FG500 while this was not in the model. On molgenis 46, the entities were not put in a package but when I set permissions for the anonymous user (read for these entities and FG500_public_data), I got "No read permission", when I altered the name of these entities in the User permissions table to FG500_DEM1, FG500_ROK1 and FG500_CISAVINFO, the anonymous user was finally able to see the public data table. 
### Expected behavior
The entities outside the package, stay outside the package, also when it is a refEntity of an entity in the package. 
Permissions are given on the entity name (outside the package, when the entity is outside the package)

### Observed behavior
Locally entities are in the package while they should not be in it. 
On molgenis46 entities are outside the package but in the permission manager they should be defined as they are in the package.

**Comment by Mark-de-Haan** [comment]
@marikaris I have no clue about what the actual issue is :')

**Comment by marikaris** [comment]
Fixed because entityTypes just have to be in packages
