### ISSUE TITLE
403 page when first having no permissions as anonymous user and then logging in

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5635]
### How to Reproduce
On molgenis46 and molgenis10 when going to an entity: https://molgenis46.gcc.rug.nl/menu/500fgdata/dataexplorer?entity=FG500_private_data
and then loggin in, you receive a 403 page, linking to: https://molgenis46.gcc.rug.nl/app/fonts/glyphicons-halflings-regular.ttf

It does not matter if you have permissions on the entity as anomymous user. 

### Expected behavior
Log in and see the table (when having permissions)

### Observed behavior
403 page

**Comment by marikaris** [comment]
David reported something like this too, just tried to reproduce in 5.1 and the 403 does not show.

**Comment by fdlk** [comment]
I see the /app URL, which makes me think you need to deploy an app to the app store or something to reproduce this.
