### ISSUE TITLE
Importing VCF as user gives permission errors

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5643]
### How to Reproduce
- Create a user with view rights on:
- importwizard
- ImportRun
- Import test.vcf (standard molgenis-app/src/test/resources/vcf)

### Expected behavior
Import succeeds

### Observed behavior
No Write permission on sys_md_EntityType

- Add write permissions for sys_md_EntityType and repeat

No WRITEMETA permission on test_Samples

**Comment by dennishendriksen** [comment]
Works in 1.21.5

**Comment by dennishendriksen** [comment]
Broken in 3.0.0-RC

**Comment by dennishendriksen** [comment]
Works in 5.2.0-SNAPSHOT.
