### ISSUE TITLE
Attribute date conversion is not working correctly

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5650]
### How to Reproduce
Activate two test classes in de code:
1. DateAttributeTypeUpdateTest
2. DateTimeAttributeTypeUpdateTest

The tests are working if you run them seperatlly
But try to run them in conjunction with other tests lets say: 
1. DateAttributeTypeUpdateTest
2. DateTimeAttributeTypeUpdateTest
3. BoolAttributeTypeUpdateTest
4. CategoricalMrefAttributeTypeUpdateTest 
then the tests will fail.

### Expected behavior
Tests are activated and they pass.

### Observed behavior
Errors in tests:
1. DateAttributeTypeUpdateTest
2. DateTimeAttributeTypeUpdateTest

**Comment by Mark-de-Haan** [comment]
No longer an issue in v5.3.0-SNAPSHOT
