### ISSUE TITLE
L2 Cache contains second-last state of JobExecution entity

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5655]
### How to Reproduce
Unsure. Run a lot of Gavin jobs.

### Expected behavior
L2Cache always contains the same version as the database.

### Observed behavior
Sometimes the gavin job as retrieved from the L2Cache still has status RUNNING and log ending with "File is ready for download." But in the database status has already been updated to FINISHED and log ends with "That took 20m12s."

**Comment by fdlk** [comment]
Dennis suggests: Make sure the updates are transactional. The bits of the repository interface that serve streams are not really transactional.

**Comment by fdlk** [comment]
I think I found the cause in https://github.com/google/guava/issues/1881

**Comment by fdlk** [comment]
Yup! Managed to reproduce by adding a lot of sleep to the cache loader.

![sequence diagram](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=CgoKVXBkYXRlciAtPiBEYXRhU2VydmljZTogdQATBSgiUlVOTklORyIsICJEb3dubG9hZCByZWFkeS4iKQphY3RpdmF0ZQAvDAoKAD0LIC0-IFJlcG8AIDBSZXBvClJlcG8gLQCBCg8KZGUAGA4AXxBDYWNoZTogZXZpY3QoAIEYCwATBSAKAAEGADocACIHAIE5Di0-IACCIwcAdQ0AgWsNSW5kZXhlcgCBLgUAgH8HbG9hZAB0EQoAfQg-IExvYWRlcgAWEgASBgoKABoGAII8CgBAEACBfAYAgyQgRklOSVNIRUQiLCAiVG9vayAyMG0gMTBzAIMMNwAqJQCDFgYAgxwnAINhCQCCCAgAhG4JAIJUgRsAgxQIAIRqCgCBIRUAg0MIAIRvCgCEIQcAgU8XAIQcB25vdGUgcmlnaHQgb2YAhj0HQ29udGFpbnMgAINICiEAGg8AhXcHACAKAIc4CCEK&s=rose)

**Comment by fdlk** [comment]
So to sum things up: This happens when a transaction commits that changes a row that is being loaded by the L2 cache. The commit triggers a call to evict() on the cache but that doesn't cancel the load and when the load finishes, the stale loaded version gets inserted into the cache.

This is a know bug in guava, and a different, compatible cache called caffeine doesn't display the bug.

I have written an integration test using a simplified version of the gavin job that occasionally reproduces the bug: [`testCacheBug()`](https://github.com/fdlk/molgenis/blob/reproduce/cachebug/molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformIT.java#L461)
It works by adding a long sleep in the cache loader to make it more likely that evictions happen while loading.

Applying the fix in this PR makes the test succeed.

**Comment by dennishendriksen** [comment]
Wow, great work spotting the issue in Guava!

**Comment by jjettenn** [comment]
👍
