### ISSUE TITLE
Error! Your import failed: Can not import file. No suitable importer found

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5658]
### How to Reproduce
Import: 
[TypeTestRef.tsv.zip](https://github.com/molgenis/molgenis/files/621417/TypeTestRef.tsv.zip)

or

[TypeTestRef.csv.zip](https://github.com/molgenis/molgenis/files/621418/TypeTestRef.csv.zip)

### Expected behavior
Imported

### Observed behavior
Error! Your import failed:
Can not import file. No suitable importer found

**Comment by Mark-de-Haan** [comment]
I wouldnt be suprised if it should be base_TypeTestRef
If It can not find the metadata, it will also throw this error (I think)

**Comment by jjettenn** [comment]
add base_ in the name
