### ISSUE TITLE
Can't import ontology as a user

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5660]
### How to Reproduce
1. Add a user
2. Give permissions:
a. sys_ImportRun entity
b. importwizard plugin
c. sys_ont_* entities
3. Log in as user
4. Import [biobank_ontology.owl.zip](https://github.com/molgenis/molgenis/files/621443/biobank_ontology.owl.zip)

### Expected behavior
Ontology is imported within a few seconds

### Observed behavior
Importer takes a long time, then throws generic "An error occurred" message

**Comment by dennishendriksen** [comment]
Cannot reproduce in 5.2.0-SNAPSHOT, user import finishes successfully within a couple of seconds.
