### ISSUE TITLE
Tagging attributes as a user requires WRITE permission on Attribute and EntityType

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5666]
### How to Reproduce
1. As admin, import [mappingservice-test.xlsx](https://github.com/molgenis/molgenis/files/621716/mappingservice-test.xlsx)
2. As admin, import [uo.owl.zip](https://github.com/molgenis/molgenis/files/621718/uo.owl.zip)
1. Add a user
2. Give permissions to user:
a. tagwizard plugin + Tag entity
b. All Ontology entities
c. All entities in mappingservice-test.xlsx 
3. Log in as user
4. Go to Tag Wizard
5. Add some tags

### Expected behavior
Tags are added

### Observed behavior
Errors: No WRITE permission for Attribute & EntityType

**Comment by dennishendriksen** [comment]
This observed behavior is the expected behavior. In order to improve usability of tagging for non-superusers we require row level security, see [story in the backlog](http://www.molgenis.org/ticket/3747).
