### ISSUE TITLE
DATE and DATE_TIME persisted with too much detail in PostgreSQL

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5674]
### How to Reproduce
1. Open data explorer, Token entity
2. Select a row to edit
3. Save without changing value
4. Save

### Expected behavior
Is saved

### Observed behavior
Error! The attribute 'creationDate' of entity 'sys_sec_Token' can not be changed it is readonly. (entity 1)

**Comment by Mark-de-Haan** [comment]
IMO this is how it should be. Tokens are generated by the system, and is a system entity. Read only is expected behaviour
