### ISSUE TITLE
Can't create EntityType via forms

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5681]
### How to Reproduce
1. Go to EntityType in data explorer
2. Add new EntityType
3. Fill in form and submit

### Expected behavior
EntityType is created

### Observed behavior
**Entity could not be created. Entity [test] is missing required ID attribute**

**Comment by dennishendriksen** [comment]
Closing this request for enhancement, see [backlog story](http://www.molgenis.org/ticket/4028).
