### ISSUE TITLE
Installation manual should document minimal versions of key components

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5702]
### How to Reproduce
* Go to the installation manual on molgenis.github.io and read the instructions

### Expected behavior
* I can tell what is the minimum version of tomcat, java, and database that I need to install MOLGENIS

### Observed behavior
* The manual doesn't specify the minimal versions

**Comment by fdlk** [comment]
We cannot fix this in this repository. Could you file this in the http://github.com/molgenis/molgenis.org repo instead?

**Comment by djvanenckevort** [comment]
Done: https://github.com/molgenis/molgenis.org/issues/54
