### ISSUE TITLE
Date datatype problems

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5717]
### How to Reproduce
Upload a date: 1976-13-03
View it in entity report.

### Expected behavior
1. Get error, there are only 12 months in a year
2. If date were correct, show only the date

### Observed behavior
1. MOLGENIS thinks to be smart and converts it to: 1977-01-03
2. Date type shows as datetime type and puts 0:00 after the date

**Comment by fdlk** [comment]
Fixed in 5.0.1 (and probably also in 4.1.0).
When importing I get:

> Conversion failure in entity type [it_emx_datatypes_TypeTest] attribute [xdatenillable]; Failed to convert from type [java.lang.String] to type [java.time.LocalDate] for value '1976-13-03'; nested exception is java.time.format.DateTimeParseException: Text '1976-13-03' could not be parsed: Invalid value for MonthOfYear (valid values 1 - 12): 13
