### ISSUE TITLE
Package for entity cannot be selected during EMX import

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5728]
### How to Reproduce
- Extract and import [it_emx_self_references.zip](https://github.com/molgenis/molgenis/files/661317/it_emx_self_references.zip) using the 'Upload' plugin
- In the 'Options' import step select 'Add'

### Expected behavior
- The 'Packages' import step displays the entity 'PersonTest' for package selection

### Observed behavior
- The 'Packages' import step displays no entities. Selecting package 'it_emx_selfreferences' followed by 'Next' results in the error 'File did not pass validation see results below. Please resolve the errors and try again.'

**Comment by Mark-de-Haan** [comment]
There was an error in your EMX, the datasheet also needs to have the fully qualified name
PersonTest should not be available in the package selection, because in your entities sheet, you specify that 'PersonTest' should be in the 'it_emx_selfreferences' package
