### ISSUE TITLE
When having a reference in an abstract entity and I want to delete the refEntity, I get a weird error message

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5741]
### How to Reproduce
Upload: 
[very_advanced_data_example_v20161214.xlsx](https://github.com/molgenis/molgenis/files/669003/very_advanced_data_example_v20161214.xlsx)
Delete patients and employees
Now you think all entities with references to "users" are gone, so you try to delete "users"
But you get a weird message: Error! Value 'root_hospital_users' for attribute 'fullName' is referenced by entity 'sys_md_Attribute'.
The abstract entity persons is still there, but the message does not really tell that. 

### Expected behavior
Give proper error message like: Abstract entity "Persons" has reference to this table. 

### Observed behavior
Error! Value 'root_hospital_users' for attribute 'fullName' is referenced by entity 'sys_md_Attribute'.

**Comment by marikaris** [comment]
This also happens when not referencing from an abstract entity. Each time you want to delete an entity that is used as ref entity, this error message is presented, which does not tell the user why the entity cannot be deleted.

**Comment by Mark-de-Haan** [comment]
I can delete users in version 5.3.0-SNAPSHOT
