### ISSUE TITLE
Weird behaviour in uploading dates: 1818-01-01 and 1818/01/01

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5742]
### How to Reproduce
uploading a date datatype with: 1818-01-01
loads perfectly and shows the proper date
uploading 1818/01/01 throws exception, telling it is not a valid date, while 1990/01/01 is a valid date

### Expected behavior
Uploading behaviour is the same for both ways of formatting (and I think it should be a proper date, it should not matter that it was long ago it still is a proper date)

### Observed behavior
The same dates, formatted differently, are handled differently.

**Comment by dennishendriksen** [comment]
@marikaris Feature request: please create a ticket titled something like 'Support yyyy/mm/dd date format in EMX' in Trac, put a link to the story in this issue and close the issue.

**Comment by marikaris** [comment]
Altered the issue, the problem is that the importer does accept the format, but not for certain years

**Comment by dennishendriksen** [comment]
Cannot reproduce. Unzipping [emx_5742.zip](https://github.com/molgenis/molgenis/files/802943/emx_5742.zip) and importing it results in ```Failed to convert from type [java.lang.String] to type [java.util.Date] for value '1990/01/01'; nested exception is java.lang.IllegalArgumentException: Invalid dateformat [1990/01/01] should be of format yyyy-MM-dd'T'HH:mm:ssZ OR yyyy-MM-dd OR yyyy-MM-dd HH:mm:ss```

**Comment by marikaris** [comment]
When making the date a "text" type in excel, I also cannot reproduce, so it was some "excel magic" i guess, but the "magic" only works for the 20th and 21th century. So agree, cannot reproduce.
