### ISSUE TITLE
Queries on referenced entity attribute reported invalid

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5751]
### How to Reproduce
- Extract and import [emx_nested_query.zip](https://github.com/molgenis/molgenis/files/698881/emx_nested_query.zip) using the 'Upload' plugin
- Select entity 'MyEntity' in the 'Data explorer' plugin
- In the 'Data item selection' panel set a filter from: 4 to 7 on attribute ref > int

### Expected behavior
- Table displays rows with ref > int in range [4, 7]

### Observed behavior
```Error! Query rule field [ref.int] refers to unknown attribute in entity type [usr_dennis_MyEntity]```

**Comment by bartcharbon** [comment]
when filtering for "label1" for the xxref.label in typetest this error does not occur. The error described in this issue is reproducable with the provided dataset on the same server.
