### ISSUE TITLE
I can't save an entity if it refers to another entity that has a colon (:) in it's idAttribute

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5754]
### How to Reproduce
- Create a model with two entities, where the first entity has a MREF to the second entity
- Create an instance of the second entity with an identifier that has a colon in it
- Create an instance of the first entity and select the instance of the second entity with the colon in it's id attribute

### Expected behavior
- The entity is created

### Observed behavior
- I get an error that the referenced entity cannot be found.

**Comment by djvanenckevort** [comment]
When uploading the entities as EMX it works fine. I suspect that there is an issue with encoding the idAttribute for the REST API.

**Comment by marikaris** [comment]
Which version of molgenis? It seems like I cannot reproduce it in 2.0 (or i might be doing it wrong...)

**Comment by marikaris** [comment]
Cannot be reproduced in 2.0

**Comment by dennishendriksen** [comment]
Cannot reproduce in 3.0 using existing Script and ScriptParameter entity types.
