### ISSUE TITLE
PostgreSQL undefined column exception exposes internal server message

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5760]
### How to Reproduce
- Cause a PostgreSQL exception ```undefined_column``` with error code ```42703```, see ```org.molgenis.data.postgresql.PostgreSqlExceptionTranslator```. For example by by changing the return value of ```PostgreSqlNameGenerator.getColumnName(Attribute attr, boolean quotedIdentifier)```

### Expected behavior
- Molgenis validation exception message: ```Attribute 'myAttr' of entity 'MyEntity' does not exist```

### Observed behavior
- Molgenis validation exception message: ```column "myColumn" does not exist```

**Comment by dennishendriksen** [comment]
The PostgreSQL exception does not contain the table, so the expected behavior cannot be produced from the exception. Log the PostgreSQL exception and return a MolgenisValidationException with a general unknown attribute exception message?

**Comment by Mark-de-Haan** [comment]
@dennishendriksen Will this issue be covered with the new global exception handling?

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Yes, the internal server message won't be exposed anymore. Unfortunately it will be replaced with a L10n version of ```A data access error occurred.```.

**Comment by dennishendriksen** [comment]
internal server message is not exposed anymore
