### ISSUE TITLE
Annotation fails with a "AnnotationJobExecution" not found.

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5763]
[data.zip](https://github.com/molgenis/molgenis/files/716916/data.zip)
![screen shot 2017-01-19 at 15 37 50](https://cloud.githubusercontent.com/assets/3714029/22111383/7184bb14-de5f-11e6-85ab-884a4455896c.png)

### How to Reproduce
upload the attached file
run cadd annotator

### Expected behavior
process finishes succesfull

### Observed behavior
error occurs, see attached screenshot

**Comment by Mark-de-Haan** [comment]
No references to sys_AnnotationJobExecution exist in the code base.
sys_job_AnnotationJobExecution is now the correct table. Can not reproduce in v5.3.0-SNAPSHOT
