### ISSUE TITLE
Mapping TypeTest (zip) on itself does not yield any autogenerated mappings

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5772]
### How to Reproduce
- load attached zip
- create a mapping service project mapping TypeTest on TypeTest

### Expected behavior
- almost all attributes have auto generated mappings (like for instance when you do the same with "it_emx_datatypes.xlsx")

### Observed behavior
- Not a single generated mapping. 
See screenshot.

[emx_all_datatypes.zip](https://github.com/molgenis/molgenis/files/723451/emx_all_datatypes.zip)
![screen shot 2017-01-23 at 12 44 32](https://cloud.githubusercontent.com/assets/3714029/22202792/198590d8-e16a-11e6-98a0-0a65f1db3735.png)

**Comment by Mark-de-Haan** [comment]
Auto mappings work in v5.3.0-SNAPSHOT
