### ISSUE TITLE
Root package has disappeared

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5776]
### How to Reproduce
Go to the Data explorer, select Package entity, look through the list of packages.

### Expected behavior
There is a single root package, like in 1.x.

### Observed behavior
There's a sys package and a base package and, depending on what other emx files have been imported, even more packages that are not the child package of any other packages.

Also, importer behavior has changed since it can no longer import entities into the root package. It will now import to the base package by default, resulting in a `base_` prefix for all imported entities that are not in a package.

This is especially tricky since molgenis doesn't have a not query functionality so I cannot think of a way to query for the list of top-level packages. (The ones that have no "_" in their name / that do not occur in any other package's children mref).

To fix this, perhaps we can create an xref parent and make children the one_to_many of that xref (I'm a bit scared of the consequences) or reintroduce the root package and put these packages as children of that package.

**Comment by mswertz** [comment]
During last architecture meeting we decided that ideally we wouldn't change anything. That would mean that querying for the root package == querying for all packages with parent=null

**Comment by fdlk** [comment]
@mswertz I don't think you can query for null value.

**Comment by Mark-de-Haan** [comment]
You can query for null value! `parent==""`
