### ISSUE TITLE
When mapping to target I get Runtime exception

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5782]
### How to Reproduce
Use mapping copy on molgenis21 with rd connect model v20, bioner data, ncl biomarker samples and ring14 samples. (in drive projects folder RD connect mariska and marieke)

### Expected behavior
mapping succeeds or gives appropriate message which tells what is wrong

### Observed behavior
java.lang.NumberFormatException: For input string: "org.molgenis.script.ScriptException: java.lang.RuntimeException: Unable to convert [ScriptObjectMirror]"
[mappingservice_stacktrace.txt](https://github.com/molgenis/molgenis/files/741367/mappingservice_stacktrace.txt)

**Comment by dennishendriksen** [comment]
@marikaris which MOLGENIS version? could you please add labels to this issue

**Comment by marikaris** [comment]
I noticed, I was editing as you typed ;)

**Comment by marikaris** [comment]
I had to use the intelliJ debugger to find the issue in my mapping, so a proper error message would be in place

**Comment by dennishendriksen** [comment]
@marikaris Is this the same issue as #5824?

**Comment by marikaris** [comment]
Not exactly, this one is about the error message being unclear
