### ISSUE TITLE
System entity metadata differs from persisted metadata

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5783]
### How to Reproduce
- In Java perform `metadataService.getEntityType` for an entity type that is extended by other entity types.
- Call 'entityType.getExtendedBy()'

### Expected behavior
- Method returns an Iterable containing the entity types extending this entity type

### Observed behavior
- Method returns an Iterable containing no items
- Executing `EntityType entityType = metadataService
				.getRepository(EntityTypeMetadata.ENTITY_TYPE_META_DATA, EntityType.class).findOneById(entityTypeId);` does show the expected behavior

**Comment by Mark-de-Haan** [comment]
EntityType no longer support `getExtendedBy()`

**Comment by dennishendriksen** [comment]
We should add a ONE_TO_MANY attribute EXTENDED_BY to EntityTypeMetaData.
