### ISSUE TITLE
When using SORTA, I cannot review my matches because I get an error

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5788]
### How to Reproduce
upload: 
[ordo_orphanet.owl.zip](https://github.com/molgenis/molgenis/files/747071/ordo_orphanet.owl.zip)
Go to sorta
Make the job like this:
![screen shot 2017-02-02 at 08 48 55](https://cloud.githubusercontent.com/assets/10075439/22541087/7609ad5a-e924-11e6-9a76-ebf06ec1f89b.png)
Press match

![screen shot 2017-02-02 at 08 44 06](https://cloud.githubusercontent.com/assets/10075439/22541053/3cb4a1a4-e924-11e6-9590-049b20389ca1.png)
press go to result
![screen shot 2017-02-02 at 08 44 15](https://cloud.githubusercontent.com/assets/10075439/22541104/8e03c36e-e924-11e6-8690-bd4bed461e20.png)
And press match
![screen shot 2017-02-02 at 08 44 23](https://cloud.githubusercontent.com/assets/10075439/22541115/9aa18e08-e924-11e6-9bf7-a53e0054e81d.png)

### Expected behavior
Seeing the matching screen

### Observed behavior
Weird error (I cannot find a stacktrace in my console...)

**Comment by dennishendriksen** [comment]
Fixed in #6720
