### ISSUE TITLE
Cannot delete an entity in the DataExplorer

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5789]
### How to Reproduce
1. Upload an entity 
2. Go to the data explorer and select the entity
3. Click on the delete button and select 'delete data and metadata'

### Expected behavior
The entity is deleted.

### Observed behavior
The entity is not deleted and I receive an error message:
Error! Unknown attribute for column name [fullName]

Tested on 2.1.0-SNAPSHOT built on 2017-02-02 01:11 UTC (molgenis01)

**Comment by marikaris** [comment]
duplicate #5773
