### ISSUE TITLE
Access to Data Explorer should not require explicit access to metadata

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5791]
### How to Reproduce
* Grant anonymous user access to the Data Explorer
* Access the data explorer as anonymous user

### Expected behavior
The anonymous user can see the data explorer and the entities to which he has access

### Observed behavior
I get an error that access to the sys_md_EntityType entity is necessary

Tested on MOLGENIS 2.0.0 built on 2016-12-02 10:04 UTC.

**Comment by mswertz** [comment]
this is as designed. Why is this important? You don't want to see 'system' entities in the pulldown? I believe that with implementation of navigator this issue goes away.

**Comment by djvanenckevort** [comment]
I think you misunderstood. The issue is that as aan administrator I need to give access to several system entities in order to make the data explorer work. If the data explorer needs access to the metadata it should be able get that access in a controlled manner through an internal API that is available for plugins, without the admin having to grant this access to each user.

Please remove icebox, this is a usability issue that makes deployment of MOLGENIS much harder than needed and exposes internals that should not be exposed.

**Comment by fdlk** [comment]
@djvanenckevort I think that, as a feature, plugin permissions should also grant the entity class permissions needed to use the plugin. Would that fix it or do you or do you think that's the wrong way to solve this?

**Comment by djvanenckevort** [comment]
@fdlk that would work, but it would still expose data that is part of the internals of MOLGENIS. I think it would be better to encapsulate the required access to the metadata in some API the plugin can use. That way MOLGENIS can change the way the metadata is stored without changing the plugins that require metadata access.

**Comment by fdlk** [comment]
@djvanenckevort What you're saying is that you don't like the "Metadata is just data" approach?

**Comment by djvanenckevort** [comment]
@fdlk I guess so :-)

**Comment by Mark-de-Haan** [comment]
Seeing as this is currently working as intended, pending any stories on this topic, I will close this issue
