### ISSUE TITLE
A user with access to the data explorer should not need explicit access to the data explorer settings

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5792]
### How to Reproduce
* Give the anonymous user access to the data explorer
* Go to the data explorer as anonymous user

### Expected behavior
The user can use the data explorer

### Observed behavior
The data explorer gives an error message that read access to sys_set_dataexplorer is necessary

Tested on MOLGENIS version 2.0.0 built on 2016-12-02 10:04 UTC
I believe this is a general principle, access to the plugin should include all access to make it work. The plugin should handle access to its settings and this should be opaque to the user or admin.

**Comment by fdlk** [comment]
We've a story to implement this feature: Plugin settings permissions should be set through the Plugin permissions instead of entity permissions http://www.molgenis.org/ticket/4338

**Comment by mswertz** [comment]
closed because there is a feature request story
