### ISSUE TITLE
Complex filters through the wizard don't work

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5793]
### How to Reproduce
- Go to the data explorer
- Click on the wizard button
- Enter a filter with two or more conditions.

### Expected behavior
- The data is filtered on the conditions
- Data item filters shows the active filters
- The URL is updated to reflect the active filters

### Observed behavior
- I get the following error:
`
Error! An error occurred. Please contact the administrator.
SyntaxError: Expected ",", ";", [^"'();,=!~<> ], or end of input but "=" found.
`

Tested on MOLGENIS 2.1.0-SNAPSHOT built on 2017-02-02 09:04 UTC.

**Comment by fdlk** [comment]
Tried on molgenis01, open filter wizard and in the first tab select country and biobank.
The attributeFilterRSQL that gets parsed is invalid because there's no separator between the constraints.
