### ISSUE TITLE
Enable byte code weaving to improve db performance

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#582]
Apply static weaving by adding <property name="eclipselink.weaving" value="static" /> to PersistenceGen.xml.ftl and running the eclipselink-staticweave-maven-plugin compile time. Alternatively use dynamic weaving using Spring: http://static.springsource.org/spring/docs/3.2.x/spring-framework-reference/html/orm.html#orm-jpa

Put the eclipselink log level to FINEST and inspect weaving messages to check if it is working as expected.

**Comment by Mark-de-Haan** [comment]
Story 3407 added to the backlog
