### ISSUE TITLE
In the newest version of Java Dates cannot be mapped

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5826]
### How to Reproduce
Load data from RD connect in java 8  patch 121
Map the data in the mapping service using the loaded mapping

### Expected behavior
Table is mapped because the mapping is correct (as it works in patch 60)

### Observed behavior
Error: for input string(epoch time string)

**Comment by Mark-de-Haan** [comment]
Can you give the data and the mappings?
