### ISSUE TITLE
Wrong generated entity equals/hashcode  

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#583]
When i define two entities:

```
<entity name="MUser">
			<field name="id" type="autoid" />
			<field name="username" unique="true" />
			<field name="password" />
		</entity>
		<entity name="MUserRole">
			<field name="id" type="autoid" />
			<field name="mUser" type="xref" xref_entity="MUser" />
			<field name="role" />
		</entity>
```

This is the equals and hashcode for the MUserRole:

    @Override
    public boolean equals(Object obj)
    {
	    if (this == obj) return true;
	    if (obj == null) return false;
	    if (getClass() != obj.getClass()) return false;
	    return true;
    }
	
    @Override
    public int hashCode()
    {
	    int result = 1;
	    return result;
    }

So two MUserRole objects always return equals true

**Comment by mswertz** [comment]
only fix at the moment you have to create workaround code to deal with this issue.

**Comment by erwinwinder** [comment]
Generators are removed
