### ISSUE TITLE
Catalogue does not display CATEGORICAL_MREF options

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5839]
### How to Reproduce
Import TypeTest
Go to Catalogue
Click categorical_mref

### Expected behavior
There are possible values, like categorical

### Observed behavior
no possible values

**Comment by dennishendriksen** [comment]
This is a bug for CATEGORICAL_MREF. The desired behavior for XREF and MREF is correct, because these lookup lists could contain millions of rows.
