### ISSUE TITLE
When uploading a date, the date is displayed minus a day

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5845]
### How to Reproduce
Upload the demo data: 
[very_advanced_data_example_v20170126.xlsx](https://github.com/molgenis/molgenis/files/796052/very_advanced_data_example_v20170126.xlsx)

Go to patients and look at date of death
In the EMX the date of death is for a number of patients 1998/05/02 (Fred Weasley for instance) and in the dataexplorer this date is 1998/05/01
### Expected behavior
1998/05/02 as date of death for Fred Weasley

### Observed behavior
1998/05/01 as date of death for Fred Weasley

**Comment by dennishendriksen** [comment]
I cannot import the example EMX file: ```Invalid characters in: [sample_types] Only letters (a-z, A-Z), digits (0-9) and hashes (#) are allowed.```. @marikaris Can you provide a working EMX file to reproduce this issue?

**Comment by marikaris** [comment]
Sorry, I dont know what happened with that file, here is a new one: 
[very_advanced_data_example_v20170126.xlsx](https://github.com/molgenis/molgenis/files/803624/very_advanced_data_example_v20170126.xlsx)

**Comment by fdlk** [comment]
I can reproduce

**Comment by fdlk** [comment]
Cell content, if I format as number, is 35917
