### ISSUE TITLE
Label of EntityType should not be "Entity" but "EntityType"

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5853]
### How to Reproduce
In the dropdown in the dataexplorer the EntityType table is displayed as "Entity"

### Expected behavior
I can select "EntityType"

### Observed behavior
I can select "Entity"

**Comment by mswertz** [comment]
We want to use simpler terminology so not 'entity' but 'row' and not 'entitytype' but 'table'

**Comment by Mark-de-Haan** [comment]
Fixed in v5.3.0-SNAPSHOT
