### ISSUE TITLE
VCFs are not imported to a package

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5857]
### How to Reproduce
- import a vcf file into molgenis

### Expected behavior
- file is imported and added to the "base" package

### Observed behavior
- file is imported and not added to a package at all

Furthermore there is no mechanism to choose a package for a VCF file in the import wizard.

**Comment by dennishendriksen** [comment]
Fixed by https://github.com/molgenis/molgenis/pull/7413
