### ISSUE TITLE
Copy functionality does not work for users

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5863]
### How to Reproduce
As admin import TypeTest
As user, with edit permissions on TypeTest, go to the dataexplorer
Press the copy button and name the entity UserCopy

### Expected behavior
A UserCopy entity is created

### Observed behavior
Error: Entity [it_emx_datatypes_UserCopy] does not exist

**Comment by dennishendriksen** [comment]
Fixed by #5878?

**Comment by ConnorStroomberg** [comment]
Not fixed with #5878 , expected behaviour is not seen.

Observed behaviour: "Error! Unknown entity [it_emx_datatypes_UserCopy]"

**Comment by marikaris** [comment]
Please attach file next time
