### ISSUE TITLE
When uploading a table with a type decimal column but not all values are decimals, the importer succeeds, but the table cannot be shown

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5865]
### How to Reproduce
Upload:
[test.xlsx](https://github.com/molgenis/molgenis/files/809962/test.xlsx)
Go to test

### Expected behavior
Importer fails telling me my data does not match my model

### Observed behavior
<img width="808" alt="screen shot 2017-03-01 at 08 41 25" src="https://cloud.githubusercontent.com/assets/10075439/23450441/840b7fea-fe5b-11e6-89a3-378cd2dee0dd.png">

Which leads to:
<img width="1262" alt="screen shot 2017-03-01 at 08 41 17" src="https://cloud.githubusercontent.com/assets/10075439/23450427/7190a778-fe5b-11e6-98bd-91891ec81452.png">

**Comment by fdlk** [comment]
Mark and I have taken a look.
* decimal data type is ill described in EMX, let's update the documentation
* In Java we use double
* In JavaScript we use number, which is a 64 bit double precision floating point number
* In Postgres database we use "double precision" data type

All of those in theory will happily accept the NaN value used in the excel sheet.
A couple hiccups prevent the NaN value from getting from A to B:

* The PostgreSQL row mapper reads the value using getBigDecimal() before converting to Double (why?!?) and that method doesn't like NaN. (We can use getDouble() instead)
* The GSON config is willing to parse NaN but by default not to serialize it. (We can use [serializeSpecialFloatingPointValues()](https://google.github.io/gson/apidocs/com/google/gson/GsonBuilder.html#serializeSpecialFloatingPointValues--) to force it to accept them)

However, the JSON parser in the browser rightly refuses to parse NaN and there is the final hiccup which makes it a bit hard to allow this value throughout molgenis.

**Comment by tommydeboer** [comment]
After discussion with @fdlk and @marikaris, we decided that the importer should fail on ```NaN```.
