### ISSUE TITLE
REST api update gives dateformat error

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5866]
### How to Reproduce
try the batch update request specified in:
https://docs.google.com/spreadsheets/d/1MGDCd3R6I5EkzPB9fV4spSoTx0F6obzxQCczQuIBv_4/edit#gid=186451052

line 17

### Expected behavior
200 OK

### Observed behavior
"Attribute [xdatetimenillable] value [1985-08-12T081213+0200] does not match date format [yyyy-MM-dd'T'HH:mm:ssZ]"

**Comment by bartcharbon** [comment]
possibly related to:  #4216

**Comment by dennishendriksen** [comment]
Error in test plan, the correct value is ```1985-08-12T08:12:13+0200```
