### ISSUE TITLE
Compound structure disappears after "eye" is clicked

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5867]
### How to Reproduce
import typetest
click the edit icon on a datarow in the dataexporer
![form_incl_compound](https://cloud.githubusercontent.com/assets/3714029/23454484/aed05050-fe6c-11e6-8b8e-d95a0d17cfd1.png)
click the eye symbol

### Expected behavior
nillable's are hidden, "compound headers" are still in place

### Observed behavior
nillable's are hidden and so ar the compound headers
![actual](https://cloud.githubusercontent.com/assets/3714029/23454483/aec55344-fe6c-11e6-91df-3984515cadc8.png)

**Comment by Mark-de-Haan** [comment]
Can not reproduce in 5.3.0-SNAPSHOT
