### ISSUE TITLE
When deleting row in source and mapping again to same target, row is not deleted in target

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5876]
### How to Reproduce
Upload: files in this folder: https://drive.google.com/drive/folders/0B7QjWv5iC182cEU4WWNjak1QTGM
Use HOP as target and lifelines and prefend as source
Map it to new entity (targetRepo)
Go to created entity, check if id 1 is present
Go to prefend
Delete row with id 1
Map again to same target
Check if id 1 is present (it is)

### Expected behavior
Id not present in source and target
### Observed behavior
Id present in target, not in source

**Comment by fdlk** [comment]
I think this behavior is actually needed if you want to map multiple sources to the same target.

**Comment by marikaris** [comment]
But it is described otherwise in the testplan

**Comment by ConnorStroomberg** [comment]
test plan, updated
