### ISSUE TITLE
REST API v1 and v2 will return all data when specifying num=0

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#5885]
### How to Reproduce
curl https://directory.bbmri-eric.eu/api/v2/eu_bbmri_eric_collections?num=0

### Expected behavior
Only the metadata is returned and no items, nextHref is set to get the first batch of items.

### Observed behavior
All data is returned.

**Comment by ConnorStroomberg** [comment]
I now see this issue needs to be fixed for rest api v1 as well. In rest api v1 pageSize is set to default if num size is set to "0". Maybe v2 needs the save behaviour ?

EntityCollectionRequestV2 has a \@Min annotation for the num field set to zero. maybe this should be changed to 1 to match v1 api behaviour.
