### ISSUE TITLE
REST v2 entity not exist errors for existing entity

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5887]
### How to Reproduce
- Intialize MOLGENIS with data located at ```molgenis@molgenis62 /srv/molgenis/backup_5887```
- GET ```https://<host>/api/v1/it_emx_datatypes_TypeTest```
Context: data manipulations took place on the package of TypeTest and the entity type itself. During some operations exceptions occurred.

### Expected behavior
- 200OK with content

### Observed behavior
- "Operation failed. Unknown entity: 'it_emx_datatypes_TypeTest'"
- The data set can be accessed through ```https://<host>/menu/main/dataexplorer?entity=it_emx_datatypes_TypeTest```

**Comment by dennishendriksen** [comment]
The issue cannot be reproduced when:
- Uploading https://github.com/molgenis/molgenis/blob/3.0/molgenis-platform-integration-tests/src/test/resources/xls/it_emx_datatypes.xlsx as superuser
- Editing package 'datatypes' label and description
- Deleting package 'it'

Performing these actions as non-superuser with the relevant permissions also does not reproduce the issue.

**Comment by dennishendriksen** [comment]
@tommydeboer @ConnorStroomberg which EMX file and which import options did you use in the metadata editing test suite setup?

**Comment by tommydeboer** [comment]
We used the default import options and **it_emx_datatypes.xlsx** from the integration test module

**Comment by ConnorStroomberg** [comment]
Retested using the "it_emx_datatypes.xlsx from the integration test module", can not reproduce the issue
