### ISSUE TITLE
Adding an attribute, deleting the entity and then upload the entity again does not work.

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5893]
### How to Reproduce
- upload 
[it_emx_datatypes.xlsx](https://github.com/molgenis/molgenis/files/821049/it_emx_datatypes.xlsx)
- add and attribute "newString"
- delete typetest
- upload the file again

### Expected behavior
- great success, typetest is present again in its original form without the added attribute

### Observed behavior
- during import:
column "newString" of relation "EntityType#6a3870a0" does not exist

**Comment by bartcharbon** [comment]
Unable to reproduce locally

**Comment by dennishendriksen** [comment]
Cannot reproduce as well.
