### ISSUE TITLE
Molgenis Integration Tests need the application database.

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5896]
### How to Reproduce
Try and run the molgenis Integration tests without "molgenis" db present

### Expected behavior
- works fine since a test db is created and used

### Observed behavior
- I cannot start the IT, the fail to initialise the application context
- if the "molgenis" db is there it works fine, and a new db is created and used.

**Comment by bartcharbon** [comment]
Furthermore I could not delete the "molgenis" db when an IT was still running.

**Comment by Mark-de-Haan** [comment]
No longer an issue in v5.3.0-SNAPSHOT.
Travis also runs IT tests without a molgenis db
