### ISSUE TITLE
REST API cannot check for id's with > in it

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5902]
### How to Reproduce
create dataset with a row with id: MEFV:c1437C>G
look in the rest api for this row using this query: /api/v2/yourtable?q=MEFV%3Ac1437C>G&num=10000
or this query
/api/v2/yourtable?q=MEFV%3Ac1437C%3EG&num=10000
(in your adress bar %3E will be converted to > anyway in chrome and firefox both)

### Expected behavior
you get one item with the id you requested

### Observed behavior
<img width="552" alt="screen shot 2017-03-08 at 15 42 30" src="https://cloud.githubusercontent.com/assets/10075439/23708460/40f72252-0416-11e7-8086-f99c6aeae6b1.png">

**Comment by dennishendriksen** [comment]
REST call is incorrect, the value of q should be of form <field><operator<value> instead of <value>
