### ISSUE TITLE
Adding attributes to abstract entities is broken

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5910]
### How to Reproduce
1. Upload [AddToAbstract-After.emx.xlsx](https://github.com/molgenis/molgenis/files/830629/AddToAbstract-After.emx.xlsx)
2. Go to the Attribute table
3. Add a new attribute:
 a. name = *anotherAttribute*
 b. entity = *Parent1*

### Expected behavior
**Parent1** has a new attribute 'anotherAttribute'

### Observed behavior
**Child1** has the new attribute. When you delete the attribute and try to add it again you get this error:
```Error! ; nested exception is org.postgresql.util.PSQLException: ERROR: column "anotherAttribute" of relation "Child2#2213925e" already exists```

**Comment by dennishendriksen** [comment]
Issues within an issue: PSQLException should not be exposed to user.
