### ISSUE TITLE
When copying an entity as user with only read permission, I can only edit my rows after I first deleted one

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5914]
### How to Reproduce
Upload 
[typetest.xlsx](https://github.com/molgenis/molgenis/files/830859/typetest.xlsx)

Create a user with read permissions on typetest (and its ref entities)
Log in with the user
Copy the entity
Try to edit a row in the altered entity
Error! (weird message, but means you do not have permissions)
Delete a row
Try edit again
It succeeds

### Expected behavior
I can edit a row after the copy entity is created

### Observed behavior
I first have to delete a row

**Comment by dennishendriksen** [comment]
Cannot reproduce on the current master branch. The 'Try to edit a row in the altered entity' action is performed without reporting any errors.

**Comment by marikaris** [comment]
Cannot be reproduced, must be fixed somewhere
