### ISSUE TITLE
When using the REST api v2 to update data I get an internal server error

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5926]
### How to Reproduce
Load data of BBMRI nl 
Mail Mariska for queries done on data and use these

### Expected behavior
Data gets updated, no error occurs

### Observed behavior
Data gets updated, but internal server error is also shown

**Comment by dennishendriksen** [comment]
The REST queries provided by Mariska and the resulting errors are probably caused by #5891 which is fixed in MOLGENIS 3.0.
