### ISSUE TITLE
It should be impossible to use mref as id attribute in the mapping service

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5938]
### How to Reproduce
Upload the demo dataset
[very_advanced_data_example_v20170126.xlsx](https://github.com/molgenis/molgenis/files/847764/very_advanced_data_example_v20170126.xlsx)
Create a mapping project with as source root_hospital_patients and as target the same. 
Map! (name dataset: test) 
Cannot map blablabla duplicate value blabla... 
Now alter the id to patient_id
Map again (name dataset: test) 
Mapping succeeds. 
Change the id to children again and map again to dataset test

Can also be reproduced by mapping to the source table. 

### Expected behavior
Cannot map blablabla duplicate value blabla... 

### Observed behavior
Mapping succeeds. Weird rows are in the table

**Comment by Mark-de-Haan** [comment]
The real issue is, is that the mapping service guessing algorithm is not really accurate. Closing.
