### ISSUE TITLE
Genome browser popups appear under the entity report

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5939]
### How to Reproduce
Put the Genome browser in an entity report. Open the entity report. Click on an item in one of the tracks.

### Expected behavior
A popup appears.

### Observed behavior
No popup. If you close the entity report, the popup is shown, it was hiding under the modal.

**Comment by ConnorStroomberg** [comment]
The issue appears to related to the fact that the genome browser itself is being shown inside a model. The modal that contains the genome browser itself had a z-index of 1040.

the gray modal background has a index of 1039

and the "popup" that is being hidden has a index of 1010 ( and therefore is hidden)

**Comment by ConnorStroomberg** [comment]
@bartcharbon please consider quick fix one, if this is not satisfactory, reopen the issue.

**Comment by bartcharbon** [comment]
Fixes/hacks influence the genome browser in the actual MOLGENIS window.

**Comment by bartcharbon** [comment]
fixed by adding this line to the entityreport:
`entitygenomebrowser.featurePopup = function empty() {}`
this does not influence the browser in the main dataexplorer itself
