### ISSUE TITLE
Removing filter with '>' in the filter value breaks data explorer

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5940]
### How to Reproduce
Surf to https://molgenis42.gcc.rug.nl/menu/main/dataexplorer?entity=col7a1_Patients&hideselect=true&mod=entitiesreport&filter=cDNAchange1==c.409C%3ET
The filter view shows a filter on change1.
Click the cross next to the filter

### Expected behavior
The filter is removed, all data is shown

### Observed behavior
> Error! An error occurred. Please contact the administrator.
SyntaxError: Expected ",", ";", [^"'();,=!~<> ], or end of input but ">" found.

**Comment by dennishendriksen** [comment]
The URL in how to reproduce is incorrect since it is missing double quotes to escape the RSQL value, the correct URL is [this](https://molgenis42.gcc.rug.nl/menu/main/dataexplorer?entity=col7a1_Patients&hideselect=true&mod=entitiesreport&filter=cDNAchange1=="c.409C%3ET").
