### ISSUE TITLE
Invalid swagger yaml if entity name contains `#`

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5944]
### How to Reproduce
Upload entity with # in the name.
Open swagger plugin

### Expected behavior
Swagger yaml is valid

### Observed behavior
Error message in bottom right of screen complains that Swagger yaml is invalid

**Comment by dennishendriksen** [comment]
Related to #5930

**Comment by fdlk** [comment]
Seen this at EOS on molgenis01, with an entity named Something#1 and Something#2.
But cannot reproduce this anymore.
Closing the issue.
