### ISSUE TITLE
Cmd line annotator doesn't support bgzip input/output

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5972]
#### How to Reproduce
- Add the resources and command line annotator integration tests from #5972 to code base
- Execute integration tests: gonlVcfInBgzipVcfOut, gonlBgzipVcfInVcfOut and gonlBgzipVcfInBgzipVcfOut

#### Expected behavior
- Tests succeed

#### Observed behavior
- Tests fail

**Comment by ConnorStroomberg** [comment]
Please add steps to reproduce, expected and observed behaviour so the fix may be reviewed and tested.

**Comment by dennishendriksen** [comment]
@ConnorStroomberg done
