### ISSUE TITLE
When deleting a package, the entities are not deleted from data explorer dropdown

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5984]
### How to Reproduce
Upload model2 and 4 on drive in folder projects/Leiden, search for RP in dropdown, you see:
![screen shot 2017-03-28 at 14 34 51](https://cloud.githubusercontent.com/assets/10075439/24405054/beb48830-13c3-11e7-85c8-1ab388277157.png)
Go to Packages
Delete WP2
Go to dropdown again, typ RP

### Expected behavior
Only see one RP entity (which directs to leiden_RP)

### Observed behavior
![screen shot 2017-03-28 at 14 34 51](https://cloud.githubusercontent.com/assets/10075439/24405107/f302d3ee-13c3-11e7-8124-148150fde552.png)

**Comment by marikaris** [comment]
When refreshing, they disappear, but this is weird

**Comment by Mark-de-Haan** [comment]
Known issue, the list of entities is added to the FreemarkerModel on page load, so the list will not refresh untill you refresh the page
