### ISSUE TITLE
Broken links and outdated README.md

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5991]
### How to Reproduce
- Navigate to https://github.com/molgenis/molgenis/
- Inspect documentation at the bottom of the page

### Expected behavior
- Links to https://molgenis.gitbooks.io/
- No links to https://molgenis.github.io/

### Observed behavior
- No links to https://molgenis.gitbooks.io/
- Links to https://molgenis.github.io/
- Broken link at the bottom
```
Documentation

{% include "./docs/SUMMARY.md" %}
```

**Comment by Mark-de-Haan** [comment]
Fixed in  #6007
