### ISSUE TITLE
MOLGENIS documentation should use consistent example URLs compliant with RFC 2606

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6031]
### How to Reproduce
Go to the REST and FAIR Datapoint sections to see examples of the differences.

### Expected behaviour
Consistent example URLs are used in the documentation, this usage is explained and compliant with RFC 2606.

### Observed behaviour
URLs vary throughout the documentation and are not compliant with RFC 2606.

**Comment by Mark-de-Haan** [comment]
Hey David,

I have no idea what RFC 2606 compliant means, feel free to update and create a PR

**Comment by djvanenckevort** [comment]
https://www.rfc-editor.org/rfc/rfc2606.txt
