### ISSUE TITLE
Server keeps indexing when applying mapping several times

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6047]
### How to Reproduce
Go to molgenis80 using ssh and in browser
tail -1000f apache-tomcat/logs/catalina.out
run on the server this mapping: Mappings for the EuroBiobank - Met UCL en nieuwe NCL
map to the entity: catalogue
do this three times

### Expected behavior
Mappings finish properly each time without excessive logging

### Observed behavior
First time mappings are soon done, and the server tells you so
Second time, server is indexing for half an hour repeating messages in the log (it logs way too much, it repeats everytime and puts the new logs after the repeated part)
Third time: indexing is now in progress for 45 minutes, still repeating itself

**Comment by Mark-de-Haan** [comment]
Can no longer be reproduced in v5.3.0-SNAPSHOT
