### ISSUE TITLE
Error when trying to tag an entity in the TagWizard

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6051]
### How to Reproduce
Import these files
- [uo.owl.zip](https://github.com/molgenis/molgenis/files/1021468/uo.owl.zip)
- [biobank_ontology.owl.zip](https://github.com/molgenis/molgenis/files/1021469/biobank_ontology.owl.zip)
- [mappingservice-test.xlsx](https://github.com/molgenis/molgenis/files/1021477/mappingservice-test.xlsx)

Go to the tagwizard
Tag Body_Mass_Index with Height and Weight

### Expected behavior
Succesfull tagging

### Observed behavior
```
 Call to TraversableResolver.isReachable() threw an exception
javax.validation.ValidationException: Call to TraversableResolver.isReachable() threw an exception
```

**Comment by dennishendriksen** [comment]
@Mark-de-Haan can you attach the files?

**Comment by fdlk** [comment]
Happened in just about all methods of the TagWizard.
