### ISSUE TITLE
Various errors when blocking third-party cookies

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6060]
### How to Reproduce
1. Block third-party cookies and site data (in Chrome: Settings > Advanced > Privacy > Content Settings...
2. Go to MOLGENIS

### Expected behavior
Site works as intended. If Google Analytics is turned on, user should not be tracked and not receive any warnings.

### Observed behavior
Every page shows an error:

```
Error! An error occurred. Please contact the administrator.
Script error.
```

And the Log out button doesn't work.

**Comment by dennishendriksen** [comment]
Duplicate of #5869
