### ISSUE TITLE
EntityModelWriter treats DATE values as dateTime

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6066]
### How to Reproduce
Let EntityModelWriter serialize a DATE attribute
(e.g. run testCreateRfdModelDATE unit test)

### Expected behavior
xml schema type is date and value shows only date value

### Observed behavior
(see expected value in unit test)
xml schema type is dateTime and value includes time value

**Comment by Mark-de-Haan** [comment]
3.0 as well?

**Comment by fdlk** [comment]
@Mark-de-Haan yes 3.0 as well, fixed in #6032
