### ISSUE TITLE
Importer doesn't throw error when user tries to import data for abstract entity

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6081]
### How to Reproduce
Import *it_emx_lookup_attribute.xlsx*, which contains a datasheet for abstract entity **Ref1** 

### Expected behavior
Importer throws an error explaining that the user is trying to import data to an abstract entity.

### Observed behavior
The datasheet is ignored.

**Note**: when fixing this issue, also update our test files:
- *it_emx_lookup_attribute.xlsx* (contains data sheet for abstract **Ref1**)
- *it_emx_deep_nesting.xlsx* (contains data sheet for abstract **TestEntity1**)

**Comment by Mark-de-Haan** [comment]
Can no longer reproduce in 5.3.0-SNAPSHOT.
