### ISSUE TITLE
When uploading vcf using curl, entitiyName argument is now entityTypeId, but no warning is given

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6095]
### How to Reproduce
Upload: [your-path]/git/molgenis/molgenis-data-annotators/target/test-classes/hpo/test.vcf
Copy: [your-path]/git/molgenis/molgenis-app/target/test-classes/vcf/di@gno$&.vcf to another place in your file system and rename it to diagno.vcf or something else valid
Run the following commands:
curl -H "x-molgenis-token:[TOKEN]" -X POST -F"file=@[your-path]/git/molgenis/molgenis-data-annotators/target/test-classes/hpo/test.vcf" -FentityName=test -Fnotify=true [molgenis-url]/plugin/importwizard/importFile
curl -H "x-molgenis-token:[TOKEN]" -X POST -F"file=@[your-path]/diagno.vcf" -Faction=add -FentityName=test [molgenis-url]/plugin/importwizard/importFile

### Expected behavior
Unrecognized argument: entityName

### Observed behavior
Entity is created with the name of the file, the given entityname seems to be ignored, but the argument is invalid and now should be named: entityTypeId.

**Comment by Mark-de-Haan** [comment]
This is covered by documentation. Closing.
