### ISSUE TITLE
Downloaded metadata inconsistent with existing metadata

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6110]
### How to Reproduce
Do the emx downloader test sheet

### Expected behavior
Downloaded metadata is compatible with the original metadata

### Observed behavior
Test case 4 fails, the original EMX file refuses to upload in add/update mode, complaining that the metadata is incompatible, making the download / update roundtrip harder than it needs to be.

Manual inspection hows that the values of auto, lookupAttribute and labelAttribute are different from the original values. The metadata reported by /meta gives the derived values, but the compatibility check doesn't take that into account.

**Comment by mswertz** [comment]
Expected behavior incorrect?

**Comment by fdlk** [comment]
@mswertz updated expected behavior

**Comment by Mark-de-Haan** [comment]
Duplicate of #6024
