### ISSUE TITLE
File ingest is broken

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6141]
### How to Reproduce
* Import [city.xlsx](https://github.com/molgenis/molgenis/files/979794/city.xlsx).
* Create a new FileIngest job, set the URL to http://molgenis26.target.rug.nl/downloads/omx/city.csv and target entity to the base_city entity you just imported.
* Press play on the job.

### Expected behavior
Cities get imported.

### Observed behavior
Job fails
> Failed. Null id

**Comment by fdlk** [comment]
Just checked, it fails on molgenis09

**Comment by fdlk** [comment]
@bartcharbon tested on 4.0 RC1, it worked fine then.

**Comment by tommydeboer** [comment]
File wasn't served correctly by download server. Correct file to use is:
https://molgenis26.target.rug.nl/downloads/molgenis-release-test/city.csv
