### ISSUE TITLE
Metadata of abstract entity cannot be altered

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6143]
### How to Reproduce
Upload 
[vkgl_prod_08052017_without_data.xlsx](https://github.com/molgenis/molgenis/files/983325/vkgl_prod_08052017_without_data.xlsx)

Go to Attributes
Try to set the attribute "timestamp" to AUTO true

### Expected behavior
Attribute updates

### Observed behavior
<img width="767" alt="screen shot 2017-05-08 at 13 29 42" src="https://cloud.githubusercontent.com/assets/10075439/25802919/d68f88dc-33f4-11e7-9e1b-fed4da035d14.png">

**Comment by dennishendriksen** [comment]
Relevant issue #6282

**Comment by dennishendriksen** [comment]
```java
public void addAttribute(EntityType entityType, Attribute attribute)
{
  EntityType updatedEntityType = entityTypeCopier.copy(entityType);
  Attribute attributeCopy = attributeCopier.copy(attribute);
  // Issue cause: in case of abstract entity types this is a concrete entity type
  updatedEntityType.addAttribute(attributeCopy);
  ...
}
```

**Comment by dennishendriksen** [comment]
Cannot reproduce in 7.1
