### ISSUE TITLE
Simple Python script sometimes does not produce output

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6185]
### How to Reproduce
Create a script according to python testplan:

```
Name: pythontest
Type: python
Content: print "Hello ${name}"
Generate security token: N/A
Parameters: name
```

run script with name MOLGENIS

### Expected behaviour
Showing log will show Hello MOLGENIS as output

### Observed behaviour
No output

**Comment by fdlk** [comment]
I suspect it's a threading issue where the output appended to the log gets lost between the read and the write of the log value.
