### ISSUE TITLE
Error roundtripping rsql query

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6189]
### How to Reproduce
Surf to https://molgenis62.gcc.rug.nl/menu/main/dataexplorer?entity=it_emx_datatypes_TypeTest&mod=data&filter=(xmrefnillable_value==ref3,xmrefnillable_value==ref2,xmrefnillable_value==ref1)
Open filter dialog for xmrefnillable_value

### Expected behavior
Single filter with three values

### Observed behavior
Three filters with each one value
If you correct the filter, you get an error

> unknown query operator [undefined]

**Comment by fdlk** [comment]
Duplicate

**Comment by Mark-de-Haan** [comment]
in 5.3.0-SNAPSHOT, a single filter requires the xmrefnillable_value=in=(ref1, ref2, ref3)
Your example will indeed generate 3 separate filters. This is working as intended
