### ISSUE TITLE
Failing query when searching for many values in an mref

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6223]
### How to Reproduce
- Go to the bbmri-eric directory
- Click on the Wizard
- Click on Donor Data
- For diagnosis_available fill in J4 and select all codes that show up
- Click on Apply

### Expected behavior
The directory shows all matching collections

### Observed behavior
An error pops up with an SQL error:
```Error! ; nested exception is org.springframework.dao.DataAccessResourceFailureException: PreparedStatementCallback; SQL [SELECT COUNT(DISTINCT this."id") FROM "eu_bbmri_eric_collections" AS this LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter1" ON (this."id" = "diagnosis_available_filter1"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter2" ON (this."id" = "diagnosis_available_filter2"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter3" ON (this."id" = "diagnosis_available_filter3"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter4" ON (this."id" = "diagnosis_available_filter4"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter5" ON (this."id" = "diagnosis_available_filter5"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter6" ON (this."id" = "diagnosis_available_filter6"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter7" ON (this."id" = "diagnosis_available_filter7"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter8" ON (this."id" = "diagnosis_available_filter8"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter9" ON (this."id" = "diagnosis_available_filter9"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter10" ON (this."id" = "diagnosis_available_filter10"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter11" ON (this."id" = "diagnosis_available_filter11"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter12" ON (this."id" = "diagnosis_available_filter12"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter13" ON (this."id" = "diagnosis_available_filter13"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter14" ON (this."id" = "diagnosis_available_filter14"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter15" ON (this."id" = "diagnosis_available_filter15"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter16" ON (this."id" = "diagnosis_available_filter16"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter17" ON (this."id" = "diagnosis_available_filter17"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter18" ON (this."id" = "diagnosis_available_filter18"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter19" ON (this."id" = "diagnosis_available_filter19"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter20" ON (this."id" = "diagnosis_available_filter20"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter21" ON (this."id" = "diagnosis_available_filter21"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter22" ON (this."id" = "diagnosis_available_filter22"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter23" ON (this."id" = "diagnosis_available_filter23"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter24" ON (this."id" = "diagnosis_available_filter24"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter25" ON (this."id" = "diagnosis_available_filter25"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter26" ON (this."id" = "diagnosis_available_filter26"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter27" ON (this."id" = "diagnosis_available_filter27"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter28" ON (this."id" = "diagnosis_available_filter28"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter29" ON (this."id" = "diagnosis_available_filter29"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter30" ON (this."id" = "diagnosis_available_filter30"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter31" ON (this."id" = "diagnosis_available_filter31"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter32" ON (this."id" = "diagnosis_available_filter32"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter33" ON (this."id" = "diagnosis_available_filter33"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter34" ON (this."id" = "diagnosis_available_filter34"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter35" ON (this."id" = "diagnosis_available_filter35"."id") LEFT JOIN "eu_bbmri_eric_collections_diagnosis_available" AS "diagnosis_available_filter36" ON (this."id" = "diagnosis_available_filter36"."id") WHERE ("diagnosis_available_filter1"."diagnosis_available" = ? OR "diagnosis_available_filter2"."diagnosis_available" = ? OR "diagnosis_available_filter3"."diagnosis_available" = ? OR "diagnosis_available_filter4"."diagnosis_available" = ? OR "diagnosis_available_filter5"."diagnosis_available" = ? OR "diagnosis_available_filter6"."diagnosis_available" = ? OR "diagnosis_available_filter7"."diagnosis_available" = ? OR "diagnosis_available_filter8"."diagnosis_available" = ? OR "diagnosis_available_filter9"."diagnosis_available" = ? OR "diagnosis_available_filter10"."diagnosis_available" = ? OR "diagnosis_available_filter11"."diagnosis_available" = ? OR "diagnosis_available_filter12"."diagnosis_available" = ? OR "diagnosis_available_filter13"."diagnosis_available" = ? OR "diagnosis_available_filter14"."diagnosis_available" = ? OR "diagnosis_available_filter15"."diagnosis_available" = ? OR "diagnosis_available_filter16"."diagnosis_available" = ? OR "diagnosis_available_filter17"."diagnosis_available" = ? OR "diagnosis_available_filter18"."diagnosis_available" = ? OR "diagnosis_available_filter19"."diagnosis_available" = ? OR "diagnosis_available_filter20"."diagnosis_available" = ? OR "diagnosis_available_filter21"."diagnosis_available" = ? OR "diagnosis_available_filter22"."diagnosis_available" = ? OR "diagnosis_available_filter23"."diagnosis_available" = ? OR "diagnosis_available_filter24"."diagnosis_available" = ? OR "diagnosis_available_filter25"."diagnosis_available" = ? OR "diagnosis_available_filter26"."diagnosis_available" = ? OR "diagnosis_available_filter27"."diagnosis_available" = ? OR "diagnosis_available_filter28"."diagnosis_available" = ? OR "diagnosis_available_filter29"."diagnosis_available" = ? OR "diagnosis_available_filter30"."diagnosis_available" = ? OR "diagnosis_available_filter31"."diagnosis_available" = ? OR "diagnosis_available_filter32"."diagnosis_available" = ? OR "diagnosis_available_filter33"."diagnosis_available" = ? OR "diagnosis_available_filter34"."diagnosis_available" = ? OR "diagnosis_available_filter35"."diagnosis_available" = ? OR "diagnosis_available_filter36"."diagnosis_available" = ?)]; ERROR: could not write to hash-join temporary file: No space left on device; nested exception is org.postgresql.util.PSQLException: ERROR: could not write to hash-join temporary file: No space left on device```

### Notes
The system creates multiple left joins with the eu_bbmri_eric_collections_diagnosis_available table, which is not necessary and leads to the creation of a large temporary table.

**Comment by fdlk** [comment]
molgenis@molgenis83 ~> df -k
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/vda1       14987656 6949816   7269840  49% /
tmpfs            1962256       4   1962252   1% /dev/shm

**Comment by dennishendriksen** [comment]
Another example using ```molgenis-platform-integration-tests\src\test\resources\xls\it_emx_datatypes.xlsx``` when filtering ```xmref_value``` on ```label1``` OR ```label2```:
```sql
SELECT DISTINCT this."id" FROM "it_emx_datatypes_TypeTest#8a25d662" AS this 
  LEFT JOIN "it_emx_datatypes_TypeT#8a25d662_xmref_value" AS "xmref_value_filter1" ON (this."id" = "xmref_value_filter1"."id") 
  LEFT JOIN "it_emx_datatypes_TypeT#8a25d662_xmref_value" AS "xmref_value_filter2" ON (this."id" = "xmref_value_filter2"."id") 
  WHERE ("xmref_value_filter1"."xmref_value" = 'ref1'  OR "xmref_value_filter2"."xmref_value" = 'ref2')
```
The following query returns the same result:
```sql
SELECT DISTINCT this."id" FROM "it_emx_datatypes_TypeTest#8a25d662" AS this 
  LEFT JOIN "it_emx_datatypes_TypeT#8a25d662_xmref_value" AS "xmref_value" ON (this."id" = "xmref_value"."id") 
  WHERE ("xmref_value" = 'ref1'  OR "xmref_value" = 'ref2')
```
I remember the 'filter' thing being introduced to fix a querying issue, but not know which issue ...

**Comment by dennishendriksen** [comment]
Example with two mref attributes referencing the same entity type:
```sql
SELECT DISTINCT this."id" FROM "it_emx_datatypes_TypeTest#8a25d662" AS this
  LEFT JOIN "it_emx_datatypes_TypeT#8a25d662_xmref_value" AS "xmref_value_filter1" ON (this."id" = "xmref_value_filter1"."id")
  LEFT JOIN "it_emx_datatypes_TypeT#8a25d662_xmref_value" AS "xmref_value_filter2" ON (this."id" = "xmref_value_filter2"."id")
  LEFT JOIN "it_emx_datatypes_TypeT#8a25d662_xmrefnillable_value" AS "xmrefnillable_value_filter3" ON (this."id" = "xmrefnillable_value_filter3"."id")
  LEFT JOIN "it_emx_datatypes_TypeT#8a25d662_xmrefnillable_value" AS "xmrefnillable_value_filter4" ON (this."id" = "xmrefnillable_value_filter4"."id")
WHERE (("xmref_value_filter1"."xmref_value" = 'ref1'  OR "xmref_value_filter2"."xmref_value" = 'ref2') AND ("xmrefnillable_value_filter3"."xmrefnillable_value" = 'ref3'  OR "xmrefnillable_value_filter4"."xmrefnillable_value" = 'ref4'))
```
The previous rewrite *won't work* since two joins are actually required here (different data):
```sql
SELECT DISTINCT this."id" FROM "it_emx_datatypes_TypeTest#8a25d662" AS this
  LEFT JOIN "it_emx_datatypes_TypeT#8a25d662_xmref_value" AS "xmref_value" ON (this."id" = "xmref_value"."id")
WHERE (("xmref_value"."xmref_value" = 'ref1'  OR "xmref_value"."xmref_value" = 'ref2') AND ("xmref_value"."xmref_value" = 'ref3'  OR "xmref_value"."xmref_value" = 'ref4'))
```

**Comment by fdlk** [comment]
client-side it could generate an IN query instead of a ton of OR query rules

**Comment by dennishendriksen** [comment]
Solution strategies:
1. Fix PostgresSqlRepository such that it produces better queries (advantage: solves this issue and similar issues, disadvantage: high impact fix)
2. Fix dataexplorer filter to produce an IN query rule instead of OR query rules (advantage: low impact fix, disadvantage: join-explosion issue not solved, same query on data service will result in same issue, filter code is untested and hard to adjust)
3. Extend query repository decorator with functionality to rewrite MOLGENIS queries (advantage: easy to implement and test, other backend implements don't have to deal with strange queries, normalized queries are cached) disadvantage: issue will still occur for other queries such as AND's)

What do you think @fdlk?

**Comment by fdlk** [comment]
@dennishendriksen 
Agreed. In the end we need to fix both 1 and 2 I think, but for this bug either one will do.
1 seems a bit hairy to me, the OR case should be fixable but keeping AND on mref values working may be harder
2 seems easier to me, Mark and I walked around in the filter code in January and it wasn't as horrible as rumors would have it :)
3 seems a bit of an odd workaround, and can also bite you in the back when debugging queries that are getting rewritten by the middle man. Should be easy enough to just generate a simpler query whenever we generate one

Owh and:
4. detect these cases and delegate to elasticsearch
