### ISSUE TITLE
One_to_many issues bbmri eric data

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6237]
### How to Reproduce
Case 1
Upload: 
[eric_one_to_many_test.xlsx](https://github.com/molgenis/molgenis/files/1073785/eric_one_to_many_test.xlsx)
Case 2
Upload: 
[eric_one_to_many_test_another.xlsx](https://github.com/molgenis/molgenis/files/1073791/eric_one_to_many_test_another.xlsx)

### Expected behavior
Uploads perfectly, having one_to_many's in the model

### Observed behavior
Case 1
<img width="1275" alt="screen shot 2017-06-14 at 08 55 38" src="https://user-images.githubusercontent.com/10075439/27119865-dac9a1e4-50e1-11e7-9e74-3529268cc153.png">
Case 2
<img width="872" alt="screen shot 2017-06-14 at 08 56 03" src="https://user-images.githubusercontent.com/10075439/27119902-f4968100-50e1-11e7-9f51-c37324558486.png">

**Comment by dennishendriksen** [comment]
Error in your data: duplicate column 'mappedBy' without any data in column X. After removing the duplicate column Case 1 imports successfully.
