### ISSUE TITLE
Attribute enumOptions in REST response are not consistent with our existing Attribute types

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6245]
### How to Reproduce
Use `api/v2/sys_md_Attribute/meta/type`

### Expected behavior
Attribute types are STRING and INT,
expected the enumOptions list to contain these as well

### Observed behavior
enumOptions in api response are lower case. 
Using these when editing Attribute types will result in `No enum constant org.molgenis.data.meta.AttributeType.string` or `No enum constant org.molgenis.data.meta.AttributeType.int`

**Comment by ConnorStroomberg** [comment]
Possibly add this as a test case to the REST test set ?

**Comment by dennishendriksen** [comment]
REST API metadata response differs from the internal Attribute representation, this is by design to assure that the API doesn't change when AttributeMetaData changes. @Mark-de-Haan Can you include the HTTP request causing this issue?

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Can you add a version label?

**Comment by dennishendriksen** [comment]
@Mark-de-Haan I would appreciate a reply to my previous comments

**Comment by Mark-de-Haan** [comment]
Not an issue, as separation between technical model and frontend model is good to have.
