### ISSUE TITLE
PostgreSqlIdGenerator throws null pointer exception if an Attribute object has no 'name' attribute

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6246]
Code causing the null pointer:
```java
@Override
public String generateId(Attribute attribute)
{
    String attrName = attribute.getName();
    if (PATTERN_WORD.matcher(attrName).matches() && attrName.length() <= maxIdentifierByteLength) 
    {
        return attrName;
    }
    else
    {
        String idPart = generateHashcode(attribute.getIdentifier());
	String namePart = truncateName(cleanName(attribute.getName()));
	return namePart + SEPARATOR + idPart;
    }
}
```
PostgreSqlIdGenerator.java line: 41-55

**Comment by dennishendriksen** [comment]
Attribute.name cannot be null according to its metadata, so the issue is upstream.
@Mark-de-Haan how to reproduce?

**Comment by dennishendriksen** [comment]
@Mark-de-Haan can you add a version label?

**Comment by Mark-de-Haan** [comment]
This was an issue during development in the Metadata manager.
Attribute.name is not allowed to be null according to its Metadata

**Comment by Mark-de-Haan** [comment]
This was an issue during the development of the Metadata manager.
Should not occur normally.
