### ISSUE TITLE
Error on updating form that has a non empty file input

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#6249]
### How to Reproduce
Fill out a form that has a input element of type file-input ( the create new app form for example). 
Make sure to select a file as part of filling out the form, and save the form.
Now try to edit the a field ( for instance description ) in the form.

### Expected behavior
A successful change to the form data. 

### Observed behavior
A error is thrown containing the following message; 

> This input element accepts a filename, which may only be programmatically set to the empty string.

The browser view setting the value of the fileinput element though code as a security risk.

**Comment by bartcharbon** [comment]
duplicate of https://github.com/molgenis/molgenis/issues/5532
