### ISSUE TITLE
MOLGENIS documentation should warn that you should use the AJP protocol from proxies

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6264]
### How to Reproduce
- Go to the installation instruction for MOLGENIS in the manual

### Expected behavior
- The installation instructions should note special considerations such as requiring AJP if you use a proxy in front of Tomcat
- We should refer to AJP documentation such as http://httpd.apache.org/docs/2.4/mod/mod_proxy_ajp.html on how to configure things instead of writing extensive documentation

### Observed behavior
- The installation instructions do not tell this.

**Comment by mswertz** [comment]
is there way to have molgenis test this?

**Comment by fdlk** [comment]
I think we should document *why* you'd want to proxy with apache httpd to begin with!

**Comment by djvanenckevort** [comment]
> Op 2 jul. 2017, om 14:21 heeft Fleur Kelpin <notifications@github.com> het volgende geschreven:
> 
> I think we should document why you'd want to proxy with apache httpd to begin with!

A few reasons why I would do it:
- allows tomcat to run as an unprivileged user
- allows load balancing
- allows mod_security as an application firewall
- allows integration with other web applications that use different technologies and that are not container based

-- 
David van Enckevort, MA
Project Manager
Dept of Genetics, UMCG
+31 (0)6 54 33 22 76
Skype: enckevort76

**Comment by Mark-de-Haan** [comment]
See #6948
