### ISSUE TITLE
Problem when indexing entity with many references to it

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6266]
Look at [**this code**](https://github.com/molgenis/molgenis/blob/23053c6d63b98acb6285bcdb74227985d01ce115/molgenis-data-index/src/main/java/org/molgenis/data/index/IndexActionRegisterServiceImpl.java#L167-L169) in ```IndexActionRegisterServiceImpl```. Conclude that because of the query it caps at the default page size of 1000 and therefore may skip indexing entities when there are many references. In actuality it should be paging through all the references.

**Comment by fdlk** [comment]
Fixed when we introduced the dependency model I think.

**Comment by fdlk** [comment]
Yup. Fixed in 5.0
