### ISSUE TITLE
Mapping Service won't auto-map any attributes when using (old) dataset

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6279]
### How to Reproduce
1. Import [emx_all_datatypes.xlsx](https://github.com/molgenis/molgenis/files/1102342/emx_all_datatypes.xlsx)
2. Create a new Mapping Project with *org_molgenis_test_TypeTest* as target
3. Add *org_molgenis_test_TypeTest* as a source

### Expected behavior
Source is added and most of the attributes are automatically mapped.

### Observed behavior
Source is added and not one attribute is mapped automatically.

**Comment by dennishendriksen** [comment]
@tommydeboer can you add a version label?

**Comment by Mark-de-Haan** [comment]
Can no longer reproduce in 5.3.0-SNAPSHOT
