### ISSUE TITLE
Job's view page refreshing interferes with ability to use the system

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6286]
### How to Reproduce
- Go to the Admin -> Jobs page

### Expected behavior
- I can see the jobs and interact with them

### Observed behavior
- Continuous refreshing interferes with the ability to interact with the system

**Comment by fdlk** [comment]
Is not reproducible everywhere.

**Comment by djvanenckevort** [comment]
> Op 28 jun. 2017, om 10:54 heeft Fleur Kelpin <notifications@github.com> het volgende geschreven:
> 
> Is not reproducible everywhere.

I have a screen recording to show the issue if you want.

-- 
David van Enckevort, MA
Project Manager
Dept of Genetics, UMCG
+31 (0)6 54 33 22 76
Skype: enckevort76

**Comment by fdlk** [comment]
Perhaps caused by #6327
