### ISSUE TITLE
Glypicons do not work poperly in IE11

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#6314]
### How to Reproduce
go to data explorer in IE11 

### Expected behavior
icons for the search and clear search buttons for the "google search"

### Observed behavior
see attachement
![image002](https://user-images.githubusercontent.com/3714029/27790856-b2559c48-5ff2-11e7-87e6-ffbf1a9b957d.png)

Exact IE version:
![image001](https://user-images.githubusercontent.com/3714029/27790850-a6e74488-5ff2-11e7-9d14-6b1855f1792c.png)

**Comment by bartcharbon** [comment]
I cannot reproduce on my machine (11.0.43)

**Comment by fdlk** [comment]
Duplicates #3900.
