### ISSUE TITLE
Tagging wizard fails if tags are present

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#6322]
### How to Reproduce
- select tag wizard from menu
- Select the entity HOP_Selenium from pulldown		
- Press the 'edit' button for the attribute that is called Body_Mass_Index	
- In the input box search for Height and select it
- In the input box search for Weight and select it
- Press the 'Save changes' button
- navigate away from tag wizard, ot any other plugin, and than return to it
- Select HOP_Selenium again

### Expected behavior
the entity is selected and tags are shown for the attributes

### Observed behavior

**type** Exception report

**message** Request processing failed; nested exception is freemarker.core._TemplateModelException: Java method "com.google.common.collect.AbstractSetMultimap.get(Object)" threw an exception when invoked on com.google.common.collect.LinkedHashMultimap object "{isAssociatedWith=[OntologyTerm{IRI=http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Weight,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Height, label=(Weight and Height), description=null, synonyms=[(Weight and Height)]}]}"; see cause exception in the Java stack trace.

**description** The server encountered an internal error that prevented it from fulfilling this request.

**exception**

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is freemarker.core._TemplateModelException: Java method "com.google.common.collect.AbstractSetMultimap.get(Object)" threw an exception when invoked on com.google.common.collect.LinkedHashMultimap object "{isAssociatedWith=[OntologyTerm{IRI=http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Weight,http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Height, label=(Weight and Height), description=null, synonyms=[(Weight and Height)]}]}"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list relationsAndTagsMap.get(relatio...  [in template "view-tag-wizard.ftl" at line 104, column 29]

**Comment by tommydeboer** [comment]
Tried al sorts of combinations of ontologies and users but couldn't reproduce.
