### ISSUE TITLE
Creation of mapping for BMI causes nullpointer in mapping service

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#6323]
### How to Reproduce
https://docs.google.com/spreadsheets/d/1zu0kmIQ7ETLxaIxOFlNPaYPdaXoIQIJZraAW_5JgdKI/edit#gid=1050243087
follow test plan up to line 43

### Expected behavior
a mapping is created

### Observed behavior
save button is disables until after "validate" is clicked
after "validate and "save" molgenis reports: Error! An error occurred. Please contact the administrator.
Message:null

**Comment by tommydeboer** [comment]
Can not reproduce.
