### ISSUE TITLE
Browser reloads when you upload a file and don't have write permissions

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#6333]
### How to Reproduce
When you upload a file and the user has no write-permissions, the browser reloads and the startup-screen is showing.

### Expected behavior
An error is shown that says "no write-permissions to upload the file".

### Observed behavior
The browser reloads and the startup-screen is showing.

**Comment by Mark-de-Haan** [comment]
Closing due to available workaround.
Will be addressed in upcoming permission story
