### ISSUE TITLE
Genome browser popup doesn't always show filter for mutation ID

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6338]
### How to Reproduce
Upload test.vcf from https://github.com/molgenis/commandline-annotators/tree/master/src/test/resources/fitcon
Open dataexplorer
Select test entity
Click on a mutation in the 'test' track in the genome browser
Check the popup

### Expected behavior
The popup contains a filter for the mutationID

### Observed behavior
The popup doesn't contain a link to add a filter for the mutationID.

Oddly enough, if you copy the test entity using the copy button, select that entity and click on a mutation in the 'testCopy' track, the filter is shown(!)

**Comment by bartcharbon** [comment]
I propose not to fix since the story to replace MyDAS and with that the entire GenomeBrowser mechanics is already in progress

**Comment by Mark-de-Haan** [comment]
Genome browser popup is now configurable
