### ISSUE TITLE
Google login flashes a window on your screen

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6339]
### How to Reproduce
Enable google signup, signup with a google account, and then log in with google

### Expected behavior
No window gets opened

### Observed behavior
Each time you log in with google, a window flashes up and gets closed again.
On mac, it opens on your main screen, even if the browser is on another screen.
I accidentally maximized it and now it won't even close anymore.

**Comment by Mark-de-Haan** [comment]
I can not reproduce in 5.3.0-SNAPSHOT
Because I have multiple Google accounts, I will get a popup asking me which one to log in with.
But I can not see the reported behaviour
