### ISSUE TITLE
Type ahead search in xref / mref is case sensitive

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6346]
### How to Reproduce
1. In the BBMRI-ERIC directory click on Wizard
2. Click on the Imaging data tab
3. Type 'skull' in the body part examined field

### Expected behavior
T-11100 SKULL is found

### Observed behavior
Nothing is found

**Comment by fdlk** [comment]
The select sends queries to the REST API. I think the API  behavior is deliberately case sensitive, so I'm inclined to label this a feature request. Nontrivial too because in other cases, like identifier lookups, we insist on case sensitivity. So for which operators do we want which behavior?

**Comment by djvanenckevort** [comment]
> Op 12 jul. 2017, om 15:19 heeft Fleur Kelpin <notifications@github.com> het volgende geschreven:
> 
> The select sends queries to the REST API. I think the API behavior is deliberately case sensitive, so I'm inclined to label this a feature request. Nontrivial too because in other cases, like identifier lookups, we insist on case sensitivity. So for which operators do we want which behavior?

I think we want to make this configurable, because it will vary on the use case / data. The only quick rule of thumb I could think of is that we would want exact match for the ID attribute, but case insensitive match otherwise.

**Comment by LuukDijkhuis** [comment]
configurable as in "user controlled toggle with a sensible default"

**Comment by djvanenckevort** [comment]
> Op 13 jul. 2017, om 08:51 heeft Luuk Dijkhuis <notifications@github.com> het volgende geschreven:
> 
> configurable as in "user controlled toggle with a sensible default“

Indeed. the sensible default could be case sensitive for ID attribute, case insensitive in the other cases.

**Comment by djvanenckevort** [comment]
Also reported as an issue for the directory by users.
https://helpdesk.bbmri-eric.eu/Ticket/Display.html?id=668

**Comment by dennishendriksen** [comment]
@djvanenckevort Unfortunately this is the intended behavior which has been yo-yo-ing between sensitive/insensitive over the last couple of years. Can you create a story in the backlog or add your request to a possible existing story?

**Comment by djvanenckevort** [comment]
This was fixed in story 3032 and there is another open story 5107 for this.
