### ISSUE TITLE
MOLGENIS should wrap long string values

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6347]
### How to Reproduce
- Go to https://catalogue.bbmri.nl/ 
- Click on Biobank Catalogue

### Expected behavior
Columns would never be extremely wide, long text should wrap to a next line

### Observed behavior
The name column is so wide that it takes up almost the entire width of the screen

**Comment by marikaris** [comment]
please add this to the dataexplorer 2.0 document
