### ISSUE TITLE
As directory user I would like to have a fast search wizard

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6348]
### How to Reproduce
- Go to https://directory.bbmri-eric.eu/ over a 4G connection
- Open the search wizard

### Expected behavior
- The search wizard opens within 1s

### Observed behavior
- The search wizard takes several seconds to open
- MOLGENIS disables browser caching by specifying no-cache in the http headers. This means that the metadata and all the lookup lists have to be retrieved again.

**Comment by marikaris** [comment]
please add this to the dataexplorer 2.0 document, metadata should become a prop of the search wizard.
