### ISSUE TITLE
Using double quotes in the search bar gives an error

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6349]
### How to Reproduce
- Go to the BBMRI-ERIC Directory
- Type a search term in double quotes, e.g. "Brain bank"

### Expected behavior
- The directory is searched for the term "Brain bank"

### Observed behavior
- I get an error: "Error! An error occurred. Please contact the administrator."

**Comment by marikaris** [comment]
Duplicate with: #3865
