### ISSUE TITLE
Range filter is non standard and difficult to use

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6350]
### How to Reproduce
- Go to the BBMRI-ERIC directory
- Open the search wizard
- Open the donor data tab

### Expected behavior
- The age low and age high items should show standard components for specifying an range. i.e. entry boxes for upper and lower bounds in fixed positions. e.g. [10] - [20]
- Close ranges can be selected, e.g. [65][67]

### Observed behavior
- Non standard controls are shown
- Controls are not fully initialized until you click them, which makes it unclear how they work
- Close ranges cannot be selected because the range selector will push the other range selector away

**Comment by marikaris** [comment]
Please add this to the dataexplorer 2.0 document.
