### ISSUE TITLE
System entity metadata does not follow security rules

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6357]
### How to Reproduce
As an anonymous user without permissions on anything:
`molgenisxx.gcc.rug.nl/api/v2/sys_md_EntityType` -> No permissions
`molgenisxx.gcc.rug.nl/api/v2/sys_md_EntityType/meta` -> No permissions
`molgenisxx.gcc.rug.nl/api/v2/sys_md_EntityType/meta/id` -> Json with the metadata for ID

### Expected behavior
`molgenisxx.gcc.rug.nl/api/v2/sys_md_EntityType/meta/id` -> No permissions

**Comment by dennishendriksen** [comment]
This issue is not limited to system entity types. Importing  
[it_emx_autoid.xlsx](https://github.com/molgenis/molgenis/files/1305575/it_emx_autoid.xlsx) using the 'Advanced data import' plugin and performing ```GET <host>/api/v2/it_emx_autoid_testAutoId/meta/id``` results in the same observed behavior.

**Comment by dennishendriksen** [comment]
The issue is caused because the following methods
```java
MetadataServiceImpl.hasRepository(String entityTypeId)
MetadataServiceImpl.getEntityType(String entityTypeId)
MetadataServiceImpl.getEntityTypeById(String entityTypeId)
```
use the ```SystemEntityTypeRegistry``` to retrieve system entity type thus bypassing the ```EntityType``` repository that validates whether the current user is permitted to read requested entity types.
