### ISSUE TITLE
Google sign-in only works as long as user signup is enabled and moderation is disabled

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6360]
### How to Reproduce
Open app settings, enable google sign-in

### Expected behavior
* I can enable google sign-up in combination with moderation
* Accounts that have signed up using google can still log in even if I disable signup

### Observed behavior
* I can only allow google sign-in in combination with signup enabled and moderation disabled

**Comment by fdlk** [comment]
I've no official specs document or test plan but this seems pretty blocking for many (most?) use cases to me.

**Comment by tommydeboer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix #6360 OIDC login and sign-up/moderation settings](https://trello.com/c/jHgF3YpA/672-fix-6360-oidc-login-and-sign-up-moderation-settings)
