### ISSUE TITLE
Can't map undefined values to decimal even when attribute is nillable

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6362]
### How to Reproduce

1 | 2
-- | --
Download from this page, use the 3.0 subfolder | https://goo.gl/cfdzDL
Upload HOP-10-attributes.xls |  
Upload lifelines-emx-demo.xls |  
Upload prevend-emx-demo.xls |  
Create a new mapping project:- target: HOP |  
Add sources to the project:- lifelines- prevend |  
Create integrated dataset:- check the pulldown with existing datasets. It only contains the HOP entity | It only contains the HOP entity
Create integrated dataset:- name: TargetRepo, label: Target repository, package: base, add source attribute: true | Progress bar finishes.New entity "TargetRepo" is created in the base package with label "Target Repository". A source attribute is added.
Create integrated dataset: - Select TargetRepo from the list of existing entities | Progress bar finishes, result remains the same
Add, update and delete entities in the sourcerepositories (lifelines and prevend) and create integrated dataset:- Select TargetRepo from the list of existing entities | Mapping Service correctly added, updated, on delete we expect the entities are not deleted form the target repo

### Expected behavior
Testplan is OK

### Observed behavior
12:36:59.445 - Execution started.
12:36:59.839 - progress (0, Checking target repository [TargetRepo]...)
12:37:03.543 - Applying mappings to repository [TargetRepo]
12:37:03.544 - Mapping source [lifelines]...
12:37:04.914 - Failed. 'undefined' can't be converted to type 'DECIMAL'

**Comment by fdlk** [comment]
The offending input is the glucose algorithm

**Comment by dennishendriksen** [comment]
@Mark-de-Haan @fdlk Is the error located in the algorithm that should return ```null``` instead of ```undefined```? Or do we expect our Java code to handle ```undefined``` as algorithm return values?

**Comment by fdlk** [comment]
@dennishendriksen I think I'd prefer to fail fast and not quietly mangle the user's data. But it's a matter of preference probably.

**Comment by Mark-de-Haan** [comment]
Error in how I wrote the mapping algorithm.
Do not run mappings with invalid algorithms.
