### ISSUE TITLE
Aggregate permission broken

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6383]
### How to Reproduce
Give a user aggregate permissions on an entity

### Expected behavior
When the user visits the entity in the data explorer the entity is shown as aggregates only and the data tab is hidden.

### Observed behavior
The user receives an error Unknown entity [entity_name]

Tested with 4.1.0-RD-CONNECT built on 2017-06-13 10:42 UTC

**Comment by fdlk** [comment]
Fixed in #6546
