### ISSUE TITLE
Google Analytics is not loaded if "Google analytics account privacy friendly" is set to false, even if the user accepts analytics

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6402]
### How to Reproduce
- Configure MOLGENIS with Google Analytics and set Google analytics account privacy friendly to false
- Clear your browser cookies and disable any tracking blocking extensions in your browser
- Go to another page in MOLGENIS
- Accept analytics when you get the popup
- Go to another page in MOLGENIS

### Expected behavior
- The analytics.js script is loaded (it can be seen in the browser inspection window)
- Google Analytics reports a hit

### Observed behavior
- The analytics.js script is not loaded
- Google analytics does not report a hit

**Comment by dennishendriksen** [comment]
@djvanenckevort Did you encounter this issue on localhost? Google Analytics doesn't work on localhost (https://stackoverflow.com/questions/4375447/can-you-test-google-analytics-on-a-localhost-address).

**Comment by djvanenckevort** [comment]
No, this was on the BBMRI-ERIC Directory (production). The browser web developer tools doesn't even report the script being loaded.
