### ISSUE TITLE
As data manager user I require that 'label' attribute cannot be nillable

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis#6418]
### How to Reproduce
Create a table with a label attribute that is nillable

### Expected behavior
When I select this attribute in metadata manager I get an error message.
(I expect it to be selectable otherwise users don't get it).

### Observed behavior
Is accepted. As a consequence these attributes are invisible in mapping service.

**Comment by fdlk** [comment]
1. This is a breaking change, even our own system metadata (accidentally) has a nillable labelAttribute.
So will other people's emx files.
2. I'd validate it at a lower level as well, not just in the EMX and the metadata manager

**Comment by marikaris** [comment]
I just found a project that will break when we fix this: E-rare

In the table of each lab, the classification is nillable and the label of the table, so when you see the consensus table, you only see the classifications of labs that were classified (the others remain empty, while they do exist in the lab tables). Therefore we do not need a script to generate the consensus table, which will be updated every time someone updates the classification in a lab table. 

It will make me really sad if I cannot load the data of this project anymore.

**Comment by LuukDijkhuis** [comment]
Apparently the actual wish is to be able to select attributes with a null label so that they show up in the mapping service. ( "As a consequence these attributes are invisible in mapping service"). Maybe we can rephrase this issue to reflect that?

**Comment by tommydeboer** [comment]
@mswertz @LuukDijkhuis Have we decided on this yet? Workaround or breaking change?

**Comment by LuukDijkhuis** [comment]
There are conflicting views about this. A. you don't want to break e-rare, so IF you fix this you will need a mogenis-feature to support their use case in a different way. B. you want to take a decision that aligns with the design views: is it logical within the Domain that a label can be null or is it actually nonsensical. In the meantime you can set labels to not-nullable in your model, so on a per instance basis, as a workaround to make sure your plugins (that, wrongfully or not, see B, assume that a label is never null) don't break. I propose we have a short discussion on A. and B. and their interactions, and plan to either build the features or fix the wrongful assumptions.

**Comment by mswertz** [comment]
it is nonsensical to have 'null' labels. But in practice data managers will face this problem and fix it if desired by changing the model (as you suggest) or use this actual flexibility. So given that there is a way to enforce not-null I propose to lower the urgency of this one and give prio to other bugs.

**Comment by tommydeboer** [comment]
As discussed, we'll make label attributes non-nillable and we'll use another solution for E-Rare.
