### ISSUE TITLE
MOLGENIS REST API does not support the RSQL =out= operator

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6449]
### How to Reproduce
Create a query using the RSQL documentation using the =out= operator to return all attributes that are not bool, categorical or categoricalmref

https://molgenis01.gcc.rug.nl/api/v2/sys_md_Attribute?q=type%3Dout%3D(bool,categorical,categoricalmref)

### Expected behavior
MOLGENIS returns the attributes

### Observed behavior
MOLGENIS returns an error:

{"errors":[{"message":"Unknown RSQL query operator [=out=]"}]

**Comment by fdlk** [comment]
Neither does the molgenis query API. I think this is a feature request.

**Comment by Mark-de-Haan** [comment]
issue for adding documentation on RSQL operators added to the 111 milestone.
Created [a story](http://wiki.gcc.rug.nl/ticket/5508#ticket) for this.

Closing
