### ISSUE TITLE
Tomcat Access denied page after successful login

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6464]
### How to Reproduce
1. Setup a MOLGENIS instance where the anonymous user has access to the data explorer
2. Create a menu item that links to the data explorer for a specific entity to which the anonymous user has no access
3. As the anonymous user click on the menu item for the data explorer
4. When you get the message in the data explorer that you need to login, click on the login page

### Expected behavior
After successful login you return to the dataexplorer with the entity selected as setup in the link

### Observed behavior
Got a tomcat standard 403 error page for the following link /app/fonts/glyphicons-halflings-regular.woff

**Comment by fdlk** [comment]
@djvanenckevort Is this a public server that I could surf to? I'm a bit confused by the `/app` URL.

**Comment by fdlk** [comment]
@djvanenckevort I tried in a docker on 5.0.1 and cannot reproduce. I've created a menu item Scripts with the query string `entity=sys_scr_Script`. I've given read permissions to user anonymous for DataExplorer plugin and on all entity types in sys_md package and on sys_set_dataexplorer.

When I log out and click the link I get 
![screen shot 2017-08-01 at 11 01 44](https://user-images.githubusercontent.com/1523838/28817657-37863e46-76a9-11e7-97a0-bba5d7a124a6.png)

**Comment by marikaris** [comment]
I recognize the problem, I found this a few times too, but I cannot reproduce it on the current master

**Comment by fdlk** [comment]
@djvanenckevort The server I got access to from you to reproduce still is down.

**Comment by djvanenckevort** [comment]
That server will be redeployed with the new version for RD-Connect. If we can't reproduce on that built I guess we should close this issue.

**Comment by Mark-de-Haan** [comment]
Can no longer reproduce in 5.3.0-SNAPSHOT
