### ISSUE TITLE
MOLGENIS Manual should be a regular menu item

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6468]
### How to Reproduce
Install MOLGENIS 5.0

### Expected behavior
The Manual option in the menu is a regular menu item that can be managed with the menu manager

### Observed behavior
- The Manual option in the menu is a link that is placed in the logout form on the right hand side of the menu.
- I cannot manage the visibility or position of the manual with the menu manager

**Comment by bartcharbon** [comment]
This issue could be fixed by removing the link altogether. Via the redirect plugin the desired behaviour can be achieved.

However, this would mean you cannot get the link in the current location (outlined to the right)

**Comment by djvanenckevort** [comment]
In my opinion that would not be a problem, that spot is usually reserved for an account page.

**Comment by tommydeboer** [comment]
I just checked Bart's suggestion and indeed it's possible to get a similar (but configurable) effect with the redirect plugin. However, as far as I know it's not possible to add this help-link to the default menu.

**Comment by Mark-de-Haan** [comment]
@mswertz what is the spec for this?
