### ISSUE TITLE
Users can still sign in with /login when their passwords needs to be reset

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6505]
### How to Reproduce
1. Create a user and set the resetPassword field to true
2. Try to sign in as the user via the REST API ```/login``` route

### Expected behavior
User can't sign in, with the message that they need to reset their password.

### Observed behavior
User can sign in.

**Comment by dennishendriksen** [comment]
@tommydeboer how about when their account is inactive?

**Comment by tommydeboer** [comment]
@dennishendriksen That's working correctly: they can't sign in.
