### ISSUE TITLE
Google Analytics Opt out link throws a gaOptout is undefined error

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis#6508]
### How to Reproduce
* Configure MOLGENIS with Google Analytics
* Set the Google analytics account privacy friendly option to true
* Go to the MOLGENIS home page and click on the "opt out" link at the bottom

### Expected behavior
* I get an opt out page or dialog

### Observed behavior
* I get an error: "Error! An error occurred. Please contact the administrator. Uncaught ReferenceError: gaOptout is not defined"

**Comment by mswertz** [comment]
Is this an error that occurs on our production servers at the moment? If yes, then we fix it urgently, if not we will postpone. Please advice.

**Comment by djvanenckevort** [comment]
Yes, it occurs on production servers.

**Comment by mswertz** [comment]
So than this must be solved because an anonymous user facing broken window.
