### ISSUE TITLE
CSS href setting does not take a href but a file in the /css/ directory making it impossible to include custom CSS without access to the server

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6519]
### How to Reproduce
Set the "CSS href" property in the configuration to a fully qualified URL (e.g. http://www.example.org/css/custom.css)

### Expected behavior
MOLGENIS includes http://www.example.org/css/custom.css

### Observed behavior
MOLGENIS tries to include /css/http://www.example.org/css/custom.css

### Details
In molgenis/molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl lines 42-44
```
    <#if app_settings.cssHref?has_content>
        <link rel="stylesheet" href="<@resource_href "/css/${app_settings.cssHref?html}"/>" type="text/css">
    </#if>
```
Should not include /css/

**Comment by tommydeboer** [comment]
I don't think that field is meant to support fully qualified URLs. The description of the field mentions this:

```
CSS file name to add custom CSS (see molgenis-core-ui/src/main/resources/css).
```
So only css files in the resource folder can be added here.

Is this a feature request?

**Comment by djvanenckevort** [comment]
But the name CSS href suggests differently, so at least there is the bug that the name and description are inconsistent.
Limiting it to a file in the /css/ directory means that you need to have access to server, which is not always the case.
Also this is inconsistent with the option for including javascript or the one for including an image above the menu, both of which allow specifying a fully qualified URL.

**Comment by marikaris** [comment]
This is working as intended, I agree that the name is confusing but the functionality has always worked this way. I do however agree that we should allow for this and we have been talking about this previously, I think we wrote some stories about it as well.

**Comment by Mark-de-Haan** [comment]
Currently working as intended.
[Stories available](http://wiki.gcc.rug.nl/ticket/5372)
