### ISSUE TITLE
When you upload a csv-file for the second time the server throws an error 

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#6522]
### How to Reproduce
Upload attributes.csv 2 times. Attributes.csv is located in the zip archive. You can also view the stacktrace which is included in the zip archive.

### Expected behavior
Upload attributes.csv 2 times

### Observed behavior
A spinning throbber and a server error.

[stacktrace_uploadfile.zip](https://github.com/molgenis/molgenis/files/1228395/stacktrace_uploadfile.zip)

**Comment by Mark-de-Haan** [comment]
Can not reproduce in 5.3.0-SNAPSHOT
