### ISSUE TITLE
Adding javascript to the "Custom javascript header" slows down the server 

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6526]
### How to Reproduce
1. Go to Application Settings
2. Add the contents of (https://molgenis26.gcc.rug.nl/downloads/row-click.js) in the "Custom javascript header". 
3. Save changes

### Expected behavior
Server doesn't break down.

### Observed behavior
Server becomes unresponsive. Logfile is continuously spammed with ResourceFingerprintRegistry exceptions.

**Comment by bartcharbon** [comment]
What happens is that the field get interpreted as intended; a comma separated list of js files. So if you past a script in this field, it gets split on comma's. Every pageload MOLGENIS tries to load every result from this split as a file, cannot find it a this results in the exception.
