### ISSUE TITLE
ResourceFingerprintRegistry exceptions when adding an existing javascript to the header

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6527]
### How to Reproduce
From the testplan:
1. Add an exisiting script (https://molgenis26.gcc.rug.nl/downloads/row-click.js) in the "Custom javascript header". 
2. Save changes and check if it was included in the <head> of the webpage

### Expected behavior
Script is added to the header.

### Observed behavior
Continuous exceptions.

**Comment by bartcharbon** [comment]
cannot reproduce.

added the script url, reloaded the page: script gets added to header, no exceptions
