### ISSUE TITLE
RCurl package not installed on OpenCPU

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6532]
### How to Reproduce
From the 'Scripts' testplan:
1. import file 'molgenis-scripts/src/test/resources/Rtest.xlsx'
2. Add a Script in the Scripts plugin:
```R
library(RCurl)
eval(expr = parse(
text = 
getURL("https://molgenisXX.gcc.rug.nl/molgenis.R?molgenis-token=${molgenisToken}")))
 df <- molgenis.get("base_Rtest")
 df2 <- apply(df, 1,as.numeric)
 is.na(df2) <- sapply(df2, is.infinite)
 df2[is.na(df2)] <- 0
 df2[is.nan(df2)] <- 0
 png('${outputFile}')
 heatmap(as.matrix(df2),symm=FALSE,trace="none")
 dev.off()
 molgenis.logout()
```
File extension:  PNG
Security token: true

3. Execute script

### Expected behavior
Script runs.

### Observed behavior
```there is no package called 'RCurl' In call: library(RCurl)```

**Comment by dennishendriksen** [comment]
Did you encounter this issue on either molgenis01 or molgenis62? I forgot to reinstall the R packages according to our VM solved. Works after reinstalling the packages.
