### ISSUE TITLE
Entering invalid recovery code 3 times should cause timeout of 30 seconds

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#6535]
### How to Reproduce
Testplan states:
Login as user "Piet" | You will be redirected to a page that shows the "Enter verification code"-box
Click on: "Enter a recoverycode" | The modal will collapse and the recovery box will appear
Enter a wrong recovery code | You will get an error "Invalid recovery code"
Enter a wrong recovery code (3rd time) | Get an error "You entered the wrong verification code x (default 3) times, please wait x default 30) seconds before you try again"

Observed:
"You entered the wrong verification code x (default 3) times, please wait x default 30) seconds before you try again" does not show, I can continue to spam the box with codes

**Comment by sidohaakma** [comment]
Could we discuss this sometime today. What the right way of implementing this failsafe is?

**Comment by sidohaakma** [comment]
@mswertz Do we need the 3 times wrong 30 seconds delay on entering the recovery code. No it is only implemented in entering the verification code. Brute force attacks on entering recovery codes are not likely to succeed because of the length of the recoverycodes.

**Comment by sidohaakma** [comment]
The check on entering the recovery code 3 times is removed from testplan.

**Comment by Mark-de-Haan** [comment]
Closing as the reported issue is no longer expected behaviour
