### ISSUE TITLE
When I delete the current applied theme an error occures while a warning was expected

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#6552]
### How to Reproduce
Delete the current applied theme via the Data Explorer stylesheet entity

### Expected behavior
A warning was expected with the following content: "Cannot delete the currently selected bootstrap theme"

### Observed behavior
A error occured: "Error! An error occurred. Please contact the administrator."

**Comment by bartcharbon** [comment]
Both Mariska and myself cannot reproduce this issue

**Comment by bartcharbon** [comment]
The exception with the expected message is thrown, however somewhere it is catched and translated to this general message.

**Comment by bartcharbon** [comment]
Discussed with Morris: won't fix for 5.1.0. We might want to add "delete" functionality to the theme manager?

**Comment by Mark-de-Haan** [comment]
in v5.3.0-SNAPSHOT, you get the message that you can not delete the currently selected bootstrap theme.
