### ISSUE TITLE
When I sign up, fill in the captcha wrong and reset it, my wrong input does not go away

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6554]
### How to Reproduce
Log in as admin. Go to Admin --> Settings --> Authentication settings. Switch on "Allow users to sign up" and disable "Sign up moderation". Log out.
Sign up. 
Type captcha (wrong)
![screen shot 2017-08-23 at 15 49 32](https://user-images.githubusercontent.com/10075439/29619198-bda4cace-881a-11e7-90e1-bac5a503f12a.png)
Reset by clicking on image

### Expected behavior
My typed input will be gone

### Observed behavior
My typed input is still there
![screen shot 2017-08-23 at 15 49 43](https://user-images.githubusercontent.com/10075439/29619217-cd6ab2c0-881a-11e7-8285-b12c2ed79a24.png)

**Comment by bartcharbon** [comment]
never worked like this (testen on lifelines acceptance 1.2.3), so enhancement rather than bug

**Comment by mswertz** [comment]
we will replace this captcha with another system
