### ISSUE TITLE
REST calls with an id that ends with a file extension get swallowed by Spring

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6575]
### How to Reproduce
Go to dataexplorer
Select StyleSheet
Try to alter StyleSheet

### Expected behavior
I can alter it

### Observed behavior
Error! No logging.

**Comment by tommydeboer** [comment]
The StyleSheet rows happen to have ids in the format of: ```style.sheet.css```. Because .css is a file type recognized by Spring, it gets picked up before it can reach the REST Controller.

**Comment by tommydeboer** [comment]
Semi-related to #5431. Mentioning it here for future reference. Both issues are fixed in ```MolgenisWebAppConfig```
