### ISSUE TITLE
Index queries fail when index doesn't exist (yet)

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#6583]
### How to Reproduce
go to the dataexplorer
select index action
enter any "search" query in the "google search box" on the top left

### Expected behavior
search is preformed and matching rows, if any, are shown

### Observed behavior
Error! One or more indexes 'sysidxindexaction_43bbc99b' not found.

**Comment by dennishendriksen** [comment]
Cannot reproduce using the following steps:
1. Start application with an empty database and no Elasticsearch indices
2. Search for 'script' in entity type 'Entity type' using the search box in the data explorer plugin
Result: table is filtered, matching rows are displayed.

@bartcharbon How to reproduce?

**Comment by fdlk** [comment]
@dennishendriksen The entity name matters. Try https://molgenis01.gcc.rug.nl/menu/main/dataexplorer?entity=sys_idx_IndexActionGroup&mod=data&query%5Bq%5D%5B0%5D%5Boperator%5D=SEARCH&query%5Bq%5D%5B0%5D%5Bvalue%5D=test
