### ISSUE TITLE
When changing search query from 'ref1' to 'ref' in searchAll plugin, the list is not updated correctly

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6587]
### How to Reproduce
- Import type test
- Go to search all plugin
- Search 'ref1' -> TypeTestRef is found with 1 row
- Change Search to 'ref'

### Expected behavior
Existing panel for TypeTestRef is replaced
TypeTestRef is found with 5 rows

### Observed behavior
Panel is not replaced, but an extra one is added
<img width="634" alt="screen shot 2017-09-05 at 09 26 21" src="https://user-images.githubusercontent.com/3625016/30049882-8b968dd6-921c-11e7-8014-332f9193b564.png">

Found 0 rows (but this is an elastic search thingy I guess)

**Comment by bartcharbon** [comment]
Cannot reproduce this in the current master. Screen is update properly.

@Mark-de-Haan do you have testdata, the screenshot in the issue suggests it is not the default TypeTestRef entity

**Comment by Mark-de-Haan** [comment]
No special data used, just the standard it_emx all data types file from the repository

**Comment by Mark-de-Haan** [comment]
There were some searchAll fixes in the release, could be this was fixed?

**Comment by Mark-de-Haan** [comment]
Can not reproduce in v5.3.0-SNAPSHOT
