### ISSUE TITLE
Advanced importer does not show entity fields

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#6609]
Seen and reproduced on molgenis01 where 5.2.0-SNAPSHOT is deployed. A valid EMX file is put in the advanced importer, and after going through the steps the import does success as expected.

However, in screen 4 (Validation), there are no entity fields shown. Here, it should have shown a number of fields about to be imported. See screenshot.

<img width="366" alt="screen shot 2017-09-08 at 8 57 24 am" src="https://user-images.githubusercontent.com/82420/30199642-e82fed2c-9473-11e7-859b-06e3a555a975.png">

**Comment by fdlk** [comment]
@joerivandervelde Can you attach the emx file? I think it may be related to there being only an attributes sheet and no entities sheet

**Comment by joerivandervelde** [comment]
Also seen in 5.1.0. Used EMX file @ https://molgenis26.gcc.rug.nl/downloads/gavin/variantclassificationwebtool/GAVIN_ruleguide_r0.3.xlsx
