### ISSUE TITLE
Search queries with spaces do not get sent to negotiator

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6618]
### How to Reproduce
- Go to the BBMRI-ERIC directory
- Search for OMEGA alpha
- Click on 'Go to sample/data negotiation'
- Click on 'Yes, send to negotiator'

### Expected behavior
I'm taken to the Negotiator

### Observed behavior
I receive an error: 
`Error! An error occurred. Please contact the administrator.`

**Comment by dennishendriksen** [comment]
@djvanenckevort which BBMRI-ERIC directory server/MOLGENIS version? ​https://molgenis83.gcc.rug.nl/?

**Comment by djvanenckevort** [comment]
Current production version (https://molgenis21.gcc.rug.nl/).

**Comment by Mark-de-Haan** [comment]
This is a DNS issue
Doing requests from https://directory.bbmri-eric.eu will work
Doing requests from https://molgenis21.gcc.rug.nl will fail

This is an issue on the negotiator side and is communicated with the WP2 people

**Comment by djvanenckevort** [comment]
This is NOT a DNS issue. I can reproduce the issue with https://directory.bbmri-eric.eu/ See screenshot.

![schermafbeelding 2017-09-26 om 12 41 43](https://user-images.githubusercontent.com/1942445/30856315-3d0bac1c-a2b8-11e7-8c72-cefa0a2c1d1a.png)

In the console I see the following error (see screenshot):
![schermafbeelding 2017-09-26 om 12 43 53](https://user-images.githubusercontent.com/1942445/30856366-6cfc7686-a2b8-11e7-92b9-352fab764283.png)

And when I directly try the given API URL I also see that MOLGENIS returns a 400 error:

https://directory.bbmri-eric.eu/api/v2/eu_bbmri_eric_collections?num=10000&q=*=q=alpha+omega

MOLGENIS creates an invalid API request to MOLGENIS when querying for the list of collections

**Comment by Mark-de-Haan** [comment]
This URL works:
`https://directory.bbmri-eric.eu/menu/main/dataexplorer?entity=eu_bbmri_eric_collections&mod=data&attrs%5B%5D=country&attrs%5B%5D=biobank&attrs%5B%5D=collection&hideselect=true&query%5Bq%5D%5B0%5D%5Boperator%5D=SEARCH&query%5Bq%5D%5B0%5D%5Bvalue%5D=alpha%2Bomega`

This URL fails:
`https://directory.bbmri-eric.eu/menu/main/dataexplorer?entity=eu_bbmri_eric_collections&mod=data&attrs%5B%5D=country&attrs%5B%5D=biobank&attrs%5B%5D=collection&hideselect=true&query%5Bq%5D%5B0%5D%5Boperator%5D=SEARCH&query%5Bq%5D%5B0%5D%5Bvalue%5D=alpha+Bomega`

Alas, the second one is the one being created by MOLGENIS

**Comment by fdlk** [comment]
Root cause: https://bugs.jquery.com/ticket/3400
