### ISSUE TITLE
The age() function in script-evaluator.js is broken

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6635]
### How to Reproduce
- Import [this EMX](https://github.com/molgenis/molgenis/files/1299271/simple-questionnaire.xlsx)
- Go to questionnaires
- Enter date 1990-11-13

### Expected behavior
Question "Do you have a drivers license" should appear

### Observed behavior
Nothing appears

If you use other visible expressions, like $('age').ge(18).value(), you will have a working questionnaire. The problem is with the age() function

**Comment by dennishendriksen** [comment]
Documentation of the age function in ```script-evaluator.js```:
```
            /**
             * Returns the age based on the date of birth and the current year
             *
             * Example: $('Date_Of_Birth').age().value()
             *
             * @memberof $
             * @method age
             */
            age: function () {
                if (_isNull(this.val)) {
                    this.val = undefined;
                } else {
                    this.val = Math.floor((Date.now() - this.val) / (365.2425 * 24 * 60 * 60 * 1000));
                }
                return this;
            },
```

**Comment by dennishendriksen** [comment]
See #6112
