### ISSUE TITLE
as molgenis server owner I want elasticsearch to automatically reconnect if server is rebooted

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis#6639]
### How to Reproduce

when servers are rebooted (e.g. as on our servers on monday) the connection with elasticsearch cannot be made resulting in unfunctional molgenis

### Expected behavior

elastiscsearch automatically reconnects if connection is lost/not yet available. 
thus service is available

### Observed behavior

molgenis is not usable

**Comment by dennishendriksen** [comment]
See http://www.molgenis.org/ticket/5272
