### ISSUE TITLE
Menu hides content on iPad

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6642]
### How to Reproduce
Go to any current MOLGENIS On your iPad.

### Expected behavior
I see the menu layed out as a normal menu in a line.

### Observed behavior
I see the menu items layed out in a list covering the content of MOLGENIS, making the system unusable.

**Comment by dennishendriksen** [comment]
MOLGENIS supports the following resolutions:
```
1280x800
1280x1024
1366x768
1680x1050
1920x1080
```
Which resolution does the iPad have with which you encountered the issue?

**Comment by djvanenckevort** [comment]
https://www.apple.com/nl/ipad-mini-4/specs/ says that the resolution is 2048 x 1536 pixels.

**Comment by dennishendriksen** [comment]
@fdlk Can you take a look on your iPad?

**Comment by Mark-de-Haan** [comment]
There is a [story](http://wiki.gcc.rug.nl/ticket/5137) for fixing resolutions.
Il add Ipad and your rez to the acceptance criteria
