### ISSUE TITLE
Creating a new attribute in a compound attribute will break the metadata during first bootstrap

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6647]
## How to Reproduce
- Start the app with a clean database
- Stop the app
- in the DataExplorerSettings `addGeneralSettings()` method, add the following code at the end:
```java
addAttribute("testAttribute").setDataType(BOOL)
.setNillable(true)
.setDefaultValue("true")
.setLabel("Attribute to show issue");
```
- Start the app
- Go to the data explorer and open the settings

### Expected behavior
There is one "Attribute to show issue" option with a Radio button

### Observed behavior
"Attribute to show issue" is added twice
If you save, everything is completely broken

### Note
Might have something to do with 
SystemEntityTypeInitializer.java line 48: //TODO: doesn't this mean all attributes get added twice?

**Comment by sidohaakma** [comment]
This behaviour occurs when you add an attribute to a compound attribute in a Settings.class.

**Comment by sidohaakma** [comment]
The MetaDataService.upsertEntityTypes breaks the list of attributes in the DataExplorerSettings.

**Comment by sidohaakma** [comment]
When dataservice.update(ENTITY_TYPE_META_DATA, entity) is called the attributelist is corrupted (line 369 in MetaDataServiceImpl.java).

**Comment by sidohaakma** [comment]
When the addAttribute in the PostgreSqlRepositoryCollectionDecorator is called, a copy is made of the entityType and the attribute. This breaks the original entityType (see line 57).

**Comment by Mark-de-Haan** [comment]
duplicate of #6729
