### ISSUE TITLE
When executing an  R script, only the last output is shown

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6650]
### How to Reproduce
Put this script in your scripts plugin as R script:
```R
print("test")
print("test2")
```

### Expected behavior
Get the output of the first and last print (as it always happened before)

### Observed behavior
I only receive the last output
![issue](https://user-images.githubusercontent.com/10075439/30477676-49b07d9c-9a0e-11e7-8871-9691b44b3288.png)

**Comment by dennishendriksen** [comment]
According to @marikaris older versions used to print all outputs.
