### ISSUE TITLE
ClientFactory issues

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6661]
### How to Reproduce
Code inspect ClientFactory.

* Transport addresses are added twice. Why?
* Each retry opens a new client but the old ones never get closed. Is this safe?
* Retry code does send log.info messages that it cannot connect but doesn't log.info when connection succeeds.
* Code eats up InterruptedException and keeps retrying
* Suppressed warning no longer is relevant

**Comment by dennishendriksen** [comment]
Auto-close failed, closing manually.

**Comment by fdlk** [comment]
Autoclose didn't fail, still needs to be merged with master.
