### ISSUE TITLE
When adding attribute with ref entity to table, the complete table breaks

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6672]
### How to Reproduce
Upload 
[vkgl-model.xlsx](https://github.com/molgenis/molgenis/files/1317714/vkgl-model.xlsx)
Go to 'Attribute', in the dataexplorer
Add a new attribute (categorical mref) to the 'consensus'
Delete the new attribute
### Expected behavior
Add a new attribute (categorical mref): Works fine
Delete the new attribute: Deletes fine

### Observed behavior
Add a new attribute (categorical mref): Complete table broken
Delete the new attribute: Weird postgresql error, but when just clicking once and when being patient, the attribute gets deleted (and the table works again phew!)

**Comment by LuukDijkhuis** [comment]
which weird postgresql error would that be?

**Comment by LuukDijkhuis** [comment]
see also #6673

**Comment by dennishendriksen** [comment]
@marikaris could you take a look at @LuukDijkhuis his question?

**Comment by marikaris** [comment]
Fixed in 5.2

**Comment by dennishendriksen** [comment]
Hmmm ... why wasn't it closed automatically? @Mark-de-Haan any idea? Are we sure it was merged back to the master?

**Comment by marikaris** [comment]
I am pretty sure it was merged back but I will check. I just closed another one as well, which I did verify on molgenis01, this one was fixed in the same release
