### ISSUE TITLE
When adding a header logo above the menu bar parts of plugins are not clickable

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6677]
### How to Reproduce
Go to admin settings
Add http://bestanimations.com/Animals/Mammals/Horses/unicorn/unicorn-animated-picture-gif-6.gif to Logo above navigation bar
Save

### Expected behavior
Everything moves down and makes place for the unicorns, I can still use my plugins

### Observed behavior
Some parts of plugins are hidden below the unicorns and I cannot click things anymore

**Comment by LuukDijkhuis** [comment]
Blocking? Hmm... Maybe timebox this

**Comment by marikaris** [comment]
Introduces after 8 september. Thats when I build the master for the last time and there it was working as intended.

**Comment by dennishendriksen** [comment]
Fixed in #7543 and #7629.
