### ISSUE TITLE
Can not create png via R script 

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#6681]
### How to Reproduce
From test plan: 

1. create a new script
2. set name to **test123**
3. set type as **R**
4. set the content as below
5. set the Result file extension to **png**
6. create and add parameters for  **amplitude**, **period** and **outputFile**
7. Create and Run the script

```
png('${outputFile}')
  x<-seq(-pi,2*pi, by=0.01)
 plot(x,${amplitude} * sin(x * 2 * pi / (${period}) ), type='l')
 dev.off()

```
### Expected behavior
Script runs successful and returns png graph

### Observed behavior
```
Script job

javax.script.ScriptException: ReferenceError: "png" is not defined in <eval> at line number 1
```

**Comment by ConnorStroomberg** [comment]
When i run a similar script locally in R it returns a graph, maybe there is some issue with the new RServe setup ?

**Comment by dennishendriksen** [comment]
It appears that your script was of type 'JavaScript' instead 'R' (see the script with name 'Release test connor' on https://molgenis62.gcc.rug.nl/menu/plugins/scripts). Creating the script according to the test case in the test plan generates the correct image.
