### ISSUE TITLE
Linking back from Negotiator results in error

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6683]
### How to Reproduce
1. Import [BBMRI_DIRECTORY_NEGOTIATOR_DATA_molgenis3.xlsx](https://drive.google.com/drive/folders/0B_GWMZiAUjDdfm5kTHZnYTUzQmNqVUdtLXNSYUVaWVdXMnRXaGlQQ0hkSEJQbXhLZ2ZFSTA)
2. Go to the Directory settings in the Admin -> Settings screen
3. See test case *DATAEXPLSYSNEGOT001* for the credentials and fill them out
4. Select BBMRI collection entity in Data Explorer
5. Search for 'BB'
6. Press the "Export to BBMRI Negotiator" button
7. Press the "researcher"-button
8. Fill in a Title, Project description and a Request description for your query
9. Click "Add query"
10. Select your query in the Negotiator
11. Edit the query

### Expected behavior
Collections dataset opens up in the Data Explorer with the query applied

### Observed behavior
Uncaught TypeError: e.match is not a function

**Comment by LuukDijkhuis** [comment]
Fleur/Mariska: at least investigate what's the problem here

**Comment by Mark-de-Haan** [comment]
I can not reproduce this.

**Comment by marikaris** [comment]
@tommydeboer Did you find this on localhost?

**Comment by tommydeboer** [comment]
@marikaris I found this on m62 during testing of 5.2.0-RC-1
