### ISSUE TITLE
When downloading CSV with labels I get Id's for xrefs

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6685]
### How to Reproduce
Load the VKGL data (contact me; it's a lot and it's private for now)
Go to consensus
Download as csv with both parameters on labels

### Expected behavior
my lab_classification (i.e. UMCG_classification) columns are filled with classification labels (i.e. Benign)

### Observed behavior
the id of the variant in the lab table (lab_chromosome_startposition_stopposition_ref_alt_gene)

**Comment by dennishendriksen** [comment]
Cannot reproduce in 5.2.0-RC1

**Comment by marikaris** [comment]
I think something went terribly wrong on that server. I cannot reproduce it locally (and the server won't cooperate now); let's close it until further notice
