### ISSUE TITLE
When downloading the content as xlsx of a large table (66.000 rows) the complete site goes down for some time

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6687]
### How to Reproduce
Upload the VKGL data (contact me)
Go to consensus table
Download as xlsx

### Expected behavior
Download xlsx hidden in big datasets or no errors when downloading

### Observed behavior
First internal server error and after that the server is temporarily unavailable
<img width="1279" alt="screen shot 2017-09-21 at 08 23 31" src="https://user-images.githubusercontent.com/10075439/30682730-f16083a2-9eaa-11e7-8b1c-91769152bd74.png">
<img width="981" alt="screen shot 2017-09-21 at 08 31 05" src="https://user-images.githubusercontent.com/10075439/30682731-f163e704-9eaa-11e7-9f82-0c0d1b9401c4.png">

**Comment by dennishendriksen** [comment]
Related to #1552

**Comment by LuukDijkhuis** [comment]
Fleur/Mariska: allow only csv for > X "cells":  [task: find X]   Cells, as in: it is related both to rows and columns. Initial estimate: X=10000
