### ISSUE TITLE
Complex valid csv of testplan does not upload in one-click-importer

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6692]
### How to Reproduce
Upload https://drive.google.com/drive/u/0/folders/0B-ElyQryGh-OVzdSSjBLZy04THM with one-click-importer

### Expected behavior
Succes

### Observed behavior
![screen shot 2017-09-21 at 09 38 01](https://user-images.githubusercontent.com/10075439/30684213-9af80c00-9eb0-11e7-9348-7ac15ac5da9b.png)

**Comment by ConnorStroomberg** [comment]
The 'complex-valid.csv' does not look valid to me, column names are missing.
For a invalid file i would ideally like to see a more actionable error message.

**Comment by marikaris** [comment]
With the fix in the testfile it works, thanks :)
