### ISSUE TITLE
One-click-importer permission issue for non-superusers

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6713]
### How to Reproduce
Create a user with:
- View permissions on one click importer plugin, OneClickImporterJobExecution
- View permissions on dataexplorer and dataexplorer-settings and genomebrowsersettings and attributes
- Write permissions on attribute, entityType, Package
- Login as user
- Import a simple csv or xlsx
- Click the link to the dataexplorer

### Expected behavior
I can see my data

### Observed behavior
Error
After looking at permissions on the EntityType, I can see the user has none

**Comment by Mark-de-Haan** [comment]
## Note

```
/**
 * Updates current user permissions as system user, changes take effect immediately.
 */
public interface PermissionSystemService
{
	void giveUserWriteMetaPermissions(EntityType entityType);

	void giveUserWriteMetaPermissions(Collection<EntityType> entityTypes);
}
```
>  changes take effect immediately

Is not true apparently

>

**Comment by Mark-de-Haan** [comment]
## Note
```
private void updateSecurityContext(SecurityContext context, Collection<? extends GrantedAuthority> authorities)
```

Creates a new Authentication, but does not include the authorities passed down as parameter

**Comment by Mark-de-Haan** [comment]
Passing this to platform @fdlk @dennishendriksen

**Comment by dennishendriksen** [comment]
I get the error:
```Import failed; No [WRITE] permission on entity type [Package] with id [sys_md_Package]```
When I grant WRITE permissions on Package to the user I get:
```Import failed; No [WRITE] permission on entity type [Entity type] with id [sys_md_EntityType]```
When I grant WRITE permissions on EntityType to the user I get:
Import failed; No [WRITE] permission on entity type [Attribute] with id [sys_md_Attribute]
When I grant WRITE permissions on Attribute I can reproduce this issue.
