### ISSUE TITLE
When uploading a zip with one table with references in it; it fails because it cannot find the refentities while they are in the zip

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6714]
### How to Reproduce
Import vkgl model 
Import vkgl data (all labs + comments + consensus) 
Mail me for data+model

### Expected behavior
Import successful because everything is in the zip

### Observed behavior
Unknown xref value 'ERASMUS_12_124829474_124829474_G_A_NCOR2' for attribute 'ERASMUS_classification' of entity 'VKGL_consensus'.
 
When I first upload the zip with the consensus excluded and then import the csv with the consensus separately, it works.

**Comment by fdlk** [comment]
@marikaris So you mean a CSV with self-references?

**Comment by dennishendriksen** [comment]
@marikaris Could you answer the questions from @fdlk?

**Comment by marikaris** [comment]
The consensus table references to the lab tables which are included in the same zip file in CSV's. I use the advanced importer.

**Comment by marikaris** [comment]
Cannot reproduce :)
