### ISSUE TITLE
Footer does not render at all on IE9

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6717]
### How to Reproduce
Using IE9 browser, surf to molgenis

### Expected behavior
Page shows footer

### Observed behavior
No footer. No menu either (#6716) which means the entire page is blank

**Comment by ConnorStroomberg** [comment]
If we want/need (@mswertz ?) to support ie9 maybe we can not use bootstrap4 see; https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#internet-explorer

> Unofficially, Bootstrap should look and behave well enough in Chromium and Chrome for Linux, Firefox for Linux, and Internet Explorer 9, though they are not officially supported.
> 
> For a list of some of the browser bugs that Bootstrap has to grapple with, see our Wall of browser bugs.
> 
> Internet Explorer
> Internet Explorer 10+ is supported; IE9 and down is not. Please be aware that some CSS3 properties and HTML5 elements are not fully supported in IE10, or require prefixed properties for full functionality. Visit Can I use… for details on browser support of CSS3 and HTML5 features.
> 
> If you require IE8-9 support, use Bootstrap 3. It’s the most stable version of our code and is still supported by our team for critical bugfixes and documentation changes. However, no new features will be added to it.
