### ISSUE TITLE
Import error message unclear for duplicate mref values

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#6727]
### How to Reproduce
1. First upload the BBMRI-ERIC model: 
[bbmri_eric_complete_EMX_test_error_messages.xlsx](https://github.com/molgenis/molgenis/files/1336725/bbmri_eric_complete_EMX_test_error_messages.xlsx)

2. Now load the BBMRI-ERIC IT model + data:
[IT_EMX_data_test_error_message.xlsx](https://github.com/molgenis/molgenis/files/1336735/IT_EMX_data_test_error_message.xlsx)

### Expected behavior
 Correct error message, like it was in version 2.x:
![screen_shot_error_message_2 x](https://user-images.githubusercontent.com/8615163/30909061-0f7d788e-a380-11e7-9ce9-f8ed9f547b58.png)

### Observed behavior
Incorrect error message without detailed information in 5.x:
![screen_shot_error_message_5 x](https://user-images.githubusercontent.com/8615163/30909086-22f8deb2-a380-11e7-9e96-5a1797d06a52.png)

Maybe useful, this was the error message in 4.x:
![screen_shot_error_message_4 x](https://user-images.githubusercontent.com/8615163/30909099-33125526-a380-11e7-93f0-e4761c428d2f.png)

**Comment by dennishendriksen** [comment]
@marieke-bijlsma What do you think about the following message?
```
Duplicate list value 'urn:miriam:icd:E75' for attribute 'diagnosis_available' from entity 'eu_bbmri_eric_IT_collections' with id 'bbmri-eric:ID:IT_1383214533073227:collection:1444717400944419'.
```

**Comment by marieke-bijlsma** [comment]
@dennishendriksen The new error message looks good, but I think you should change the title of the issue. The error messages are also wrong in case a value does not exist in the reference table. I think you can reproduce this by removing the duplicate value from the file. The remaining errors are from non-existing values.

**Comment by dennishendriksen** [comment]
@marieke-bijlsma Removing the duplicate value from the mref value list results in the following error:
```
Unknown xref value 'urn:miriam:icd:G15' for attribute 'diagnosis_available' of entity 'eu_bbmri_eric_IT_collections'.
```
What is the message that you expect?

**Comment by marieke-bijlsma** [comment]
@dennishendriksen That is exactly what I was expecting. Then I think this message was only incorrect in version 4.x and in 5.x only the duplicate values are giving wrong error messages. Thanks for looking into this :-)
