### ISSUE TITLE
Genomebrowser broken when using IE10

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#6732]
### How to Reproduce
- Use IE10
- Sign in as superuser
- Extract and import [test.zip](https://github.com/molgenis/molgenis/files/1317919/test.zip) using the 'Advanced data import' plugin
- Navigate to the 'Data explorer' plugin and select 'test' in the dropdown

### Expected behavior
- Genomebrowser displays track information

### Observed behavior
- Genomebrowser does not display track information
- Error:
```
Error! An error occurred. Please contact the administrator.
Resource has already been provided.
```
- Console log:
```
Failed to boot workers SecurityError
```

Might be a localhost only issue

**Comment by bartcharbon** [comment]
also breaks on m62:
gb is shown, menu only, tracks are absent

console:
eval code (506) (11,3795)
An error occurred. Resource has already been provided.  11

**Comment by dennishendriksen** [comment]
According to https://github.com/dasmoth/dalliance:
```
It works with current versions of Chrome, Firefox, and Safari and (with minor visual glitches) Internet Explorer 11. It is also usable with current mobile web browsers.
```
I propose disabling the genome browser for IE10 in the same way as we do for IE9 currently.
