### ISSUE TITLE
Metadata manager cannot store order by column

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#6739]
### How to Reproduce
Open metadata manager for TypeTestRef entity
Add new attribute with name and label `test`, of data type onetomany
Select a referring attribute from the list
Set Order by to `id;ASC`
Press Save

### Expected behavior
Attribute gets created

### Observed behavior
Sweetalert with incomprehensible error message
> Could not read JSON: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1102; nested exception is com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1102

**Comment by fdlk** [comment]
Cause is that the submitted JSON fills in a string but the model expects an EditorSort object

**Comment by fdlk** [comment]
The mapping is absent both ways. When I select an existing onetomany attribute with order by, the order is displayed as [Object object]
http://localhost:8080/menu/dataintegration/metadata-manager/sys_md_Attribute/aaaacxvx62lbknqy3mljq7aaaq

**Comment by Mark-de-Haan** [comment]
Fixed, but not closed automatically
