### ISSUE TITLE
Metadata editor is very slow causing saving to be clicked twice giving error message the second time

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6755]
### How to Reproduce
Go to metadata manager
Edit an entitytype
Press save twice

### Expected behavior
Save button is disabled after first time

### Observed behavior
Because the metadatamanager is very slow, i have to wait very long and then I get two messages, 1 succes and then: ; nested exception is org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [DROP TABLE "VKGL_consensus#e69b42f9_pu35tpw"]; nested exception is org.postgresql.util.PSQLException: ERROR: table "VKGL_consensus#e69b42f9_pu35tpw" does not exist

**Comment by dennishendriksen** [comment]
Processing metadata changes can be expected to take a long time in case of attribute type changes in combination with a large number of entities.

Besides disabling the save button we should show a spinner (in the non-Vue plugins this is performed automatically when a async HTTP requests takes longer then 500ms).
