### ISSUE TITLE
Move OneClickImporter tests from RestControllerV2APIIT.java to the OneClickImporter module

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#6757]
### Expected behaviour
In the molgenis-data-rest module there are system tests which test the controller and services of a specific module. See story http://wiki.gcc.rug.nl/ticket/4720.

### Observed behaviour
The tests are included in the RestControllerV2APIIT.java that have module specific code. 

Note: This needs to be picked up when the story 4720 is chosen in the sprint.

**Comment by dennishendriksen** [comment]
Note that https://github.com/molgenis/molgenis/pull/6777 will remove these tests due to cyclic dependency issues introduced by data-rest --> one-click-importer dependency.
