### ISSUE TITLE
Users can't delete EntityTypes

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6768]
### How to Reproduce
1. Be a user
2. Import a file with the one-click importer
3. Follow the link to the data explorer

### Expected behavior
There is a big red Delete button in the top right.

### Observed behavior
There is no button.

**Comment by tommydeboer** [comment]
Not sure if this is a bug or specs.

**Comment by fdlk** [comment]
Devs created the big red delete button on a hunch without actual user demand. So we tentatively put it in as admin-only feature. I'd currently expect this sort of thing in the metadata editor.

**Comment by dennishendriksen** [comment]
@tommydeboer Since this is not a bug but an enhancement: could you create a story in the backlog or update an existing story?
