### ISSUE TITLE
Multiple tracks in the genome browser all show the data of one entity

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#6769]
### How to Reproduce
Go to: https://drive.google.com/drive/folders/0B7PqYDHrD159M0s4NjlRUU04X28
follow the "before test" instructions from the testplan
Navigate to #/menu/main/dataexplorer?entity=base_genomebrowserTestExon
click a row to get the variants in view

### Expected behavior
an exon track is show for the genomeBrowserTestExon entity

### Observed behavior
an numeric track is show for the genomeBrowserTestExon entity

**Comment by bartcharbon** [comment]
update: all genomebrowser entities seem to duplicate one track for all entities rather than showing the track of the specific entity

**Comment by dennishendriksen** [comment]
> follow the "before test" instructions from the testplan

Executing on the 5.2 branch:
```
upload gb_test_plan_emx.xlsx
upload corner_cases.vcf as "test1"
upload corner_cases.vcf as "test2"
```
fails on the second import of corner_cases.vcf with error message (which is improved in https://github.com/molgenis/molgenis/pull/6761 on the master branch):
```
Error! Your import failed:
null
````
and log entry:
```
ERROR org.molgenis.data.vcf.VcfRepository - Failed to read VCF Metadata from file
java.io.IOException: missing column headers
	at org.molgenis.vcf.meta.VcfMetaParser.parse(VcfMetaParser.java:63)
	at org.molgenis.vcf.VcfReader.parseVcfMeta(VcfReader.java:66)
	at org.molgenis.vcf.VcfReader.getVcfMeta(VcfReader.java:53)
	at org.molgenis.data.vcf.VcfRepository.parseVcfMeta(VcfRepository.java:72)
```

**Comment by dennishendriksen** [comment]
Without ```upload corner_cases.vcf as "test2"``` my genome browser look like this:
![image](https://user-images.githubusercontent.com/2477186/31163037-c46a7f16-a8e0-11e7-9ab3-e1e5774f36fb.png)
