### ISSUE TITLE
When adding a new setting, using it after restart will add a comma to all inputs

### ISSUE THREAD

**Issue by mark-de-haan** [molgenis/molgenis#6792]
### How to Reproduce
- Create a new Java setting in DataExplorerSettings.java, boolean is easy
- Restart the app
- Go to the dataexplorer
- Open the settings with the cog and set the new setting to true
- Save and close

### Expected behavior
Dataexplorer works and setting is true when you open up the cog again

### Observed behavior

<img width="408" alt="screen shot 2017-10-05 at 17 09 10" src="https://user-images.githubusercontent.com/3625016/31234710-ec7a5cfa-a9ef-11e7-9754-a41c16c50b6c.png">
<img width="205" alt="screen shot 2017-10-05 at 17 07 07" src="https://user-images.githubusercontent.com/3625016/31234699-e4774540-a9ef-11e7-8616-d2cb10899e82.png">

**Comment by Mark-de-Haan** [comment]
The RestController does `StringUtils.join(values, ',')` on the parameter map from a request.
For fields that were **not** filled in, the request contains a list of two empty values, which is then joined into one ','.

**Comment by Mark-de-Haan** [comment]
Possibly related to #6729

**Comment by marikaris** [comment]
Let's fix this before we release molgenis 7.0
