### ISSUE TITLE
Metadata editor does not allow updating valid entity, when id attribute is changed 

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#6794]
### How to Reproduce
- Create a entity ( using metadataeditor), press save to persist the entity.
- Update the entity by adding a new attribute, make this new attribute unique and non nullable, make this new attribute the id attribute, update the old id attribute by making it non-unique and nullable.
- save the changes.
### Expected behavior
The updated entity is stored.

### Observed behavior
A error is show ' can not update entity, id attribute can not be nullable' , and the entity is not updated.

**Comment by ConnorStroomberg** [comment]
Workaround: Split updating the entity into 2 steps ( create new attribute, and change the id attribute). Persist between steps.

**Comment by dennishendriksen** [comment]
@ConnorStroomberg which version(s) are affected? can you add the relevant version label(s)?

**Comment by mswertz** [comment]
we aim to discontinue user defined ID so that should overcome this issue

**Comment by dennishendriksen** [comment]
Duplicate of #6928
