### ISSUE TITLE
Not able to enter multiple email addresses for scheduled jobs

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#6800]
### How to Reproduce

Enter a comma separated list of email addresses in the succes email or failure email field.

### Expected behavior

I can enter multiple email addresses, comma separated.
This is actually what the description of the field tells me: "Comma-separated list of emails. Leave blank if you don't want to receive emails if the jobs failed."

### Observed behavior

Only one email can be given. It gives an error message : "please enter a valid email address."

**Comment by dennishendriksen** [comment]
Relevant: [As explorer user I want to work with lists of primitives](http://www.molgenis.org/ticket/2681)
