### ISSUE TITLE
When making a mistake editing the menu json it breaks the entire webapp

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#6803]
### How to Reproduce
- edit the menu though the application settings
- remove or introduce some chars to create invalid json
### Expected behavior
an error is reported and the change is not saved

### Observed behavior
no error, settings are saved, upon reload (or navigation to any part of the application) I get a 500 page caused by freemarker

**Comment by mswertz** [comment]
why do you edit via app settings? I would expect you use menu mgr

**Comment by bartcharbon** [comment]
I encountered this while copy-pasting the menu form one server to another (way less work than recreating in the menu manager). But if you selected one character too little during the copy it'll break the entire app
