### ISSUE TITLE
Error: null when uploading EMX file with an error in it

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6807]
### How to Reproduce
- Upload the precision.xlsx sent to the data team

### Expected behavior
- I get an error message telling me what is wrong with this file

### Observed behavior
- I get an error message saying 'null'

**Comment by dennishendriksen** [comment]
@djvanenckevort which MOLGENIS version?

**Comment by djvanenckevort** [comment]
MOLGENIS 2.1 up to current snapshot on molgenis01
