### ISSUE TITLE
When I try to delete the DH part (meta data) of the chromosome 6 questionnaire, I get out of shared memory error

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6809]
### How to Reproduce
Upload: 
[Chr6_vragen_emx_testimport_11.6.xlsx](https://github.com/molgenis/molgenis/files/1393695/Chr6_vragen_emx_testimport_11.6.xlsx)
Go to base_chromosome_d_h
Delete data and meta data

### Expected behavior
The entitytype gets deleted

### Observed behavior
![screen shot 2017-10-18 at 09 07 11](https://user-images.githubusercontent.com/10075439/31705145-8c44f9d6-b3e4-11e7-9384-10aee68f0965.png)

**Comment by dennishendriksen** [comment]
We've encountered ```max_locks_per_transaction``` issues during bootstrapping on the https://github.com/molgenis/molgenis/pull/6638 branch. This is not a code issue.

In my opinion the correct fix is increasing the ```max_locks_per_transaction``` from the default ```64``` to ```128```:
- Update PostgreSQL configuration on golden VM and restart PostgreSQL
- Update PostgreSQL configuration all VMs running PostgreSQL and restart PostgreSQL
- Update PostgreSQL requirements in the MOLGENIS documentation
- Update PostgreSQL configuration in Docker images
- Notify all developers to update their PostgreSQL configuration locally

**Comment by marikaris** [comment]
The problem still occurs when I increase max locks per transaction to 256. After 30 min, I get this cryptic error message.

**Comment by dennishendriksen** [comment]
Looking at the error message I noticed that an attempt is made to update an ```Attribute```. Possibly related to https://github.com/molgenis/molgenis/issues/6822 which has been fixed on the master?

**Comment by ConnorStroomberg** [comment]
I increased max_locks_per_transaction to 512 (just a high number to test) and the entity is successfully deleted ( is does take some time). So maybe the fix @dennishendriksen suggested should be implemented ( with a higher number of locks). A more long term solution could be the change the way molgenis handles deletes making a more efficient but probably less general.

**Comment by dennishendriksen** [comment]
AttributeRepositoryDecorator is probably causing the Attribute updates:
```java
@Override
public void delete(Attribute attr)
{
	// If compound attribute is deleted then change the parent of children to null
	// This will change the children attributes into regular attributes.
	if (AttributeType.COMPOUND.equals(attr.getDataType()))
	{
		attr.getChildren().forEach(e ->
		{
			if (null != e.getParent())
			{
				dataService.getMeta()
						   .getRepository(AttributeMetadata.ATTRIBUTE_META_DATA)
						   .update(e.setParent(null));
			}
		});
	}

	// remove this attribute
	delegate().delete(attr);
}
```
Since we expect foreign keys to be valid at the end of a transaction this code shouldn't be necessary.

**Comment by ConnorStroomberg** [comment]
a log file with output from backend during delete may be found at: 

umcg.hpc.rug.nl/groups/umcg-gcc/prm02/rawdata/logs/delete-entity.log
