### ISSUE TITLE
When I try to upload the chromosome6 questionnaire on a server i get 503

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6810]
### How to Reproduce
Go to molgenis01
Go to advanced data import 
Import: 
[Chr6_vragen_emx_testimport_12_everything_nillable.xlsx](https://github.com/molgenis/molgenis/files/1418452/Chr6_vragen_emx_testimport_12_everything_nillable.xlsx)

Click next: 

### Expected behavior
The importer continues

### Observed behavior
![screen shot 2017-10-18 at 09 15 24](https://user-images.githubusercontent.com/10075439/31705419-9884240a-b3e5-11e7-9d9a-cfabb9310550.png)

**Comment by ConnorStroomberg** [comment]
Importing the file on my local dev machine i do not have a problem.
Importing the file on molgenis01 i am able to reproduce the problem.
After increasing the molgenis memory from 1 gigabyte  to 2 gigabyte i am able to import the file.

**Comment by ConnorStroomberg** [comment]
discussed with @marikaris and closed
