### ISSUE TITLE
V2 api does not support '=in=' operator for specific attributes

### ISSUE THREAD

**Issue by mark-de-haan** [molgenis/molgenis#6811]
### How to Reproduce
1) import [example.xlsx](https://github.com/molgenis/molgenis/files/1394274/example.xlsx)
2) do the following query
`/api/v2/base_collections?q=materials.label=in=(RNA,DNA)`

### Expected behaviour
I get a list of collection items that have a either RNA OR DNA as value in the materials label column

### Observed behaviour
I get an empty list

### Notes
- querying `/api/v2/base_collections?q=materials=in=(RNA,DNA)` will give you result, because the ID attribute also contains these values
- adding materials.label as a lookup attribute does not work
- known workaround: `/api/v2/base_collections?q=materials.label==RNA,materials.label==DNA`

**Comment by dennishendriksen** [comment]
@Mark-de-Haan please add a version label

**Comment by dennishendriksen** [comment]
Fixed by #8857.
