### ISSUE TITLE
REST API V2 does not respect the 'AND' operator in an RSQL query

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6815]
### How to Reproduce
1) Import TypeTest
2) Call the API directly with 
```
/api/v2/it_emx_datatypes_TypeTest?attrs=xmref_value&q=xmref_value.value==ref1,xmref_value.value==ref3;*=q=notanexistingvalue
```

### Expected behavior
I get back 0 items, because there is not a single row containing the 'notanexistingvalue' string and no matter what I filter xmref on, there is an 'AND' operator

### Observed behavior
I get 26 items, seemingly only corresponding to the xmref filters

**Comment by dennishendriksen** [comment]
@Mark-de-Haan please add a version label

**Comment by Mark-de-Haan** [comment]
My bad
Adding proper nesting  will make the query work
```
/api/v2/it_emx_datatypes_TypeTest?attrs=xmref_value&q=(xmref_value.value==ref1,xmref_value.value==ref3);*=q=notanexistingvalue
```
