### ISSUE TITLE
Inconsistent results retrieving entities with offset and page size without sort

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#6836]
### How to Reproduce
- Upload all files
- Go to the DataExplorer and select "Samples"
- Click on "Download"

### Expected behavior
The correct size of the data should be:
- samples: 24114
- subjects: 23730
- biobanks: 25
- measurements: 24074

### Observed behavior
Variable line count per download try observed in csv-file

Metadata has to be delivered yet!
[testdata.zip](https://github.com/molgenis/molgenis/files/1410894/testdata.zip)

**Comment by dennishendriksen** [comment]
@sidohaakma please add labels (version, module, type)

**Comment by djvanenckevort** [comment]
Actually the behaviour is that there are some rows duplicated and some rows missing, while the number of lines matches. So make sure you check for unique lines.

**Comment by djvanenckevort** [comment]
The testdata.zip contains the metadata for the entities, I can't send the actual data, you would have to generate test data for this.

**Comment by marikaris** [comment]
Look at fix for #6689

**Comment by dennishendriksen** [comment]
Cannot reproduce the issue using [generated test data](https://github.com/molgenis/molgenis/files/1617828/6836-testData.xlsx) and performing the following steps:
1. Launch MOLGENIS 5.3.0-SNAPSHOT with an empty database and no indices
2. Sign in as superuser
3. Import the test data using the 'Advanced data import' plugin with default options
4. Navigate to the 'Data Explorer' and select 'samples' in the entity type dropdown
5. Select 'Download' and select 'Download' in the displayed modal
6. Repeat the previous step ten times

The [resulting csv in this zip](https://github.com/molgenis/molgenis/files/1617856/base_samples_2018-01-10_08_25_01.zip) consistently contains 24114 unique sample identifiers.

**Comment by hailiangmei** [comment]
We encountered this problem at bbmri catalogue acc server (https://catalogue-acc.bbmri.nl/). Is it using version 5.2 or 5.3-SNAPSHOT? The built date of the acc server is 2017-04-06 13:11 UTC as the site indicates. Also we don't see this error in an older version of Molgenis so this could be well a version specific issue. Thus, you need to test the exact version to identify the root cause of this error.

**Comment by fdlk** [comment]
We got a report in the mail on oct 19, 2017 at 14:10 that duplicate rows occur in a download of all bbmri_nl_rp4_measurements in csv format from https://catalogue-acc.bbmri.nl/menu/rp4/  (version  2.1.0-BBMRI-NL-CATALOGUE)

**Comment by sidohaakma** [comment]
At the end of November 2017 Mariska and I tried to reproduced the issue. It is most likely that we used BBMRI-Eric data to reproduce the issue. We tried to reproduce it locally on the dev-version at that time (that would be 5.2-SNAPSHOT).

The result was that the line count was correct but the content was corrupt. There were duplicate lines and lines were missing.

**Comment by marikaris** [comment]
December the 13th we had an issue with inconsistent data in the BBMRI eric dataset on the current master. The number of rows in the download did match the number of rows in the database, but some of the rows were duplicated, others were missing. 
![screen shot 2018-01-11 at 08 50 03](https://user-images.githubusercontent.com/10075439/34814074-b3c7bb78-f6ac-11e7-9b74-0ce1c874820e.png)

**Comment by dennishendriksen** [comment]
> Is it using version 5.2 or 5.3-SNAPSHOT?
2.1.0-BBMRI-NL-CATALOGUE is based on MOLGENIS 2.1.0

**Comment by dennishendriksen** [comment]
Likely cause of this issue is SQL SELECT queries with OFFSET and LIMIT but without ORDER BY (https://www.postgresql.org/docs/9.6/static/queries-limit.html). Additionally a similar issue could also occur when the downloaded data is being modified during download because the set of SQL SELECT queries is not executed in the same (read-only) transaction.

**Comment by djvanenckevort** [comment]
BBMRI acceptance is using the following build: 2.1.0-BBMRI-NL-CATALOGUE built on 2017-04-06 13:11 UTC (but want to upgrade).
@dennishendriksen I agree that this is a likely cause, we should at least solve the issue in the case that there is no concurrent edit.
