### ISSUE TITLE
Datetime field shows 0 AM/PM as 12 AM/PM

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6840]
### How to Reproduce
1. Import *it_emx_datatypes.xlsx*
2. Open TypeTest in the Data Explorer
3.  Update the field 'xdatetime label' field a few times and look at the value in the table:

| value | expected | actual |
| --- | --- | --- |
| 1985-08-12T00:00:00+0200 | Aug 12, 1985 00:00 AM | Aug 12, 1985 12:00 AM |
| 1985-08-12T00:30:00+0200 | Aug 12, 1985 00:30 AM | Aug 12, 1985 12:30 AM |
| 1985-08-12T12:30:00+0200 | Aug 12, 1985 00:30 PM | Aug 12, 1985 12:30 PM |

(To discuss: should we use a 24-hour clock?)

**Comment by fdlk** [comment]
I took a look at [moment js](http://momentjs.com/docs/#/displaying/) and then at [the definition of the 12-hour clock on Wikipedia](https://en.wikipedia.org/wiki/12-hour_clock) and this behavior is in fact correct.

> Each period consists of 12 hours numbered: 12 **(acting as zero)**, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, and 11.
