### ISSUE TITLE
After adding a setting to Application Settings, there's an error on save

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6846]
### How to Reproduce
1. Add an attribute to ```AppDbSettings.Meta```: ```addAttribute("test");```
2. Start up the app
3. Go to the settings plugin, open the Application Settings
4. Change something and click save

### Expected behavior
Settings are saved.

### Observed behavior
```Updating read-only attribute 'ga_acc_privacy_friendly_mgs' of entity 'sys_set_app' with id 'app' is not allowed.```

When restarting the app again, the problem goes away. Different but possibly related to #6792 and #6729

**Comment by Mark-de-Haan** [comment]
This is issue #6792. It will try and update the entity with a ',' value for ga_acc_privacy_friendly_mgs.
But this attribute is readonly, causing the error
