### ISSUE TITLE
EMX with attributes sheet doesn't import data

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6853]
### How to Reproduce
- Start your MOLGENIS locally
- Run `RestControllerV1APIIT.testDeleteMeta()`

### Expected behaviour
Test succeeds

### Observed behaviour
Test fails.

## Notes
When debugging, looking at base_APITest3, the metadata is imported, but the data is not.
PR #6814 did some stuff with the importer and import modi. This might be the cause. 

EDIT: Confirmed that after reverting #6814 the tests work again
EDIT: The importer via the UI also can not import [this file](https://github.com/molgenis/molgenis/files/1429956/RestControllerV1_API_DeleteEMX.xlsx)

EDIT: **EMX files without a Package and Entity sheet only import metadata**

The REST tests import via the import API with the following parameters:
```
 .param("file")
 .param("action", "ADD_UPDATE_EXISTING")
 .header(X_MOLGENIS_TOKEN, adminToken)
 .post("plugin/importwizard/importFile")
```

**Comment by LuukDijkhuis** [comment]
Ik zou geen bugs inschieten voor broken tests

**Comment by dennishendriksen** [comment]
@LuukDijkhuis This issue is an actual importer issue in https://github.com/molgenis/molgenis/tree/master so should be reported (and should've described the user issue instead of a failing test).
