### ISSUE TITLE
Can't use one-click-importer anonymously

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6877]
### How to Reproduce
1. Give permissions to anonymous user for:
 - sys_md_EntityType
 - sys_md_Package
 - sys_md_Attribute
 - sys_md_Language
 - one-click-importer
2. Log out and go to the Quick data import
3. Try to import something

### Expected behavior
The file is imported

### Observed behavior
Nothing happens after selecting a file.

**Comment by Mark-de-Haan** [comment]
Set permission on the ImportJob
