### ISSUE TITLE
Fdp endpoint should be an API endpoint (/api/fdp)

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#6894]
### How to Reproduce
- Inspect ```org.molgenis.fair.controller.FairController```

### Expected behavior
- @RequestMapping("/api/fdp/")

### Observed behavior
- - @RequestMapping("/fdp")

All public APIs should be listed under /api

**Comment by fdlk** [comment]
I'd love to get started with the /api names but don't want to put new stuff in there before we map out how we want to use it. (i.e. versioning, what goes where, how do we document it, what belongs there and what not) Shall we briefly discuss?

**Comment by dennishendriksen** [comment]
Lets resolve this issue once we have decided on how to structure APIs.

**Comment by dennishendriksen** [comment]
Fixed in bdacaae482e59b02fa31e729900e4625cc3c94e7
