### ISSUE TITLE
Nillable expression does somehow not work with c6 questionnaire

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6901]
### How to Reproduce
Try to upload:
[Chr6_vragen_emx_testimport_12.xlsx](https://github.com/molgenis/molgenis/files/1454384/Chr6_vragen_emx_testimport_12.xlsx)

### Expected behavior
It imports fine

### Observed behavior
It does not import:
![screen shot 2017-11-08 at 16 14 18](https://user-images.githubusercontent.com/10075439/32556511-e915f9c8-c49f-11e7-8bec-673c1c0f6b54.png)

Note: I tried to make an easier model, but I cannot reproduce it with this one: 
[test_nillable_expression_questionnaire.xlsx](https://github.com/molgenis/molgenis/files/1454395/test_nillable_expression_questionnaire.xlsx)

**Comment by LuukDijkhuis** [comment]
it is reproducable with the test model if you set the nillable value for id to the expression that is used twice for id in the chr6 version: 
$('status').eq('OPEN').value()

In chr6 there are two "id" lines with that expression for nillable, on lines 992 and 1185.

If you remove those expressions in the chr6 file it loads fine, and if you add the expression to the test file then it gives the same error.

**Comment by fdlk** [comment]
What you're watching is the `validationExpression` for the `isNullable` attribute of the `Attribute` Entity type complaining that it evaluates to false. This expression reads `$('isNullable').eq(true).or($('nullableExpression').isNull()).value()` which I think means that if the `isNullable` attribute is set to `false`, the `nullableExpression` attribute must be `null`.

**Comment by marikaris** [comment]
Oh, cool, then I found another bug... I merged the three parts of the questionnaire, but forgot to remove the extra two id columns. The data set with everything nillable imports without problems. I don't know what it does with the additional id columns...

**Comment by LuukDijkhuis** [comment]
I think this one should be closed then, right? And perhaps open a new one for "the extra two id columns"?

**Comment by fdlk** [comment]
Yes, think so too.
