### ISSUE TITLE
When clicking on entity I don't have permission for, I get error instead of user-friendly message

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#6912]
### How to Reproduce
Create menu item with entity that is not accessible for the anonymous user.

### Expected behavior
A user-friendly message that says you should be logged in to view this entity.

### Observed behavior
Error! Unknown error

**Comment by Mark-de-Haan** [comment]
In v5.3.0-SNAPSHOT, you get a message saying you do not have permission on the entity
