### ISSUE TITLE
When I import scheduled jobs, the username gets filled in as SYSTEM

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6921]
### How to Reproduce
Make a scheduled job
Run it
It runs fine
Download the scheduled jobs table (! as xlsx, otherwise job parameters get messed up)
Delete the data in the table
Import the scheduled job again
Run it again

### Expected behavior
It runs fine, username is admin (as it was)

### Observed behavior

Caused by:
ScheduledJobRepositoryDecorator.java
```java
private static void setUsername(ScheduledJob job)
	{
		job.setUser(SecurityUtils.getCurrentUsername());
	}
```

This only can be fixed in the Importer. In the RunAsSystem annotation is the system user used to populate the SecurityContext. 
You can tweak the RunAsSystem annotation to use the current active SecurityContext, but the real cause of this problem is the current implementation of the security framework. With the completion of the security epic this bug will be resolved.

**Comment by dennishendriksen** [comment]
Fixed in 7.0 by cba5e78bd65672820814bcc2ce715ee3547cf0af
