### ISSUE TITLE
When altering static content, spans without text are destroyed

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6923]
### How to Reproduce
Go to homepage
Click on "Edit page"
Paste this in source:
```html
<div class="row">
    <div class="col-md-12">
        <h2>TEST</h2>
        Test buttons with glyphicons:
        <button>Envelope icon: <span class="glyphicon glyphicon-envelope"></span></button> 
        <button>Search icon: <span class="glyphicon glyphicon-search"></span></button>
        <button>Print icon: <span class="glyphicon glyphicon-print"></span></button>
        <br/>
        Test span with glyphicon:
        <span class="glyphicon glyphicon-print"></span>
        <br/>
        Test span with glyphicon and text:
        <span class="glyphicon glyphicon-print">Test</span>
        <br/>
        Test button with other class (hello) and text:
        <button class="hello">test</button>
        <br/>
        Test button without text with other class (hello2):
        <button class="hello2"></button>
        <br/>
        Test span with other class (hello3) without text:
        <span class='hello3'></span>
    </div>
</div>
```
Save
Checkout homepage
![screen shot 2017-11-15 at 12 50 00](https://user-images.githubusercontent.com/10075439/32834633-8bd6311a-ca03-11e7-8ba0-7bb41739b69e.png)

Click on "Edit page", click source

### Expected behavior
![screen shot 2017-11-15 at 12 50 51](https://user-images.githubusercontent.com/10075439/32834661-a6bb66d0-ca03-11e7-9902-8baa3fffa16c.png)

Save
![screen shot 2017-11-15 at 12 50 00](https://user-images.githubusercontent.com/10075439/32834666-aa31b9d6-ca03-11e7-9e25-0626a6188be7.png)

### Observed behavior
![screen shot 2017-11-15 at 12 51 50](https://user-images.githubusercontent.com/10075439/32834695-c9851cba-ca03-11e7-9923-8f6ec03f32e6.png)

Save
![screen shot 2017-11-15 at 12 52 16](https://user-images.githubusercontent.com/10075439/32834714-da59054c-ca03-11e7-9048-ce668dfe1a17.png)

**Comment by Mark-de-Haan** [comment]
Found a possible solution @ https://stackoverflow.com/questions/18250404/ckeditor-strips-i-tag

in view-staticcontent-edit.ftl
```js
<script>
    CKEDITOR.replace('elm1');
    CKEDITOR.dtd.$removeEmpty['i'] = false;
    CKEDITOR.dtd.$removeEmpty['span'] = false;
    CKEDITOR.dtd.$removeEmpty['button'] = false;
</script>
```
