### ISSUE TITLE
dataService findAll returns encoded JSON structure, causing the download to produce invalid JSON

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6925]
### How to Reproduce
Go to the molgenis114.gcc.rug.nl select "Admin --> Settings" and copy the menu JSON.
Go to your own molgenis instance and copy the menu JSON in the "Admin --> Settings --> Menu"

Go to the "DataExplorer" select "Application settings" click on "Download". Select "names" and "ids" and ouput form is "xlsx".

Open the menu xlsx.

### Expected behavior
JSON is downloaded correctly.

### Observed behavior
JSON is UTF-8 encoded in xslx-file.

If you import it in molgenis, it renders the menu correctly :-S.

**Comment by marikaris** [comment]
While debugging we found the dataservice.findall (on line 90) in the DataExplorerDownloadHandler class already returns the wrong data.

**Comment by Mark-de-Haan** [comment]
Note:
```java
// Debugging entities with evaluate -> `collect(Collectors.toList())` will already give you the wrong data
Stream<Entity> entities = dataService.findAll(entityTypeId, dataRequest.getQuery());
csvWriter.add(entities);
```

**Comment by bartcharbon** [comment]
The xlsx contains the wrong value to start with...

**Comment by sidohaakma** [comment]
The menu-JSON-data in molgenis114, 21 and 109 are already corrupted at the time of the download. So the downloader is downloading the data as is! Works as intended. Please correct the menu-JSON-data in the menu and it will download correctly.
