### ISSUE TITLE
When creating a PNG image with scripts plugin, an error occurs

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#6926]
### How to Reproduce
Create a script with the script plugin:
-Type = R
-Result file extension = png

Script:
plot(c(1,2,3), c(4,5,6))
png('${outputFile}')

### Expected behavior
A PNG image is shown when clicking on the button 'Go to result'

### Observed behavior
The script succeeds, but the 'Go to results' button results in a "This site can't be reached" error.

**Comment by Mark-de-Haan** [comment]
I tested with

```R
png('${outputFile}')
  x<-seq(-pi,2*pi, by=0.01)
 plot(x,2 * sin(x * 2 * pi / (3) ), type='l')
 dev.off()
```

and this worked

**Comment by Mark-de-Haan** [comment]
Using your example:

```R
png('${outputFile}')
plot(c(1,2,3), c(4,5,6))
dev.off()
```

Works, closing the issue

**Comment by Mark-de-Haan** [comment]
Updated the documentation for creating images [here](https://github.com/molgenis/molgenis/pull/6930/files)
