### ISSUE TITLE
Attribute.idAttribute update shouldn't be allowed

### ISSUE THREAD

**Issue by mark-de-haan** [molgenis/molgenis#6928]
### How to Reproduce
- In the metadata manager, create a new EntityType
- Add an attribute name = id_1, label = First ID
- set First ID as ID attribute and as Label attribute
- Save
<br></br>
- Add an attribute name = id_2, label = Second ID
- Set Second ID as ID attribute and as Label attribute
- Save
<br></br>
- Set First ID as nullable
- Save

### Expected behavior
Save is successful because First ID is no longer the ID attribute

### Observed behavior
`; nested exception is org.postgresql.util.PSQLException: ERROR: column "id_1" is in a primary key`

**Comment by mswertz** [comment]
we aim to disable user defined IDs. So only fix if small.
