### ISSUE TITLE
Can't add self-referencing OneToMany with Metadata Manager

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6954]
### How to Reproduce
1. Import *it_emx_datatypes.xlsx*
2. Go to the Metadata Manager
3. Add an attribute to TypeTestRef
    a. name: xref
    b. type: xref
    c. reference entity: TypeTestRef
4. Save the changes
5. Add another attribute to TypeTestRef
    a. name: onetomany
    b. type: onetomany
6. Notice that you can't select the reference entity for the OneToMany attribute

### Expected behavior
The field 'reference entity' is visible and can be used to select the reference entity, after which the 'mapped by' field can be used to select the xref attribute.

OR:

The field 'mapped by' also shows self referencing xrefs. (Now it just shows xrefs that originate in TypeTest). Example of the expected 'mapped by' options:

- TypeTest - xxref_value
- TypeTest - xcategorical_value
- TypeTestRef - xref

### Observed behavior
There is no 'reference entity' field for the OneToMany attribute and the list of 'mapped by' options does not list the self-referencing xref in TypeTestRef.

**Comment by dennishendriksen** [comment]
@marikaris this is a more complicated use case of adding a one-to-many https://github.com/molgenis/molgenis/issues/7474

**Comment by dennishendriksen** [comment]
Fixed by #7474 in 7.0
