### ISSUE TITLE
Downloading a big dataset (66.000 rows, 27 columns) can only be done downloading ids, names and csv

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6962]
### How to Reproduce
Upload the vkgl data model and data (this data consists of 66.000 rows, the model contains 28 columns, 8 columns are xref, 1 is an mref with omim terms)
Go to consensus table in dataexplorer
Click on download

### Expected behavior
I can select any option I would like

### Observed behavior
If i choose any option different from ids, names and CSV I get internal server error 

Now the dataset is 97.000 rows, I cannot download it in any way

Edit DH: httpd logs:
```
[Thu May 31 08:10:43 2018] [error] ajp_read_header: ajp_ilink_receive failed
[Thu May 31 08:10:43 2018] [error] (70007)The timeout specified has expired: proxy: read response failed from [::1]:8009 (localhost)
```

**Comment by Mark-de-Haan** [comment]
I think that download issues (slow!!!!! not working for labels) should be solved by running downloads as a Job, and running them smarter.

I created a story [here](http://wiki.gcc.rug.nl/ticket/5537#ticket)

**Comment by marikaris** [comment]
It's still an issue though

**Comment by dennishendriksen** [comment]
Fixed on the server in question by updating the httpd Timeout from 60 to 600.
