### ISSUE TITLE
MenuManagerServiceImpl bean not found during bootstrap on mac os version 'high sierra'

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#6967]
### How to Reproduce
- Install high sierra on a apple mac
- checkout and build molgenis master
- run molgenis

### Expected behavior
- molgenis bootstraps and starts 

### Observed behavior
- startup fails with error message indicating 'MenuManagerServiceImpl' bean can not be found, but is needed in 'AppDbSettings'

**Comment by fdlk** [comment]
I've updated the issue title to include the class of the bean that cannot be found. I remember running into the same error in tomcat 8.
