### ISSUE TITLE
Icons are not fetched when a server is behind a firewall

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6976]
### How to Reproduce
Go to molgenis61 (use safari)
login
import a simple file (which you can delete as well) in the advanced importer

### Expected behavior
There is a spinner in the final import screen

### Observed behavior
You see a question mark. The server is behind a firewall and can not fetch icons.

In the console:
<img width="1245" alt="screen shot 2017-12-01 at 10 03 51" src="https://user-images.githubusercontent.com/3625016/33475513-fd4e2096-d67e-11e7-8c8f-c2455c6ca3f4.png">

**Comment by ConnorStroomberg** [comment]
what is the type of importer used to reproduce( simple or advanced ) ?

**Comment by Mark-de-Haan** [comment]
Its the spinner icons and the icons in the [datexplorer tab](https://molgenis01.target.rug.nl/menu/main/dataexplorer)

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Could you provide the full URL of failed requested resources from your screenshot?

**Comment by Mark-de-Haan** [comment]
It tries to get `server-url/img/image.icon`.

It turned out that, because this is behind a firewall, we manually copied the war to the server. This WAR somehow was faulty, causing the error to occur. So we can close this.
