### ISSUE TITLE
When using the questionnaire after some time chrome completely crashes with "too many open files"

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6987]
### How to Reproduce
Use Google chrome (I have not tried it with other browsers yet)
Play around with the questionnaire, add new rows, alter some, the more rows, the more likely you will get lucky in reproducing the bug. Also having lots of tabs open in chrome might help, but having only two will do the trick sometimes as well. Use this initially:
[Chr6_vragen_emx_testimport_12_fix.xlsx](https://github.com/molgenis/molgenis/files/1534335/Chr6_vragen_emx_testimport_12_fix.xlsx)
and:
[c6_questionnaire_2017-12-06_09_11_03.xlsx](https://github.com/molgenis/molgenis/files/1534344/c6_questionnaire_2017-12-06_09_11_03.xlsx)

### Expected behavior
Everything goes well, sometimes I have to wait a few seconds, but everything works (just the way it does most of the time).

### Observed behavior
Lots of errors, the most important one:
```
Dec 05, 2017 12:14:16 PM org.apache.catalina.loader.WebappClassLoaderBase openJARs
WARNING: Failed to open JAR [null]
java.io.FileNotFoundException: /Users/mslofstra/git/molgenis/molgenis-app/target/molgenis-app-5.3.0-SNAPSHOT/WEB-INF/lib/molgenis-ontology-core-5.3.0-SNAPSHOT.jar (Too many open files in system)
	at java.util.zip.ZipFile.open(Native Method)
```
After this chrome crashes totally (and if you don't kill tomcat run molgenis fast enough intellij as well), can be fixed by clearing the index and restarting the app (and if you waited too long with killing first restarting your computer). 

Using the lsof command shows a load of files opened by Google (Chrome).

Here some more stacktraces I get:
[balaat.txt](https://github.com/molgenis/molgenis/files/1534347/balaat.txt)

We should find out why so many files are opened when doing this.

**Comment by marikaris** [comment]
Update: it turned out my postgresql was really mad when I reproduced this issue, it produced a log file of 152 GB! So when working on this, keep in mind that you might have to clear your postgresql logs.

**Comment by sidohaakma** [comment]
Is rewritten in VUE in MOLGENIS version 7.0.0. This behavior is not observed anymore.
