### ISSUE TITLE
Rest controller test classes contain ugly JSON strings

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7028]
### How to Reproduce
Look at the rest controller test classes

### Expected behavior
Tests are readable

### Observed behavior
Stuff like this: https://github.com/molgenis/molgenis/blob/a640675602cb76527649ee428ef768847a5da207/molgenis-data-rest/src/test/java/org/molgenis/data/rest/v2/RestControllerV2Test.java#L1179

**Comment by dennishendriksen** [comment]
Responses were moved to files.
