### ISSUE TITLE
Mapping service fails when using a target entity with auto id's

### ISSUE THREAD

**Issue by pmhuizinga** [molgenis/molgenis#7047]
### How to Reproduce
when mapping to a table with an auto id the mapping fails

### Expected behavior
for each new mapped record the autoid should be populated

### Observed behavior
error when mapping. See molgenis107

**Comment by dennishendriksen** [comment]
I've reproduced the issue using [this test data](https://github.com/molgenis/molgenis/files/1617956/7047-testData.xlsx):
1. Launch MOLGENIS 5.3.0-SNAPSHOT with an empty database and no indices
2. Sign in as superuser
3. Import the test data using the 'Advanced data import' plugin with default options
4. Navigate to the 'Mapping service' plugin, select 'Add Mapping Project', use 'test' as Mapping project name, select 'base_target' as target, select 'Create project'
5. Select 'Add source', select 'base_source' in the dropdown and select 'Add source'
6. Select the 'pencil' icon on row with the 'label' attribute
7. Select the attribute 'text' in the table, select 'Validate algorithm', select 'Save', select 'Cancel and go back'
8. Select 'Create integrated data set', select 'Existing data set', select 'base target (target)', select 'Start mapping!'

The mapping job fails with log:
```
09:18:59.069 - Execution started.
09:18:59.073 - progress (0, Checking target repository [base_target]...)
09:18:59.075 - Applying mappings to repository [base_target]
09:18:59.075 - Mapping source [source]...
09:18:59.964 - Failed. Null id
```
