### ISSUE TITLE
Metadata manager not working for entity extending from abstract entity

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#7048]
### How to Reproduce
1) Create EMX with two entities. One abstract entity and the other extending from that entity.
2) Upload the EMX and try to change the datatype (from string to int for example) for an attribute of the abstract entity, using the metadata manager or Attribute entity (both fail).

### Expected behavior
The data type has successfully changed from string to int.

### Observed behavior
Duplicate key error.

NOTE: When removing the entity extending from the abstract entity, it will change the datatype successfully.

**Comment by pmhuizinga** [comment]
[emx_test_mapping.xlsx](https://github.com/molgenis/molgenis/files/1614568/emx_test_mapping.xlsx)

**Comment by pmhuizinga** [comment]
1. import file
2. map table test1, field name to table test2, field name (do NOT map the ID fields)
3. errormessage "null id" will occur.
