### ISSUE TITLE
core-ui js files not generated during clean install on windows machine

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#7062]
```
    <execution>
        <id>webpack production build</id>
        <goals>
            <goal>webpack</goal>
        </goals>
        <configuration>
           <outputdir>target/classes/js/dist</outputdir>
            <arguments>-p --config webpack.production.config.js</arguments>
        </configuration>
    </execution>
```

Output dir uses unix file separator characters. On windows machine this doesn't work.
Should use ${file.separator} to insert OS specific file separators

#### Reproduce
Clean install molgenis-core-ui module

#### Observed
On my windows 10 machine @home I saw that the `molgenis-core-ui/target/classes/js/dist/molgenis-vendor.js` was not generated, resulting in a non functional app. Normally I clean install again to make it work, but after running a build 4 times, the folder was still not generated. Replacing the hardcoded `/` with `${file.separator}`, the folder including the files was created.

**Comment by dennishendriksen** [comment]
Can you add a how to reproduce with the observed behavior?

**Comment by dennishendriksen** [comment]
Cannot reproduce on Windows 10:
```mvn clean install``` in module ```molgenis-core-ui``` results in a ```target\classes\js\dist``` folder with files:
- molgenis-global.js
- molgenis-global.js.map
- molgenis-global-ui.js
- molgenis-global-ui.js.map
- molgenis-vendor-bundle.js
- molgenis-vendor-bundle.js.map

Do you expect ```molgenis-vendor.js``` as well?

**Comment by Mark-de-Haan** [comment]
Could not reproduce on other dev machines
