### ISSUE TITLE
It is not possible to have an 'auto' parameter for a date field in an EMX File.

### ISSUE THREAD

**Issue by pmhuizinga** [molgenis/molgenis#7081]
In the metadata editor it is possible to check the 'auto' parameter of a date field. This causes every new record to be populated with the current date (which becomes 'entry date'). In an EMX file it is unfortunately not possible to select this option. 

### How to Reproduce
I tried using the IDAttribute field with value 'AUTO'.

### Expected behavior
Imported emx file with datefield 'AUTO'

### Observed behavior
error on upload. idAttributie 'AUTO' is only possible for string types.
[gdio_test.xlsx](https://github.com/molgenis/molgenis/files/1651633/gdio_test.xlsx)

**Comment by dennishendriksen** [comment]
This is feature request, closing it in favor of http://molgenis.org/ticket/5361.
