### ISSUE TITLE
Nillable expression unclear error message

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7087]
### How to Reproduce
Upload: 
~~[Chr6_vragen_emx_testimport_12_fix.xlsx](https://github.com/molgenis/molgenis/files/1659449/Chr6_vragen_emx_testimport_12_fix.xlsx)~~ (6.0 version)

Go to questionnaire
Submit

### Expected behavior
Nice message telling me that some fields which are required are not filled in. 

### Observed behavior
Overkill: 
![screen shot 2018-01-24 at 11 29 03](https://user-images.githubusercontent.com/10075439/35327509-0837ff90-00fa-11e8-8c16-94190ca1e055.png)

**Comment by tommydeboer** [comment]
@marikaris I'm unable to import the dataset you attached:

`Duplicate attribute name [Intro] for entity type [c6_questionnaire]`

**Comment by tommydeboer** [comment]
This issue can't happen in the new questionnaire plugin in 7.0
