### ISSUE TITLE
Mapping service algorithm is filled in automatically with "test"

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#7109]
### How to Reproduce
* [Import TypeTest](https://github.com/molgenis/molgenis/files/1677463/it_emx_datatypes.xlsx)
* Go to the mapping service
* Create a new mapping project with **TypeTestRef** as target
* Add TypeTestRef as new source
* Edit label attribute

### Expected behaviour
Label to label is such an easy mapping, I expect it to be filled in

### Observed behaviour
Label is not automatically matched, and instead the algorithm contains `test`

**Comment by marikaris** [comment]
I tried to reproduce it, but the label is not filled in with "test" (it is also not filled in with label, so it is a bug but less severe?)

Can you try to reproduce it again?

**Comment by Mark-de-Haan** [comment]
Can not reproduce :S
