### ISSUE TITLE
standalone entity reports do not work with entities with special chars in the identifier

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#7115]
### How to Reproduce
upload a vcf
add a row with simple string values for the required field, but "éé#$é^" for the identifier
enable standalone entity reports
click the magnifying glass for the newly added row
copy the link to the standalone report (left upper corner)
paste in the URL bar of your browser

### Expected behavior
the report is shown

### Observed behavior
500
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> entity  [in template "view-standalone-report-default.ftl" at line 7, column 12]

**Comment by dennishendriksen** [comment]
The URL to the standalone report in the entity report is incorrect, since the entity identifier is not encoded. The correct URL is ```.../menu/main/dataexplorer/details/testdata/%C3%A9%C3%A9%23%24%C3%A9%5E```.  The subsequent issue is Spring decoding the path variable incorrectly.
