### ISSUE TITLE
Unclear error 'add' importing an EMX file twice

### ISSUE THREAD

**Issue by Sipkovandam** [molgenis/molgenis#7131]
### How to Reproduce
Advanced data import -> Import database.emx --> add entities (finish all steps)
repeat:
Advanced data import -> Import database.emx --> add entities (finish all steps)
This gives an error

### Expected behavior
Correct error indicating the data was already loaded and needs to be dropped before importing data or suggesting "add/update option".

### Observed behavior
Import failed
Unknown attribute for column name ["FileID"]

**Comment by marikaris** [comment]
Can you define your How to Reproduce better?

**Comment by dennishendriksen** [comment]
@Sipkovandam Could you address @marikaris her questions?

**Comment by Sipkovandam** [comment]
Sorry, I think I accidently removed some info when I initially submitted this ticket. If you import an emx you readily imported and then use the same options again, it does not inform you that you have already imported this data, but gives an unrelated error.

 I hope this is clear?  Otherwise just let me know.
