### ISSUE TITLE
Label of mail sender properties ends with .

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7133]
### How to Reproduce
Go to dataexplorer
Type mail in dropdown

### Expected behavior
Mail sender properties

### Observed behavior
![screen shot 2018-02-01 at 16 31 46](https://user-images.githubusercontent.com/10075439/35686872-a15a1518-076d-11e8-9c02-ac7211a0d924.png)

**Comment by mswertz** [comment]
why is this important?
