### ISSUE TITLE
Index job execution user incorrectly set to "admin"

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7167]
### How to Reproduce
Use RD connect app
Create superuser other than admin
Login as superuser
Trigger ID card indexer
Go to index job execution

### Expected behavior
Job owner is my superuser name

### Observed behavior
Job owner is admin, causing indexing to fail when admin is disabled

Problem is here:
https://github.com/molgenis/molgenis/blob/d2e57093a5163f7d918cd8179212aee695b87664/molgenis-data-index/src/main/java/org/molgenis/data/index/job/IndexJobSchedulerImpl.java#L67

**Comment by Mark-de-Haan** [comment]
Why would you disable admin?

**Comment by marikaris** [comment]
There are reasons to do this and this actually is an issue on a production server so this is relevant and not just a theorethical case.

**Comment by marikaris** [comment]
The real question is: why is there a hardcoded line "admin" in the code?

**Comment by LuukDijkhuis** [comment]
will be fixed by story #5676

**Comment by mswertz** [comment]
Is this now indeed fixed @LuukDijkhuis

**Comment by mswertz** [comment]
id card indexer will be discontinued

**Comment by tommydeboer** [comment]
@mswertz This is not just an id card indexer problem. See [M5676](http://molgenis.org/ticket/5676)

**Comment by dennishendriksen** [comment]
Fixed by 3a56fb5badf6cf1f3ffa1de3e75a1edc19ba60cf
