### ISSUE TITLE
When I upload data with one row, data is not uploaded

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7183]
### How to Reproduce
Upload with advanced importer, add mode: 
[eric_de_test_model.xlsx](https://github.com/molgenis/molgenis/files/1744269/eric_de_test_model.xlsx)
Upload csv in this zip: 
[eu_bbmri_eric_DE_biobanks.csv.zip](https://github.com/molgenis/molgenis/files/1744288/eu_bbmri_eric_DE_biobanks.csv.zip)

### Expected behavior
1 row is added to the biobanks table

### Observed behavior
Import succeeds, 0 rows imported

**Comment by dennishendriksen** [comment]
CSV file is an invalid EMX file since the number of column headers (18) does not match the number of values (17). Invalid lines like this are ignored, by design, in our CSV iterator.
