### ISSUE TITLE
Mapping service should not allow creating a mapping to a computed variable

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#7199]
### How to Reproduce
- Create an entity with a computed variable
- Create a mapping project

### Expected behavior
The mapping project does not have a mapping for the computed variable, since it is computed and not stored

### Observed behavior
The mapping service tells that the computed variable is a required variable to map.

**Comment by marikaris** [comment]
In 6.0 I get the "missing" tag but the mapping runs correctly

**Comment by dennishendriksen** [comment]
Example EMX file to reproduce the issue: [it_emx_computed.xlsx](https://github.com/molgenis/molgenis/files/2067373/it_emx_computed.xlsx)
