### ISSUE TITLE
Package link to navigator is shown for users without navigator plugin permissions

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#7215]
### How to Reproduce
- create a user
- grant permissions on dataexplorer, GenomeBrowserConfiguration...
- login as this user and navigate to the dataexplorer

### Expected behavior
- no link to the navigator is shown besides the entity name in the title bar, since the user has no navigator permissions

### Observed behavior
link to the navigator is shown besides the entity name in the title bar, clicking it results in a 403 page

### NOTE:
The dataexplorer checks 2 things for showing this link: is the dataexplorersetting for showing this is set to true, and if the navigator is in the menu. The second check depends on a "run as system" function, and seems to check if the navigator is in the menu before a filtering based on permissions is performed.

**Comment by ConnorStroomberg** [comment]
> "The second check depends on a "run as system" function, and seems to check if the navigator is in the menu before a filtering based on permissions is performed"

Is this new behaviour introduced by changes to the permission system ? In that case this should really be fixed right now and we should check the other modules that use a similar system for optionally rendering links to other plugins.

**Comment by dennishendriksen** [comment]
@bartcharbon can you add label(s) for affected version(s)?

**Comment by mswertz** [comment]
We have defaulted sensible combinations of permissions in global roles. So urgency has been reduced.

**Comment by bartcharbon** [comment]
It's not happening anymore in the current master (8.3)
