### ISSUE TITLE
Error when selecting an mref with default values referring a row level secured entity type

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7226]
### How to Reproduce
1. As admin:
a. Upload it_emx_datatypes
b. Make TypeTestRef row level secured
c. Give user VIEW permission to Location and Person
c. Give user EDIT permission to TypeTest, TypeTestRef
2. As user:
a. Go to TypeTestRef and add a row 'testref'
b. Go to TypeTest and start adding a new row
c. Check the box for 'xcategoricalmref_value' 

### Expected behavior
User can select 'testref' for 'xcategoricalmref_value' without problems

### Observed behavior
```Uncaught TypeError: Cannot read property 'label' of undefined```

This issue is probably related to the fact that TypeTest uses default values for reference types that refer to rows that are not accessible to the user (ref1 and ref2). When removing the default values from the metadata of TypeTest, the issue doesn't occur.

**Comment by dennishendriksen** [comment]
@tommydeboer can you add labels for affected version(s)?

**Comment by dennishendriksen** [comment]
@tommydeboer *bump*

**Comment by dennishendriksen** [comment]
Issue only exists on branch.
