### ISSUE TITLE
Hidden attributes can be used as lookups

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7247]
### How to Reproduce
1. Import [hidden_and_lookup.xlsx](https://github.com/molgenis/molgenis/files/1841150/hidden_and_lookup.xlsx)
2. Go to entity 'test'
3. Edit a row and look at the entity select box for 'ref'

### Expected behavior
Importer won't allow it, explaining that hidden attributes are hidden and can't be used as a lookup

### Observed behavior
The values of the hidden attribute are visible in the entity select box

**Comment by tommydeboer** [comment]
@djvanenckevort @marikaris @marieke-bijlsma is this safe to fix? Are you aware of any datasets that use this bug as a 'feature'?

**Comment by djvanenckevort** [comment]
I can't think of an example where it is used at the moment.
