### ISSUE TITLE
Label attribute can be hidden

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7248]
### How to Reproduce
1. Import [label_is_hidden.xlsx](https://github.com/molgenis/molgenis/files/1841235/label_is_hidden.xlsx)
2. Go to entity 'test'
3. Edit a row and inspect the entity select box

### Expected behavior
A hidden label doesn't really make sense and should be denied on import

### Observed behavior
The values of the hidden attribute are visible in the entity select box, but in the 'ref' entity the attribute is actually hidden.

**Comment by dennishendriksen** [comment]
@tommydeboer can you add labels for affected version(s) and likely causal module(s)?
