### ISSUE TITLE
Test fails if multiple jobs run the same test on ci

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7250]
### How to Reproduce
Run multiple test-jobs on CI

### Expected behavior
Test succeed if al expectations are met 

### Observed behavior
CsvIteratorTest.testIteratorFromCsvFile fails.
This test uses a file that is mutated by multiple jobs

**Comment by fdlk** [comment]
Duplicates #7434 , let's fix them all together.
