### ISSUE TITLE
Cannot update attributes for an abstract entity that is extended by concrete entity

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#7254]
### How to Reproduce
Using the RD-Connect data model:
- Change the Ontology Term abstract entity to remove IRI from the lookup attributes

### Expected behavior
The entity is correctly updated

### Observed behavior
An error message: Duplicate key AttributeDescription{name=IRI}

**Comment by dennishendriksen** [comment]
@djvanenckevort which version is affected?

**Comment by djvanenckevort** [comment]
Tested it in 4.1 and 6.0 Docker

**Comment by fdlk** [comment]
Happens for even the smallest updates to attributes in an abstract entity. The postgres repositorycollection decorator mucks up the copying of the entity type, attempting to remove and re-add it to the concrete subclass, never noticing that the attribute comes from the abstract entity.

**Comment by fdlk** [comment]
If I try this through the metadata manager, I run into plenty more bugs related to abstract entity types.
