### ISSUE TITLE
When clicking on the x on the first lookup attribute in the Metadata manager the last lookup attribute is removed

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#7255]
### How to Reproduce
Using the RD-Connect datamodel
- Select the Ontology Term entity in the metadata manager
- Click on IRI to remove it from the lookup attributes

### Expected behavior
IRI is removed from the list of lookup attributes

### Observed behavior
Code is removed from the list of lookup attributes

**Comment by dennishendriksen** [comment]
@djvanenckevort which version is affected?

**Comment by djvanenckevort** [comment]
Tested it in MOLGENIS 6 docker.
