### ISSUE TITLE
Activating google signup breaks molgenis on safari with adblocker enabled

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7262]
### How to Reproduce
On safari with adblocker enabled:
Log in as admin, open Authentication settings
Enable signup, disable moderation, enable google signup, save.
Reload the page
Click logout button

### Expected behavior
Logged out

### Observed behavior
> Error! An error occurred. Please contact the administrator.
ReferenceError: Can't find variable: gapi

Also, a fresh browser arriving at a molgenis instance with google signup enabled gets:

> Error! An error occurred. Please contact the administrator.
Script error.

**Comment by dennishendriksen** [comment]
@fdlk can you add version label(s)?

**Comment by ConnorStroomberg** [comment]
unable to reproduce on localhost

**Comment by ConnorStroomberg** [comment]
unable to reproduce on https://molgenis01.gcc.rug.nl/

**Comment by dennishendriksen** [comment]
@fdlk @ConnorStroomberg which browsers did you use?

**Comment by fdlk** [comment]
Had a little debug session with @ConnorStroomberg and the cause is my ad blocker.

**Comment by mswertz** [comment]
duplicated issue

**Comment by fdlk** [comment]
@mswertz which one does it duplicate? This Is different from #6508 in that entire application becomes unusable but only for this specific setup.
