### ISSUE TITLE
Label attribute refers to invisible attribute

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7285]
### How to Reproduce
- Import it_emx_autoid.xlsx
- Update the id attribute visible --> non-visible using the metadata manager
- Result: label attribute now refers to an invisible attribute

### Expected behavior
- Error message

### Observed behavior
- Action succeeds

**Comment by tommydeboer** [comment]
Fixed in #7395

**Comment by mswertz** [comment]
so can be closed?
