### ISSUE TITLE
Search all plugin missing results

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#7302]
### How to Reproduce
- Load typetest into MOLGENIS
- Go to the DataExplorer 
- Select TypeTest table
- Type str: you get multiple rows matching str in row content
- Go to searchAll plugin
- Type str: you will get only the matches in typetestref metadata 

### Expected behavior
You see the rows in typetest when typing "str" in the search all plugin.

### Observed behavior
You will get only the matches in typetestref metadata 

### Possible code entries
- SearchAllService --> look at DataService.count

[it_emx_datatypes.xlsx](https://github.com/molgenis/molgenis/files/1914989/it_emx_datatypes.xlsx)

**Comment by dennishendriksen** [comment]
> SearchAllService --> look at DataService.count

dataService.count(entityType.getId(), new QueryImpl<>().search(searchTerm)) returns 38 for ```it_emx_datatypes_TypeTest```.

**Comment by dennishendriksen** [comment]
The response does contain:
```
{
"label": "TypeTest",
"description": "MOLGENIS Data types test entity",
"id": "it_emx_datatypes_TypeTest",
"packageId": "it_emx_datatypes",
"labelMatch": false,
"descriptionMatch": false,
"attributes": [
{
"label": "xcompound_string label",
"description": "TypeTest compound string attribute",
"dataType": "STRING"
},
{
"label": "xstring label",
"description": "Typetest string attribute",
"dataType": "STRING"
},
{
"label": "xstringnillable label",
"description": "Typetest nillable string attribute",
"dataType": "STRING"
},
{
"label": "xstring_hidden label",
"description": "Typetest hidden string attribute",
"dataType": "STRING"
},
{
"label": "xstringnillable_hidden label",
"description": "Typetest nillable hidden string attribute",
"dataType": "STRING"
},
{
"label": "xstring_unique label",
"dataType": "STRING"
}
],
"nrOfMatchingEntities": 38
}
```

**Comment by dennishendriksen** [comment]
The browser console displays:
```
vendor.js?8zHMww:6 TypeError: Cannot read property 'toString' of undefined
    at o.highlight (app.js?pbN0mw:1)
    at o.n (vendor.js?8zHMww:6)
    at app.js?pbN0mw:1
    at ot [as _l] (vendor.js?8zHMww:6)
    at o.render (app.js?pbN0mw:1)
    at o.e._render (vendor.js?8zHMww:6)
    at o.r (vendor.js?8zHMww:6)
    at zi.get (vendor.js?8zHMww:6)
    at new zi (vendor.js?8zHMww:6)
    at Ye (vendor.js?8zHMww:6)
```
