### ISSUE TITLE
Maven build yarn errors

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7332]
### How to Reproduce
- Execute ```"<java_path>\java.exe" -Dmaven.multiModuleProjectDirectory=<molgenis_path>\molgenis -Xms1g -Xmx2g "-Dmaven.home=<maven_path>\lib\maven3" "-Dclassworlds.conf=<maven_path>\lib\maven3\bin\m2.conf" "-javaagent:<intellij_path>\idea_rt.jar=50020:<intellij_path>\bin" -Dfile.encoding=UTF-8 -classpath "<maven_path>\lib\maven3\boot\plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2018.1.2 -T 3 -DskipTests=true clean install```

### Expected behavior
Build completes successfully with no logged errors

### Observed behavior
Build completes successfully with the following logged errors:
```
[ERROR] warning Waiting for the other yarn instance to finish (2788)
[ERROR] warning Waiting for the other yarn instance to finish (2788)
[ERROR] warning "@molgenis/molgenis-ui-form@0.10.2" has incorrect peer dependency "vue@2.5.13".
[ERROR] warning "@vue/test-utils@1.0.0-beta.12" has unmet peer dependency "vue-server-renderer@2.x".
[ERROR] warning Waiting for the other yarn instance to finish (4276)
[ERROR] warning "ajv-keywords@1.5.1" has unmet peer dependency "ajv@>=4.10.0".
[ERROR] (node:13132) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
[ERROR] parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
[ERROR] warning Waiting for the other yarn instance to finish (12832)
[ERROR] warning "@molgenis/molgenis-ui-form@0.10.2" has incorrect peer dependency "vue@2.5.13".
[ERROR] warning "eslint-config-vue@2.0.2" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
[ERROR] warning "eslint-plugin-flowtype-errors@3.5.1" has incorrect peer dependency "flow-bin@>=0.66.0".
[ERROR] warning "eslint-plugin-flowtype-errors@3.5.1" has incorrect peer dependency "flow-bin@>=0.66.0".
```

**Comment by ConnorStroomberg** [comment]
i think this is related to: 
[DeprecationWarning being logged as error #680](https://github.com/eirslett/frontend-maven-plugin/issues/680)

will need to look into the webpack behaviour described in the issue linked above

**Comment by dennishendriksen** [comment]
Resolved, since this part of the frontend was moved from https://github.com/molgenis/molgenis to https://github.com/molgenis/molgenis-frontend
