### ISSUE TITLE
Metadata manager 'unknown error' when creating a file attribute

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#7335]
### How to Reproduce
- Create a new entity
- Add a new attribute
- Set the name, label and set type to file
- Save the entity

### Expected behavior
A new attribute is created

### Observed behavior
An 'unknown error' message pops up.

**Comment by dennishendriksen** [comment]
@djvanenckevort Which version did you use?

**Comment by djvanenckevort** [comment]
Latest version on molgenis01
