### ISSUE TITLE
Jobs that fail with internationalized exception get debug string in exception log

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7354]
### How to Reproduce
Run a job that fails with coded runtime exception
Open the log

### Expected behavior
Exception message is formatted in the job user's locale

### Observed behavior
Exception message is in the id:value debug format used in getMessage()

**Comment by fdlk** [comment]
See http://wiki.gcc.rug.nl/ticket/5524

**Comment by dennishendriksen** [comment]
I don't think this is a bug: the observed behavior is the intended behavior for log files.

**Comment by mswertz** [comment]
wontfix, works as intended.
