### ISSUE TITLE
Cannot opt out of google analytics if you have ad blocker installed on safari

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7377]
### How to Reproduce
On safari, with ad blocker installed, go to a molgenis with google analytics enabled and click on the opt out link in the footer.

### Expected behavior
Opted out or already opted out due to ad blocker and hence no opt out link

### Observed behavior
> Error! An error occurred. Please contact the administrator.
ReferenceError: Can't find variable: gaOptout

Spotted on https://molgenis109.gcc.rug.nl/

**Comment by djvanenckevort** [comment]
This is a generic problem, not related to Safari or Ad blockers, I can reproduce it with Chrome or with ad blockers disabled. I created an issue for this before (#6508) and the issue is present since at least 2.1.

**Comment by mswertz** [comment]
duplicated ticket see #6508.
