### ISSUE TITLE
Import wizard package assignment broken

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7379]
### How to Reproduce
- As superuser import [it_emx_autoid_no_packages.xlsx](https://github.com/molgenis/molgenis/files/2038681/it_emx_autoid_no_packages.xlsx) using the 'Advanced data import' plugin. In step 3 select package ```it_emx```.

### Expected behavior
- Entity type ```testAutoId``` is imported in package ```it > emx```

### Observed behavior
- Entity type ```testAutoId``` is imported in package ```base```

**Comment by tommydeboer** [comment]
Closed in #7413
