### ISSUE TITLE
Data explorer entered-data lost on click outside of modal

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7412]
### How to Reproduce
Go to dataexplorer
Click on add row
Fill in everything
Click on grey background next to modal

### Expected behavior
Nothing happens, I can fill in everything without my modal closing

### Observed behavior
Modal closes, data gone, sad datamanager

**Comment by marikaris** [comment]
https://getbootstrap.com/docs/3.3/javascript/#modals-usage

the option backdrop should be set to 'static'

**Comment by mswertz** [comment]
is this in the 'old' or in the 'new' forms?

**Comment by tommydeboer** [comment]
@mswertz this is in the old forms
