### ISSUE TITLE
Example app from docs is not a valid zip file

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7423]
### How to Reproduce
go to https://molgenis.gitbooks.io/molgenis/content/developer_documentation/app-development.html 

and download the 'example-app.zip' file linked
### Expected behavior
A valid zip file can be downloaded and extracted

### Observed behavior
The file downloaded can not be extracted

**Comment by sidohaakma** [comment]
Closed by #7685
