### ISSUE TITLE
Leftover plugin when deleting active app

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7431]
### How to Reproduce
Upload an app, activate, delete.
Upload app again

### Expected behavior
Cannot delete active app or app can be uploaded again after deleting

### Observed behavior
> Object identity 'org.molgenis.data.plugin.model.PluginIdentity[Type: plugin; Identifier: app/example2/]' already exists

Happens because the Plugin that got created for the App still exists.
The plugin cannot be deleted in the data explorer either because the id has a / in it..

**Comment by mswertz** [comment]
Important because want to delete app and then upload again

**Comment by bartcharbon** [comment]
Deletion of active apps is blocked in the ui.

However, you can delete the app using the data explorer or REST API, this way the specific code for the apps is never fired, the standard entity delete mechanism takes care of the deletion. Leaving the plugin and zip file where they are, regardless of the (in)activity of the app.

To fix this the delete method for apps should be moved to a decorator.
