### ISSUE TITLE
Putting apps in the menu relies on plugin ID hack

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7432]
### How to Reproduce
Upload app, add it to the menu, open data explorer, select Plugin

### Expected behavior
Plugin ID does not contain /

### Observed behavior
Plugin ID equals `app/uri/`, where uri is the actual app id.
This is not okay, because the REST api cannot handle identifiers containing /

**Comment by mswertz** [comment]
unclear what design should be

**Comment by mswertz** [comment]
Elegant solution would put the path in a seperate attribute and does not abuse the ID attribute
