### ISSUE TITLE
Some tests are writing to the system temp folder resulting in concurrency issues

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7434]
Some tests write to the system temp folder, for example:

```java
public class CsvIteratorTest extends AbstractMolgenisSpringTest {

        ...

	private File createTmpFileForResource(String fileName) throws IOException
	{
		InputStream in = getClass().getResourceAsStream("/" + fileName);
		File csvFile = new File(FileUtils.getTempDirectory(), fileName);
		FileCopyUtils.copy(in, new FileOutputStream(csvFile));
		return csvFile;
	}
}
```
This can lead to unexpected behaviour when two builds are executing these tests around the same time:

```
Exception reading [/tmp/zipFileWithBom.zip]; nested exception is java.util.zip.ZipException: zip file is empty
```

Other usages of `FileUtils.getTempDirectory()` in tests can be found in: `CsvRepositorySourceTest`, `VcfRepositoryTest` and `CsvRepositoryTest`.

Temp folders should be unique for the current build and the way we manage the generation and cleanup of these folders in tests should be generalised.

**Comment by fdlk** [comment]
copied priority label from duplicate bug
