### ISSUE TITLE
Link to manual in app manager is broken

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7436]
### How to Reproduce
Open app manager click link to manual

### Expected behavior
Manual is shown

### Observed behavior
Browser surfs to https://molgenis.gitbooks.io/molgenis/content/user_documentation/guide-app-manager.html which shows
> page not found

**Comment by dennishendriksen** [comment]
@sidohaakma @ConnorStroomberg Is this the intended link? https://molgenis.gitbooks.io/molgenis/content/developer_documentation/app-development.html

**Comment by fdlk** [comment]
Checked on molgenis01, yup, link is fixed.
