### ISSUE TITLE
Submitted questionnaire can still be edited

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7441]
### How to Reproduce
Load questionnaire: 
[test_nillable_expression_questionnaire.xlsx](https://github.com/molgenis/molgenis/files/2097790/test_nillable_expression_questionnaire.xlsx)
Finish the questionnaire in the questionnaire plugin, submit
Click on go back to list
Click on view

### Expected behavior
I see overview page

### Observed behavior
I can start again and alter my answers

**Comment by bartcharbon** [comment]
This only occurs after the first submit.
When submitting for a second time, the expected behaviour occurs

**Comment by sidohaakma** [comment]
Is fixed as side affect of row-level security fix
