### ISSUE TITLE
Unexpected filter results in data explorer

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7443]
### How to Reproduce
Upload:
[test_version.xlsx](https://github.com/molgenis/molgenis/files/2097959/test_version.xlsx)
Go to mm_serverlist
Filter on version: 1.3.0
![screen shot 2018-06-13 at 13 54 38](https://user-images.githubusercontent.com/10075439/41349812-5afdc446-6f11-11e8-8179-b6c0d629180e.png)

### Expected behavior
I get one row: molgenis60

### Observed behavior
I get 93 rows and I do not get why it matches those rows

**Comment by dennishendriksen** [comment]
Unfortunately this is the intended search behavior implemented in https://github.com/molgenis/molgenis/issues/2275.
```java
// determine query operator for attribute type
var attrOperator;
switch (attribute.fieldType) {
  case 'BOOL':
  case 'CATEGORICAL':
  case 'CATEGORICAL_MREF':
  case 'DATE':
  case 'DATE_TIME':
  case 'DECIMAL':
  case 'ENUM':
  case 'INT':
  case 'LONG':
  case 'MREF':
  case 'XREF':
  case 'ONE_TO_MANY':
  case 'FILE':
      attrOperator = 'EQUALS';
      break;
  case 'EMAIL':
  case 'HTML':
  case 'HYPERLINK':
  case 'SCRIPT':
  case 'STRING':
  case 'TEXT':
     attrOperator = 'SEARCH';
     break;
  case 'COMPOUND':
     throw 'Unsupported data type: ' + attribute.fieldType;
  default:
     throw 'Unknown data type: ' + attribute.fieldType;
}
```
I pretty sure there is a story in the backlog to change this behavior, but I'm not able to find it ...

**Comment by fdlk** [comment]
![image](https://user-images.githubusercontent.com/1523838/41473361-5c3babda-70b9-11e8-8384-e3246ac4b33b.png)
