### ISSUE TITLE
Questionnaire text input saves after every character I type

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7461]
### How to Reproduce
Upload 
[test_nillable_expression_questionnaire.xlsx](https://github.com/molgenis/molgenis/files/2118483/test_nillable_expression_questionnaire.xlsx)
Go to questionnaire plugin
Start questionnaire
Type name: Henkie
12
something else
Type this: hello, this feature is very slow because its saving every time i type a character

### Expected behavior
Save waits until I'm done typing

### Observed behavior
Saving is done after every character typed, which makes it really slow in bigger questionnaires

**Comment by mswertz** [comment]
unclear what should be desired behavior, can this been done in background thread or something that syncs input with state but without blocking user entry?
