### ISSUE TITLE
Error during filling out c6 questionnaire

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7479]
### How to Reproduce
Import the c6 questionnaire ( see data/projects folder on drive for model)
Start questionnaire
Fill out chapter one
 - select as child
- add date ( current date) 
- select male

### Expected behavior
100% completed , and can go on to next chapter

### Observed behavior
0% completed and can not continue

**Comment by ConnorStroomberg** [comment]
Cannot reproduce ( anymore ), but looking a the 'isVisible' column for the 'consent' fields these seem complex and may contain some inconsistent state ? . But i am not able to reproduce the bug.

**Comment by bartcharbon** [comment]
Cannot reproduce either (checked some additional combinations of anwsers)

**Comment by ConnorStroomberg** [comment]
I have the same issue as reported above on

_7.0.0-SNAPSHOT built on 2018-07-16 10:19 UTC._ 

Using questionnaire emx verison 15
