### ISSUE TITLE
Can not open the downloaded questionnaire directly from browser in current chrome version

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7480]
### How to Reproduce
Fill out a questionnaire
Click the download button
Click the downloaded pdf in de browser

### Expected behavior
pdf is shown inside the browser

### Observed behavior
'file not found' is show inside the browser

**Comment by ConnorStroomberg** [comment]
Note: this does work on chrome canary ( might be a chrome bug )that is fixed in upcomming release

**Comment by bartcharbon** [comment]
Works on Chrome for windows, but fails on Internet Explorer as well, not sure if these issues are related.
Download on internet explorer results in file without extension
