### ISSUE TITLE
When I import HPO owl ontology, my importer breaks completely

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7501]
### How to Reproduce
Import: 
[hp.owl.zip](https://github.com/molgenis/molgenis/files/2154524/hp.owl.zip) using advanced importer
Press next, wait for a very long time (at least 5 minutes), click next, next, ..., until you get 500 error. 
Go to dataexplorer/navigator/something else fun
Go to importer again

Restarting molgenis fixes it.

### Expected behavior
No 500 error in the first place, but at least nog after switching plugins

### Observed behavior
500 error, every time I click on the importer

**Comment by tommydeboer** [comment]
Couldn't reproduce
