### ISSUE TITLE
When I reload questionnaire page, the answers are gone

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7502]
### How to Reproduce
Open questionnaire, fill in some answers, and reload the page or switch language.

### Expected behavior
Answers appear on reloaded page

### Observed behavior
Answers are gone

**Comment by dennishendriksen** [comment]
Importing ```molgenis-questionnaires\src\test\resources\emx-questionnaire.xls``` results in:
```
Error! Your import failed:
EntityType [TestQuestionnaire] must define a label attribute because the identifier is hidden
```
Which questionnaire did you use?
