### ISSUE TITLE
Mapping service does not always? fill self reference in parent / children relation within one entity

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7504]
### How to Reproduce
- BBMRI-ERIC data model
- Biobank Graz has subcollections in the fluids collection in staging area
- Mapping service maps country staging to production

### Expected behavior
The parent and children attributes of the model are filled in production

### Observed behavior
The parent and children attributes of the model are empty in production

**Comment by fdlk** [comment]
trying to reproduce with simple example

**Comment by fdlk** [comment]
Mariska showed me around on the mappings:
Parent collection attribute and sub collections attribute are in the root of the entity, not a compound. (But they got moved around, they used to be in a compound).
Parent comes before the children.
Same in all sources and the target entity.

**Comment by dennishendriksen** [comment]
Cannot reproduce using a test scenario provided by @djvanenckevort.
