### ISSUE TITLE
Travis build Yarn task fails

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7512]
### How to Reproduce
- Let Travis build #7499

### Expected behavior
- Build successful

### Observed behavior
- Build failed with
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (yarn install) on project molgenis-questionnaires: Failed to run task: 'yarn --mutex network --frozen-lockfile' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :molgenis-questionnaires
```
Full log: [log.txt](https://github.com/molgenis/molgenis/files/2165871/log.txt)

Note that the code changed in the pull request is in no way related to the molgenis-questionnaires modules.

**Comment by fdlk** [comment]
The root cause is https://github.com/molgenis/molgenis-ui-form/issues/175 plus a hiccupy github service that refused to serve connor's fork of vue-select.

**Comment by LuukDijkhuis** [comment]
leave it for now, unless we experience a lot of difficulties managing rc's

**Comment by fdlk** [comment]
We can publish the fork to our own npm repository now.

**Comment by dennishendriksen** [comment]
Frontend moved out of molgenis repository.
