### ISSUE TITLE
Footer below Vue plugin: link to MOLGENIS website broken

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7520]
### How to Reproduce
- Select `Quick data plugin` in the `Import data` menu
- Select `MOLGENIS database generator` link in the footer

### Expected behavior
- MOLGENIS main page is displayed in new window

### Observed behavior
![image](https://user-images.githubusercontent.com/2477186/42442735-c8f5ddc6-836b-11e8-986c-eb99bc5e9951.png)

**Comment by mswertz** [comment]
I suppose the 's' needs to removed from https
