### ISSUE TITLE
Package already exists exception in security manager is not internationalized 

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7527]
### How to Reproduce
Upload typetest
Go to security manager
Add group it

### Expected behavior
Internationalized error message with an error code

### Observed behavior
![screen shot 2018-07-10 at 13 53 45](https://user-images.githubusercontent.com/10075439/42508522-266701f0-8449-11e8-940a-b13a0856fdbd.png)
```
org.springframework.security.acls.model.AlreadyExistsException: Object identity 'org.molgenis.data.security.PackageIdentity[Type: package; Identifier: it]' already exists
```
The spring exception have a molgenis implementation with internationalization and code.

**Comment by ConnorStroomberg** [comment]
I think the expected behavior should be that the name is checked before 'Create' can be selected, and a alternate name should be suggested.

or

A error message telling the user the group name is already taken, and a other name should be used ( not some technical stuff about packages )

**Comment by fdlk** [comment]
The exception is a spring runtime exception that should not end up with the user.

**Comment by ConnorStroomberg** [comment]
After consultation with PR suggestion is to:

- On handle create group; Warn user about group name not being available, suggest to pick a new one.
-  In frontend before group is created and after name is given, warn user is name is not available, and block creation until available name is given.

**Comment by dennishendriksen** [comment]
Current behavior on ```molgenis/master```:
in English
```
Unable to create group; Entity 'it' of type 'Package' already exists.
```
in Dutch:
```
Unable to create group; Entiteit 'it' van entiteitsoort 'Package' bestaat al.
```

I suspect that the non-l10n string 'Unable to create group' and the missing error code are a client-side issue since the response from the server is: 
```json
{
    "errors": [
        {
            "message": "Entiteit 'it' van entiteitsoort 'Package' bestaat al.",
            "code": "D09"
        }
    ]
}
```
