### ISSUE TITLE
Data Explorer dropdown shows system entity types to users again

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7534]
### How to Reproduce
1. Add a user
2. Add a group
3. Add the user to the group's VIEWER role.
4. Log in as the user and go to the data explorer
5. Observe the contents of the entity select box

### Expected behavior
User only sees non-system entity types. (None, in this case.)

### Observed behavior
![image](https://user-images.githubusercontent.com/5362890/42574611-13a1e892-851f-11e8-8efe-d220021b85f8.png)

**Comment by bartcharbon** [comment]
This is caused by the fact that you have permissions on these entities but not on their package, which results in entityTypes that return null for the getPackage. This isSystemEntityType check then concludes that this is not a system entity.
