### ISSUE TITLE
Vue style plugins are broken when using a "top" logo

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#7543]
### How to Reproduce
- download: [logo](https://avatars1.githubusercontent.com/u/1688158?s=200&v=4)
- upload downloaded file as logo via the menu manager
- use the settings screen to copy the value of "Logo in navigation bar" to "Logo above navigation bar"
- go to "search all data" (or any other VUE plugin)

### Expected behavior
input controls for  search are below the menu bar

### Observed behavior
input controls for seach are through the top logo
<img width="558" alt="screen" src="https://user-images.githubusercontent.com/3714029/42689020-f9bcaf3a-869e-11e8-9e5c-6a2214033252.png">

**Comment by mswertz** [comment]
This is another reason why we want the vue based menu component right?

**Comment by bartcharbon** [comment]
Actually, for the vue plugins we already use a vue based menu bar

**Comment by dennishendriksen** [comment]
Cause:
![image](https://user-images.githubusercontent.com/2477186/42870264-a181fbf4-8a77-11e8-9b1c-1a58a931dc00.png)

**Comment by dennishendriksen** [comment]
Broken for vue plugins when no top logo is used:
![image](https://user-images.githubusercontent.com/2477186/42925610-064172ce-8b2f-11e8-9d96-a94af5852aa9.png)
