### ISSUE TITLE
SearchAll does not show thrown exceptions

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#7545]
### How to Reproduce
- add search all plugin permissions for the anonymous user via the permission manager
- logout and search "test"

### Expected behavior
exception stating that I do not have permissions on sys_ms_entityType (which is throws and logged)

### Observed behavior
empty screen

**Comment by mswertz** [comment]
I would actually expect to be able to search across all entityTypes and entities that I have permission on. So empty result maybe right if I don't have access.

**Comment by bartcharbon** [comment]
This exception is just an example, error messages are never shown in the searchall.

In this case there are entities to be searched and results to be shown, however the search fails due to the "isSystemEntity" check, which throws an exception for lacking permissions on "sys". In the case that I do not have permission on any entity to search I would expect the no results message rather than an empty screen.
