### ISSUE TITLE
Vue plugins do not render login dialog properly

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#7546]
### How to Reproduce
- add permissions of one or more vue plugins to anonymous
- logout
- click login

### Expected behavior
- correctly rendered login with working close button

### Observed behavior
see attachment + close button is broken

<img width="302" alt="login" src="https://user-images.githubusercontent.com/3714029/42697797-66f81ce8-86bc-11e8-88e0-251fd0204b5d.png">

**Comment by ConnorStroomberg** [comment]
I can not reproduce on current master 

@bartcharbon can you retest this ? I think it is solved in current master ( and 7.2, and 7.3).

note: user is taken to login screen,

**Comment by bartcharbon** [comment]
Agreed, seems to be resolved
