### ISSUE TITLE
Questionnaire UI: Option '[]' not defined

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7556]
### How to Reproduce
- As superuser import [emx-questionnaire.xlsx](https://github.com/molgenis/molgenis/files/2197842/emx-questionnaire.xlsx) from `molgenis-questionnaires\src\test\resources\emx-questionnaire.xls` in Chrome 67.0.3396.99
- Navigate to the 'Questionnaires' plugin in menu 'Plugins'
- Select 'View Questionnaire' for questionnaire 'Test questionnaire'
- Select 'Start questionnaire'
- Open 'Genders?' dropdown

### Expected behavior
- Caret rendering in correct location
- No error message when opening dropdown
- Dropdown contains entries for genders mentioned in input data

### Observed behavior
![image](https://user-images.githubusercontent.com/2477186/42761557-2aa4d228-890e-11e8-81dd-50aa1c533385.png)

**Comment by ConnorStroomberg** [comment]
Moved the style part of the issue to https://github.com/molgenis/molgenis/issues/7575 to allow to monitor fixes for separate issues. #7575 is due to form specific css not being included

**Comment by ConnorStroomberg** [comment]
related to molgenis-ui-form issue https://github.com/molgenis/molgenis-ui-form/issues/176
