### ISSUE TITLE
Quick data import fails: Text could not be parsed at index x

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7585]
### How to Reproduce
- Extract [example.zip](https://github.com/molgenis/molgenis/files/2212773/example.zip) and as superuser import the csv using the 'quick data import' plugin

### Expected behavior
- Import succeeds

### Observed behavior
- Import fails with message
```
Import failed; Text '2018-05-31' could not be parsed at index 10
```

**Comment by LuukDijkhuis** [comment]
done
