### ISSUE TITLE
Viewer cannot see questionnaire added by manager

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7586]
### How to Reproduce
- Create a group and two users, add one user as 'manager' to this group and the other as 'viewer'
- Sign in as manager and import [emx-questionnaire.xlsx](https://github.com/molgenis/molgenis/files/2213265/emx-questionnaire.xlsx) in the group
- Sign in as superuser and enable row-level security for the imported questionnaire through the 'permission manager' plugin
- Navigate to the Questionnaires plugin
- Sign in as viewer and navigate to the Questionnaires plugin

### Expected behavior
- Manager sees imported questionnaire 
- Viewer sees imported questionnaire

### Observed behavior
- Manager sees imported questionnaire 
- Viewer sees no questionnaires

**Comment by fdlk** [comment]
Discussed at standup: Only editor should see the Questionnaire plugin

Viewer has no use for it, cause you only see the instance you've written and a viewer cannot write.
