### ISSUE TITLE
In data-row-edit plugin I can not add a new row or edit a row in TypeTest

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#7599]
### How to Reproduce
Goto DataExplorer
Change setting "Edit the data row using the forms edit plugin" to yes
Add new row in DataExplorer
Try to "Save"

### Expected behavior
Button is enabled

### Observed behavior
Button is disabled

**Comment by tommydeboer** [comment]
It's also not possible to edit and save existing rows.

**Comment by LuukDijkhuis** [comment]
This was tested with the TypeTest dataset. With other EntityTypes it works fine. In the TypeTest there is a hidden not-nillable field with a default, but the default is not picked up by the form, therefore it never gets an enabled Save button. So I changed the issue to "default values are not picked up correctly by the new data-row-edit plugin"

**Comment by sidohaakma** [comment]
I could not use this plugin with the LifeCycle model either. I will take a look at the LifeCycle model again to determine what the problem is in that model.
