### ISSUE TITLE
Theme fonts not rendered due to wrong URLs

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7625]
### How to Reproduce
- As superuser navigate to the 'Theme manager' plugin in the 'Admin' menu
- Select 'rdconnect' in the theme drop-down and select 'Save current theme'
- Navigate to the 'Data explorer' plugin
- Check developer console in browser

### Expected behavior
- No theme related warnings/errors

### Observed behavior
- ```<origin>/css/app/fonts/glyphicons-halflings-regular.woff 404 (Not Found)```

**Comment by sidohaakma** [comment]
Solution: remove RD-connect themes.

**Comment by sidohaakma** [comment]
Is this an RD-connect specific issue? Because of lacking bootstrap4 theme. Or MOLGENIS wide issue.

**Comment by sidohaakma** [comment]
This is RD-connect specific. There is no bootstrap 4 theme. Solution: delete RD-connect theming from codebase.

**Comment by LuukDijkhuis** [comment]
done
