### ISSUE TITLE
Security Managers allows adding disabled users to groups

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7639]
### How to Reproduce
1. Add an active user
2. Add a disabled user
2. In the security manager:
  a. Add a group
  b. Add a member

### Expected behavior
I can only add active users as members.

### Observed behavior
I can add all users as members.

**Comment by LuukDijkhuis** [comment]
this needs more specification about what "disabled" means, so we will close this issue now. Currently there are reasons to add a disabled user to a group because we don't have more refined functionality to manage user lifecycle management.
