### ISSUE TITLE
Navigator empty when visiting as (super)user

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7658]
### How to Reproduce
- Sign in as user with role (viewer/editor/manager or as superuser)  
- Navigate to the 'Navigator' plugin

### Expected behavior
- According to the test case: "A list off packages and entities should be shown at the root level"

### Observed behavior
![no_package](https://user-images.githubusercontent.com/2477186/43630801-a3db66b0-9701-11e8-8db9-d107a38b3c62.png)

**Comment by LuukDijkhuis** [comment]
done
