### ISSUE TITLE
Navigator zip package click link to navigator not working

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7661]
### How to Reproduce

OCI001 | Import valid files |   |   |  
-- | -- | -- | -- | --
1 | Login as henkie | Logged in successfully |   |  
2 | Go to "Import data" --> "Quick data import" | List of imports is empty |   |  
3 | Import the files in the following folder (see comment) | All should be imported correctly |   | Valid files
4 | Click the name of an EntityType for a successful import | You are redirected to the dataexplorer, showing the correct EntityType |   |  
5 | For a zip import, select the package name | You are redirected to the navigator, showing the correct package |   |  

### Expected behavior
- Selecting the folder icon links to the navigator:
![image](https://user-images.githubusercontent.com/2477186/43633210-dcbdef3c-9708-11e8-8888-0bca16a43459.png)

### Observed behavior
- Nothing happens when selecting the folder icon
- Mouse cursor doesn't change when hovering over the icon

**Comment by LuukDijkhuis** [comment]
done
