### ISSUE TITLE
Sign out doesn't work in Vue plugins with Google Sign-in activated

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#7662]
## How to Reproduce
- As superuser navigate to the 'Settings' plugin in menu 'Admin'
- Select 'Authentication settings' in the dropdown
- Set 'Allow users to sign up' to 'Yes'
- Set 'Sign up moderation' to 'No'
- Navigate to the 'Navigator' plugin (or any other Vue-based plugin) in the main menu
- Select 'Sign out'

### Expected behavior
- I'm signed out

### Observed behavior
- Nothing happens
- Console displays ```SCRIPT5009: 'gapi' is undefined```

**Comment by fdlk** [comment]
Taken a look.
The google api integration code simply does not get included for the vue version of the header.

**Comment by fdlk** [comment]
Fixed in 7.0

**Comment by LuukDijkhuis** [comment]
done
