### ISSUE TITLE
Sign up impossible because captcha isn't showing

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7663]
### How to Reproduce
1. Sign in as superuser
2. Go to Admin --> Settings --> Authentication settings
3. Switch on "Allow users to sign up" and disable "Sign up moderation"
4. Sign out
5. Click "sign up"

### Expected behavior
I can sign up

### Observed behavior
I can't complete the form because the captcha isn't showing

![image](https://user-images.githubusercontent.com/5362890/43633749-6affe380-970a-11e8-8547-48a131d96f67.png)

**Comment by dennishendriksen** [comment]
Cause: the modal show event is (sometimes) fired before event handler registration completed. Since register-modal.ftl is loaded async the script doesn't need to be executed in a jquery-ready-function and is guaranteed to be executed before the modal show event fires.
