### ISSUE TITLE
From testplan /Data explorer/row 271, the link don't work

### ISSUE THREAD

**Issue by aneashodselmans** [molgenis/molgenis#7674]
This one doesn't work
### How to Reproduce
1) Open testplan 7.0
2) go to data explorer
3) go to row 271

Click on the link 

https://molgenis62.gcc.rug.nl/menu/main/dataexplorer?entity=test&mod=data&filter=%23CHROM=q=13 

4) the link don't work

**Comment by LuukDijkhuis** [comment]
needs more info

**Comment by tommydeboer** [comment]
The filter is looking for a row with `#CHROM=13` but the `test` dataset doesn't have one. It's an error in the test plan. I'll fix it and close this issue.
