### ISSUE TITLE
metadata manager UI doesn't refresh correctly after error state

### ISSUE THREAD

**Issue by LuukDijkhuis** [molgenis/molgenis#7676]
### How to Reproduce
create a new nullable attribute and save
make it not-nullable with the checkbox (uncheck)
try to save
error message appears (as intended)

### Expected behavior
checkbox not-nullable gets checked again and save button gets disabled again (as in not-dirty)

### Observed behavior
checkbox not-nullable DOESN'T get checked again. If you check it again yourself then the save button gets enabled. So it now looks like you had indeed made it not-nullable (which is not true).

**Comment by dennishendriksen** [comment]
Suppose that a user:
- Removes one attribute
- Adds two attributes
- Updates an attribute
- Updates the nullable attribute that you mention
- Selects 'Save all changes'

Refreshing the state would mean loosing all your work. I prefer the current behavior that allows you to fix your errors and change the functionality of the metadata manager such that saves resulting in errors are not possible. @LuukDijkhuis @marikaris What do you think?

**Comment by fdlk** [comment]
There will always be ways that errors can occur, so it should have a strategy for recovering from those. But this particular error is preventable.

**Comment by dennishendriksen** [comment]
I propose the stategy 'fix your mistakes and try again' because of the reasons mentioned in my previous comment.

**Comment by LuukDijkhuis** [comment]
Good point, but then I think you should keep the Save button enabled after the error message, and an explicit cancelation option that will lead to a state refresh. It should be clear that you have entered an "I am seeing what I have changed" situation. The issue is the discrepancy between the state of the Save button and the values that you see on screen.
