### ISSUE TITLE
Vue forms don't recognise changes in categoricals when editing a row

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7680]
### How to Reproduce
1. As admin, import 
[mappingservice-test.xlsx](https://github.com/molgenis/molgenis/files/2266355/mappingservice-test.xlsx)
2. In the Data Explorer settings enable "Edit the data row using the forms edit plugin. "
3. In the Data Explorer go to _HOP_selenium_
3. Add a new row
4. Edit the row: only change some categoricals (the radio buttons).

### Expected behavior
I can save the form.

### Observed behavior
I can't save the form if I only edit some of the radio buttons. (i.e.: the save-button remains inactive)

**Comment by ConnorStroomberg** [comment]
see  molgenis/molgenis-ui-form#188

**Comment by fdlk** [comment]
Caused by https://github.com/molgenis/molgenis-ui-form/issues/254
