### ISSUE TITLE
When running a simple MAGMA script the script runner fails

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#7683]
### How to Reproduce
Add a new script:
Name: test
Type: Javascript Magma
Content: $('weight').div($('height').pow(2)).value();
Parameters: weight and height

Run script with height = 1.80 and weight = 75

### Expected behavior
Result: 23.148148148148145

### Observed behavior
Errors on null-pointer

**Comment by dennishendriksen** [comment]
Duplicate of #7607
