### ISSUE TITLE
PENDING index jobs aren't picked up after an application restart

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7684]
### How to Reproduce
1. Import [Chr6_vragen_emx_testimport_14.xlsx](https://github.com/molgenis/molgenis/files/2270340/Chr6_vragen_emx_testimport_14.xlsx)
2. As soon as the import has finished, shut down the server
3. Restart the server
4. Inspect Index Action in the Data Explorer 

### Expected behavior
Index actions that were PENDING are started.

### Observed behavior
PENDING actions stay PENDING.

**Comment by LuukDijkhuis** [comment]
done
