### ISSUE TITLE
Consent question not shown when filling in questionnaire initially

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7692]
### How to Reproduce
1. Upload as c6 manager: 
[Chr6_vragen_emx_testimport_15.1.xlsx](https://github.com/molgenis/molgenis/files/2282853/Chr6_vragen_emx_testimport_15.1.xlsx)
2. Make test user with as role c6 viewer
3. Give edit permissions on c6_questionnaire for the c6 viewer role. 
4. Give permissions on questionnaire plugin for the c6 viewer
5. Open the questionnaire, start questionnaire
6. Fill in: my child, female, some date

### Expected behavior
Consent question is shown and I can give consent

### Observed behavior
No question shown, however, when i switch the my child to myself and then back to my child, it is shown and can be filled in.

**Comment by LuukDijkhuis** [comment]
done

**Comment by LuukDijkhuis** [comment]
done
