### ISSUE TITLE
Navigator tree disappears after highlighting search in internet explorer

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#7728]
### How to Reproduce
- navigate to the navigator
- click in the search field
- click below the search field

### Expected behavior
- packages stay visible as long as I did not type, or will at least show again when focus on the empty search field is lost

### Observed behavior
- tree disappears on focus and does not return after loss of focus

**Comment by ConnorStroomberg** [comment]
fixed by: https://github.com/molgenis/molgenis/pull/7737
