### ISSUE TITLE
Using the navigator clicking Entity does not open in a new tab

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#7729]
### How to Reproduce | Expected behavior
Go to the Navigator | A list off packages and entities should be shown at the root level
Search for "Mail" in searchbox | The list of packages and entities that are defined within the 'Mail' package should been shown.
Click the 'Mail settings' entity | A new tab should open showing the 'Mail settings' entity in the dataexplorer

### Observed behavior
Mail settings opens in same tab (Windows 10 Chrome and internet explorer)

**Comment by dennishendriksen** [comment]
Updated test plan expected behavior to: ```Browser navigates to page showing the 'Mail settings' entity in the dataexplorer```
