### ISSUE TITLE
Cannot deploy molgenis app due to UnsatisfiedDependencyException

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7733]
### How to Reproduce
- run `mvn clean install` on molgenis master branch
- Start molgenis app as described in molgenis manual 

### Expected behavior
Molgenis all starts 

### Observed behavior
Molgenis ass does not start and error is show in log.

`RROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sortaController' defined in URL [jar:file:/Users/connorstroomberg/Code/molgenis/molgenis-app/target/molgenis-app-7.1.0-SNAPSHOT/WEB-INF/lib/molgenis-ontology-7.1.0-SNAPSHOT.jar!/org/molgenis/ontology/sorta/controller/SortaController.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobExecutionConfig': Unsatisfied dependency expressed through field 'executorService'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'executorService': Requested bean is currently in creation: Is there an unresolvable circular reference?`

23-     Server version:        Apache Tomcat/8.5.33
23-     Server built:          Aug 12 2018 08:20:08 UTC
23-     Server number:         8.5.33.0
23-     OS Name:               Mac OS X
23-     OS Version:            10.13.6
23-     Architecture:          x86_64
23-     Java Home:             /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
23-     JVM Version:           1.8.0_171-b11
23-     JVM Vendor:            Oracle Corporation
23-     CATALINA_BASE:         /Users/connorstroomberg/Library/Caches/IntelliJIdea2018.1/tomcat/Unnamed_molgenis_3
23-     CATALINA_HOME:         /Users/connorstroomberg/Code/apache-tomcat-8.5.33
23-     Command line argument: -Djava.util.logging.config.file=/Users/connorstroomberg/Library/Caches/IntelliJIdea2018.1/tomcat/Unnamed_molgenis_3/conf/logging.properties
23-     Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
23-     Command line argument: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50330,suspend=y,server=n
23-     Command line argument: -javaagent:/Users/connorstroomberg/Library/Caches/IntelliJIdea2018.1/captureAgent/debugger-agent.jar=file:/private/var/folders/v8/7n_rklzj0fv8tvtg2ttxw8j00000gn/T/capture356.props
23-     Command line argument: -Dmolgenis.home=/Users/connorstroomberg/.molgenis/omx
23-     Command line argument: -Xmx4g
23-     Command line argument: -Des.discovery.zen.ping.multicast.enabled=false
23-     Command line argument: -Des.network.host=localhost
23-     Command line argument: -XX:+UnlockCommercialFeatures
23-     Command line argument: -XX:+FlightRecorder
23-     Command line argument: -Dcom.sun.management.jmxremote=
23-     Command line argument: -Dcom.sun.management.jmxremote.port=1099
23-     Command line argument: -Dcom.sun.management.jmxremote.ssl=false
23-     Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
23-     Command line argument: -Djava.rmi.server.hostname=127.0.0.1
23-     Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
23-     Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
23-     Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
23-     Command line argument: -Xmx2g
23-     Command line argument: -XX:+UseConcMarkSweepGC
23-     Command line argument: -XX:+CMSClassUnloadingEnabled
23-     Command line argument: -Dmolgenis.home=/Users/connorstroomberg/.molgenis/omx
23-     Command line argument: -Dignore.endorsed.dirs=
23-     Command line argument: -Dcatalina.base=/Users/connorstroomberg/Library/Caches/IntelliJIdea2018.1/tomcat/Unnamed_molgenis_3
23-     Command line argument: -Dcatalina.home=/Users/connorstroomberg/Code/apache-tomcat-8.5.33
23-     Command line argument: -Djava.io.tmpdir=/Users/connorstroomberg/Code/apache-tomcat-8.5.33/temp

**Comment by fdlk** [comment]
Probably the Intellij version of #7712

**Comment by ConnorStroomberg** [comment]
@fdlk updated intelij to 2018.2.2 still have same issue with 'Error creating bean with name 'sortaController''

**Comment by ConnorStroomberg** [comment]
Same behaviour when not using intelij and running war created by CI server, will update issue title

**Comment by bartcharbon** [comment]
Fixed: https://github.com/molgenis/molgenis/pull/7735
