### ISSUE TITLE
CI build not starting due to error ( missing settings file)

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7736]
### How to Reproduce
Create a PR on github ( for example https://github.com/molgenis/molgenis/pull/7735 )

### Expected behavior
PR gets build 

### Observed behavior
Error during build 

[molgenis_molgenis_PR-7735-7DHWN26CBFVOTXBUHL7XOBDNEIFZ6TFFONJJTMQFGS75D6DMIUAQ] Running shell script

+ mvn versions:set -DnewVersion=0.0.0-SNAPSHOT-PR-7735-1 -DgenerateBackupPoms=false

[ERROR] Error executing Maven.

[ERROR] 1 problem was encountered while building the effective settings

[FATAL] Non-parseable settings /home/jenkins/.m2/settings.xml: end tag name </servers> must match start tag name <settings> from line 1 (position: TEXT seen ...</server>\n  </servers>... @36:13)  @ /home/jenkins/.m2/settings.xml, line 36, column 13

script returned exit code 1

**/target/surefire-reports/**.xml
— Archive JUnit-formatted test results
<1s
Recording test results

No test report files were found. Configuration error?

**Comment by fdlk** [comment]
Somehow the vault secret got corrupted (cc @sidohaakma). Restoring to its former glory.

**Comment by fdlk** [comment]
done

**Comment by ConnorStroomberg** [comment]
@fdlk maybe add details on fix for future reference

**Comment by fdlk** [comment]
Be very careful when adding a new server to the settings.xml secret in Vault, because if you muck up the syntax it breaks the build.

**Comment by sidohaakma** [comment]
I am very sorry, I was trying to add the gogs credentials to the settingsfile. Now it works again.
