### ISSUE TITLE
Readonly and visibility false not working for xref with default value

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7768]
### How to Reproduce
Upload: 
[all_lifecycle_metadata_prod_bug.xlsx](https://github.com/molgenis/molgenis/files/2361194/all_lifecycle_metadata_prod_bug.xlsx)
Go to the DNBC Harmonization table
Add row

### Expected behavior
The cohort attribute is invisible (or at least readonly)

### Observed behavior
I can select the attribute and I can save it and the preselection is not shown

**Comment by dennishendriksen** [comment]
By design? (see comment in other issue)

**Comment by dennishendriksen** [comment]
@marikaris I can't import the data:
```
Error! Your import failed:
EntityType [LifeCycle_ALSPAC_Harmonizations] does not contain any attributes. Did you use the correct package+entity name combination in both the entities as well as the attributes sheet?
```

**Comment by marikaris** [comment]
Sorry about that, this one works:
[all_lifecycle_metadata_prod_bug.xlsx](https://github.com/molgenis/molgenis/files/2366716/all_lifecycle_metadata_prod_bug.xlsx)

**Comment by dennishendriksen** [comment]
This works as intended:
- When creating a new entity
  - inputs for hidden attributes are displayed so you can assign them a value
  - inputs for read-only attributes are enabled so you can assign them a value
- When editing an existing entity
  - inputs for hidden attributes are displayed so you can edit their value
  - inputs for read-only attributes are read-only
