### ISSUE TITLE
Can not import 'Minimal example' emx example from Molgenis Help doc

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7793]
### How to Reproduce
Select help from de main menu
Go to; 'User Documentation -> Data -> Import data -> Advanced data upload -> EMX Format
Download the 'minimal example' 
Import the downloaded minimal example file using the 'Advanced data import' plugin
Click 'Next' at each import step

### Expected behavior
At step 5 the data import is successful 

### Observed behavior
Error is shown at step 5 
<img width="818" alt="screen shot 2018-09-12 at 09 45 15" src="https://user-images.githubusercontent.com/1277621/45410278-990b1480-b671-11e8-9589-3b0d0f2ce57d.png">

**Comment by ConnorStroomberg** [comment]
Looking at the file it looks like the data field is formatted as YYYY-DD-MM while the importer seems to expect YYYY-MM-DD 

![screen shot 2018-09-12 at 09 45 24](https://user-images.githubusercontent.com/1277621/45410358-c952b300-b671-11e8-81f9-35be20275e23.png)

**Comment by dennishendriksen** [comment]
Fixed by https://github.com/molgenis/molgenis/pull/7795
