### ISSUE TITLE
Validation expression does not work properly

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7808]
### How to Reproduce
Upload:
[test_expression.xlsx](https://github.com/molgenis/molgenis/files/2382552/test_expression.xlsx)

### Expected behavior
It imports succesfully

I tested the expression with the string, using https://regex101.com/ for javascript.
![screen shot 2018-09-14 at 10 27 24](https://user-images.githubusercontent.com/10075439/45539171-3ba9cb80-b809-11e8-901d-fda70d26d71f.png)

### Observed behavior
![screen shot 2018-09-14 at 10 28 29](https://user-images.githubusercontent.com/10075439/45539116-17e68580-b809-11e8-80fe-53479d591731.png)

Originally found in 4.1, reproduced in 7.1

**Comment by dennishendriksen** [comment]
Your regular expression is valid, but this is not a valid validationExpression, see the ```matches``` information: https://molgenis.gitbooks.io/molgenis/content/v/7.0/user_documentation/modify-data/ref-expressions.html.
