### ISSUE TITLE
Disable vuex strict node in production

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7809]
### How to Reproduce
Build molgenis web app

### Expected behavior
Vuex store object is created using strict mode = false , see [vuex docs on strict mode](https://vuex.vuejs.org/guide/strict.html#development-vs-production)

### Observed behavior
Looking a the code most modules using vuex use set strict mode to true

**Comment by ConnorStroomberg** [comment]
search all plugin is already using suggested setup (`strict: process.env.NODE_ENV !== 'production'`)

**Comment by dennishendriksen** [comment]
Vue was removed from this repository as part of #8628.
