### ISSUE TITLE
Metadata manager i18n button gets rendered on top of input fields

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7849]
### How to Reproduce
Open the metadata manager

### Expected behavior
Interface elements do not overlap

### Observed behavior
<img width="520" alt="screen shot 2018-09-28 at 09 58 27" src="https://user-images.githubusercontent.com/1277621/46196676-05d80d00-c308-11e8-9035-44c4e77bceec.png">

**Comment by dennishendriksen** [comment]
Actually the button is rendered in the right place, but the outline is not rendered. Will fix as part of #7853.
