### ISSUE TITLE
JobExecution entity delete allowed for running job

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7886]
### How to Reproduce
1. Start a job
2. While the job is running, remove its JobExecution row
3. Wait for the job to finish

### Expected behavior
It shouldn't be possible to remove the JobExecution row while the job is running.

### Observed behavior
Row is removed and later an exception is thrown because the job tries to write to a non-existing row.

**Comment by mswertz** [comment]
well, alternative behavior I can imagine is that the job is first terminated and then removed. Don't you agree?
