### ISSUE TITLE
Update single attribute put/post is rejected if body is empty or null

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#7942]
### How to Reproduce
Send a post to the rest api endpoint 
http://[server]/api/v1/[entity-id]/[attribute-id]
method: PUT or Post
Content-Type: application/json'
With empty request body 

### Expected behavior
The attribute of the referenced entity is cleared / set to null.

### Observed behavior
The request is rejected with the message that the request is not valid, due to missing request body.

**Comment by dennishendriksen** [comment]
@ConnorStroomberg what is the status of this issue?

**Comment by connoratrug** [comment]
its been merged in the master
