### ISSUE TITLE
Search-all broken link in documentation

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8014]
### How to Reproduce
- Navigate to https://molgenis.gitbooks.io/molgenis/content/user_documentation/finding-data/guide-search.html

### Expected behavior
- All images load correctly

### Observed behavior
![image](https://user-images.githubusercontent.com/2477186/49362664-a4556580-f6df-11e8-9f0d-902552fa3160.png)

**Comment by mswertz** [comment]
Is reporting this bug not more work than fixing it?

**Comment by dennishendriksen** [comment]
The image exists at the mentioned location and renders in the IDE preview.
