### ISSUE TITLE
Vue menu can overlap plugin

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8019]
### How to Reproduce
- Create a menu with entries as displayed in the image and resize the browser window
![menu_overlap_bug](https://user-images.githubusercontent.com/2477186/49374444-a6302080-f701-11e8-9d44-7d587e19ffa7.png)

### Expected behavior
- Menu similar to the menu that is displayed for non-Vue plugins:
![image](https://user-images.githubusercontent.com/2477186/49374517-dbd50980-f701-11e8-8740-9e2e1d4be9e9.png)

### Observed behavior
- See image

**Comment by marikaris** [comment]
Probably fixed in new menu?

**Comment by dennishendriksen** [comment]
> Probably fixed in new menu?

Confirmed :)
