### ISSUE TITLE
Vendor bundle is much larger than it needs to be

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8023]
### How to Reproduce
Open the data explorer while logging network traffic. Take a look at the size of the vendor bundle. Compare to older versions of molgenis.

### Expected behavior
It's comparable to the size it had before.

### Observed behavior
It's twice as large, went from about 2MB to about 4MB
This is due to the -Pproduction profile missing in Jenkins

**Comment by dennishendriksen** [comment]
This also affects error reporting to users and in my opinion should be fixed in a patch release for 7.2 and 7.3 (@mswertz).

**Comment by fdlk** [comment]
Fixed in 7.3.5
