### ISSUE TITLE
Cannot import data and metadata of BBMRI eric at the same time

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8028]
### How to Reproduce
Import:
[eric_data_dec2018.xlsx](https://github.com/molgenis/molgenis/files/2642861/eric_data_dec2018.xlsx)

Updating data and metadata separately is a workaround

### Expected behavior
It imports within a reasonable time (less than 5 minutes and that is still quite long)

### Observed behavior
It takes over 30 minutes and I am not sure whether it will succeed or fail ever

**Comment by dennishendriksen** [comment]
@marikaris can you add the PostgreSQL settings (SHOW ALL)?

**Comment by dennishendriksen** [comment]
Root cause of the issue is the validation of xref computed attributes. I'll try to add more details tomorrow.
