### ISSUE TITLE
Validation of a mapping algorithm that refers to an unknown attribute succeeds

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8052]
### How to Reproduce
- Using the e.g. data explorer plugin add a row to the 'ScriptParameter' entity type
- Using the mapping service plugin create a new project with target 'sys_scr_ScriptParameter'
- Add source 'sys_scr_ScriptParameter'
- Edit the algorithm 'name'and update to ```$('unknown').value();```
- Select the 'Validate algorithm' button

### Expected behavior
- 1 error, because attribute unknown does not exist

### Observed behavior
- Total: 1 Success: 1 Errors: 0

**Comment by mswertz** [comment]
I suppose you expect '1 error, because ATTRIBUTE unknown does not exist', right?

**Comment by dennishendriksen** [comment]
Yes, typo, I've updated the issue.

**Comment by dennishendriksen** [comment]
Updating `molgenis-js\src\main\resources\js\script-evaluator.js` from
```js
MagmaScript.$ = function (attrName) {
  ...
}
```
to
```js
MagmaScript.$ = function (attrName) {
  if(!(attrName in this)) {
    throw 'Unknown attribute \'' + attrName + '\''
  }
  ...
}
```
doesn't work due to [JDK bug](https://bugs.openjdk.java.net/browse/JDK-8173480) that has been fixed in JDK9. Alternatives such as hasOwnProperty are also not available when running in the Nashorn engine.
