### ISSUE TITLE
As questionnaire manager I want to be able to see my data

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#8085]
### How to Reproduce
- Login as Manager on https://questionnaire.chromosome.org (use c6_testuser with the known password)
- Goto Dataexplorer and select "questionnaire"

### Expected behavior
See all rows of all users

### Observed behavior
Seeing not a single row

This is because of the rowlevel secured rows. But as a Manager I do want to see the data. At this moment only the superuser has this ability.

**Comment by dennishendriksen** [comment]
Please report features and feature change requests in the backlog.
