### ISSUE TITLE
Mapping plugin ui 'breaks' for non-large screens

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#8097]
### How to Reproduce
As Admin user go to the mapping plugin 

### Expected behavior
UI that uses available space to render clear UI

### Observed behavior
<img width="1171" alt="screenshot 2018-12-31 at 11 35 11" src="https://user-images.githubusercontent.com/1277621/50558670-82f09500-0cf0-11e9-925c-23dbdfbfbba0.png">

**Comment by dennishendriksen** [comment]
Looks good on all supported resolutions on my machine with the latest Google Chrome:
```
5.3.2 Resolutions
1280x800
1280x1024
1366x768
1680x1050
1920x1080
```

@ConnorStroomberg which browser/resolution are you using?

**Comment by dennishendriksen** [comment]
Your resolution is not supported by MOLGENIS as you can see in the provided list. Please create a feature request in the backlog if you would like to have your resolution supported.
