### ISSUE TITLE
Id of dataexplorer settings is visible

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8115]
### How to Reproduce
Go to dataexplorer
Click on the settings icon

### Expected behavior
Id is invisible 

### Observed behavior
<img width="764" alt="screen shot 2019-01-09 at 11 05 15" src="https://user-images.githubusercontent.com/10075439/50892665-5a0e8500-13ff-11e9-9c73-17237f9889a4.png">

**Comment by dennishendriksen** [comment]
The 'id' attribute is also the label attribute for the data explorer settings metadata and thus has to be visible. Which attribute do you want to use as label attribute when 'id' is made invisible?
