### ISSUE TITLE
Multiple persons in import is not possible (importwizard)

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#8165]
### How to Reproduce
In BBMRI-NL there are biobanks, with principal_investigators, this field is an mref to persons. To reproduce make EMX with one biobank, with multiple persons in field principal_investigators.

### Expected behavior
Expected behaviour import all persons 

### Observed behavior
Importer gives error.
When removing all multiple persons, and only adding 1 person per biobank import is successful.

**Comment by Fernananas** [comment]
error message:
<img width="826" alt="error_import_multiple_perons" src="https://user-images.githubusercontent.com/40240913/51521174-1156c300-1e26-11e9-8fb3-d65fde2f3419.png">
Even after formatting excel (text instead of number).

**Comment by bartcharbon** [comment]
adding a singlequote as prefix for the values solves the issue.
