### ISSUE TITLE
Downloading questionnaire with Navigator results in file that is not importable

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8177]
### How to Reproduce
Import: 
[Chr6_questionnaire_15.5.xlsx](https://github.com/molgenis/molgenis/files/2782303/Chr6_questionnaire_15.5.xlsx)
Go to navigator
Click on the chromosome6 package
Select the questionnaire checkbox
Click on download
Go to advanced importer
Import the data again

## Expected behavior
Import succeeds

### Observed behavior
![screen shot 2019-01-22 at 11 24 14](https://user-images.githubusercontent.com/10075439/51529068-4d931f00-1e38-11e9-80da-92a8517a49ec.png)

**Comment by bartcharbon** [comment]
The reported behaviour is fixed, however this does not fix the issue reported in the title:
related:
- Nillable and visible expressions cause errors if the were empty string in the original upload.
- #8213 needs to be fixed for the upload to succeed.
