### ISSUE TITLE
New default theme css file link breaks after migration from 7.4 to 8.0 

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8180]
### How to Reproduce
Start molgenis om version 7.4
Upgrade to molgenis 8.0

### Expected behavior
New styling is applied

### Observed behavior
Old styling is applied with new name, in the stylesheet table a row for molgenis-blue is created, but the files in that row are not available. For bootstrap 3 plugins, molgenis will fall back to its basic theme, but the bootstrap 4 plugins have no styling at all.

**Comment by ConnorStroomberg** [comment]
@marikaris Can not reproduce locally, can you give more details on the used upgrade steps ?, can you point to a server ?

Background:

- At application startup  the BootstrapThemePopulator.populate is run .
- Populate check files in the resource dir agains the files listed in the StyleSheet entity
- If there are 'new' style sheets these are saved in the files store and a row is added to both FileMeta and StyleSheet entities. 

This specific case: new molgenis-blue file is detected as being a new style, matching bs4 files is found and both are placed in the files store and a new style is added to the stylesheet entity.

**Comment by ConnorStroomberg** [comment]
Can not reproduce

**Comment by dennishendriksen** [comment]
I can reproduce the issue on my local machine. The GUI after booting with 8.0:
![image](https://user-images.githubusercontent.com/2477186/51897562-52635000-23af-11e9-8f32-218328a3b9d0.png)

@ConnorStroomberg Did you launch 7.4 with an empty database, removed indices and an empty file store? You might have forgotten to clear your file store.

**Comment by ConnorStroomberg** [comment]
@dennishendriksen If i remember correctly id did empty the file store. Could you add the exact steps ( and any additional information ) you followed so i can reproduce this issue. I will then follow these steps en log to progress.

**Comment by dennishendriksen** [comment]
I followed the 'how to reproduce' steps reported by @marikaris in this issue on my local system:
- Empty database
- Remove all Elasticsearch indices
- Remove all files from the file store
- Start MOLGENIS 7.4 and wait until bootstrapping completes
- Stop MOLGENIS
- Start MOLGENIS 8.0.0-SNAPSHOT and wait until bootstrapping completes
- Navigate to localhost:8080 in latest Google Chrome and sign in
- Inspect GUI

**Comment by ConnorStroomberg** [comment]
Gone though all the steps, and logged each step, still can not reproduce the issue. 

@dennishendriksen in your previous comment you included a screen shot, i do not see how this screenshot is related to the issue as reported by @marikaris. Could it be you and @marikaris are talking about separate issues ? 

Adding [additional loggin to theme bootstrapper](https://github.com/molgenis/molgenis/pull/8204) to help triage the issue

**Comment by dennishendriksen** [comment]
> i do not see how this screenshot is related to the issue as reported by @marikaris
It is displaying something resembling the old styling, not the new styling: - different font color in menu entries, old logo (but bigger than the one in 7.4) , rounded off button

@marikaris could you provide a screenshot with your GUI after upgrading?

**Comment by dennishendriksen** [comment]
@marikaris could you please add the appropiate labels to your issues?

**Comment by mswertz** [comment]
please check if blocker for 8.0

**Comment by sidohaakma** [comment]
Cannot reproduce. Either way we are going not going to migrate from 7.4 to 8.0 by replacing the war. We are always loading a new dump in pg11 and copying the filestore to the new machine. We should be aware of the same problem when migrating from 8.0.0 to 8.x.x.
