### ISSUE TITLE
Button icons are drawn above center

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8189]
### How to Reproduce
Open data explorer, look at the icons

### Expected behavior
They are centered on the button

### Observed behavior
They are floating above the center of the button
<img width="116" alt="screenshot 2019-01-24 at 16 03 01" src="https://user-images.githubusercontent.com/1523838/51687208-5deef980-1ff2-11e9-91d3-71a5ac95e989.png">

**Comment by connoratrug** [comment]
related to: https://github.com/molgenis/molgenis/issues/8206

**Comment by mswertz** [comment]
we will not fix new them on non-vue pages

**Comment by mswertz** [comment]
I checked and I couldn't reproduce in data explorer 8.0.0-SNAPSHOT built on 2019-03-14 15:03 UTC.
