### ISSUE TITLE
Default logo does not match default style

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8190]
### How to Reproduce
Install fresh molgenis, look at logo.

### Expected behavior
Logo matches the style of the rest of the page, i.e. is white and blue.
For instance:
<img width="600" alt="screenshot 2019-01-24 at 16 21 24" src="https://user-images.githubusercontent.com/1523838/51688138-3f89fd80-1ff4-11e9-9de0-b2cb9957d28a.png">

### Observed behavior
Logo is black and green, rest of the page is white and blue.
<img width="559" alt="screenshot 2019-01-24 at 16 17 54" src="https://user-images.githubusercontent.com/1523838/51687961-db673980-1ff3-11e9-8f26-d1465407961b.png">

**Comment by ConnorStroomberg** [comment]
@fdlk please add screen shot of both expected and observed behavior

**Comment by mswertz** [comment]
would indeed expect blue logo in blue colors as in screenshots.
