### ISSUE TITLE
Link to privacy settings pdf is broken

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8192]
### How to Reproduce
As admin, open the settings manager and follow the link mentioned for the tracking cookies

### Expected behavior
I end up on a page with instructions on how to configure the cookies in a privacy-friendly way

### Observed behavior
The link to https://autoriteitpersoonsgegevens.nl/sites/default/files/atoms/files/handleiding_privacyvriendelijk_instellen_google_analytics_0.pdf is broken

**Comment by dennishendriksen** [comment]
@fdlk https://autoriteitpersoonsgegevens.nl/sites/default/files/atoms/files/138._handleiding_privacyvriendelijk_instellen_google_analytics_aug_2018.pdf

**Comment by mswertz** [comment]
either remove the link or fix it. Current link now directs on molgenis01 to something else.
