### ISSUE TITLE
Default molgenis theme breaks ui on non vue pages

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8206]
### How to Reproduce
Start molgenis (master branch) with empty db, the default molgenis theme is selected.
View non vue page ( every page except navigator, security manager, questionnaire, data-row-edit, metadata-manager, app-manager). 

### Expected behavior
Syling looks oke, no overlapping text/buttons/bars ..

### Observed behavior
Syling looks broken, overlapping text/buttons/bars ..

**Comment by mswertz** [comment]
is this 'new' or 'old' molgenis theme? If 'old' theme than it needs urgent fixing. Otherwise it can wait beyond 8.0

**Comment by mswertz** [comment]
Cannot reproduce? Can you add screenshot?

**Comment by fdlk** [comment]
@mswertz I believe this was added as a sort of umbrella issue for the other styling issues.
