### ISSUE TITLE
Scheduled job email addresses are nillable but can't be left empty

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8221]
### How to Reproduce
- As superuser navigate to the 'Scheduled Jobs' plugin
- Select the '+' button
- Fill in all required form fields thus leaving 'Failure email' and 'Success email' empty
- Select the 'Create' button

### Expected behavior
- Scheduled job created successfully

### Observed behavior
![image](https://user-images.githubusercontent.com/2477186/52350544-1bcdab00-2a29-11e9-8bbb-63f5f67867c3.png)

The validation expression introduced in 0ff3a3a7d09fec3a8ea673ee610c715714e027dd fails.

**Comment by marikaris** [comment]
This is not broken yet in the latest 7.4.1 release. 

Suggestion of Dennis: Could it be due to the Java upgrade, nashhorn evaluates the regular expression differently?

**Comment by sidohaakma** [comment]
#8243 is part the same issue

**Comment by dennishendriksen** [comment]
This issue was introduced by https://github.com/molgenis/molgenis/issues/8052 which includes stricter expression checks:

![image](https://user-images.githubusercontent.com/2477186/53718579-de0f4700-3e5b-11e9-99b3-38b1d3191d8b.png)

The client-side expression validation fails because an exception occurs due to failureEmail being unknown.
