### ISSUE TITLE
Auto generated dates not working in new forms

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8235]
### How to Reproduce
Go to the token table in dataexplorer
Enable new forms in dataexplorer settings
Add a token by clicking on the green +

### Expected behavior
The creation date is not there, like in the "old forms" because it is automatically generated

### Observed behavior
The creation date is there and when I don't fill it in, I get an validation error because I did not fill in the creation date

**Comment by mswertz** [comment]
Only fix in the new forms (if it there still exists)

**Comment by LuukDijkhuis** [comment]
fixed by #255
