### ISSUE TITLE
Validation expression for date not correct in new forms

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8236]
### How to Reproduce
Go to the token table in dataexplorer
Enable new forms in dataexplorer settings
Add a token by clicking on the green +
Fill in token and user (and creation date see issue #8235)
Click on save

### Expected behavior
My token is saved because the expiration date is not required

### Observed behavior
Validation error, expiration date is required. 

Using the "old" forms it still works

**Comment by mswertz** [comment]
we assume it is fixed in new forms, thus we want to add this into release 8.0
