### ISSUE TITLE
No 'readmeta' permission when doing a request with an invalid token

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#8241]
### How to Reproduce
Do a request (for example GET http://localhost:8080/api/v2/sys_md_EntityType) with an invalid `x-molgenis-token` in the header.

### Expected behavior
401: unauthorized, specifying that the token isn't valid.

### Observed behavior
It's as if the token isn't there and a `DS04` is returned:
`"No 'Read metadata' permission on entity type 'Entity type' with id 'sys_md_EntityType'."`

See the following snippet from `TokenAuthenticationFilter`:
```java
try {
  // Authenticate the token
  RestAuthenticationToken authToken = new RestAuthenticationToken(token);
  Authentication authentication = authenticationProvider.authenticate(authToken);
  if (authentication.isAuthenticated()) {
    // Log user in
    SecurityContextHolder.getContext().setAuthentication(authentication);
  }
} catch (AuthenticationException e) {
  // Cannot authenticate the user based on the token, act as if it wasn't there
}
```

**Comment by tommydeboer** [comment]
According to @bartcharbon, this is intended behaviour: if your token is not valid anymore, you'd still expect to be able to see the stuff anonymous users are allowed to see.

**Comment by bartcharbon** [comment]
Related to the "ui" variant of this behaviour: #8513

**Comment by bartcharbon** [comment]
Replaced by story http://wiki.gcc.rug.nl/ticket/7091: since this is works this way by design this more a feature request than an issue.
