### ISSUE TITLE
Calls with token plus session change the session's authentication

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8251]
### How to Reproduce
Create a token `blah` for user A.
Log in on molgenis as user B. (You get a session cookie for B.)
Make any call in the browser with `?molgenis-token=blah` (So with a session cookie for A and a token for B)
Now go back to making calls with the session cookie.

### Expected behavior
Calls with the session cookie still give results for user A.

### Observed behavior
Calls with the session cookie now give results for user B.
The session got changed into one for B.

**Comment by mswertz** [comment]
We propose to fix in 8.0 because we cannot predict consequences of this
