### ISSUE TITLE
Search for 'File' in navigator results in errors.

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8253]
### How to Reproduce
Login as admin user
Go to the navigator
Select the Sys package
Type "File" into the search box

### Expected behavior
Packages and entities that contain the word "File" in the name or description are returned

### Observed behavior
<img width="1210" alt="nav-errorscreenshot 2019-03-06 at 14 42 47" src="https://user-images.githubusercontent.com/47183404/53885513-3a21c900-401e-11e9-9f14-d03b6687fa3d.png">

**Comment by mswertz** [comment]
@connoratrug Cannot reproduce in version 8.0.0-SNAPSHOT built on 2019-03-14 15:03 UTC.
