### ISSUE TITLE
Attributes of compounds disappear, when using metadata manager

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#8269]
### How to Reproduce

Go to accept of BBMRI-ERIC, https://molgenis101.gcc.rug.nl. Login as admin, go to the metadata manger, select biobanks in package :eu_bbmri_eric.

Add new attribute, move attributes above compounds, e.g. under 'description'. Using arrows is also possible. Then all attributes in the compounds disappear. So when you save, these attributes are gone. You still see compound folder, so for user not paying attention to all attributes, save will be pressed.

### Expected behavior

When using metadata manager, that you can not delete items, without pressing delete button.

### Observed behavior

If added attribute is placed above compounds items disappear.

**Comment by dennishendriksen** [comment]
I can reproduce the issue when dragging the label attribute between id and compound:
![metadata-manager-dragdrop](https://user-images.githubusercontent.com/2477186/54534734-4c402780-498d-11e9-9ff3-6d14af1b4ff0.png)
With the up/down errors I'm not able to reproduce the issue.
