### ISSUE TITLE
Login attempts should be throttled to prevent brute forcing passwords

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#8306]
### How to Reproduce
Try to login multiple times

### Expected behavior
Login should be throttled

### Observed behavior
You can keep on login attempts.

**Comment by dennishendriksen** [comment]
Instead of throttling we use the widely supported bcrypt algorithm to hash passwords. In order to make it more resistent to password cracking, bcrypt is deliberately slow (tuned to take about 1 second to verify a password on the system).

**Comment by djvanenckevort** [comment]
Ok
