### ISSUE TITLE
Downloading extends, give multiple duplicate attributes

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#8318]
### How to Reproduce
- In the navigator use download button to download multiple entities that extend the same entity.

### Expected behavior
When using the download button, that I get a file that can be uploaded without removing items from the file

### Observed behavior
In the downloaded file in the attributes tab the attritutes of entities that extend another entity are displayed multiple times. 
To import this file again, you first have to remove the duplicated attributes.

Example: 
If you look in the file(all data with patient information is removed), you get multiple "demo_standard_categorical", "demo_standard_xref" and the same for "lung_standard_categorical", "lung_standard_xref" 
[lung_download.xlsx](https://github.com/molgenis/molgenis/files/3017560/lung_download.xlsx)

--

**Comment by bartcharbon** [comment]
Already fixed in 8.0
