### ISSUE TITLE
No sign up button on home page

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8338]
### How to Reproduce
Go to the home page of a molgenis where signup is enabled 

### Expected behavior
A signup button ( or link, or some visual indication the use can sign up ) 

### Observed behavior
Only a sign in button is shown

**Comment by dennishendriksen** [comment]
@connoratrug by design the sign up button is part of the sign in dialog. since feature and feature change requests are administered in the backlog and not in GitHub could you create story?
