### ISSUE TITLE
No options found for XREF / MREF until you start typing

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8344]
### How to Reproduce
Open data row edit plugin for entity with xref or mref fields
Click an xref or mref select

### Expected behavior
I get a list of options even if I don't type, just like in the react form

### Observed behavior
I get `no options found` until I start typing

**Comment by connoratrug** [comment]
Given 100 or 10000000 options which of these would you like to 'get' and how ( visually ) would you like to get then ? The first 10, 6 ... how should the options be ordered ? Could giving the first 10 options   possibly confuse the user in thinking these are all the options ?

**Comment by fdlk** [comment]
Same as the original forms, a top five or so I believe

**Comment by LuukDijkhuis** [comment]
for 8.0: remove the "no options found"

**Comment by connoratrug** [comment]
caused by: https://github.com/molgenis/molgenis-ui-form/issues/167

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
