### ISSUE TITLE
No way to add xref/mref values in data row editor

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8349]
### How to Reproduce
Open data row editor for an entity type with an xref or mref attribute
Make sure you have permission to add rows to the attribute's refEntity

### Expected behavior
There is a way to add a new row to the ref entity table

### Observed behavior
No way to add a new row to the ref entity table

**Comment by mswertz** [comment]
actually a story. Moved it to the story backlog.

**Comment by mswertz** [comment]
close because a story.
