### ISSUE TITLE
Data row editor does not enforce maximum string lengths

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8352]
### How to Reproduce
Fill in more than 255 characters in a string attribute input
Or fill in more than 64k characters in a text / html or script input

### Expected behavior
Validation message, save button is not active

### Observed behavior
No validation message, save button is active.
When I save the error message is hidden from me by #8351

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
