### ISSUE TITLE
Data row editor shows True/False instead of Yes/No for boolean values

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8356]
### How to Reproduce
Compare boolean labels for old and new data row editor

### Expected behavior
They are the same, i.e. Yes / No

### Observed behavior
They differ, data row editor shows True / False instead of Yes / No
Old:
![Screenshot 2019-04-04 at 11 24 22](https://user-images.githubusercontent.com/1523838/55544840-3e4c0f80-56cc-11e9-8b24-a930ed3a9a9b.png)
New:
![Screenshot 2019-04-04 at 11 25 39](https://user-images.githubusercontent.com/1523838/55544921-6b002700-56cc-11e9-8740-c8ce0725b428.png)

**Comment by connoratrug** [comment]
- add i18n label to data row edit props files
- use props in mapper options in 'dataRowRepository.js' line 6

**Comment by marikaris** [comment]
The frontend part of this fix is merged. This PR can be merged if the frontend is released and the version is bumped in this PR.

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
