### ISSUE TITLE
Homepage button opens in same tab rather than target _blank

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8358]
### How to Reproduce
Go to your molgenis
Click "Learn more"

### Expected behavior
Site opens in new tab

### Observed behavior
Site opens in same tab and I lost my website

**Comment by mswertz** [comment]
I think this actually works as intented.

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
