### ISSUE TITLE
When I search for a source attribute in the mapping service attribute mapping screen the attribute is not showing

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#8359]
### How to Reproduce
- Execute the commander script of testplan Mapping Service
- Execute case: "Mapping project overview"
- Then click on the pencil on source attribute "Gender"
- Then try to search for "Hypertension"

### Expected behavior
- "Bloodpressure etc." attribute should move to the top in order

### Observed behavior
- The ordering of the attributes stays the same

**Comment by dennishendriksen** [comment]
Cause: under the hood no search results are found for the query 'hypertension' and thus all results are returned

**Comment by dennishendriksen** [comment]
@sidohaakma since both source and target attributes aren't tagged I think the observed result is the expected result.

**Comment by mswertz** [comment]
This is not intented behavior. When we designed this we envisoned to have real search matches to trump the tag based search matches. With the idea that simple matches should go always go before magic based matches.
