### ISSUE TITLE
New forms do not enforce max long value

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8360]
### How to Reproduce
Enter 9223372036854775808 into a long field.

### Expected behavior
Validation fails

### Observed behavior
Validation does not notice it. Server error message gets eaten up by #8351

**Comment by fdlk** [comment]
Caused by https://github.com/molgenis/molgenis-ui-form/issues/267

**Comment by mswertz** [comment]
Is this easy to fix? If not, does the server throw an error?

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
