### ISSUE TITLE
Can not activate inactive user

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8361]
### How to Reproduce
Create a user with the user manager plugin, do not active the user 
Place the user in a group ( for example test group , manager role)
Use  the usermanager to active the user

### Expected behavior
The user is activated 

### Observed behavior
Error message is shown: Error! An error occurred. Please contact the administrator.

**Comment by dennishendriksen** [comment]
Run into the same issue. Workaround: use dataexplorer plugin to change 'active' status of user.
