### ISSUE TITLE
Data row editor form layout is less compact than the old one

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8364]
### How to Reproduce
Open data row editor, inspect the form layout

### Expected behavior
[Horizontal form](https://getbootstrap.com/docs/4.3/components/forms/#horizontal-form): Labels are printed to the left of the input fields

### Observed behavior
Labels are printed above the input fields

**Comment by fdlk** [comment]
It is a matter of taste and the new forms are roomier, but IIRC it was an active decision to make the original form layout horizontal.

**Comment by LuukDijkhuis** [comment]
Morris likes it as-is. Closed, won't fix
