### ISSUE TITLE
Group membership API allows adding same user to same group in multiple roles

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8367]
### How to Reproduce
Run mcmd script
```
add group c6
add user bofkeC6
make bofkeC6 c6_viewer
make bofkeC6 c6_editor
make bofkeC6 c6_viewer
```

### Expected behavior
api should enforce the business rule that a user can have only one role in a group

### Observed behavior
bofke has three c6 memberships

**Comment by mswertz** [comment]
should be idempotent. I.e., if I add to a role that I already have, I will not be added again. However, also no need to throw an error. This is typical what you would do: simply supply a list of rules.
