### ISSUE TITLE
Canceling jobs are shown incorrectly in job overview

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8370]
### How to Reproduce
Start a long running job and cancel it, then go to the job overview while it's still being canceled (test plan JOBVIEW004)

### Expected behavior
While the job is still being canceled I'd expect it to be listed in the running jobs table.

### Observed behavior
Job row already appears in the Finished Jobs table with empty status label:
<img width="1165" alt="Screenshot 2019-04-04 at 17 25 53" src="https://user-images.githubusercontent.com/1523838/55567902-f1356100-56fe-11e9-9a2d-06b8e3790cad.png">

linked to: https://github.com/molgenis/molgenis/issues/8370

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
