### ISSUE TITLE
IE11 Error while creating group

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8377]
### How to Reproduce
1. IE11: As superuser navigate to the 'Security manager' plugin
2. IE11: Select 'Add group'
3. IE11: Start typing in the 'Group name' input

### Expected behavior
- No errors

### Observed behavior
- ```An error has occurred.``` alert appears

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
