### ISSUE TITLE
Importer ignores tags in the database, causing unjustified UnknownTagExceptions

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8378]
### How to Reproduce
Do NAVDOWN002 for the navigator:
Run the "testplan_navigator" script with mcmd
log in as nav_manager
Go to Navigator
click on package "nav"
select TypeTest
click the download icon
once the alert appears that your download is ready, click the link in the message to download the file
delete 'TypeTest'
import the file using the upload plugin

### Expected behavior
File imports and my typetest is back

### Observed behavior
![Screen Shot 2019-04-08 at 09 55 43](https://user-images.githubusercontent.com/10075439/55712908-e248fa00-59ef-11e9-9720-2fddbcae9e04.png)

**Comment by LuukDijkhuis** [comment]
either you don't delete the tags when you delete the entity, or you download and re-upload the tags. Bottom line: this roundtrip should work

**Comment by marikaris** [comment]
If I did something wrong, the testplan needs to be fixed. I'm not sure why those Tags are in the file actually, and how they are connected to the TypeTest table.

**Comment by bartcharbon** [comment]
Known behaviour.

From the docs:
"Tags on your metadata will not be downloaded, these need to be added to the file manually before it can be uploaded into MOLGENIS via the import plugin."

Problem is that the importer does not resolve tags in the system, it only looks in the file.

Why they are in the file and how they are connected is quite simple, the typetest entity is tagged...

**Comment by bartcharbon** [comment]
@marikaris This is probably one of the reasons this testplan had an "own" typetest emxfile

**Comment by mswertz** [comment]
please verify if this really is a bug, otherwise we will move it to next milestone

**Comment by mswertz** [comment]
we need to be able to roundtrip download/uploads.
