### ISSUE TITLE
Scheduled job timestamp incorrect

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8379]
### How to Reproduce
- Sign in as superuser on https://latest.test.molgenis.org/
- Import [city.xlsx](https://github.com/molgenis/molgenis/files/3053575/city.xlsx)
- Using the 'Scheduled jobs' plugin create a new job:
```
Name | File Ingest Test Job
-- | --
Cron expression | 0/20 * * * * ?
Active | yes
Failure email | <your email>
Type | File ingest
Job parameters | {"url": "invalid","loader": "CSV","targetEntityId": "fdp_city"}
```

### Expected behavior
- Failure email contains correct timestamps

### Observed behavior
- Timestamps are off by a couple of hours

**Comment by LuukDijkhuis** [comment]
FK: probably the server is on GMT but you can't see that in the timestamp. For now: add timezone to the time format

**Comment by mswertz** [comment]
indeed, add timezone. And if possible, use timezone where server is situated.
