### ISSUE TITLE
IE11 Script run button hard to click due to tooltip

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8380]
### How to Reproduce
- IE11: Sign in as superuser
- IE11: Navigate to the 'Scripts' plugin in menu 'Plugins'
- IE11: Create a script and select the 'Run' button

### Expected behavior
- Script is executed

### Observed behavior
- Script is not executed due to tooltip being in the way

![script_popup](https://user-images.githubusercontent.com/2477186/55717021-b8480580-59f8-11e9-9abb-d884da35b670.png)

**Comment by mswertz** [comment]
please remove tooltip.

**Comment by MaxPostema** [comment]
Fixed in:
https://github.com/molgenis/molgenis-frontend/pull/90
