### ISSUE TITLE
JavaScript (Magma) script execution broken

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8382]
### How to Reproduce
See test case SCRIPTSYS002
1.  Create script BMI
Name: BMI
Type: JavaScript (Magma)
Content: $('weight').div($('height').pow(2)).value();
Generate security token: No
Result file extension: leave empty
2. Run script

### Expected behavior
Script executes successfully

### Observed behavior
Script output: org.molgenis.script.core.ScriptException: Unknown attribute 'weight'

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
