### ISSUE TITLE
Python script executor: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8383]
### How to Reproduce
See test case SCRIPTSYS003

- Create script Hello (on https://latest.test.molgenis.org/)
Name: Hello
Type: Python
Content:  print "Hello ${name}!"
Generate security token: No
Result file extension: leave empty
- Execute Hello script with name = MOLGENIS

### Expected behavior
- Script runs successfully

### Observed behavior
- ```Error running [/usr/local/tomcat/temp/9785049303791475280.py]. File "/usr/local/tomcat/temp/9785049303791475280.py", line 1print "Hello world!"^ SyntaxError: Missing parentheses in call to 'print' ```

**Comment by LuukDijkhuis** [comment]
python 2 print will work without parentheses, python 3 print will not. So the testcase should be 
Content: print("Hello ${name}!")

**Comment by fdlk** [comment]
I've updated the test plan
