### ISSUE TITLE
Metadatamanager huge checkbox

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8386]
### How to Reproduce
- Sign in as superuser
- Navigate to the 'Metadata Manager' plugin in menu 'Data Integration'
- Select an entity type from the dropdown

### Expected behavior
- Similar styling of checkboxes

### Observed behavior
![image](https://user-images.githubusercontent.com/2477186/55724203-301f2b80-5a0b-11e9-8332-f2baa611375d.png)

**Comment by mswertz** [comment]
small thing I suppos

**Comment by connoratrug** [comment]
@mswertz yes, it's been handing in the test column for a week now, somebody just needs to test it.

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
