### ISSUE TITLE
ScriptJob fails when scheduled, succeeds when started manually

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#8402]
### How to Reproduce
1. Create a JavaScript script in the Scripts Plugin:
```
var x = false;
```
2. Run it and see that it succeeds
3. Add a scheduled job:

Name | Test Job
-- | --
Cron expression | 0/20 * * * * ?
Active | No
Type | Script
Job parameters | {"name": "test", "parameters":""}

4. Run it (by clicking the green play button)

### Expected behavior
The scheduled job succeeds

### Observed behavior
It doesn't. Log:

```
10:34:29.308 - Execution started.
10:34:29.326 - Failed. null
```

**Comment by dennishendriksen** [comment]
@tommydeboer what is the error?

**Comment by tommydeboer** [comment]
@dennishendriksen I've updated the description

**Comment by dennishendriksen** [comment]
I think your job parameters value in your example is incorrect since the docs state that parameters is ```A String containing a JSON object describing the Script parameters```.

```
{"name": "test"} --> error, but should be ok
{"name": "test", "parameters":""} --> ok, but should be error
{"name": "test", "parameters":"{}"} --> ok and should stay ok
{"name": "test", "parameters":null} --> error, but should be ok
{"name": "test", "parameters":undefined} --> error, but should be ok
```
