### ISSUE TITLE
OIDC client; when changing client name, this change is not displayed on login button

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#8404]
### How to Reproduce
Make a OIDC client, save and add this client to the authentication settings.
When modifying this OIDC client, the "clientName" , login button does not change.
This happened on molgenis21, when removing TMF (see images).

### Expected behavior
When modifying clientName on OIDC client login button changes when changes are saved.
<img width="589" alt="githubissue" src="https://user-images.githubusercontent.com/40240913/55865771-55cd4180-5b7f-11e9-9e28-8428334a89a4.png">

### Observed behavior
Name does not change after modification. 
![image](https://user-images.githubusercontent.com/40240913/55865592-fa9b4f00-5b7e-11e9-8860-5aecdb72b54d.png)
Workaround: Stop and start tomcat, name is changed.

**Comment by mswertz** [comment]
only fix if small. Otherwise move to first.
