### ISSUE TITLE
Settings can't be saved after update

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8408]
### How to Reproduce
- Sign in as superuser
- Navigate to the 'Data explorer' plugin
- Select 'OIDC client' entity type in the dropdown
- Create an entity with bogus information
- Navigate to the 'Settings' plugin in menu 'Admin'
- Select 'Authentication Settings' in the dropdown
- Set 'Allow users to sign up' to 'True'
- Set 'Sign up moderation' to 'False'
- Select 'Save changes'
- Select the bogus 'OIDC client' as 'Authentication service'

### Expected behavior
- 'Save changes' button is enabled so that I can save my changes

### Observed behavior
- 'Save changes' button stays disabled

**Comment by mswertz** [comment]
I propose to have button always enabled. If you save with errors, it should give error message (either client or server side).

**Comment by connoratrug** [comment]
Caused by: https://github.com/molgenis/molgenis-ui-form/issues/274

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
