### ISSUE TITLE
Settings 'Saved changes' enabled for unchanged settings

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8409]
### How to Reproduce
- Sign in as superuser
- Navigate to plugin 'Settings' in menu 'Admin'
- Change text in application title
- Undo text change in application title

### Expected behavior
- 'Save changes' button is disabled because settings is unchanged

### Observed behavior
- 'Save changes' button is enabled

**Comment by mswertz** [comment]
I like always active button better.

**Comment by dennishendriksen** [comment]
Ok
