### ISSUE TITLE
Language dropdown drops up and is missing searchbox

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8412]
### How to Reproduce
- Sign in as superuser
- Active all languages via ```/menu/main/dataexplorer?entity=sys_Language```
- Sign out
- Sign in
- Navigate to the home plugin
- Open the language dropdown

### Expected behavior
![image](https://user-images.githubusercontent.com/2477186/55944738-85488080-5c49-11e9-8df5-1eeee842fb90.png)

### Observed behavior
IE10:
![image](https://user-images.githubusercontent.com/2477186/55944695-7235b080-5c49-11e9-8c93-c57ef48d566a.png)

- Dropdown drops in wrong direction
- Select box is missing searchbox

**Comment by connoratrug** [comment]
Personally i think i prefer the observed behaviour

**Comment by mswertz** [comment]
I don't think this needs search box. And we should revisit how we want popups to look like. I think it should be consistent behavrio.
