### ISSUE TITLE
8.0 RC1 links to wrong documentation version

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8414]
### How to Reproduce
- Sign in as superuser
- Select 'Help' button in menu on https://latest.test.molgenis.org/

### Expected behavior
- I land at a page with 8.0 documentation

### Observed behavior
- I land at a page with current documentation

**Comment by fdlk** [comment]
Is feature request, I think? You have always ended up at page with documentation for all versions.

**Comment by LuukDijkhuis** [comment]
duplicates #8497
