### ISSUE TITLE
Recaptcha settings should have nullable expressions

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8419]
### How to Reproduce
Go to application settings
Set recaptcha to true

### Expected behavior
The code fields I need to add become red, because they are required

### Observed behavior
I can set recaptcha to true without providing the codes and then the sign up is not working at all.

**Comment by mswertz** [comment]
does the manual state this?

**Comment by mswertz** [comment]
either this or #8420 should be fixed
