### ISSUE TITLE
Logo above menu bar is not displayed

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#8422]
### How to Reproduce
- SET004 from the settings test plan:
Set 'Logo above navigation bar' to "/img/logo_molgenis_small.png", Save changes, reload page

### Expected behavior
Logo is shown above the menu bar in all plugins
like: 'https://chd7.org/' and 'https://www.deb-central.org/'

### Observed behavior
Logo is not shown above the menu bar in new style Vue plugins

**Comment by dennishendriksen** [comment]
Related?
![image](https://user-images.githubusercontent.com/2477186/56015738-58a07180-5cfa-11e9-85ef-98508231b1b5.png)
