### ISSUE TITLE
Footer text differs per plugin: 2018 paper reference missing

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8423]
### How to Reproduce
- Navigate to MOLGENIS frontpage

### Expected behavior
- Footer displays something similar to:
```
This database was created using the open source MOLGENIS software version 8.0.0 built on 2019-04-02 14:54 UTC.
Please cite Van der Velde et al (2018), Swertz et al (2010) or Swertz & Jansen (2007) on use.
```

### Observed behavior
- Some plugins display a different text with different references:
```
This database was generated using the open source MOLGENIS database generator 8.0.0 built on 2019-04-02 14:54 UTC. 
Please cite Swertz et al (2010) or Swertz & Jansen (2007) on use.
```

**Comment by mswertz** [comment]
is this in the 'old' or 'new' footer. If only in old then this issue will be closed.

**Comment by dennishendriksen** [comment]
'new' footer only.

**Comment by fdlk** [comment]
Fixed in the molgenis-ui-context, we still need to use this in the molgenis repo.
