### ISSUE TITLE
Google analytics footer message sometimes not displayed

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8426]
### How to Reproduce
- Enable Google Analytics

### Expected behavior
Footer always states:
```
We use Google Analytics to review this site's usage and improve our services.
To optimally protect your privacy we have signed the Data Processing Amendment, masked parts of your IP address and disabled data sharing with other Google services.
Click here to opt-out of Google Analytics.
```

### Observed behavior
Footer sometimes does not include this statement.

**Comment by mswertz** [comment]
I didn't know this was always shown. I would like to have a shorter version of this text: only first sentence+ opt-out link. And on mouseover whole text.

**Comment by MaxPostema** [comment]
Note: Will show in Analytics text bootstrap 3 pages. It wont show in bootstap 4 pages.

**Comment by MaxPostema** [comment]
Further note: the opt-out link is also broken.
