### ISSUE TITLE
Configuring other email than no-reply@molgenis.org does not work

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#8432]
### How to Reproduce
Try to setup molgenis@gmail.com in Settings plugin

### Expected behavior
Admin user emails with molgenis@gmail.com again

### Observed behavior
MOLGENIS does not send emails anymore.

**Comment by fdlk** [comment]
Works well for me on molgenis118 with 0.0.0-SNAPSHOT-PR-8446-6

**Comment by sidohaakma** [comment]
This does not work on the cluster, because of authentication problem on smtp.gmail.com. I am now looking into creating an email box for the molgenis-user at the RuG. The request is set out at Harm.

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)

**Comment by mswertz** [comment]
so can it be closed here then also?

**Comment by fdlk** [comment]
Yes
