### ISSUE TITLE
Cannot enter negative numbers into new form

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8433]
### How to Reproduce
Open Type test with data row editor, set integer value to -1

### Expected behavior
It works

### Observed behavior
The - character gets eaten up shortly after you type it

**Comment by fdlk** [comment]
There is a workaround, first type the 1 and then type the - in front of it.

**Comment by fdlk** [comment]
Caused by https://github.com/molgenis/molgenis-ui-form/issues/277

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
