### ISSUE TITLE
Attribute deleted when moving it from a compound whilst also removing said compound

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#8451]
### How to Reproduce
1. Import [invuse.xlsx](https://github.com/molgenis/molgenis/files/3106676/invuse.xlsx)
2. Go to the Metadata Manager and open the Sample entity
3. Move the attribute **startdate** from the compound **lab** to the root
4. Delete the compound attribute **lab**
5. Save the changes

### Expected behavior
Attribute **lab** is deleted
Attribute **startdate** is not deleted and is no longer in a compound

### Observed behavior
Attribute **lab** is deleted
Attribute **startdate** is also deleted

**Comment by mswertz** [comment]
discuss if this does, or does not, work as intended.

**Comment by mswertz** [comment]
I have memory that this one was fixed. Is that correct?

**Comment by dennishendriksen** [comment]
@tommydeboer could you address the comment of @mswertz?

**Comment by tommydeboer** [comment]
@mswertz This seems to be fixed indeed!
