### ISSUE TITLE
"Save and run" button in script plugin does not work in IE

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8457]
### How to Reproduce
Open IE
Go to scripts plugin
Create a script
Click "Save and run"

### Expected behavior
Script runs after it is saved

### Observed behavior
Page seems to refresh, script doesn't run

**Comment by MaxPostema** [comment]
Issue originates from IE11 popup blocker. The popup blocker reloads the page before it accepts the site to open popups.
This behaviour is outside of our control.
