### ISSUE TITLE
Metadata manager save message starts with :

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8468]
### How to Reproduce
Create an entity and save it

### Expected behavior
Normal message

### Observed behavior
Message starts with `:`

> : Metadata succesvol opgeslagen voor Entiteit: label

**Comment by mswertz** [comment]
This one seems so small that I don't understand why you have spent time on reporting instead of fixing. So if indeed small please fix before this release so I don't have to triage it again :-)
