### ISSUE TITLE
Header is not sticky in new pages

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8481]
### How to Reproduce
Add large content to home page
Scroll around

### Expected behavior
header is sticky

### Observed behavior
header is not sticky

**Comment by connoratrug** [comment]
Possible direction for fixing this : https://codepen.io/elleestcrimi/pen/LENQvr

**Comment by fdlk** [comment]
Best solution I found: https://jsfiddle.net/pgv57c46/ (But https://caniuse.com/#search=sticky)

**Comment by connoratrug** [comment]
@fdlk yes, BD-4 docs warns about ie not implementing sticky, i still think we should look at a flex box solution with or without BS
