### ISSUE TITLE
Easier way to select multiple options in mref field

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#8492]
### How to Reproduce
When adding a collection in DE registry (molgenis21), manually it is a lot of work to add all diagnosis available in that collection. For example: C03,C04,C05,C15,C16,C17,C18,C19,C20,C22,C23,C24,C25,C32,C34,C37,C44,C48,C49,C50,C53,C61,C62,C64,C65,C70,C71,C72,C73,C74,C75,C77,C80
These codes all have to be entered for one collection.

### Preferred behavior
easy way to select multi options in mref field.

### Observed behavior
Instead, add one code, in same rule add other code and so one. Since options in diagnosis available are plentiful it takes a long time to load all options.

**Comment by mswertz** [comment]
if the list of choices is limited then you can use categorical_mref which would give you checkboxes. would that work in this case?

**Comment by fdlk** [comment]
@mswertz No, options are plentiful

**Comment by dennishendriksen** [comment]
@Fernananas could you add a story to the backlog since this is a feature request?
