### ISSUE TITLE
Help link refers to dev version of the documentation, not the documentation for the deployed version

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#8497]
### How to Reproduce
Click on the help menu item

### Expected behavior
I go to help pages for the actual deployed version

### Observed behavior
I go to the 'current / dev' version of the documentation (Observed in Molgenis 7)

**Comment by LuukDijkhuis** [comment]
Morris says: remove the help button - if someone wants help they can add a Helo menu item to their "own" specific documentation.

**Comment by djvanenckevort** [comment]
That would work for me. Especially if we can add links directly, instead of using the redirect plugin.

**Comment by LuukDijkhuis** [comment]
will be fixed by story M6666
