### ISSUE TITLE
Cannot delete abstract entity type

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8498]
### How to Reproduce
Upload: 
[vkgl-model2019.xlsx](https://github.com/molgenis/molgenis/files/3181334/vkgl-model2019.xlsx)
Go to navigator
Select entities: AMC, LUMC, VUMC, RADBOUD, UMCG, UMCU, Erasmus, consensus and vkgl_map_lab_model
Press delete button 

### Expected behavior
Everything is deleted, because I select the abstract entity with its children and another table

### Observed behavior
Error: Value 'vkgl_map_lab_model' for attribute 'id' is referenced by entity 'sys_md_EntityType'.

**Comment by mswertz** [comment]
can you delete in two steps? I.e. delete first the non-abstract and then the abstract?

**Comment by dennishendriksen** [comment]
@marikaris could you address the comment of @mswertz?

**Comment by dennishendriksen** [comment]
@marikaris *bump*

**Comment by marikaris** [comment]
Sorry about that! Yes, in two steps it does work.

**Comment by dennishendriksen** [comment]
The delete fails correctly since you are not removing the entity type ```nki``` which extends from the entity type ```vkgl_map_lab_model```. The delete succeeds when you add ```nki``` to the list of deleted entity types.
