### ISSUE TITLE
Password reset case sensitive

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#8499]
### How to Reproduce
On the molgenis120 (INVUSE). I got this mail from users:
![image003](https://user-images.githubusercontent.com/40240913/57833657-ca1c8580-77ba-11e9-8be3-d89e37af3514.jpg)

### Expected behavior
The mailadress was correct, so normal resest

### Observed behavior
Got error, user used lower case for mailadress. But email for user was imported and was in captital letters (at least the firstname letters and first letter of last name). So if you use the same format for mailadres the reset works fine.

Is it possible to make this field (forgot password) not so specific? So a non case sensitive field (or how do you call it?)

**Comment by dennishendriksen** [comment]
RFC 5321 2.4 states
```
SMTP implementations MUST take care to preserve the case of mailbox local-parts. In particular, for some hosts, the user "smith" is different from the user "Smith".
```
So I don't think we should treat email addresses as case-insensitive.

**Comment by djvanenckevort** [comment]
For the check in this dialog you can do a case insensitive check. It is comparing the user input with what is on record. For sending the e-mail you have to use the e-mail address on record.

**Comment by mswertz** [comment]
I agree. The rule Dennis mentioned is for systems; but we are dealing with users. So what I see in other applications is that they treat it case insensitive. Then user gets email. If by any chance there would be multiple users with same email (when case insensitive) that this other user would get the email and can ignore it.

Bottomline: we must fix this.

**Comment by LuukDijkhuis** [comment]
wish: all users in the db that match the email address case insensitively will receive the reset-mail

**Comment by LuukDijkhuis** [comment]
discuss: if we do this then we should implement email case-insensitivity everywhere or you will end up with inconsistent behaviour

**Comment by fdlk** [comment]
> wish: all users in the db that match the email address case insensitively will receive the reset-mail

There should only ever be one! Otherwise user B gets a password reset email that allows them to take over the account of user A.

**Comment by djvanenckevort** [comment]
The following behaviour would be safe:
- Password reset dialog case insensitive e-mail check
- Accounts case sensitive e-mail field
On password reset
- Case insensitive search of accounts
- For each of the matched accounts do the password reset and send the link to the e-mail address as recorded in the account
Because you send the e-mail to the address as recorded in the account it will not allow someone to take over the account.

**Comment by fdlk** [comment]
https://security.stackexchange.com/questions/214814/why-can-i-log-in-to-my-facebook-account-with-a-misspelled-email-password?utm_source=Iterable&utm_medium=email&utm_campaign=the-overflow-newsletter&utm_content=10-02-19

**Comment by dennishendriksen** [comment]
I think this is feature change request that requires careful thinking, not a security issue. @Fernananas could you create a story in the backlog?
