### ISSUE TITLE
When you have an account on a server sign in screen always shown, instead of homepage

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis#8513]
### How to Reproduce
When you have an account on a server (for example directory.bbmri-eric.eu) and you want to visit the server, the sign in screen pops up immediately 

### Expected behavior
When my session is expired AND I am visiting a page that doesn't require sign in THEN we don't show the login dialogue. Otherwise you get login as currently.

### Observed behavior
Immediately redirected to the sign in page with the message 'Warning! Your login session has expired.'

**Comment by mswertz** [comment]
Alternatively: add a link to the login that says 'back to home'

**Comment by fdlk** [comment]
@mswertz but pushing that link would redirect you to the same login dialog, I expect.

**Comment by mswertz** [comment]
Proposed solution: when my session is expired AND I am visiting a page that doesn't require sign in THEN we don't show the login dialogue. Otherwise you get login as currently. Updated description accordingly above
