### ISSUE TITLE
Unit test randomly fails with "mock object was garbage collected"

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#8516]
We see this error now and again in our builds:
..."java.lang.IllegalStateException: The mock object was garbage collected. This should not happen in normal circumstances when using public API."...

This is probably caused by:
https://github.com/mockito/mockito/issues/1541
Which was fixed in late in 2018:
https://github.com/mockito/mockito/pull/1544
However testNg support was dropped earlier that year:
https://github.com/mockito/mockito-testng

possible workaround, if it only happening in this test in our case, is to rewrite the test to a separate mock declaration and behaviour line. (so, no "one-liner stub")

**Comment by mswertz** [comment]
sound like technical debt, I mean, are you suggesting to update dependency?

**Comment by dennishendriksen** [comment]
Fixed by #8627.
