### ISSUE TITLE
removing data value in the forms does not work

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#8520]
### How to Reproduce
create a token with a expiration date
save
edit the token, click the "clear"-cross for the expiration date
save

### Expected behavior
expiration date is empty

### Observed behavior
expiration date is unchanged

**Comment by connoratrug** [comment]
Related to: [Date(time) field clear button does not clear the value #299 ](https://github.com/molgenis/molgenis-ui-form/issues/299)
