### ISSUE TITLE
Error message refers to empty string when telling an mref doesn't exist

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8521]
### How to Reproduce
Go to advanced importer
Import: 
[vkgl-demo-without-labs.xlsx](https://github.com/molgenis/molgenis/files/3216559/vkgl-demo-without-labs.xlsx)

### Expected behavior
Unknown mref value '617883' for attribute 'OMIM disease' of entity 'demo_consensus'.
(so xref should be mref and the attribute name should be there) 

### Observed behavior
![Screen Shot 2019-05-24 at 13 09 12](https://user-images.githubusercontent.com/10075439/58323805-58c97c00-7e25-11e9-9f43-d6af500190cc.png)

**Comment by dennishendriksen** [comment]
The value is a single cross-reference (xref) value, so the term xref is correct here. In this case the attribute could not be determined resulting in ```<unknown>``` being rendered incorrectly. I'll put up a fix for that.
