### ISSUE TITLE
nextHref contains URI of server

### ISSUE THREAD

**Issue by cpavanrun** [molgenis/molgenis#8534]
We have a reverse-proxy setup to connect our full URL to the localhost:8080 on the server.

I am trying to use the molgenis-tools-emx-downloader (with PageSize set to 5) to download a entity that has more than 5 instances. Lower than 5 will make sure that the api end-point will return a nextHref that can be followed to further download the data.

 However, for Molgenis v4.1 and v8.1.1 this will result in a connection error because the `/api/v2/test_entity1` REST end-point returns a `nextHref` field that includes the _http://localhost:8080_ which cannot be reached from where a clients lives (hence the reverse proxy).

### How to Reproduce
Upload this [example EMX model](https://surfdrive.surf.nl/files/index.php/s/MNC6c8NvPJQ9UwK)
Make a GET request as follows:
```
curl -X GET "http://localhost:8080/api/v2/test_entity1?attrs=~id&sort=column1%3Aasc&start=0&num=5" -H  "accept: application/json" -H  "x-molgenis-token: XXXXX"
```
### Expected behavior
An response that has a `nextHref` that matches all other `href`s:
```JSON
"nextHref": "/api/v2/test_entity1?attrs=~id&sort=column1%3Aasc&num=4&start=5"
```
### Observed behavior
```JSON
"nextHref": "http://localhost:8080/api/v2/test_entity1?attrs=~id&sort=column1%3Aasc&num=4&start=5"
```

If needed I can provide a full docker equivalent of the reverse-proxy setup but I am pretty sure the error lies in the nextHref.

**Comment by cpavanrun** [comment]
For future googlers, the error that occurs is similar to:
```
[ERROR] - Error streaming entity data for sys_FileMeta.
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
```
A quick-fix work around is to set `ProxyPreserveHost` on a apache2/httpd configuration to `On` (default: `Off`).

**Comment by fdlk** [comment]
Hi @cpavanrun, I believe this is due to how the proxy is configured. We rely on Spring to tell us the hostname we're running on and it in turn depends on correct X-Forwarded-* headers being set.
So if your proxy sets `X-Forwarded-Host` to the external DNS name of your server and `X-Forwarded-Port` to the external port number, I expect you'll find that the URLs are again correct.

**Comment by cpavanrun** [comment]
It was indeed related to the way the proxy was configured. Since `X-*` settings are slightly bothersome in apache/httpd I have opted to set the `ProxyPreserveHost`.

However, this still keeps the presence of the hostname within the molgenis reply awkward. Possibly adding a `_next_href` would prevent anyone in the future from facing this. Or perhaps a note in the documentation about reveres proxies would suffice, then again: perhaps this issue in itself is sufficient. Good luck future reader!

**Comment by fdlk** [comment]
I checked with @dennishendriksen and also for our new data api we would like to stick with absolute URLs because of arguments given in https://opensource.zalando.com/restful-api-guidelines/#217.

**Comment by cpavanrun** [comment]
Sounds very reasonable!
