### ISSUE TITLE
If I go to a public page of MOLGENIS after an expired login I get redirected to the login page instead of seeing the public page

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#8541]
### How to Reproduce
- Login in to MOLGENIS
- Close the browser page and wait for a day to have the login expire
- Go to a public page of the same MOLGENIS

### Expected behavior
I see the public page

### Observed behavior
I am redirected to the login page

**Comment by LuukDijkhuis** [comment]
see also #8513

**Comment by holubp** [comment]
And when accessing the Directory for the second time, it goes to the public page.

**Comment by mswertz** [comment]
> And when accessing the Directory for the second time, it goes to the public page.

what do you mean?

**Comment by mswertz** [comment]
See

**Comment by mswertz** [comment]
duplicate see #8513
