### ISSUE TITLE
Poor performance adding entities to row-level secured entity type

### ISSUE THREAD

**Issue by cpavanrun** [molgenis/molgenis#8574]
Very much a copy of https://github.com/molgenis/molgenis/issues/7616 . But the performance is still very poor. Context is us trying to load in a sys_FileMeta export that has ~10.000 rows and is locked to have row-level security (RLS) enabled by system default in molgenis 8.1. Without RLS imports finish within seconds.

## How to Reproduce
- Start local docker stack of molgenis 8.1 with 5 GB MEM available in total.
- As superuser import [rls-500.xlsx](https://github.com/molgenis/molgenis/files/3381181/rls-500.xlsx)
- Navigate to the 'permission manager' plugin, select 'Row-level security' tab and enable row-level security for entity type 'RlsLarge'
- Delete all RlsLarge rows
- Import the same file again with 'Ignore metadata' and 'Add entities'

Repeat for:
- [rls-1000.xlsx](https://github.com/molgenis/molgenis/files/3381180/rls-1000.xlsx)
- [rls-2000.xlsx](https://github.com/molgenis/molgenis/files/3381179/rls-2000.xlsx)
- [rls-10000.xlsx](https://github.com/molgenis/molgenis/files/3381177/rls-10000.xlsx)

## Expected behavior

- Imports complete in a reasonable time

## Observed behavior
_Without_ RLS enabled the importing job (n=500):
```
INFO  org.molgenis.data.importer.ImportJob - Import finished in 1165 msec.
```
With RLS enabled the importing job (n=500):
```
INFO  org.molgenis.data.importer.ImportJob - Import finished in 31764 msec.
```
With RLS enabled the importing job (n=1000):
```
INFO  org.molgenis.data.importer.ImportJob - Import finished in 215718 msec.
```
With RLS enabled the importing job (n=2000):
```
INFO  org.molgenis.data.importer.ImportJob - Import finished in 314389 msec.
```

Currently running a set with ~ 10.000 rows.
<img width="1257" alt="Screenshot 2019-07-11 at 09 13 42" src="https://user-images.githubusercontent.com/9033494/61038001-80bc7100-a3cc-11e9-98b1-3b98dcdc800d.png">

**Comment by cpavanrun** [comment]
| Number of rows  |  Runtime (ms) | Runtime (hh:mm:ss)
| ------------- | ------------- | ------------- |
| 500 (No RLS) | 1165 | 00:00:01 |
| 500 | 31764 | 00:00:31 |
| 1.000 | 215718 | 00:03:35 |
| 2.000 | 314389 | 00:05:14 |
| 10.000 | ? | ? |

**Comment by dennishendriksen** [comment]
We use the third-party [JdbcMutableAclService of the Spring Security library](https://docs.spring.io/spring-security/site/docs/5.1.6.RELEASE/api/org/springframework/security/acls/jdbc/JdbcMutableAclService.html)  for creating and storing of access-control lists. I've profiled your ```rls-2000.xlsx``` case:
- 80% of the time is spend on JdbcMutableAclService.updateAcl
- 20% of the time is spend on JdbcMutableAclService.createAcl
of which almost all time is spend on database querying due to a very large amount of queries.

Unfortunately the ```MutableAclService``` interface only allows for creating/updating access-control lists one-by-one and doesn't provide a batch method.

A solution would be to create our own implementation which I estimate to be quite a bit of work due to the complexities of the implementation provided by Spring Security.

**Comment by cpavanrun** [comment]
Thank you for investigating the problem. 

It is good to know that the profile of the performance hit is. Another problem with the implementation is that the one-by-one is also done inefficiently. Going by the description of JdbcMutableAclService.updateAcl: '_This implementation will simply delete all ACEs in the database and recreate them on each invocation of this method._'.

Plus, updateACL calls clearCacheIncludingChildren which might lead to performance problems too: https://github.com/spring-projects/spring-security/issues/3330

The 10.000 instance upload never finished, I wonder when the row-level-security will be used more and more if this then not becomes an insurmountable burden on multi-million cases.

What happens if you upload without row-level-security and then enable it. Do similar things happen, or is a different heuristic used?

**Comment by dennishendriksen** [comment]
> The 10.000 instance upload never finished, I wonder when the row-level-security will be used more and more if this then not becomes an insurmountable burden on multi-million cases.

This might be caused by JdbcMutableAclService.createAcl which reads the Acl after persisting it in order to 'ensures cache registration, proper retrieval etc'. Increasing the ```max_locks_per_transaction ``` might resolve this issue (but not the performance issue).

> What happens if you upload without row-level-security and then enable it. Do similar things happen, or is a different heuristic used?

Same code paths unfortunately.

**Comment by mswertz** [comment]
I want this issue investigated so we can decide if this is solvable within this framework (and in that case we can plan the work, otherwise we must reevaluate the framework).

**Comment by dennishendriksen** [comment]
>It is good to know that the profile of the performance is. Another problem with the implementation is that the one-by-one is also done inefficiently. Going by the description of JdbcMutableAclService.updateAcl: 'This implementation will simply delete all ACEs in the database and recreate them on each invocation of this method.'. Plus, updateACL seems to call clearCacheIncludingChildren which might lead to performance problems too: spring-projects/spring-security#3330

I've tested a workaround that was mentioned in a comment in spring-projects/spring-security#3330 which results in a significant performance improvement (~30s instead of ~3m30s for rls-1000.xlsx). I think this is an acceptable workaround since populating an empty cache is orders of magnitude faster than partially clearing the cache.
