### ISSUE TITLE
Stack traces stating that tables cannot be found in postgress while running integration tests

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#8584]
### How to Reproduce
- Run integration tests (the behaviour is seen constantly in the failing CopyBoth tests (#8583 ))
- take a look at the logs

### Expected behavior
- no stacktraces

### Observed behavior
07:55:39.241 [pool-3-thread-1] ERROR o.m.data.index.job.IndexJobService - Index job failed
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT this."id_attr", this."string_attr", this."bool_attr", this."categorical_attr", NULL AS "categorical_mref_attr", this."date_attr", this."enum_attr", this."datetime_attr", this."email_attr", this."decimal_attr", this."html_attr", this."hyperlink_attr", this."long_attr", this."int_attr", this."script_attr", this."xref_attr", NULL AS "mref_attr", this."compound_child_int_attr" FROM "DataServiceItEntityType#bc570817" AS this ORDER BY "id_attr" ASC]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "DataServiceItEntityType#bc570817" does not exist

sometimes the "DynamicDecoratorEntityType" shows up as well

**Comment by mswertz** [comment]
I don't have problems with stacktraces in integration tests. Why do you think this is an issue?

**Comment by dennishendriksen** [comment]
I don't see any stack traces in the latest successful Travis integration test runs. Can you still reproduce @bartcharbon ?

**Comment by mswertz** [comment]
please close @bartcharbon unless you can reproduce

**Comment by dennishendriksen** [comment]
@mswertz @bartcharbon has been working on this yesterday cleaning up tests to get rid of this.
