### ISSUE TITLE
Docs do not mention a groups needs to be created

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8659]
### How to Reproduce
Follow the guide in https://molgenis.gitbooks.io/molgenis/content/guide-emx.html

### Expected behavior
following the guide result a data being imported

### Observed behavior
Error during import due to missing group

**Comment by mswertz** [comment]
I want that groups are automatically created when data is imported with a root package that doesn't match a group yet.  So first story M3663

**Comment by dennishendriksen** [comment]
> So first story M3663
M6336

**Comment by dennishendriksen** [comment]
Already fixed in e762e65836530fe4a708e61c8b9b45254e097094 by @connoratrug .
