### ISSUE TITLE
L1 cache can return invalid one-to-many values

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8665]
### How to Reproduce
- Enable the following ```org.molgenis.integrationtest.platform.OneToManyIT``` integration test cases
  - testPersonInsert
  - testUpdateParentValue
  - testUpdateParentOrderAscending
  - testUpdateParentOrderDescending

### Expected behavior
- All tests pass

### Observed behavior
- All tests fail.

Note that all tests pass after setting ```L1CacheRepositoryDecorator.cacheable``` to false. Tests where disabled during TestNG --> JUnit migration which fixed an existing transactionality issue in OneToManyIT resulting in the exposure of this issue.

**Comment by bartcharbon** [comment]
Problem only occurs for self-referencing one-to-many's.

For one-to-many's both the parent and the child end of the relation are evicted from the cache, however the updated entity is directly added again. In the case of a self-ref this is the version of the entity with only one side of the relation updated.
