### ISSUE TITLE
Ugly warning message rather than error message when starting questionnaire without rls

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8667]
### How to Reproduce
Do QUESTRLS001 of questionnaire testplan

### Expected behavior
I get a red error message with: No row level security enabled for questionnaire, this is not allowed

### Observed behavior
![Screen Shot 2019-09-18 at 12 41 26](https://user-images.githubusercontent.com/10075439/65141920-e43ccd80-da11-11e9-9ac5-7ba8ced82eb9.png)

**Comment by fdlk** [comment]
See also #8733

**Comment by fdlk** [comment]
Works correctly in 8.1.8

**Comment by fdlk** [comment]
Broken in the questionnaires code(!)

**Comment by fdlk** [comment]
Fixed in frontend.
