### ISSUE TITLE
EMX Downloader cant login to server

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis#8668]
### How to Reproduce
During EMX Downloader release step "EMXIMP001" 
Run (with the correct password)
`java -jar downloader.jar -f test.xlsx -u http://latest.dev.molgenis.org -a admin -p SUBSTITUTE_PASSWORD_HERE -s 2 emx_downloader_TypeTest -D`

### Expected behavior
test.xlsx is downloaded

### Observed behavior
```
[ERROR] - An error occurred:
javax.naming.AuthenticationException: Username or password is incorrect
        at org.molgenis.downloader.client.MolgenisRestApiClient.login(MolgenisRestApiClient.java:82)
```

**Comment by dennishendriksen** [comment]
@MaxPostema Could you try https://latest.dev.molgenis.org instead of http://latest.dev.molgenis.org?

**Comment by MaxPostema** [comment]
Closed in favor of:
https://github.com/molgenis/molgenis-tools-emx-downloader/issues/75
