### ISSUE TITLE
Datetimes cannot be saved when not edited in forms

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8671]
### How to Reproduce
Load typetest into MOLGENIS
Edit a record
Save the same record, without making changes

### Expected behavior
Is saved correctly

### Observed behavior
In errorlog: 

Failed to parse attribute [xdatetime] value [Tue Aug 13 1985 08:12:13 GMT+0200 (Central European Summer Time)] as datetime. Valid datetime format is [YYYY-MM-DDThh:mm:ssZ]
at org.molgenis.api.data.RestService.convertDateTime(RestService.java:317)

**Comment by LuukDijkhuis** [comment]
closed in frontend repo (see above)
