### ISSUE TITLE
Importing pointing study data slow

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8675]
### How to Reproduce
Import an emx csv.zip containing data plus metadata for a nontrivial model like bbmri eric or the pointing study. I think what they have in common is a lot of small code lists.

### Expected behavior
It works

### Observed behavior
I do not have the patience to wait it out. Does not look like it will ever finish.
If you split it into two files, one for metadata and one for data, metadata takes a while but can be imported and data finishes near instantly

**Comment by fdlk** [comment]
I think this is not new in 8.2, I heard @djvanenckevort and @marikaris complain about this before.

**Comment by dennishendriksen** [comment]
What are the ```max_locks_per_transaction``` and ```shared_buffers``` values of the PostgreSQL database of this MOLGENIS instance? Should be 1024 and 1GB (see #8255 and 25/03/19 mail conversation)? If the settings differ, could you try to reproduce the issue with the correct settings?

**Comment by fdlk** [comment]
Checked with these settings, waited it out on local docker 8.2.0 with
`command: -c 'shared_buffers=1024MB' -c 'max_locks_per_transaction=1024'`

Takes 15 minutes to import pointing study dataset for 7 patients (but about 150 categorical code lists)

**Comment by fdlk** [comment]
In 5.2, with standard postgres settings, same dataset imports in 9 minutes.

**Comment by mswertz** [comment]
both obviously to long. But this requires a story to fix I suppose. So please do a triage to see if any quick fixes exist.

**Comment by dennishendriksen** [comment]
Can anyone (@fdlk @marikaris maybe?) supply me with a data example so that I can do a triage?

**Comment by dennishendriksen** [comment]
Got one from @marikaris, thanks.

**Comment by dennishendriksen** [comment]
### EMX pointing v11.3model-DEF samen met UTO v1.3.xlsx
Imports in 141956ms using molgenis/master on my local machine
90% of the time is spend on database select queries mostly triggered via ```IndexDependencyModel.hasAttributeThatReferences```.
I would expect most data to be retrieved from cache instead of the database.
 
@fdlk any clue why your import was six times slower?

### eric_data_nov2019.xlsx
Did not wait until import finished.
99% of the time is spend in ```TemplateExpressionEvaluator``` due to deep entity serialization for the JavaScript engine.

**Comment by fdlk** [comment]
@dennishendriksen Not sure if we have the same dataset, I ran https://github.com/molgenis/molgenis-py-pointing-transform on a private data odm export.

**Comment by dennishendriksen** [comment]
@fdlk I've used https://drive.google.com/file/d/1qhy8rJL0MrB3WFUCCYN-Ze4LEQOy--gn/view?usp=sharing. Is it the same?

**Comment by fdlk** [comment]
@dennishendriksen no, that does not look familiar
