### ISSUE TITLE
'home' menu item is not shown if 'Logo in navigation bar' is empty

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#8681]
### How to Reproduce
- clear 'Logo in navigation bar' via the application settings

### Expected behavior
"Home" text is shown in the menu

### Observed behavior
the home page is absent from the menu

**Comment by connoratrug** [comment]
proposed fix in ui-context https://github.com/molgenis/molgenis-ui-context/pull/72

**Comment by mswertz** [comment]
Fix for 8.2 if small. Otherwise move to 8.3

**Comment by connoratrug** [comment]
Yes, small , its fixed in 8.2
