### ISSUE TITLE
Menu items fall outside of menu in tablet size

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8684]
### How to Reproduce
- Go to: https://latest.dev.molgenis.org/menu/main/dataexplorer
- Set browser (chrome, safari) width between 768 and ~1127 pixels
- Open the menu via the hamburger button

### Expected behavior
An open menu living within its own context

### Observed behavior
An open menu that is partially rendered outside of the menu context

<img width="284" alt="Schermafbeelding 2019-09-19 om 13 28 31" src="https://user-images.githubusercontent.com/46395349/65240916-a22f8c80-dae2-11e9-9891-c0d826d18eef.png">
Account, Help, select language and the signout button fall outside of menu

**Note**: only in bootstrap 3 pages

**Comment by dennishendriksen** [comment]
Unsupported resolution:
```
5.3.2 Resolutions
1280x800
1280x1024
1366x768
1680x1050
1920x1080
```
