### ISSUE TITLE
Slow performance retrieving data for non-superusers

### ISSUE THREAD

**Issue by LuukDijkhuis** [molgenis/molgenis#8695]
### How to Reproduce
- Sign in as non-superuser
- Navigate to the 'Data explorer' plugin

### Expected behavior
- Page displays within a second

### Observed behavior
- Page displays after ~ten seconds

**Comment by dennishendriksen** [comment]
Introduced by fix for #8502 in 50fd93007596cc9b1c999ed4b695de09b8e910fb.
