### ISSUE TITLE
Swagger V3 data api swagger-spec differs from api response

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8700]
### How to Reproduce
Load the BBMRI Eric data into a molgenis
Query the biobanks using the the V3 api 

### Expected behavior
Results follow the spec as described in https://molgenis.gitbooks.io/molgenis/content/data/data-api-v3.yaml

### Observed behavior
Some non top-level resources do not contain a 'data' property while the swagger specification describes this as being a required property.

**Comment by dennishendriksen** [comment]
@connoratrug Could you be more specific? Which endpoint(s) do not match the spec?

**Comment by dennishendriksen** [comment]
@connoratrug *bump*

**Comment by connoratrug** [comment]
@dennishendriksen see issue report, i have no further details available to make it more specific

**Comment by dennishendriksen** [comment]
ok, that's a pity. feel free to reopen when it is clear what the issue is and how to reproduce it.
