### ISSUE TITLE
No valid CSS source files found to process

### ISSUE THREAD

**Issue by vicarioush** [molgenis/molgenis#8726]
Dear all, 
I just downloaded the code and I tried to compile the project with intellij as suggested online and bumped into a problem. 
Basically during the compilation I receive this error "No valid CSS source files found to process" (minify-maven-plugin).

Best

### How to Reproduce
Just try to compile.

### Expected behavior
Error during the loading of  minify-maven-plugin

**Comment by fdlk** [comment]
@vicarioush the error message is cosmetic, the plugin should log it as a warning. We should fix this but feel free to ignore it.
