### ISSUE TITLE
@Transactional on PlatformIT fails testLanguageService() in maven,jenkins, but not intellij,travis

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#8730]
### How to Reproduce
Run PlatformIT with @Transactional annotation on the test class via maven

### Expected behavior
tests succeed

### Observed behavior
tests succeed on travis and when run in intellij
tests fail on jenkins and locally via maven

**Comment by dennishendriksen** [comment]
Observations:
- Test fails when running single threaded: ```clean verify -T1```
- Test succeeds when running single test case: ```clean verify -Dit.test=PlatformIT#testLanguageService -T1```

**Comment by dennishendriksen** [comment]
Cause: https://github.com/spring-projects/spring-framework/issues/11019
