### ISSUE TITLE
metadata-manager: set non-nullable gives unclear error

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis#8733]
### How to Reproduce
Do metadata-manager test plan: Editing existing EntityType

- Select the TypeTestRef EntityType in the dropdown 
- Edit the description and press save all changes
- Add an attribute country and make it nullable and save
- Set country to non-nullable and save

### Expected behavior
You get an error telling you that value country can not be null

### Observed behavior
Unclear error telling:
"entityTypeId:aaaac3pxzawfnnxhprdgjrqaae attributeName:country"

**Comment by fdlk** [comment]
Investigated a bit: this is indeed new. For some reason the message gets displayed instead of the localized message.

**Comment by fdlk** [comment]
Update: happens all over the board. The error handling has changed for private `/plugin/*` api methods.

**Comment by bartcharbon** [comment]
The metadatamanager has an own exception handler for the RuntimeException that returns the getMessage(). It seems like the order in which this handler and the global one are called is changed.

The thrown exception is also new, but both extend (indirect) from RuntimeException.

**Comment by bartcharbon** [comment]
Ignore previous comment: the thrown exception was changed from a deprecated DataValidationException to a new style codedException, those have a less human readable getMessage() (they use the getLocalizedMessage() instead)

order of the handlers is unchanged.
