### ISSUE TITLE
EMX downloader - emoji characters disappear when downloaded via EMX downloader 

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis#8734]
### How to Reproduce
Do testplan: EMXIMP002
- Import data set that is downloaded via the EMX downloader downloaded

### Expected behavior
String contains an iso latin, unicode and emoji character.
å ⦬🐀

### Observed behavior
Emoji character disappears on reimport
å ⦬??

**Comment by fdlk** [comment]
The error is in the downloader, see https://github.com/molgenis/molgenis-tools-emx-downloader/issues/69
