### ISSUE TITLE
Default error handling broken for /plugin/* controllers

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8736]
### How to Reproduce
See for example #8733

### Expected behavior
Controller responses are the same as before

### Observed behavior
Error handling specs have changed
* GlobalExceptionHandler no longer handles CodedRuntimeException

**Comment by fdlk** [comment]
Works correctly in 8.1.8

**Comment by bartcharbon** [comment]
Some plugins still have an own exception handler for the RuntimeException that returns the getMessage(). It seems like the order in which this handler and the global one are called is changed.

Plugins with such a handler: metadatamanager, dataexplorer, user account controller, account controller, tagmanager and the permissionmanager

**Comment by bartcharbon** [comment]
Ignore previous comment: Order of the handlers is unchanged.

CodedRuntimeException is now handled through the FallbackExceptionHandler, note that the http response status has changed from 404 to 500.

#8733 is caused by a change in the actual exception thrown.
