### ISSUE TITLE
As ops we want empty mail-user and mail-password in molgenis-server.properties template

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#8752]
### How to Reproduce
At this moment we define a user: "molgenis" and password: "xxxx".
This is not overwritten by the default installation. We use the smtp server of our facility which does not need userbased authentication. So sending mail breaks when you install a fresh MOLGENIS.

### Expected behavior
MOLGENIS is able to send mail when installed on a VM

### Observed behavior
MOLGENIS is fails to send mail when installed on a VM

### Solution
Delete the placeholder values from the template.

**Comment by dennishendriksen** [comment]
From ```org.molgenis.settings.mail.MailSettingsImpl```:
```java
    @Value("${mail.username:#{null}}")
    private String mailUsername;

    @Value("${mail.password:#{null}}")
    private String mailPassword;
```
The default values are ```null``` ...

**Comment by dennishendriksen** [comment]
@sidohaakma see previous comment. what needs to be changed?

**Comment by dennishendriksen** [comment]
@sidohaakma *bump*

**Comment by dennishendriksen** [comment]
@sidohaakma can you address my comment? else the issue will be closed because it cannot be reproduced.

**Comment by sidohaakma** [comment]
I am closing this. When we run into a problem with the email we can open a new one.
