### ISSUE TITLE
When altering name of one to many in metadata manager my attribute gets deleted

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8762]
### How to Reproduce
Import 
[lifecycle_model.xlsx](https://github.com/molgenis/molgenis/files/3846453/lifecycle_model.xlsx) and 
[menu.xlsx](https://github.com/molgenis/molgenis/files/3846454/menu.xlsx)
Go to metadata manager
Change the name of "children" to "Children"
Save
You will get a success message:
![Screen Shot 2019-11-14 at 13 31 15](https://user-images.githubusercontent.com/10075439/68857468-1f424100-06e3-11ea-9bf7-9205c3b92930.png)
 and everything looks good in the tree structure on the left:
![Screen Shot 2019-11-14 at 13 31 19](https://user-images.githubusercontent.com/10075439/68857482-249f8b80-06e3-11ea-948f-5a4cdb9ba9e2.png)

I was a happy person once I received this. I didn't expect it to succeed because altering the name of an attribute is some heavy shit. Then I went to have a look at my table in the dataexplorer and to my horror I noticed the column I just renamed, was GONE!

### Expected behavior
Either I get an error message telling met that it is impossible to update the name of an attribute (it might even be a cryptic one, I'm used to that in this tool), or my attribute gets correctly updated. 

### Observed behavior
I get a success message telling me my attribute is updated, but instead it is simply deleted (the horror!).

**Comment by dennishendriksen** [comment]
The UI should not allow changing the attribute name since attribute names are read-only in MOLGENIS.

**Comment by dennishendriksen** [comment]
@jvanveen should this issue be closed and added to the draft release notes?

**Comment by dennishendriksen** [comment]
@jvanveen *bump*
