### ISSUE TITLE
Can not delete row from Localization table in data explorer

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8791]
### How to Reproduce
- Sign in to https://lifelines.dev.molgenis.org/ as admin
- Open the Localization table in the dataexplorer
- delete row with auto generated key ( for example: aaaac3wqrnr7cbudfj5hzbyaai) 
### Expected behavior
Row is deleted

### Observed behavior
Row is not deleted, messages is show at the top of the page:
 'Error! Unknown error'

**Comment by dennishendriksen** [comment]
Can't reproduce because the table doesn't contain any entities with auto generated identifiers. Removing a random row in the table on my local machine works.

**Comment by dennishendriksen** [comment]
@connoratrug *bump* how to reproduce?

**Comment by mswertz** [comment]
@connoratrug if you want this fixed speak now otherwise it will not be fixed in current release.
Please comment.

**Comment by connoratrug** [comment]
That fine, i reported the issue as signal to improve the app, it's not a blocking issue for me now

**Comment by dennishendriksen** [comment]
@connoratrug see previous comments. how to reproduce? else the issue will closed.
