### ISSUE TITLE
Non actionable 'warning' when updating Computed value expression 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8793]
### How to Reproduce
Create new entity with id ( string) and label (string) fields
Add a row with any id, and label ( for example id='1' , label='FooBar')
Use Metadata manager plugin to add new attribute as Computed value expression
```$('label').toLowerCase()```

### Expected behavior
New attribute is added as computed field, or actionable error message is shown if invalid expression is provided 

### Observed behavior
Orange popover slides in containing the value of the  Computed value expression field

note: 
Error should provide some information on how to fix expression or continue some other way, be actionable.

**Comment by dennishendriksen** [comment]
I'm getting the error ```Expression '$('label').toLowerCase()' syntax invalid.``` which is correct according to the [expression docs](https://molgenis.gitbooks.io/molgenis/content/v/8.2/guide-expressions.html). 
The current behavior is intended and not a bug.

I suggest creating a story if you want better syntax error analysis/reporting.
