### ISSUE TITLE
Data explorer beacon table error in Firefox

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8840]
### How to Reproduce
- Open ```<baseUrl>/menu/main/dataexplorer?entity=sys_beacons_Beacon``` in Firefox 72.0.1

### Expected behavior
- Empty table displayed

### Observed behavior
```Error! An error occurred. Please contact the administrator.``` is displayed. Console prints:
```
An ajax error occurred. 
Object { type: "ajaxError", timeStamp: 1578899904273, jQuery33107114042969148017: true, isTrigger: 3, namespace: "", rnamespace: null, result: undefined, target: HTMLDocument http://localhost/menu/main/dataexplorer?entity=sys_beacons_Beacon, delegateTarget: HTMLDocument http://localhost/menu/main/dataexplorer?entity=sys_beacons_Beacon, currentTarget: HTMLDocument http://localhost/menu/main/dataexplorer?entity=sys_beacons_Beacon, … }
 
Object { readyState: 0, getResponseHeader: getResponseHeader(), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(), overrideMimeType: overrideMimeType(), statusCode: statusCode(), abort: abort(), state: state(), always: always(), catch: catch()
, … }
 
Object { url: "/api/v2/sys_beacons_Beacon?attrs=~id,id,name,api_version,beacon_organization,description,version,welcome_url,data_sets&num=20", type: "GET", isLocal: false, global: true, processData: true, async: true, contentType: "application/x-www-form-urlencoded; charset=UTF-8", accepts: {…}, contents: {…}, responseFields: {…}, … }
 <empty string>
```

All other system tables load without issues in Firefox 72.0.1. Beacon table loads without issues in Microsoft Edge 44.18362.449.0 and IE11.

**Comment by mswertz** [comment]
We need this for one of our current projects who would like us to deploy a beacon. 

However, I can't reproduce on Chrome nor on Mac+Firefox 55.0.2 so seems to be very specific. Hence not selected as uerget.

**Comment by bartcharbon** [comment]
I checked the beacons in Opera (setting up a beacon and querying the endpoint) and all seems to be fine.

**Comment by bartcharbon** [comment]
cannot reproduce this in Firefox 72.0.1 (MOLGENIS 8.3 release branch)

**Comment by dennishendriksen** [comment]
I can't reproduce the issue when running Firefox in safe mode (i.e. with addons disabled). Probable cause is one of my add-ons (add blocker?)
