### ISSUE TITLE
Redirect plugin documentation incorrect/incomplete

### ISSUE THREAD

**Issue by jprofijt** [molgenis/molgenis#8845]
### How to Reproduce
navigate to: https://molgenis.gitbooks.io/molgenis/content/guide-customize.html

Section try it out > Creating redirects to URLs outside MOLGENIS

Add a new menu item with described parameters
* Plugin: redirect
* Name: Wikipedia Link
* Query string: https://en.wikipedia.org/wiki/Bioinformatics

### Expected behavior
* Inserting url as described in documentation will redirect to url

### Observed behavior

* Response 400: Required String parameter 'url' is not present

**Comment by fdlk** [comment]
Pending better documentation for this: The query string should list the parameters, not just the value of the url parameter.
So you need to enter
`url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBioinformatics` (note the url encoding)
