### ISSUE TITLE
Cookie wall overlaps menu for vue plugins

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8862]
### How to Reproduce
- Sign in as superuser
- Navigate to the Settings plugin
- Set a dummy 'Google analytics tracking ID'
- Select 'Save changes'

### Expected behavior
- Cookie wall is displayed above the main menu
![image](https://user-images.githubusercontent.com/2477186/73156034-b44ab880-40dc-11ea-931f-984140001cef.png)

### Observed behavior
- Cookie wall overlaps the menu for Vue plugins
- Part of the cookie wall is missing on the right (sign out button is visible)
![image](https://user-images.githubusercontent.com/2477186/73156080-da705880-40dc-11ea-92db-1ff40c1cfda1.png)

Works for non-Vue plugins

**Comment by mswertz** [comment]
Should not block release of core, but should be fixed before fixing frontend version.
Because our front page is also vuejs so on vanilla MOLGENIS this is very in your face.
