### ISSUE TITLE
Missing bootstrap on creation

### ISSUE THREAD

**Issue by christianhilbrands** [molgenis/molgenis#8871]
### How to Reproduce
Difficult to reproduce. Looks like a timing issue or a not clean install of molgenis. But that was told to me by Connor but it is not tested. 

### Expected behavior
On launch of a fresh molgenis instance on the rancher cluster, if you go to the website(in this case: http://hub.test.molgenis.org) you get a page with proper populated CSS theming. 

### Observed behavior
On launch of the fresh molgenis instance on the rancher cluster, if you go to the website you get a website without styling. In the console it stated that bootstrap-yeti.css was missing. When changed to bootstrap-molgenis-blue.css we observed the same behaviour. When uploaded a bootstrap from eric the website was displayed correctly. 

Log files:
[hub.test.molgenis.org elasticsearch.log](https://github.com/molgenis/molgenis/files/4127327/hub.test.molgenis.org.elasticsearch.log)
[hub.test.molgenis.org frontend.log](https://github.com/molgenis/molgenis/files/4127328/hub.test.molgenis.org.frontend.log)
[hub.test.molgenis.org molgenis.log](https://github.com/molgenis/molgenis/files/4127329/hub.test.molgenis.org.molgenis.log)
[hub.test.molgenis.org postgresql.log](https://github.com/molgenis/molgenis/files/4127330/hub.test.molgenis.org.postgresql.log)

**Comment by dennishendriksen** [comment]
```
Caused by: java.io.UncheckedIOException: java.io.FileNotFoundException: /home/molgenis/data/filestore/aaaac35tzzwujxvxfpddmfyaae 
	at org.molgenis.core.ui.style.StyleServiceImpl.getThemeData(StyleServiceImpl.java:176)
```
Does the file exist on the file system?

The file is retrieved when you request a MOLGENIS page via:
```
<link rel="stylesheet" href="<@theme_href "/css/bootstrap-3/${app_settings.bootstrapTheme?html}"/>" type="text/css" id="bootstrap-theme">
```

**Comment by christianhilbrands** [comment]
I saw that the namespace of the hub(hub.test.molgenis.org) was created on 17 januari 2020 and just yesterday he came to me with this question so probably was the namespace not empty.

**Comment by dennishendriksen** [comment]
Please re-open in case the problem reoccurs.

**Comment by dennishendriksen** [comment]
Related? #7925
