### ISSUE TITLE
Import jobs reported running after restart

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8883]
### How to Reproduce
- Import a file user the advanced importer
- Restart the server during import

### Expected behavior
- All RUNNING imports are set to FAILED

### Observed behavior
- All RUNNING imports are still marked as RUNNING (but nothing is happening)

**Comment by mswertz** [comment]
If cheap to fix, then fix, if not then move to 8.x

**Comment by dennishendriksen** [comment]
>If cheap to fix, then fix, if not then move to 8.x

Cheap to fix
