### ISSUE TITLE
Executor services not shutdown on JVM shutdown

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8884]
### How to Reproduce
- Code inspect usages of ExecutorService

### Expected behavior
- ExecutorService shutdown is called as described in the ExecutorService javadoc to perform a orderly shutdown (e.g. not accepting not jobs during shutdown)

### Observed behavior
- No shutdown

**Comment by mswertz** [comment]
seems a broken window that we better fix immediately?

**Comment by dennishendriksen** [comment]
> seems a broken window that we better fix immediately?

agreed. prevents annoying issues when restarting at dev time.
