### ISSUE TITLE
Cannot view help docs

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#8920]
### How to Reproduce
go to https://master.dev.molgenis.org/
click help link

### Expected behavior
docs page is shown

### Observed behavior
```
This site can’t be reachedmolgenis.gitbooks.io’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by dennishendriksen** [comment]
probably a hick-up on gitbooks.io, works at the moment.
