### ISSUE TITLE
Switch from RestTemplate to org.springframework.web.reactive.client.WebClient

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8983]
Check https://github.com/spring-projects/spring-framework/issues/24503
Also for non-reactive purposes.

**Comment by connoratrug** [comment]
Used this for java version of node-edge-lifelines service, seems nicer then the RestTemplate stuff, although still not as nice a node :)

**Comment by mswertz** [comment]
this is a story for the backlog, not an issue here.
