### ISSUE TITLE
OIDC personal permissions lost

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8985]
### How to Reproduce
Turns out there's more than one way to trigger this.
The OidcClient has a configurable `userNameAttributeName`.
The permissions are lost when the value of the `userNameAttributeName` in the ID token is different from the username of the MOLGENIS User that the OpenID user gets mapped to.

1. Configure an OIDCClient, set the `userNameAttributeName` attribute to `sub` (the default).
1. Sign up a user using OIDC.
1. As admin, open the permission manager. Give user permissions on the navigator plugin to the signed up user
1. Log in with the user, look at the menu

### Expected behavior
Navigator shows up in menu

### Observed behavior
Navigator does not show up in menu.

Update the OIDCClient, set the `userNameAttributeName` attribute to `email`.
Log out and back in with the user
Now the navigator does show up in the menu

**Comment by fdlk** [comment]
Not clear to me how the attribute is supposed to work.

**Comment by fdlk** [comment]
https://github.com/molgenis/molgenis/blob/master/molgenis-security/src/main/java/org/molgenis/security/oidc/OidcUserMapperImpl.java#L95 stubbornly sets the username to the value of the email address.

**Comment by fdlk** [comment]
Value of Authentication.getName()

When logged in with OIDC:
Authentication is an OAuth2AuthenticationToken and its principal is a MappedOidcUser

Authentication.getName() is implemented in AbstractAuthenticationToken.getName()
since getPrincipal() instanceof AuthenticatedPrincipal, it returns getPrincipal().getName()

MappedOidcUser returns the MOLGENIS username in both toString and getMappedName()
But its getName() returns the value of the userNameAttribute claim configured in the OidcClient.


When logged in with username / password:
Authentication is a UsernamePasswordAuthenticationToken with as principal a UserDetails coughed up by the UserDetails service.
Authentication.getName() is implemented in AbstractAuthenticationToken.getName()
since getPrincipal instanceof UserDetails it returns getPrincipal().getUsername().

**Comment by fdlk** [comment]
How the MappedOidcUser gets loaded:
MappedOidcUserService.loadUser(OidcUserRequest)
1. call OidcUserService.loadUser(OidcUserRequest)
	1. Check if user info endpoint is specified (MOLGENIS requires it)
	2. Load OAuth2User through oauth2UserService
		1. check that userNameAttribute is present in client registration
		2. call userinfo endpoint
		3. Create authorities:
			- a OAuth2UserAuthority (ROLE_USER), with claims as attributes
			- A SCOPE_<scope> authority for each scope in the access token
		4. Return a DefaultOauth2User with these authorities and attributes and the defined userAttributeName
	3. Create a OidcUserInfo with the attributes as claims
	4. Check that the sub claim is included
	5. Check that the sub claim matches the sub claim in the ID token
	6. Create authorities:
		- A OidcUserAuthority (ROLE_USER), with the idToken and OidcUserInfo
		- A SCOPE_<scope> SimpleGrantedAuthority for each scope in the access token
	7. Return a new DefaultOidcUser with 
		these authorities, the idToken, the OidcUserInfo and the userNameAttribute.
2. Let the oidcUserMapper map the DefaultOidcUser to a MOLGENIS User (see docs PR)
3. Ask the UserDetailsService for the MOLGENIS user's authorities
4. Return a MappedOidcUser with these authorities, the id Token, the userInfo, the userNameAttributeName and the MOLGENIS username

**Comment by tommydeboer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix OIDC bug #8985](https://trello.com/c/i5qIXhry/343-fix-oidc-bug-8985)

**Comment by tommydeboer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix OIDC bug #8985](https://trello.com/c/i5qIXhry/343-fix-oidc-bug-8985)

**Comment by tommydeboer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix OIDC bug #8985](https://trello.com/c/i5qIXhry/343-fix-oidc-bug-8985)

**Comment by tommydeboer** [comment]
Fixed since 8.4.5
