### ISSUE TITLE
REST api v2 updating one value fails if attribute is of data type xref/mref/categorical/categoricalmref

### ISSUE THREAD

**Issue by LuukDijkhuis** [molgenis/molgenis#9011]
The REST api V2 functionality Update One Value for multiple IDs does work in case the attribute is of type int or string, but fails when the attribute is of type xref/categorical/mref/categoricalmref. The error messages that occurs is: "lazyEntity instead of String" 
When changing the input from for example a string value ('A') to a list ['A'] or dictionary {'A'} the errors are "ArrayList? instead of String" and "LinkedTreeMap? in stead of string".

FROM REST api V2 Documentation:

One value
If you only want to change one attribute without needing to provide all other attributes:
Request
```PUT ​http://molgenis.mydomain.example/api/v2/person/age
Content-Type: application/json
{
   entities: [
    {
      "id": 1,
      "age": "1"
    },
    {
      "id": 2,
      "age": "2"
    }
  ]
```
### How to Reproduce
With the attached EMX and python script the error can be reproduced.

### Expected behavior
No error is returned and the update is performed
### Observed behavior
An error is returned

### python and emx file to reproduce:
[issue_rest-api-v2-updating-one-xref-mref-categorical-categoricalmref.zip](https://github.com/molgenis/molgenis/files/4701063/issue_rest-api-v2-updating-one-xref-mref-categorical-categoricalmref.zip)

**Comment by LuukDijkhuis** [comment]
submitted by Dieuwke

**Comment by dennishendriksen** [comment]
Issue was reported by mail on ```Monday, March 30, 2020 4:13:53 PM```:

**Comment by mswertz** [comment]
minimally we should give error: attributes of type 'mref', 'xref' ... cannot be updated using this endpoint
