### ISSUE TITLE
Delete using URL as identifier fails

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#9012]
### How to Reproduce

Make table with an ID attribute of type 'hyperlink', add record with e.g. 'https://hematologiegroningen.nl/protocollen/download/?id=3991'. Attempt to delete, this does not work. Probably because REST calls does URL escaping, so the ID value is not recognized anymore?

### Expected behavior

Record is succesfully deleted.

### Observed behavior

Record is not deleted.

**Comment by fdlk** [comment]
Duplicates #4117
