### ISSUE TITLE
Google Analytics gets incorrect URLs

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis#9018]
### How to Reproduce
Configure MOLGENIS with GA
Look at the 'Site content' > 'All pages'

### Expected behavior
Pages are reported with the local path

### Observed behavior
Pages are reported with invalid local paths like this:
 /https://example.org/main/menu/dataexplorer?

**Comment by fdlk** [comment]
I'm sorry, cannot reproduce on localhost 8.4 branch nor on latest.test.molgenis.org, 8.4.2 release

![Schermafbeelding 2020-06-22 om 20 27 36](https://user-images.githubusercontent.com/1523838/85322669-fc70da00-b4c6-11ea-9ed6-ff07cd3a8550.png)

**Comment by fdlk** [comment]
@esthervanenckevort can you provide some more specifics?

**Comment by esthervanenckevort** [comment]
Once you start using the filters the URLs are incorrect. E.g. filtering on country cause this URL:
<img width="1077" alt="Screenshot 2020-06-23 at 09 14 31" src="https://user-images.githubusercontent.com/1942445/85372435-1eec0d00-b532-11ea-9d90-1169d8dca405.png">

**Comment by fdlk** [comment]
Found it! It's in the data explorer, the complete location is set as page.
