### ISSUE TITLE
Google analytics does not work if privacy-friendly settings are not set

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis#9023]
### How to Reproduce
Go to master.dev.molgenis.org
open dev console

## Location:
https://github.com/molgenis/molgenis/blob/master/molgenis-core-ui/src/main/resources/templates/molgenis-header-tracking.ftl

```
TypeError: $.cookie is not a functionmaster.dev.molgenis.org:29:37
    <anonymous> https://master.dev.molgenis.org/:29
    <anonymous> https://master.dev.molgenis.org/:45
```

This is for all front-ends, especialy critical for Biobank Explorer

### Expected behavior
Google Analytics works

### Observed behavior
Javascript stops executing because of error.

### Solution:

use following fnction to read cookie and no need for jquery cookie plugin

```
function getCookie(cname) {
  var name = cname + "=";
  var decodedCookie = decodeURIComponent(document.cookie);
  var ca = decodedCookie.split(';');
  for(var i = 0; i <ca.length; i++) {
    var c = ca[i];
    while (c.charAt(0) == ' ') {
      c = c.substring(1);
    }
    if (c.indexOf(name) == 0) {
      return c.substring(name.length, c.length);
    }
  }
  return "";
}
```

**Comment by fdlk** [comment]
As a workaround, you can set anonymize IPs and privacy-friendly to true.
