### ISSUE TITLE
Old version of JWKS URI used

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#9026]
### How to Reproduce
As admin, configure an oidc client with incorrect jwks uri.
Select the oidc client in authentication settings.
In a private window, try to log in, see that login fails.
As admin, fix the oidc client jwks uri.
In the private window, try to log in again

### Expected behavior
The login succeeds

### Observed behavior
The login keeps failing.
If you reboot the server, it works.

**Comment by fdlk** [comment]
There is a special mechanism that allows autowiring settings entities. The cached entity gets updated by a decorator on the settings entity repository. But this mechanism doesn't update referenced entity instances once they've been loaded so those can get stale.

**Comment by mswertz** [comment]
still revelevant?

**Comment by fdlk** [comment]
Have not explicitly checked but would expect yes.

**Comment by fdlk** [comment]
Yes, still very relevant! Running into this today with @esthervanenckevort and @erikschaberg.

**Comment by fdlk** [comment]
Debugged some and spring OidcIdTokenDecoderFactory caches the JwtDecoder
