### ISSUE TITLE
Deleting data from an entity referenced by other entities which contains no data fails

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis#9045]
### How to Reproduce
Three entities: entity 1 and 2 xref to entity 3. Entity 3 contains a lot of data. Entity 1 and 2 are empty. 
Delete the data from entity 3.
The actual situation was on molgenis106 with entity metabrain_snp (1.5 mln records). Xref from metabrain_ciseQTLs and metabrain_transeQTLs which were both empty to metabrain_snp.

### Expected behavior
When entity 1 and entity 2 are empty I expect that deleting the data will go quick as nothing has to be checked.

### Observed behavior
Several minutes after starting deleting the data it stops with: "Error! An error occurred. Please contact the administrator."
Looking in the tomcat log does not show any errors. PostgresSQL is however performing a lot of transactions which seems not to come to an end (only option is to kill the actions and restart).

**Comment by fdlk** [comment]
Is the entity row-level secured or not?

**Comment by dtroelofsprins** [comment]
No it's not. Molgenis version is indeed 7.4.9. Would upgrading it to the latest version perhaps help?

**Comment by fdlk** [comment]
Unsure how to quickly reproduce this in 8.4

**Comment by dtroelofsprins** [comment]
Eerst met een testset op docker versie 7.4 en 8.3 uitgeprobeerd. Geen probleem met het deleten van de data. 
Copy gemaakt van de package die problemen geeft op molgenis106. Geprobeerd data te verwijderen => weer dezelfde foutmelding. 
Package gedownload en lokaal getest (op 7.4) wederom geen probleem om de data te verwijderen indien de xref-s aanwezig zijn. 

Lijkt op server issue?!?!? 
Gaat bij upgrade naar 8 naar een nieuwe server (waarschijnlijk), daarom nu eerst dit issue gesloten en kijken of upgraden het probleem wat specifiek voor deze server lijkt(?) is opgelost. Work-around is bekend en redelijk makkelijk toe te passen.
