### ISSUE TITLE
FileStore returns absolute paths instead of paths relative to store

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#905]
This is a problem when you move your MOLGENIS to another server / path.

**Comment by mswertz** [comment]
what is the negative consequence of this, i.e. how does this affect user experience?

**Comment by dennishendriksen** [comment]
You cannot access your files when you move MOLGENIS to another server or you move the MOLGENIS home directory. Also the File download in table will be broken.

**Comment by dennishendriksen** [comment]
Cannot reproduce in 7.0.0-SNAPSHOT by performing the following steps:
- Start MOLGENIS with an empty database
- Download a file in the 'File metadata' entity type table using the 'Data Explorer' plugin 
- Stop MOLGENIS
- Change ```String molgenisFileStoreDirStr = molgenisHomeDir + "data" + File.separator + "filestore";``` to ```String molgenisFileStoreDirStr = molgenisHomeDir + "data" + File.separator + "filestorenew";```
- Rename the filestore folder on your local file system to filestorenew
- Build and start MOLGENIS
- Download a file in the 'File metadata' entity type table using the 'Data Explorer' plugin
This works as expected.
