### ISSUE TITLE
Unstable Group creation API test

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#9050]
### How to Reproduce
Occasionally the build will fail because the order of the roles is unpredictable. 
identitiesapicontrollerit.testcreategroup:185

### Expected behavior
Green is green

### Actual behavior
https://travis-ci.org/github/molgenis/molgenis/jobs/710175846

**Comment by tommydeboer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix unstable group API test](https://trello.com/c/UIhRaQw0/362-fix-unstable-group-api-test)
