### ISSUE TITLE
OIDC User mapper does not respect the userNameAttribute configured in OidcClient

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#9053]
### How to Reproduce

1. Configure an OIDCClient, set the userNameAttributeName attribute to sub (the default).
2. Sign up a user using OIDC.
3. As admin, check the newly created user's username

### Expected behavior
It is set to the "sub" claim in the user's ID token

### Observed behavior
It is set to the "email" claim in the user's ID token

**Comment by mswertz** [comment]
okay, so we hereby decide that usersnames are email?

**Comment by fdlk** [comment]
@mswertz it's complicated :)

**Comment by mswertz** [comment]
this issue will be closed by making this parameterizable right?

**Comment by fdlk** [comment]
First the simple part:
When the mapper creates a new user it needs to fill in a username.
Currently it always uses the value of the email claim, no matter what you specify in the config. This is a bug.

Then the complicated part:
When determining if a user already exists for the user info in the token, we currently look for an existing user with the same email address. If that user doesn't exist, we create a new one. But if the userNameAttribute is not "email" we have two ways to find a match: user.email = token.email or user.username = token[userNameAttribute].

Finally, the edge cases are nasty. If the mapper decides he cannot find the user and wants to create a new one, it's a bit weird then if that user cannot be created because one already exists for the email address or username we'd like to give our newly created user. So the mapper and the creation need to be compatible.

**Comment by fdlk** [comment]
And the standard has something to say about it too: https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability In short: you cannot rely on the email address being unique, only the issuser + sub are unique

**Comment by fdlk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix #9053 OIDC User mapper does not respect the userNameAttribute configured in OidcClient](https://trello.com/c/2b86KWmh/588-fix-9053-oidc-user-mapper-does-not-respect-the-usernameattribute-configured-in-oidcclient)
