### ISSUE TITLE
Migration (7 -> 8) fails when there is a package that previously had a group associated with it

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#9079]
### How to Reproduce
1. In molgenis 7.x: Add a package + group _test_
2. Remove the group but keep the package
3. Run the migration

### Expected behavior
Migration succeeds

### Observed behavior
Because of #9078, the `acl_sid` table still contains sids belong to the old group. Now the migration step (step 39) sees the package and tries to add a group + roles. Then it will add the sids (which will fail because they already exist).

**Note:**
Fix together with #9074 
Probable solution: the roles added in the migration should not get the package name, but the generated group hash

**Comment by mswertz** [comment]
is this root package? Because I don't want root packages without a group or vice versa. So group should not be able to delete without the underlying package. Or do I misunderstand?

**Comment by tommydeboer** [comment]
@mswertz This is about the migration that makes that specific wish come true :) It adds groups for packages that have none. The problem is that before that you _could_ remove the group.

**Comment by tommydeboer** [comment]
We are opting to close this issue without fixing it because all our servers have been migrated to 8+. 

If you run in to this issue, there's a workaround:
There are `sids` for roles in the `acl_sid` table that you will nog find in the `sys_sec_Role` table. These rows should be deleted (along with any `acl_entry` rows that referenced it).
