### ISSUE TITLE
default password 

### ISSUE THREAD

**Issue by LordBonkerz** [molgenis/molgenis#9098]
### How to Reproduce
deployed via ansible with ssl true.

ansible-playbook i_setup_molgenis_8.yml -i inventory.ini

### Expected behavior
all went well

### Observed behavior
surf to address and there is only a sign-in link and help in top right corner.  Where is the sign-up? Or what is the default admin password. I've tried all combinations and searched through the roles and used what is provided there. But still no luck!   RTFM 100x already :)

Kindly point me in the right direction.

Cheers!

**Comment by LordBonkerz** [comment]
CentOS 8

**Comment by LordBonkerz** [comment]
grep -i "password" /var/log/tomcat/catalina.out 

and there it is!!

**Comment by fdlk** [comment]
@LordBonkerz Molgenis will pick up the password from environment variables or properties file in the home dir. If no password is found, one is generated and output to the logging.

**Comment by LordBonkerz** [comment]
Cheers, thanks for the help...  Documentation should be a bit more clear on this I feel..
