### ISSUE TITLE
OIDC superuser can't see questionnaires other users

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#9113]
### How to Reproduce
Login as superuser using OIDC. Go to questionnaire and view all questionnaires started by other users.

### Expected behavior
Superuser can see all questionnaires that are started by all other users.

### Observed behavior
Supersuser logged in via OIDC can not see questionnaires from other users. IF same superuser logs in via local user login, all questionnaires can be seen, edited or deleted.

**Comment by fdlk** [comment]
@Fernananas which version are you seeing this in? We fixed https://github.com/molgenis/molgenis/issues/8985 in 8.4.5

**Comment by tommydeboer** [comment]
@Fernananas I also can't reproduce this. The issue sounds a lot like the one @fdlk mentioned, which is fixed since 8.4.5. You might be using an old OIDC Client configuration (missing a value for `claimsRolePath`).

**Comment by tommydeboer** [comment]
Looked at it with @Fernananas and we couldn't reproduce it.
