### ISSUE TITLE
Import API does not give the correct error message

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#9128]
### How to Reproduce
Import a file via the import API that normally cannot be uploaded. 
Example 1: A file containing required columns with no values.
Example 2: A file containing a duplicate column

### Expected behavior
Example 1: Correct error message: "Number of values doesn't match the number of headers", which was the case in version 8.3.11.
Example 2: Correct error message: "Duplicate column header 'column_name' not allowed", which was the case in version 8.3.11.

### Observed behavior
It says "Execution successful" while nothing is imported (version 8.5.1.) for both examples shown above.

**Comment by tommydeboer** [comment]
@marieke-bijlsma I've tried both examples you describe on version 8.5.1 and on the latest snapshot, but in all cases the imports fail. Can you upload the datasets that are succeeding on your end? I'd also like to see the exact request you send to the import API. Thanks!

**Comment by tommydeboer** [comment]
As discussed with Marieke, this issue can be closed.
