### ISSUE TITLE
Use Closure instead of YUI for javascript minifying

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#914]
Use CLOSURE as jsEngine in minify-maven-plugin instead of YUI because YUI reports a lot of warnings for variables not declared at the beginning of a scope. Furthermore YUI removed the "use strict;" line in minified code, CLOSURE does not when used with ECMASCRIPT5_STRICT as closureLanguage (see http://samaxes.github.io/minify-maven-plugin/minify-mojo.html)

**Comment by Mark-de-Haan** [comment]
Added 3413 to the backlog
