### ISSUE TITLE
Python scripts do not run in docker

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#9141]
### How to Reproduce
On the kubernetes cluster:
Follow the steps in the Script test plan, for the Hello python script

### Expected behavior
The script runs

### Observed behavior
Script throws an error

**Comment by fdlk** [comment]
Tried in 8.5 on a VM, and it works fine there

**Comment by Pacific89** [comment]
Hello :)
I might have a related issue:
using the script-plugin i created a small python test script using the following docker-compose file for the molgenis images (latest frontend, molgenis v8.4.2:

https://github.com/bibbox/app-rd-connect/blob/master/docker-compose.yml

The following error occurs:
File [/usr/bin/python] does not exist

Testing the python installation inside the running container showed that the command "Python3" works (with the existing path: /usr/bin/python3) while "Python" (path: /usr/bin/python not existing) does not work.

**Comment by fdlk** [comment]
@Pacific89 #9155 fixes this by setting the `python_script_executable` to `/usr/bin/python3` in the Dockerfile.
The default is `/usr/bin/python` and it does not exist in the container.
You should be able to add the environment variable in any docker-compose as well, so you need not wait for this to be released.

**Comment by Pacific89** [comment]
@fdlk thanks for the help! added it to our docker-compose.yml and it works fine
