### ISSUE TITLE
Unable to edit homepage in WOM for lifelines-acc.gcc.rug.nl

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis#9162]
### How to Reproduce
Log in to lifelines-acc.gcc.rug.nl as admin and try to edit homepage. Molgenis version: 3.6.2

### Expected behavior
Edit homepage text/links etc.

### Observed behavior
Menu bar jumps to middle of screen, rest of screen is white, unable to edit anything.

**Comment by fdlk** [comment]
@BrendaHijmans 3.6.2? I'm going to close this cause that's what we do when an issue is fixed in the master. Shall we take a look together to see if we can find a workaround?
