### ISSUE TITLE
Error when downloading a file with a comma in the name

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#9166]
### How to Reproduce
1. Create a file called `my,file.txt`
2. Import `it_emx_datatypes.xlsx`
3. Open `TypeTest` in the data explorer
4. Upload the file to one of the rows (attribute: `file`)
5. Go to `FileMeta`
6. Try to download the newly created file by clicking its link

### Expected behavior
Either downloads correctly, or it shouldn't have been possible to upload the file.

### Observed behavior
```ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION```

**Comment by tommydeboer** [comment]
**Workaround**: just change the file name in the `FileMeta` entity

**Comment by connoratrug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue prod lifelines](https://trello.com/c/6i24UNK0/412-issue-prod-lifelines)
