### ISSUE TITLE
RSQL operators do not match spec

### ISSUE THREAD

**Issue by odemura** [molgenis/molgenis#9198]
### How to Reproduce
Compare 
https://github.com/jirutka/rsql-parser
and https://tools.ietf.org/html/draft-nottingham-atompub-fiql-00#section-3.2.2
with https://github.com/molgenis/molgenis/blob/master/docs/guide-rsql.md
### Expected behavior
`==`, `=!=` should behave the same way as n spec,
e.g. `actor==*Bale` => `upper(actor) like upper('%Bale')`
meaning operators `=q=, =sq=, =like=, =notlike=` are redundant.

### Observed behavior
Implementation details leaked away

**Comment by fdlk** [comment]
This is intentional, we want to use the rsql syntax to expose our molgenis operators
