### ISSUE TITLE
Metadata Manager does not show rangeMin and rangeMax values

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#9206]
### How to Reproduce

In EMX fill in some range:
![Screenshot 2021-04-16 at 16 08 31](https://user-images.githubusercontent.com/40240913/115036677-04728e00-9ece-11eb-9cc5-791d35001076.png)

Import EMX, importer gives success. 
Go to metadata manager, go to the specific dataelement with rangeMin rangeMax.
Attached EMX, has a lot of ranges:
[genturis_v2.xlsx](https://github.com/molgenis/molgenis/files/6325614/genturis_v2.xlsx)

### Expected behavior
When uploading EMX with rangeMax, rangeMin (filled with some integers).
All values are stored in database and also is shown in the metadata manager.

### Observed behavior

Importing EMX give no warnings. Only success
In metadata manager all values of the rangeMin/Max are empty.
![Screenshot 2021-04-21 at 14 45 21](https://user-images.githubusercontent.com/40240913/115555798-3a3dbb00-a2b0-11eb-9909-8a1f14ce7988.png)

Forms gives warning of range.
![Screenshot 2021-04-21 at 14 44 42](https://user-images.githubusercontent.com/40240913/115555839-46297d00-a2b0-11eb-9392-76cafbd828d8.png)

**Comment by tommydeboer** [comment]
Moved to https://github.com/molgenis/molgenis-frontend/issues/609
