### ISSUE TITLE
N/A option appears when enum or categorical is not mandatory

### ISSUE THREAD

**Issue by Fernananas** [molgenis/molgenis#9207]
### How to Reproduce
Make enum or categorical item with options: "yes", "no","Unknown". Item is optional.
Open form and see extra option "N/A"

### Expected behavior
Open form and only see my options: "yes", "no","Unknown". N/A not present as option on form in edit mode.

### Observed behavior
![Screenshot 2021-04-19 at 10 12 42](https://user-images.githubusercontent.com/40240913/115204862-40d60200-a0f9-11eb-9580-096b4facde54.png)
Open form and N/A is present as extra option.

**Comment by fdlk** [comment]
This is tricky. Radio buttons cannot be deselected once you've clicked something. That's what the N/A option does.

**Comment by fdlk** [comment]
If it helps: You can rename the N/A option to something else in the localization table, it's in the ui-form namespace with key form_boolean_missing.

**Comment by fdlk** [comment]
Also, if you make the field required, it goes away and validation makes sure one of the options is checked.

**Comment by mswertz** [comment]
> This is tricky. Radio buttons cannot be deselected once you've clicked something. That's what the N/A option does.

Alternative would be to instead show a 'clear' button once an option is selected, to enable deselection

**Comment by fdlk** [comment]
> > This is tricky. Radio buttons cannot be deselected once you've clicked something. That's what the N/A option does.
> 
> Alternative would be to instead show a 'clear' button once an option is selected, to enable deselection

Yes, through [some javascript trickery](https://stackoverflow.com/questions/46166125/uncheck-radio-button) you can unset a radio button after it's been clicked.
But UX-wise it goes contrary to what people expect from a browser

**Comment by mswertz** [comment]
> But UX-wise it goes contrary to what people expect from a browser

Maybe keeping 'radio' empty can be confusing. 'Unknown' would in my mind be the 'N/A' so would relabeling be sufficient in this case? I don't know if that holds for all cases?

**Comment by fdlk** [comment]
Talked with @Fernananas We propose to make a setting to configure if you want the N/A to appear or not.

**Comment by fdlk** [comment]
To recap what was discussed: the customer has enum attributes with options Yes, No, Unknown. Depending on other fields, the user needs to explicitly look at some of these attributes and pick one of the three options. For other enums, this is optional, they may be left empty. So they never need to be able to deselect.
