### ISSUE TITLE
SORTA Examples

### ISSUE THREAD

**Issue by AJKellmann** [molgenis/molgenis#9209]
### How to Reproduce
1) Go to https://sorta.molgeniscloud.org/menu/main/home
2) Click the Example 1 Button.

### Expected behavior
A request should be sent to SORTA. 
SORTA should then execute the example query.

### Observed behavior
When clicking on the button Example1 a page with the Error 400 is shown:
"Required String parameter 'taskName' is not present"

**Comment by fdlk** [comment]
I cannot reproduce

**Comment by connoratrug** [comment]
@fdlk because @AJKellmann fixed ik think , the issue was the missing 'taskName' when the example is updated with the taskname it works

**Comment by AJKellmann** [comment]
### How to Solve:

SORTA requires an additional parameter. "taskName"

```
<form action="https://sorta.molgeniscloud.org/menu/main/sorta/match" method="POST">
    <input name="selectOntologies" type="hidden" value="http://purl.obolibrary.org/obo/hp.obo.owl" /> 
    <input name="taskName" type="hidden" value="Example1" />
    <input name="inputTerms" type="hidden" value="Name
			hearing impairment
			protruding eyeball
			hyperextensibility at elbow joint" />
    <button class="btn btn-lg btn-link" style="padding-left: 0px;" type="submit">Example 1:</button>
</form>
```

**Comment by connoratrug** [comment]
solved by add taskName https://github.com/molgenis/molgenis/issues/9209#issuecomment-823975739
