### ISSUE TITLE
REST API v2 query example incorrectly repeats the q parameter

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#9219]
### How to Reproduce
Check https://molgenis.gitbook.io/molgenis/interoperability/guide-api-rest2

### Expected behavior
Only one q parameter and one rsql expression

### Observed behavior
`GET http://molgenis.mydomain.example/api/v2/<entity_name>?q=attr0!=val;q=attr1=ge=5`

**Comment by tommydeboer** [comment]
Closed in #9220

**Comment by fdlk** [comment]
Not yet merged to master, though
