### ISSUE TITLE
Molgenis OMX web application does not work when deployed at a different context than ROOT

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#927]
If I deploy the Molgenis OMX application as omx.war (Context /omx/) I get an empty login screen and I can not login. Redeploying as ROOT.war (Context /) solves the issue.

Expected behavior: I can deploy the Molgenis OMX application in any context with full support for all the options. The code should be able to handle a different context.

**Comment by Mark-de-Haan** [comment]
Added 3414 to the backlog
