### ISSUE TITLE
Uploading a tsv file fails

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis#9289]
### How to Reproduce
Do Importer testplan
At step: IMPORTEDITOR002 | user upload existing EntityType with permissions 
when trying to upload data_hospital.tsv

### Expected behavior
File imports succesfully

### Observed behavior
Error! Your import failed:
Can not import file. No suitable importer found

**Comment by tommydeboer** [comment]
I can't reproduce this. Are you sure you are using the right file?

**Comment by tommydeboer** [comment]
@MaxPostema couldn't reproduce it either 😄
