### ISSUE TITLE
Scripts don't show output if there is an error

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#9304]
### How to Reproduce
1. Go to the Scripts plugin
2. Add the following Python script:
```python
print("show me")
raise ValueError()
```
3. Save and run it

### Expected behavior
The script fails but I can still inspect the output to see what has happened until the error occurred.

### Observed behavior
Only the error is logged:
```
09:49:34.957 CEST - Failed. Error running [/usr/local/Cellar/tomcat/9.0.35/libexec/temp/13105102389242304189.py].Traceback (most recent call last):
  File "/usr/local/Cellar/tomcat/9.0.35/libexec/temp/13105102389242304189.py", line 3, in <module>
    raise ValueError()
ValueError
```

**Comment by fdlk** [comment]
We propose to merge the standard output and standard error to one stream
